MahoganyTown_House_MapScripts::
	.byte 0


MahoganyTown_House_Eventscript_Man::
	msgbox MahoganyTown_House_Eventscript_Man_Text_0, MSGBOX_NPC
	end


MahoganyTown_House_Eventscript_Woman::
	msgbox MahoganyTown_House_Eventscript_Woman_Text_0, MSGBOX_NPC
	end


MahoganyTown_House_Eventscript_Man_Text_0:
	.string "I heard that a red GYARADOS appeared\nat the LAKE.\pThat's odd, since even ordinary\nGYARADOS are rare in that lake…$"

MahoganyTown_House_Eventscript_Woman_Text_0:
	.string "My favorite radio program?\nI'd say POKéMON MUSIC.$"
