	.align 2
voicegroup020::
	voice_keysplit_all voicegroup001
	voice_keysplit voicegroup005, KeySplitTable1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 1, 0, 7, 3, 3
	voice_directsound 60, 65, DirectSoundWaveData_sd90_classical_detuned_ep1_high, 255, 204, 77, 246
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88_tubular_bell, 255, 165, 90, 216
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88_pizzicato_strings, 255, 226, 0, 165
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88_timpani, 255, 246, 0, 226
	voice_keysplit voicegroup006, KeySplitTable2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 
	voice_square_2_alt 60, 0, 1, 0, 7, 3, 3
	voice_square_1_alt 60, 0, 0, 2, 0, 3, 0, 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_programmable_wave 60, 0, ProgrammableWaveData_86B4830, 0, 7, 15, 0

