	.align 2
voicegroup072::
	voice_directsound 60, 0, DirectSoundWaveData_unknown_open_hihat, 255, 0, 255, 0
	voice_keysplit_all voicegroup002
	voice_keysplit voicegroup005, KeySplitTable1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_high, 255, 243, 0, 1
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_low, 255, 249, 0, 222
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B4830 0, 7, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88_glockenspiel, 255, 247, 0, 222
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88_xylophone, 255, 248, 184, 214
	voice_directsound 60, 0, DirectSoundWaveData_sc88_tubular_bell, 255, 249, 0, 235
	voice_square_1_alt 60, 0, 0, 1, 0, 15, 5, 1
	voice_square_2_alt 60, 0, 1, 0, 15, 5, 1
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B4920 0, 7, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88_organ2, 255, 172, 255, 200
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88_accordion, 162, 144, 252, 214
	voice_directsound 60, 0, DirectSoundWaveData_sc88_organ2, 67, 247, 244, 200
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88_nylon_str_guitar, 255, 253, 229, 222
	voice_directsound 60, 0, DirectSoundWaveData_sc88_nylon_str_guitar, 128, 248, 51, 205
	voice_directsound 60, 0, DirectSoundWaveData_sc88_pick_bass, 255, 253, 236, 222
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B4890 0, 7, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_overdrive_guitar, 255, 253, 51, 64
	voice_directsound 60, 0, DirectSoundWaveData_unused_electric_guitar, 255, 251, 229, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B4850 0, 7, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88_pick_bass, 255, 251, 0, 222
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88_fretless_bass, 255, 0, 255, 214
	voice_directsound 60, 0, DirectSoundWaveData_sc88_fretless_bass, 255, 251, 0, 206
	voice_directsound 60, 0, DirectSoundWaveData_jv1080_slap_bass, 255, 0, 255, 230
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88_synth_bass, 255, 0, 255, 230
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 15, 5, 1
	voice_square_2_alt 60, 0, 2, 0, 15, 5, 1
	voice_directsound 60, 0, DirectSoundWaveData_sc88_wind, 37, 244, 236, 235
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88_pizzicato_strings, 255, 232, 153, 211
	voice_directsound 60, 0, DirectSoundWaveData_sc88_harp, 255, 245, 0, 221
	voice_directsound 60, 0, DirectSoundWaveData_sc88_timpani, 255, 249, 0, 224
	voice_keysplit voicegroup006, KeySplitTable2
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B4880 0, 7, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B48A0 0, 7, 15, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 15, 0, 2
	voice_square_2_alt 60, 0, 2, 0, 15, 0, 2
	voice_directsound 60, 0, DirectSoundWaveData_sc88_square_wave, 255, 250, 0, 200
	voice_directsound 60, 0, DirectSoundWaveData_sc88_bubbles, 254, 0, 255, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup007, KeySplitTable3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup008, KeySplitTable4
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B4870 0, 7, 15, 0
	voice_keysplit voicegroup009, KeySplitTable5
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_high, 255, 253, 51, 64
	voice_square_2_alt 60, 0, 1, 1, 6, 10, 2
	voice_square_2_alt 60, 0, 0, 1, 6, 10, 2
	voice_square_1_alt 60, 0, 0, 1, 1, 6, 10, 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 0, 1, 6, 10, 2
	voice_square_2_alt 60, 0, 2, 1, 6, 10, 2
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_oboe, 255, 243, 229, 228
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_low, 255, 253, 51, 64
	voice_square_2_alt 60, 0, 1, 2, 15, 13, 5
	voice_directsound 60, 0, DirectSoundWaveData_unused_sd90_oboe, 255, 243, 236, 228
	voice_square_1_alt 60, 0, 0, 2, 1, 6, 10, 2
	voice_directsound 60, 0, DirectSoundWaveData_sc88_flute, 255, 247, 224, 214
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B4840, 0, 7, 15, 0
	voice_square_1_alt 60, 0, 0, 1, 2, 15, 13, 2
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 255, 200
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_whistle, 255, 247, 210, 214
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 8, 1
	voice_square_2_alt 60, 0, 2, 0, 2, 8, 1
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 8, 1
	voice_square_2_alt 60, 0, 1, 0, 2, 8, 1
	voice_square_1_alt 60, 0, 0, 0, 0, 2, 8, 1
	voice_square_2_alt 60, 0, 0, 0, 2, 8, 1
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_2_alt 60, 0, 2, 0, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 15, 0
	voice_square_2_alt 60, 0, 1, 0, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 0, 0, 0, 15, 0
	voice_square_2_alt 60, 0, 0, 0, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 0, 0
	voice_square_2_alt 60, 0, 2, 0, 2, 0, 0
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 0, 0
	voice_square_2_alt 60, 0, 1, 0, 2, 0, 0
	voice_square_1_alt 60, 0, 0, 0, 0, 2, 0, 0
	voice_square_2_alt 60, 0, 0, 0, 2, 0, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 4, 0, 0
	voice_square_2_alt 60, 0, 2, 0, 4, 0, 0
	voice_square_1_alt 60, 0, 0, 1, 0, 4, 0, 0
	voice_square_2_alt 60, 0, 1, 0, 4, 0, 0
	voice_square_1_alt 60, 0, 0, 0, 0, 4, 0, 0
	voice_square_2_alt 60, 0, 0, 0, 4, 0, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_steinway_b_piano, 255, 200, 51, 222
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_noise_alt 60, 0, 0, 0, 0, 15, 0
	voice_noise_alt 60, 0, 0, 0, 1, 6, 2
	voice_noise_alt 60, 0, 0, 0, 2, 4, 0
	voice_noise_alt 60, 0, 0, 0, 1, 0, 0
