CherrygroveCity_GuideGentsHouse_MapScripts::
	.byte 0

CherrygroveCity_GuideGentsHouse_EventScript_GuideGent::
	msgbox CherrygroveCity_GuideGentsHouse_Text_GuideGent, MSGBOX_NPC
	end

CherrygroveCity_GuideGentsHouse_Text_GuideGent:
	.string "When I was a wee lad, I was a\n"
	.string "hot-shot TRAINER!\p"
	.string "Here's a word of advice:\n"
	.string "Catch lots of POKéMON!\l"
	.string "Treat them all with kindness!$"
