CianwoodCity_House_MapScripts::
	.byte 0


CianwoodCity_House_Eventscript_LittleGirl::
	msgbox CianwoodCity_House_Eventscript_LittleGirl_Text_0, MSGBOX_NPC
	end


CianwoodCity_House_Eventscript_Girl::
	msgbox CianwoodCity_House_Eventscript_Girl_Text_0, MSGBOX_NPC
	end


CianwoodCity_House_Eventscript_Woman::
	msgbox CianwoodCity_House_Eventscript_Woman_Text_0, MSGBOX_NPC
	end


CianwoodCity_House_Eventscript_LittleGirl_Text_0:
	.string "I've heard that the whirlpools\naround the islands are caused by the\lsea creature.\pYou might need a special move to get\npast them.$"

CianwoodCity_House_Eventscript_Girl_Text_0:
	.string "I heard that you can only see it if\nyou have a SILVER WING.\pIt must have the same scent as the\ncreature.$"

CianwoodCity_House_Eventscript_Woman_Text_0:
	.string "You came from OLIVINE?\pDo you remember the four islands\nalong the way?\pI heard that a mythical sea creature\nis hiding in them.$"
