GoldenrodCity_BillsHouse_MapScripts:: @ 8215EB3
	.byte 0

GoldenrodCity_BillsHouse_EventScript_PokefanF:: @ 8215EB4
	msgbox GoldenrodCity_BillsHouse_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

GoldenrodCity_BillsHouse_EventScript_LittleGirl:: @ 8215EBD
	msgbox GoldenrodCity_BillsHouse_Text_RoxanneKnowsALot, MSGBOX_NPC
	end

GoldenrodCity_BillsHouse_Text_TrainerSchoolExcellent: @ 8215EC6
	.string "The TRAINER'S SCHOOL is excellent.\p"
	.string "If you study there, you could even\n"
	.string "become a GYM LEADER.$"

GoldenrodCity_BillsHouse_Text_RoxanneKnowsALot: @ 8215F21
	.string "ROXANNE, the GYM LEADER, really knows\n"
	.string "a lot about POKéMON.\p"
	.string "She's really strong, too!$"

