#ifndef GUARD_CONSTANTS_DAY_NIGHT_H
#define GUARD_CONSTANTS_DAY_NIGHT_H

#define HOUR_MORNING 4
#define HOUR_DAY 10
#define HOUR_NIGHT 20

#define TIME_MORNING 0
#define TIME_DAY 1
#define TIME_NIGHT 2
#define TIMES_OF_DAY_COUNT 3

#define DAY_SUNDAY 0
#define DAY_MONDAY 1
#define DAY_TUESDAY 2
#define DAY_WEDNESDAY 3
#define DAY_THURSDAY 4
#define DAY_FRIDAY 5
#define DAY_SATURDAY 6

#endif  // GUARD_CONSTANTS_DAY_NIGHT_H
