#ifndef GUARD_CONSTANTS_FIELD_SPECIALS_H
#define GUARD_CONSTANTS_FIELD_SPECIALS_H

// PC Locations
#define PC_LOCATION_OTHER           0
#define PC_LOCATION_PLAYERS_HOUSE  1

// SS Tidal Locations
#define SS_TIDAL_LOCATION_CURRENTS  0
#define SS_TIDAL_LOCATION_SLATEPORT 1
#define SS_TIDAL_LOCATION_LILYCOVE  2
#define SS_TIDAL_LOCATION_ROUTE124  3
#define SS_TIDAL_LOCATION_ROUTE131  4

#define SS_TIDAL_BOARD_SLATEPORT     1
#define SS_TIDAL_DEPART_SLATEPORT    2
#define SS_TIDAL_HALFWAY_LILYCOVE    3
#define SS_TIDAL_LAND_LILYCOVE       4
#define SS_TIDAL_BOARD_LILYCOVE      5
#define SS_TIDAL_DEPART_LILYCOVE     6
#define SS_TIDAL_HALFWAY_SLATEPORT   7
#define SS_TIDAL_LAND_SLATEPORT      8
#define SS_TIDAL_EXIT_CURRENTS_RIGHT 9
#define SS_TIDAL_EXIT_CURRENTS_LEFT  10

#define SS_TIDAL_MAX_STEPS 205

// Scrollable Multichoice Menus
#define SCROLL_MULTI_DAY_OF_WEEK                           0
#define SCROLL_MULTI_BLUE_CARD_PRIZES                      1
#define SCROLL_MULTI_GOLDENROD_DEPT_STORE_FLOORS           2
#define SCROLL_MULTI_BF_EXCHANGE_CORNER_DECOR_VENDOR_1     3
#define SCROLL_MULTI_BF_EXCHANGE_CORNER_DECOR_VENDOR_2     4
#define SCROLL_MULTI_BF_EXCHANGE_CORNER_VITAMIN_VENDOR     5
#define SCROLL_MULTI_BF_EXCHANGE_CORNER_HOLD_ITEM_VENDOR   6
#define SCROLL_MULTI_BERRY_POWDER_VENDOR                   7
#define SCROLL_MULTI_BF_RECEPTIONIST                       8
#define SCROLL_MULTI_BF_MOVE_TUTOR_1                       9
#define SCROLL_MULTI_BF_MOVE_TUTOR_2                      10
#define SCROLL_MULTI_SS_TIDAL_DESTINATION                 11
#define SCROLL_MULTI_BATTLE_TENT_RULES                    12
#define SCROLL_MULTI_CELADON_DEPT_STORE_FLOORS            13

#define MAX_SCROLL_MULTI_ON_SCREEN 7
#define MAX_SCROLL_MULTI_LENGTH 16

// Elevator Floor Numbers
#define ELEVATOR_FLOORNUM_B4F       0
#define ELEVATOR_FLOORNUM_B3F       1
#define ELEVATOR_FLOORNUM_B2F       2
#define ELEVATOR_FLOORNUM_B1F       3
#define ELEVATOR_FLOORNUM_1F        4
#define ELEVATOR_FLOORNUM_2F        5
#define ELEVATOR_FLOORNUM_3F        6
#define ELEVATOR_FLOORNUM_4F        7
#define ELEVATOR_FLOORNUM_5F        8
#define ELEVATOR_FLOORNUM_6F        9
#define ELEVATOR_FLOORNUM_7F       10
#define ELEVATOR_FLOORNUM_8F       11
#define ELEVATOR_FLOORNUM_9F       12
#define ELEVATOR_FLOORNUM_10F      13
#define ELEVATOR_FLOORNUM_11F      14
#define ELEVATOR_FLOORNUM_ROOFTOP  15

// Lilycove Pokemon Trainer Fan Club
#define NUM_TRAINER_FAN_CLUB_MEMBERS  8

#define FANCLUB_GOT_FIRST_FANS 7
#define FANCLUB_MEMBER1        8
#define FANCLUB_MEMBER2        9
#define FANCLUB_MEMBER3        10
#define FANCLUB_MEMBER4        11
#define FANCLUB_MEMBER5        12
#define FANCLUB_MEMBER6        13
#define FANCLUB_MEMBER7        14
#define FANCLUB_MEMBER8        15

#define FANCOUNTER_DEFEATED_DRAKE    0
#define FANCOUNTER_BATTLED_AT_BASE   1
#define FANCOUNTER_FINISHED_CONTEST  2
#define FANCOUNTER_USED_BATTLE_TOWER 3

#define SPECIALMON_KENYA 0

#endif // GUARD_CONSTANTS_FIELD_SPECIALS_H
