#ifndef GUARD_CONSTANTS_FRUIT_TREES_H
#define GUARD_CONSTANTS_FRUIT_TREES_H

#define FRUIT_TREE_ROUTE_29      0
#define FRUIT_TREE_ROUTE_30_1    1
#define FRUIT_TREE_ROUTE_30_2    2

#endif // GUARD_CONSTANTS_FRUIT_TREES_H
