#ifndef GUARD_CONSTANTS_FRUIT_TREES_H
#define GUARD_CONSTANTS_FRUIT_TREES_H

#define FRUITTREE_ROUTE_29      0
#define FRUITTREE_ROUTE_30_1    1
#define FRUITTREE_ROUTE_30_2    2

#endif // GUARD_CONSTANTS_FRUIT_TREES_H
