#ifndef GUARD_CONSTANTS_GYM_LEADER_REMATCH_H
#define GUARD_CONSTANTS_GYM_LEADER_REMATCH_H

#define REMATCH_JOEY 0
#define REMATCH_WADE 1
#define REMATCH_LIZ 2
#define REMATCH_RALPH 3
#define REMATCH_ANTHONY 4
#define REMATCH_TODD 5
#define REMATCH_GINA 6
#define REMATCH_ARNIE 7
#define REMATCH_JACK 8
#define REMATCH_ALAN 9
#define REMATCH_DANA 10
#define REMATCH_CHAD 11
#define REMATCH_HUEY 12
#define REMATCH_TULLY 13
#define REMATCH_TIFFANY 14
#define REMATCH_BRENT 15
#define REMATCH_WILTON 16
#define REMATCH_VANCE 17
#define REMATCH_PARRY 18
#define REMATCH_ERIN 19
#define REMATCH_JOSE 20
#define REMATCH_REENA 21
#define REMATCH_GAVEN 22
#define REMATCH_BETH 23
#define REMATCH_TABLE_ENTRIES 24 // The total number of rematch entries.

#endif  // GUARD_CONSTANTS_GYM_LEADER_REMATCH_H