#ifndef GUARD_CONSTANTS_HEAL_LOCATIONS_H
#define GUARD_CONSTANTS_HEAL_LOCATIONS_H

#define HEAL_LOCATION_NEW_BARK_TOWN 1
#define HEAL_LOCATION_CHERRYGROVE_CITY 2
#define HEAL_LOCATION_VIOLET_CITY 3
#define HEAL_LOCATION_ROUTE32 4
#define HEAL_LOCATION_AZALEA_TOWN 5
#define HEAL_LOCATION_GOLDENROD_CITY 6
#define HEAL_LOCATION_SOUTHERN_ISLAND_EXTERIOR 7
#define HEAL_LOCATION_BATTLE_FRONTIER_OUTSIDE_EAST 8

#endif // GUARD_CONSTANTS_HEAL_LOCATIONS_H
