#ifndef GUARD_CONSTANTS_HEAL_LOCATIONS_H
#define GUARD_CONSTANTS_HEAL_LOCATIONS_H

#define HEAL_LOCATION_NEW_BARK_TOWN 1
#define HEAL_LOCATION_CHERRYGROVE_CITY 2
#define HEAL_LOCATION_VIOLET_CITY 3
#define HEAL_LOCATION_ROUTE32 4
#define HEAL_LOCATION_AZALEA_TOWN 5
#define HEAL_LOCATION_GOLDENROD_CITY 6
#define HEAL_LOCATION_SOUTHERN_ISLAND_EXTERIOR 7
#define HEAL_LOCATION_BATTLE_FRONTIER_OUTSIDE_EAST 8
#define HEAL_LOCATION_ECRUTEAK_CITY 9
#define HEAL_LOCATION_OLIVINE_CITY 10
#define HEAL_LOCATION_CIANWOOD_CITY 11
#define HEAL_LOCATION_MAHOGANY_TOWN 12
#define HEAL_LOCATION_BLACKTHORN_CITY 13
#define HEAL_LOCATION_LAKE_OF_RAGE 14
#define HEAL_LOCATION_SILVER_CAVE_OUTSIDE 15
#define HEAL_LOCATION_PALLET_TOWN 16
#define HEAL_LOCATION_VIRIDIAN_CITY 17
#define HEAL_LOCATION_PEWTER_CITY 18
#define HEAL_LOCATION_CERULEAN_CITY 19
#define HEAL_LOCATION_LAVENDER_TOWN 20
#define HEAL_LOCATION_VERMILION_CITY 21
#define HEAL_LOCATION_CELADON_CITY 22
#define HEAL_LOCATION_FUCHSIA_CITY 23
#define HEAL_LOCATION_CINNABAR_ISLAND 24
#define HEAL_LOCATION_SAFFRON_CITY 25
#define HEAL_LOCATION_ROUTE10 26

#endif // GUARD_CONSTANTS_HEAL_LOCATIONS_H
