#ifndef GUARD_CONSTANTS_HEAL_LOCATIONS_H
#define GUARD_CONSTANTS_HEAL_LOCATIONS_H

#define HEAL_LOCATION_NEW_BARK_TOWN 1
#define HEAL_LOCATION_CHERRYGROVE_CITY 2
#define HEAL_LOCATION_VIOLET_CITY 3
#define HEAL_LOCATION_ROUTE32 4
#define HEAL_LOCATION_AZALEA_TOWN 5
#define HEAL_LOCATION_GOLDENROD_CITY 6
#define HEAL_LOCATION_ECRUTEAK_CITY 7
#define HEAL_LOCATION_OLIVINE_CITY 8
#define HEAL_LOCATION_CIANWOOD_CITY 9
#define HEAL_LOCATION_MAHOGANY_TOWN 10
#define HEAL_LOCATION_BLACKTHORN_CITY 11
#define HEAL_LOCATION_LAKE_OF_RAGE 12
#define HEAL_LOCATION_SILVER_CAVE_OUTSIDE 13
#define HEAL_LOCATION_PALLET_TOWN 14
#define HEAL_LOCATION_VIRIDIAN_CITY 15
#define HEAL_LOCATION_PEWTER_CITY 16
#define HEAL_LOCATION_CERULEAN_CITY 17
#define HEAL_LOCATION_LAVENDER_TOWN 18
#define HEAL_LOCATION_VERMILION_CITY 19
#define HEAL_LOCATION_CELADON_CITY 20
#define HEAL_LOCATION_FUCHSIA_CITY 21
#define HEAL_LOCATION_CINNABAR_ISLAND 22
#define HEAL_LOCATION_SAFFRON_CITY 23
#define HEAL_LOCATION_ROUTE10 24
#define HEAL_LOCATION_ROUTE23 25
#define HEAL_LOCATION_SOUTHERN_ISLAND_EXTERIOR 26
#define HEAL_LOCATION_BATTLE_FRONTIER_OUTSIDE_EAST 27
#define HEAL_LOCATION_FAST_SHIP_CABIN 28
#define HEAL_LOCATION_ROUTE3 29

#endif // GUARD_CONSTANTS_HEAL_LOCATIONS_H
