#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

// Map Group 0
#define MAP_NEW_BARK_TOWN         (0 | (0 << 8))
#define MAP_CHERRYGROVE_CITY      (1 | (0 << 8))
#define MAP_VIOLET_CITY           (2 | (0 << 8))
#define MAP_AZALEA_TOWN           (3 | (0 << 8))
#define MAP_GOLDENROD_CITY        (4 | (0 << 8))
#define MAP_ECRUTEAK_CITY         (5 | (0 << 8))
#define MAP_OLIVINE_CITY          (6 | (0 << 8))
#define MAP_CIANWOOD_CITY         (7 | (0 << 8))
#define MAP_MAHOGANY_TOWN         (8 | (0 << 8))
#define MAP_BLACKTHORN_CITY       (9 | (0 << 8))
#define MAP_ROUTE29               (10 | (0 << 8))
#define MAP_ROUTE30               (11 | (0 << 8))
#define MAP_ROUTE31               (12 | (0 << 8))
#define MAP_ROUTE32               (13 | (0 << 8))
#define MAP_ROUTE33               (14 | (0 << 8))
#define MAP_ROUTE34               (15 | (0 << 8))
#define MAP_ROUTE35               (16 | (0 << 8))
#define MAP_ROUTE36               (17 | (0 << 8))
#define MAP_ROUTE37               (18 | (0 << 8))
#define MAP_ROUTE38               (19 | (0 << 8))
#define MAP_ROUTE39               (20 | (0 << 8))
#define MAP_ROUTE40               (21 | (0 << 8))
#define MAP_ROUTE41               (22 | (0 << 8))
#define MAP_ROUTE42               (23 | (0 << 8))
#define MAP_ROUTE43               (24 | (0 << 8))
#define MAP_ROUTE44               (25 | (0 << 8))
#define MAP_ROUTE45               (26 | (0 << 8))
#define MAP_ROUTE46               (27 | (0 << 8))
#define MAP_LAKE_OF_RAGE          (28 | (0 << 8))
#define MAP_RUINS_OF_ALPH_OUTSIDE (29 | (0 << 8))
#define MAP_SILVER_CAVE_OUTSIDE   (30 | (0 << 8))
#define MAP_PALLET_TOWN           (31 | (0 << 8))
#define MAP_VIRIDIAN_CITY         (32 | (0 << 8))
#define MAP_PEWTER_CITY           (33 | (0 << 8))
#define MAP_CERULEAN_CITY         (34 | (0 << 8))
#define MAP_LAVENDER_TOWN         (35 | (0 << 8))
#define MAP_VERMILION_CITY        (36 | (0 << 8))
#define MAP_CELADON_CITY          (37 | (0 << 8))
#define MAP_FUCHSIA_CITY          (38 | (0 << 8))
#define MAP_CINNABAR_ISLAND       (39 | (0 << 8))
#define MAP_SAFFRON_CITY          (40 | (0 << 8))
#define MAP_ROUTE1                (41 | (0 << 8))
#define MAP_ROUTE2                (42 | (0 << 8))
#define MAP_ROUTE3                (43 | (0 << 8))
#define MAP_ROUTE4                (44 | (0 << 8))
#define MAP_ROUTE5                (45 | (0 << 8))
#define MAP_ROUTE6                (46 | (0 << 8))
#define MAP_ROUTE7                (47 | (0 << 8))
#define MAP_ROUTE8                (48 | (0 << 8))
#define MAP_ROUTE9                (49 | (0 << 8))
#define MAP_ROUTE10               (50 | (0 << 8))
#define MAP_ROUTE11               (51 | (0 << 8))
#define MAP_ROUTE12               (52 | (0 << 8))
#define MAP_ROUTE13               (53 | (0 << 8))
#define MAP_ROUTE14               (54 | (0 << 8))
#define MAP_ROUTE15               (55 | (0 << 8))
#define MAP_ROUTE16               (56 | (0 << 8))
#define MAP_ROUTE17               (57 | (0 << 8))
#define MAP_ROUTE18               (58 | (0 << 8))
#define MAP_ROUTE19               (59 | (0 << 8))
#define MAP_ROUTE20               (60 | (0 << 8))
#define MAP_ROUTE21               (61 | (0 << 8))
#define MAP_ROUTE22               (62 | (0 << 8))
#define MAP_ROUTE23               (63 | (0 << 8))
#define MAP_ROUTE24               (64 | (0 << 8))
#define MAP_ROUTE25               (65 | (0 << 8))
#define MAP_ROUTE26               (66 | (0 << 8))
#define MAP_ROUTE27               (67 | (0 << 8))
#define MAP_ROUTE28               (68 | (0 << 8))

// Map Group 1
#define MAP_NEW_BARK_TOWN_PLAYERS_HOUSE_1F   (0 | (1 << 8))
#define MAP_NEW_BARK_TOWN_PLAYERS_HOUSE_2F   (1 | (1 << 8))
#define MAP_NEW_BARK_TOWN_ELMS_HOUSE         (2 | (1 << 8))
#define MAP_NEW_BARK_TOWN_NEIGHBORS_HOUSE    (3 | (1 << 8))
#define MAP_NEW_BARK_TOWN_PROFESSOR_ELMS_LAB (4 | (1 << 8))

// Map Group 2
#define MAP_CHERRYGROVE_CITY_POKEMON_CENTER_1F (0 | (2 << 8))
#define MAP_CHERRYGROVE_CITY_POKEMON_CENTER_2F (1 | (2 << 8))
#define MAP_CHERRYGROVE_CITY_MART              (2 | (2 << 8))
#define MAP_CHERRYGROVE_CITY_GUIDE_GENTS_HOUSE (3 | (2 << 8))
#define MAP_CHERRYGROVE_CITY_HOUSE1            (4 | (2 << 8))
#define MAP_CHERRYGROVE_CITY_HOUSE2            (5 | (2 << 8))

// Map Group 3
#define MAP_VIOLET_CITY_POKEMON_CENTER_1F (0 | (3 << 8))
#define MAP_VIOLET_CITY_POKEMON_CENTER_2F (1 | (3 << 8))
#define MAP_VIOLET_CITY_MART              (2 | (3 << 8))
#define MAP_VIOLET_CITY_GYM               (3 | (3 << 8))
#define MAP_VIOLET_CITY_EARLS_ACADEMY     (4 | (3 << 8))
#define MAP_VIOLET_CITY_HOUSE1            (5 | (3 << 8))
#define MAP_VIOLET_CITY_HOUSE2            (6 | (3 << 8))

// Map Group 4
#define MAP_AZALEA_TOWN_POKEMON_CENTER_1F (0 | (4 << 8))
#define MAP_AZALEA_TOWN_POKEMON_CENTER_2F (1 | (4 << 8))
#define MAP_AZALEA_TOWN_MART              (2 | (4 << 8))
#define MAP_AZALEA_TOWN_GYM               (3 | (4 << 8))
#define MAP_AZALEA_TOWN_KURTS_HOUSE       (4 | (4 << 8))
#define MAP_AZALEA_TOWN_CHARCOAL_KILN     (5 | (4 << 8))

// Map Group 5
#define MAP_GOLDENROD_CITY_POKEMON_CENTER_1F          (0 | (5 << 8))
#define MAP_GOLDENROD_CITY_POKEMON_CENTER_2F          (1 | (5 << 8))
#define MAP_GOLDENROD_CITY_POKECOM_CENTER_ADMIN_ROOM  (2 | (5 << 8))
#define MAP_GOLDENROD_CITY_GYM                        (3 | (5 << 8))
#define MAP_GOLDENROD_CITY_GAME_CORNER                (4 | (5 << 8))
#define MAP_GOLDENROD_CITY_MAGNET_TRAIN_STATION       (5 | (5 << 8))
#define MAP_GOLDENROD_CITY_NAME_RATERS_HOUSE          (6 | (5 << 8))
#define MAP_GOLDENROD_CITY_FLOWER_SHOP                (7 | (5 << 8))
#define MAP_GOLDENROD_CITY_BIKE_SHOP                  (8 | (5 << 8))
#define MAP_GOLDENROD_CITY_BILLS_FAMILYS_HOUSE        (9 | (5 << 8))
#define MAP_GOLDENROD_CITY_UNDERGROUND_NORTH_ENTRANCE (10 | (5 << 8))
#define MAP_GOLDENROD_CITY_UNDERGROUND_SOUTH_ENTRANCE (11 | (5 << 8))
#define MAP_GOLDENROD_CITY_UNDERGROUND                (12 | (5 << 8))
#define MAP_GOLDENROD_CITY_HOUSE1                     (13 | (5 << 8))
#define MAP_GOLDENROD_CITY_HOUSE2                     (14 | (5 << 8))
#define MAP_GOLDENROD_CITY_DEPT_STORE_1F              (15 | (5 << 8))
#define MAP_GOLDENROD_CITY_DEPT_STORE_2F              (16 | (5 << 8))
#define MAP_GOLDENROD_CITY_DEPT_STORE_3F              (17 | (5 << 8))
#define MAP_GOLDENROD_CITY_DEPT_STORE_4F              (18 | (5 << 8))
#define MAP_GOLDENROD_CITY_DEPT_STORE_5F              (19 | (5 << 8))
#define MAP_GOLDENROD_CITY_DEPT_STORE_6F              (20 | (5 << 8))
#define MAP_GOLDENROD_CITY_DEPT_STORE_ROOFTOP         (21 | (5 << 8))
#define MAP_GOLDENROD_CITY_DEPT_STORE_ELEVATOR        (22 | (5 << 8))
#define MAP_GOLDENROD_CITY_DEPT_STORE_B1F             (23 | (5 << 8))

// Map Group 6
#define MAP_ECRUTEAK_CITY_POKEMON_CENTER_1F (0 | (6 << 8))
#define MAP_ECRUTEAK_CITY_POKEMON_CENTER_2F (1 | (6 << 8))
#define MAP_ECRUTEAK_CITY_MART              (2 | (6 << 8))
#define MAP_ECRUTEAK_CITY_GYM               (3 | (6 << 8))
#define MAP_ECRUTEAK_CITY_DANCE_THEATER     (4 | (6 << 8))
#define MAP_ECRUTEAK_CITY_TIN_TOWER_GATE    (5 | (6 << 8))
#define MAP_ECRUTEAK_CITY_WISE_TRIOS_ROOM   (6 | (6 << 8))
#define MAP_ECRUTEAK_CITY_HOUSE1            (7 | (6 << 8))
#define MAP_ECRUTEAK_CITY_HOUSE2            (8 | (6 << 8))

// Map Group 7
#define MAP_OLIVINE_CITY_POKEMON_CENTER_1F (0 | (7 << 8))
#define MAP_OLIVINE_CITY_POKEMON_CENTER_2F (1 | (7 << 8))
#define MAP_OLIVINE_CITY_MART              (2 | (7 << 8))
#define MAP_OLIVINE_CITY_GYM               (3 | (7 << 8))
#define MAP_OLIVINE_CITY_CAFE              (4 | (7 << 8))
#define MAP_OLIVINE_CITY_PORT_PASSAGE      (5 | (7 << 8))
#define MAP_OLIVINE_CITY_PORT              (6 | (7 << 8))
#define MAP_OLIVINE_CITY_HOUSE1            (7 | (7 << 8))
#define MAP_OLIVINE_CITY_HOUSE2            (8 | (7 << 8))
#define MAP_OLIVINE_CITY_HOUSE3            (9 | (7 << 8))

// Map Group 8
#define MAP_CIANWOOD_CITY_POKEMON_CENTER_1F (0 | (8 << 8))
#define MAP_CIANWOOD_CITY_POKEMON_CENTER_2F (1 | (8 << 8))
#define MAP_CIANWOOD_CITY_GYM               (2 | (8 << 8))
#define MAP_CIANWOOD_CITY_PHARMACY          (3 | (8 << 8))
#define MAP_CIANWOOD_CITY_PHOTO_STUDIO      (4 | (8 << 8))
#define MAP_CIANWOOD_CITY_MANIAS_HOUSE      (5 | (8 << 8))
#define MAP_CIANWOOD_CITY_POKE_SEERS_HOUSE  (6 | (8 << 8))
#define MAP_CIANWOOD_CITY_HOUSE             (7 | (8 << 8))

// Map Group 9
#define MAP_MAHOGANY_TOWN_POKEMON_CENTER_1F (0 | (9 << 8))
#define MAP_MAHOGANY_TOWN_POKEMON_CENTER_2F (1 | (9 << 8))
#define MAP_MAHOGANY_TOWN_GYM               (2 | (9 << 8))
#define MAP_MAHOGANY_TOWN_SHOP              (3 | (9 << 8))
#define MAP_MAHOGANY_TOWN_HOUSE             (4 | (9 << 8))

// Map Group 10
#define MAP_BLACKTHORN_CITY_POKEMON_CENTER_1F   (0 | (10 << 8))
#define MAP_BLACKTHORN_CITY_POKEMON_CENTER_2F   (1 | (10 << 8))
#define MAP_BLACKTHORN_CITY_MART                (2 | (10 << 8))
#define MAP_BLACKTHORN_CITY_GYM_1F              (3 | (10 << 8))
#define MAP_BLACKTHORN_CITY_GYM_2F              (4 | (10 << 8))
#define MAP_BLACKTHORN_CITY_MOVE_DELETERS_HOUSE (5 | (10 << 8))
#define MAP_BLACKTHORN_CITY_HOUSE1              (6 | (10 << 8))
#define MAP_BLACKTHORN_CITY_HOUSE2              (7 | (10 << 8))

// Map Group 11
#define MAP_ROUTE29_GATEHOUSE (0 | (11 << 8))

// Map Group 12
#define MAP_ROUTE30_BERRY_MANS_HOUSE  (0 | (12 << 8))
#define MAP_ROUTE30_MR_POKEMONS_HOUSE (1 | (12 << 8))

// Map Group 13
#define MAP_ROUTE31_GATEHOUSE (0 | (13 << 8))

// Map Group 14
#define MAP_ROUTE32_POKEMON_CENTER_1F (0 | (14 << 8))
#define MAP_ROUTE32_POKEMON_CENTER_2F (1 | (14 << 8))
#define MAP_ROUTE32_GATEHOUSE         (2 | (14 << 8))

// Map Group 15
#define MAP_ROUTE34_ILEX_EAST_GATEHOUSE  (0 | (15 << 8))
#define MAP_ROUTE34_ILEX_NORTH_GATEHOUSE (1 | (15 << 8))
#define MAP_ROUTE34_DAY_CARE             (2 | (15 << 8))

// Map Group 16
#define MAP_ROUTE35_GOLDENROD_GATEHOUSE     (0 | (16 << 8))
#define MAP_ROUTE35_NATIONAL_PARK_GATEHOUSE (1 | (16 << 8))

// Map Group 17
#define MAP_ROUTE36_RUINS_OF_ALPH_GATEHOUSE (0 | (17 << 8))
#define MAP_ROUTE36_NATIONAL_PARK_GATEHOUSE (1 | (17 << 8))

// Map Group 18
#define MAP_ROUTE38_GATEHOUSE (0 | (18 << 8))

// Map Group 19
#define MAP_ROUTE39_MOO_MOO_FARM_HOUSE (0 | (19 << 8))
#define MAP_ROUTE39_MOO_MOO_FARM_BARN  (1 | (19 << 8))

// Map Group 20
#define MAP_ROUTE40_GATEHOUSE (0 | (20 << 8))

// Map Group 21
#define MAP_ROUTE42_GATEHOUSE (0 | (21 << 8))

// Map Group 22
#define MAP_ROUTE43_GATEHOUSE1 (0 | (22 << 8))
#define MAP_ROUTE43_GATEHOUSE2 (1 | (22 << 8))

// Map Group 23
#define MAP_LAKE_OF_RAGE_HIDDEN_POWER_HOUSE  (0 | (23 << 8))
#define MAP_LAKE_OF_RAGE_FISHING_GURUS_HOUSE (1 | (23 << 8))

// Map Group 24
#define MAP_RUINS_OF_ALPH_RESEARCH_CENTER      (0 | (24 << 8))
#define MAP_RUINS_OF_ALPH_INNER_CHAMBER        (1 | (24 << 8))
#define MAP_RUINS_OF_ALPH_KABUTO_CHAMBER       (2 | (24 << 8))
#define MAP_RUINS_OF_ALPH_KABUTO_ITEM_ROOM     (3 | (24 << 8))
#define MAP_RUINS_OF_ALPH_KABUTO_WORD_ROOM     (4 | (24 << 8))
#define MAP_RUINS_OF_ALPH_OMANYTE_CHAMBER      (5 | (24 << 8))
#define MAP_RUINS_OF_ALPH_OMANYTE_ITEM_ROOM    (6 | (24 << 8))
#define MAP_RUINS_OF_ALPH_OMANYTE_WORD_ROOM    (7 | (24 << 8))
#define MAP_RUINS_OF_ALPH_AERODACTYL_CHAMBER   (8 | (24 << 8))
#define MAP_RUINS_OF_ALPH_AERODACTYL_ITEM_ROOM (9 | (24 << 8))
#define MAP_RUINS_OF_ALPH_AERODACTYL_WORD_ROOM (10 | (24 << 8))
#define MAP_RUINS_OF_ALPH_HO_OH_CHAMBER        (11 | (24 << 8))
#define MAP_RUINS_OF_ALPH_HO_OH_ITEM_ROOM      (12 | (24 << 8))
#define MAP_RUINS_OF_ALPH_HO_OH_WORD_ROOM      (13 | (24 << 8))

// Map Group 25
#define MAP_SILVER_CAVE_OUTSIDE_POKEMON_CENTER_1F (0 | (25 << 8))
#define MAP_SILVER_CAVE_OUTSIDE_POKEMON_CENTER_2F (1 | (25 << 8))

// Map Group 26
#define MAP_DARK_CAVE_SOUTH                    (0 | (26 << 8))
#define MAP_DARK_CAVE_B1F                      (1 | (26 << 8))
#define MAP_SPROUT_TOWER_1F                    (2 | (26 << 8))
#define MAP_SPROUT_TOWER_2F                    (3 | (26 << 8))
#define MAP_SPROUT_TOWER_3F                    (4 | (26 << 8))
#define MAP_UNION_CAVE_1F                      (5 | (26 << 8))
#define MAP_UNION_CAVE_B1F                     (6 | (26 << 8))
#define MAP_UNION_CAVE_B2F                     (7 | (26 << 8))
#define MAP_SLOWPOKE_WELL_B1F                  (8 | (26 << 8))
#define MAP_SLOWPOKE_WELL_B2F                  (9 | (26 << 8))
#define MAP_ILEX_FOREST                        (10 | (26 << 8))
#define MAP_RADIO_TOWER_1F                     (11 | (26 << 8))
#define MAP_RADIO_TOWER_2F                     (12 | (26 << 8))
#define MAP_RADIO_TOWER_3F                     (13 | (26 << 8))
#define MAP_RADIO_TOWER_4F                     (14 | (26 << 8))
#define MAP_RADIO_TOWER_5F                     (15 | (26 << 8))
#define MAP_NATIONAL_PARK                      (16 | (26 << 8))
#define MAP_NATIONAL_PARK_BUG_CATCHING_CONTEST (17 | (26 << 8))
#define MAP_BURNED_TOWER_1F                    (18 | (26 << 8))
#define MAP_BURNED_TOWER_B1F                   (19 | (26 << 8))
#define MAP_TIN_TOWER_1F                       (20 | (26 << 8))
#define MAP_TIN_TOWER_2F                       (21 | (26 << 8))
#define MAP_TIN_TOWER_3F                       (22 | (26 << 8))
#define MAP_TIN_TOWER_4F                       (23 | (26 << 8))
#define MAP_TIN_TOWER_5F                       (24 | (26 << 8))
#define MAP_TIN_TOWER_6F                       (25 | (26 << 8))
#define MAP_TIN_TOWER_7F                       (26 | (26 << 8))
#define MAP_TIN_TOWER_8F                       (27 | (26 << 8))
#define MAP_TIN_TOWER_9F                       (28 | (26 << 8))
#define MAP_TIN_TOWER_ROOF                     (29 | (26 << 8))
#define MAP_LIGHTHOUSE_1F                      (30 | (26 << 8))
#define MAP_LIGHTHOUSE_2F                      (31 | (26 << 8))
#define MAP_LIGHTHOUSE_3F                      (32 | (26 << 8))
#define MAP_LIGHTHOUSE_4F                      (33 | (26 << 8))
#define MAP_LIGHTHOUSE_5F                      (34 | (26 << 8))
#define MAP_LIGHTHOUSE_6F                      (35 | (26 << 8))
#define MAP_WHIRL_ISLANDS_1F_NE                (36 | (26 << 8))
#define MAP_WHIRL_ISLANDS_1F_NW                (37 | (26 << 8))
#define MAP_WHIRL_ISLANDS_1F_SE                (38 | (26 << 8))
#define MAP_WHIRL_ISLANDS_1F_SW                (39 | (26 << 8))
#define MAP_WHIRL_ISLANDS_B1F                  (40 | (26 << 8))
#define MAP_WHIRL_ISLANDS_B2F                  (41 | (26 << 8))
#define MAP_WHIRL_ISLANDS_CAVE                 (42 | (26 << 8))
#define MAP_WHIRL_ISLANDS_LUGIAS_CHAMBER       (43 | (26 << 8))
#define MAP_MT_MORTAR_1F_OUTER                 (44 | (26 << 8))
#define MAP_MT_MORTAR_1F_INNER                 (45 | (26 << 8))
#define MAP_MT_MORTAR_2F                       (46 | (26 << 8))
#define MAP_MT_MORTAR_B1F                      (47 | (26 << 8))
#define MAP_TEAM_ROCKET_BASE_B1F               (48 | (26 << 8))
#define MAP_TEAM_ROCKET_BASE_B2F               (49 | (26 << 8))
#define MAP_TEAM_ROCKET_BASE_B3F               (50 | (26 << 8))
#define MAP_ICE_PATH_1F                        (51 | (26 << 8))
#define MAP_ICE_PATH_B1F                       (52 | (26 << 8))
#define MAP_ICE_PATH_B2F_MAHOGANY              (53 | (26 << 8))
#define MAP_ICE_PATH_B2F_BLACKTHORN            (54 | (26 << 8))
#define MAP_ICE_PATH_B3F                       (55 | (26 << 8))
#define MAP_DRAGONS_DEN_ENTRANCE               (56 | (26 << 8))
#define MAP_DRAGONS_DEN                        (57 | (26 << 8))
#define MAP_DRAGONS_DEN_SHRINE                 (58 | (26 << 8))
#define MAP_FAST_SHIP_1F                       (59 | (26 << 8))
#define MAP_FAST_SHIP_B1F                      (60 | (26 << 8))
#define MAP_FAST_SHIP_CABINS_NNW_NNE_NE        (61 | (26 << 8))
#define MAP_FAST_SHIP_CABINS_SE_SSE_CAPTAINS   (62 | (26 << 8))
#define MAP_FAST_SHIP_CABINS_SW_SSW_NW         (63 | (26 << 8))
#define MAP_SILVER_CAVE_ROOM1                  (64 | (26 << 8))
#define MAP_SILVER_CAVE_ROOM2                  (65 | (26 << 8))
#define MAP_SILVER_CAVE_ROOM3                  (66 | (26 << 8))
#define MAP_SILVER_CAVE_ITEM_ROOMS             (67 | (26 << 8))

// Map Group 27
#define MAP_PALLET_TOWN_REDS_HOUSE_1F      (0 | (27 << 8))
#define MAP_PALLET_TOWN_REDS_HOUSE_2F      (1 | (27 << 8))
#define MAP_PALLET_TOWN_BLUES_HOUSE        (2 | (27 << 8))
#define MAP_PALLET_TOWN_PROFESSOR_OAKS_LAB (3 | (27 << 8))

// Map Group 28
#define MAP_VIRIDIAN_CITY_POKEMON_CENTER_1F (0 | (28 << 8))
#define MAP_VIRIDIAN_CITY_POKEMON_CENTER_2F (1 | (28 << 8))
#define MAP_VIRIDIAN_CITY_MART              (2 | (28 << 8))
#define MAP_VIRIDIAN_CITY_GYM               (3 | (28 << 8))
#define MAP_VIRIDIAN_CITY_HOUSE             (4 | (28 << 8))
#define MAP_VIRIDIAN_CITY_TRAINER_HOUSE_1F  (5 | (28 << 8))
#define MAP_VIRIDIAN_CITY_TRAINER_HOUSE_B1F (6 | (28 << 8))

// Map Group 29
#define MAP_PEWTER_CITY_POKEMON_CENTER_1F (0 | (29 << 8))
#define MAP_PEWTER_CITY_POKEMON_CENTER_2F (1 | (29 << 8))
#define MAP_PEWTER_CITY_MART              (2 | (29 << 8))
#define MAP_PEWTER_CITY_GYM               (3 | (29 << 8))
#define MAP_PEWTER_CITY_HOUSE1            (4 | (29 << 8))
#define MAP_PEWTER_CITY_HOUSE2            (5 | (29 << 8))
#define MAP_PEWTER_CITY_MUSEUM_1F         (6 | (29 << 8))
#define MAP_PEWTER_CITY_MUSEUM_2F         (7 | (29 << 8))

// Map Group 30
#define MAP_CERULEAN_CITY_POKEMON_CENTER_1F (0 | (30 << 8))
#define MAP_CERULEAN_CITY_POKEMON_CENTER_2F (1 | (30 << 8))
#define MAP_CERULEAN_CITY_MART              (2 | (30 << 8))
#define MAP_CERULEAN_CITY_GYM               (3 | (30 << 8))
#define MAP_CERULEAN_CITY_HOUSE1            (4 | (30 << 8))
#define MAP_CERULEAN_CITY_HOUSE2            (5 | (30 << 8))
#define MAP_CERULEAN_CITY_HOUSE3            (6 | (30 << 8))

// Map Group 31
#define MAP_VERMILION_CITY_POKEMON_CENTER_1F (0 | (31 << 8))
#define MAP_VERMILION_CITY_POKEMON_CENTER_2F (1 | (31 << 8))
#define MAP_VERMILION_CITY_MART              (2 | (31 << 8))
#define MAP_VERMILION_CITY_GYM               (3 | (31 << 8))
#define MAP_VERMILION_CITY_POKEMON_FAN_CLUB  (4 | (31 << 8))
#define MAP_VERMILION_CITY_PORT_PASSAGE      (5 | (31 << 8))
#define MAP_VERMILION_CITY_PORT              (6 | (31 << 8))
#define MAP_VERMILION_CITY_HOUSE1            (7 | (31 << 8))
#define MAP_VERMILION_CITY_HOUSE2            (8 | (31 << 8))
#define MAP_VERMILION_CITY_HOUSE3            (9 | (31 << 8))

// Map Group 32
#define MAP_LAVENDER_TOWN_POKEMON_CENTER_1F       (0 | (32 << 8))
#define MAP_LAVENDER_TOWN_POKEMON_CENTER_2F       (1 | (32 << 8))
#define MAP_LAVENDER_TOWN_MART                    (2 | (32 << 8))
#define MAP_LAVENDER_TOWN_RADIO_TOWER_1F          (3 | (32 << 8))
#define MAP_LAVENDER_TOWN_VOLUNTEER_POKEMON_HOUSE (4 | (32 << 8))
#define MAP_LAVENDER_TOWN_SOUL_HOUSE              (5 | (32 << 8))
#define MAP_LAVENDER_TOWN_NAME_RATERS_HOUSE       (6 | (32 << 8))
#define MAP_LAVENDER_TOWN_HOUSE                   (7 | (32 << 8))

// Map Group 33
#define MAP_CELADON_CITY_POKEMON_CENTER_1F         (0 | (33 << 8))
#define MAP_CELADON_CITY_POKEMON_CENTER_2F         (1 | (33 << 8))
#define MAP_CELADON_CITY_GYM                       (2 | (33 << 8))
#define MAP_CELADON_CITY_GAME_CORNER               (3 | (33 << 8))
#define MAP_CELADON_CITY_GAME_CORNER_PRIZE_ROOM    (4 | (33 << 8))
#define MAP_CELADON_CITY_RESTAURANT                (5 | (33 << 8))
#define MAP_CELADON_CITY_MANSION_1F                (6 | (33 << 8))
#define MAP_CELADON_CITY_MANSION_2F                (7 | (33 << 8))
#define MAP_CELADON_CITY_MANSION_3F                (8 | (33 << 8))
#define MAP_CELADON_CITY_MANSION_ROOF              (9 | (33 << 8))
#define MAP_CELADON_CITY_MANSION_PENTHOUSE         (10 | (33 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_1F       (11 | (33 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_2F       (12 | (33 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_3F       (13 | (33 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_4F       (14 | (33 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_5F       (15 | (33 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_ROOF     (16 | (33 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_ELEVATOR (17 | (33 << 8))

// Map Group 34
#define MAP_SAFFRON_CITY_POKEMON_CENTER_1F    (0 | (34 << 8))
#define MAP_SAFFRON_CITY_POKEMON_CENTER_2F    (1 | (34 << 8))
#define MAP_SAFFRON_CITY_MART                 (2 | (34 << 8))
#define MAP_SAFFRON_CITY_GYM                  (3 | (34 << 8))
#define MAP_SAFFRON_CITY_DOJO                 (4 | (34 << 8))
#define MAP_SAFFRON_CITY_COPYCATS_HOUSE_1F    (5 | (34 << 8))
#define MAP_SAFFRON_CITY_COPYCATS_HOUSE_2F    (6 | (34 << 8))
#define MAP_SAFFRON_CITY_MAGNET_TRAIN_STATION (7 | (34 << 8))
#define MAP_SAFFRON_CITY_SILPH_CO_1F          (8 | (34 << 8))
#define MAP_SAFFRON_CITY_MR_PSYCHICS_HOUSE    (9 | (34 << 8))

// Map Group 35
#define MAP_FUCHSIA_CITY_POKEMON_CENTER_1F  (0 | (35 << 8))
#define MAP_FUCHSIA_CITY_POKEMON_CENTER_2F  (1 | (35 << 8))
#define MAP_FUCHSIA_CITY_MART               (2 | (35 << 8))
#define MAP_FUCHSIA_CITY_GYM                (3 | (35 << 8))
#define MAP_FUCHSIA_CITY_SAFARI_ZONE_OFFICE (4 | (35 << 8))
#define MAP_FUCHSIA_CITY_WARDENS_HOUSE      (5 | (35 << 8))
#define MAP_FUCHSIA_CITY_HOUSE              (6 | (35 << 8))

// Map Group 36
#define MAP_CINNABAR_ISLAND_POKEMON_CENTER_1F (0 | (36 << 8))
#define MAP_CINNABAR_ISLAND_POKEMON_CENTER_2F (1 | (36 << 8))

// Map Group 37
#define MAP_INDIGO_PLATEAU_POKEMON_CENTER_1F (0 | (37 << 8))
#define MAP_INDIGO_PLATEAU_POKEMON_CENTER_2F (1 | (37 << 8))
#define MAP_INDIGO_PLATEAU_WILLS_ROOM        (2 | (37 << 8))
#define MAP_INDIGO_PLATEAU_KOGAS_ROOM        (3 | (37 << 8))
#define MAP_INDIGO_PLATEAU_BRUNOS_ROOM       (4 | (37 << 8))
#define MAP_INDIGO_PLATEAU_KARENS_ROOM       (5 | (37 << 8))
#define MAP_INDIGO_PLATEAU_LANCES_ROOM       (6 | (37 << 8))
#define MAP_INDIGO_PLATEAU_HALL_OF_FAME      (7 | (37 << 8))

// Map Group 38
#define MAP_ROUTE2_HOUSE                          (0 | (38 << 8))
#define MAP_ROUTE2_GATEHOUSE                      (1 | (38 << 8))
#define MAP_ROUTE2_VIRIDIAN_FOREST_SOUTH_ENTRANCE (2 | (38 << 8))
#define MAP_ROUTE2_VIRIDIAN_FOREST_NORTH_ENTRANCE (3 | (38 << 8))

// Map Group 39
#define MAP_ROUTE5_HOUSE                     (0 | (39 << 8))
#define MAP_ROUTE5_GATEHOUSE                 (1 | (39 << 8))
#define MAP_ROUTE5_UNDERGROUND_PATH_ENTRANCE (2 | (39 << 8))

// Map Group 40
#define MAP_ROUTE6_UNDERGROUND_PATH_ENTRANCE (0 | (40 << 8))
#define MAP_ROUTE6_GATEHOUSE                 (1 | (40 << 8))

// Map Group 41
#define MAP_ROUTE7_GATEHOUSE (0 | (41 << 8))

// Map Group 42
#define MAP_ROUTE8_GATEHOUSE (0 | (42 << 8))

// Map Group 43

// Map Group 44

// Map Group 45

// Map Group 46

// Map Group 47

// Map Group 48

// Map Group 49

// Map Group 50

// Map Group 51

// Map Group 52

// Map Group 53

// Map Group 54
#define MAP_TOHJO_FALLS (0 | (54 << 8))

// Map Group 55
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                    (0 | (55 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                    (1 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              (2 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           (3 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           (4 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        (5 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (6 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     (7 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  (8 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               (9 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            (10 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     (11 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         (12 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             (13 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          (14 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       (15 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            (16 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            (17 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              (18 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              (19 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           (20 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        (21 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            (22 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  (23 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      (24 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               (25 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            (26 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     (27 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         (28 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          (29 | (55 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      (30 | (55 << 8))
#define MAP_BATTLE_FRONTIER_RANKING_HALL                    (31 | (55 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE1                         (32 | (55 << 8))
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER         (33 | (55 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE2                         (34 | (55 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE3                         (35 | (55 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE4                         (36 | (55 << 8))
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                    (37 | (55 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE5                         (38 | (55 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE6                         (39 | (55 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE7                         (40 | (55 << 8))
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                  (41 | (55 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE8                         (42 | (55 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE9                         (43 | (55 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F               (44 | (55 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F               (45 | (55 << 8))
#define MAP_BATTLE_FRONTIER_MART                            (46 | (55 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01                         (47 | (55 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02                         (48 | (55 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03                         (49 | (55 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04                         (50 | (55 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05                         (51 | (55 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06                         (52 | (55 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07                         (53 | (55 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08                         (54 | (55 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09                         (55 | (55 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10                         (56 | (55 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11                         (57 | (55 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12                         (58 | (55 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13                         (59 | (55 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14                         (60 | (55 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15                         (61 | (55 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16                         (62 | (55 << 8))
#define MAP_ARTISAN_CAVE_B1F                                (63 | (55 << 8))
#define MAP_ARTISAN_CAVE_1F                                 (64 | (55 << 8))

// Map Group 56
#define MAP_BATTLE_COLOSSEUM_2P (0 | (56 << 8))
#define MAP_TRADE_CENTER        (1 | (56 << 8))
#define MAP_RECORD_CORNER       (2 | (56 << 8))
#define MAP_BATTLE_COLOSSEUM_4P (3 | (56 << 8))
#define MAP_UNION_ROOM          (4 | (56 << 8))

// Map Group 57
#define MAP_SECRET_BASE_RED_CAVE1    (0 | (57 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1  (1 | (57 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1   (2 | (57 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1 (3 | (57 << 8))
#define MAP_SECRET_BASE_TREE1        (4 | (57 << 8))
#define MAP_SECRET_BASE_SHRUB1       (5 | (57 << 8))
#define MAP_SECRET_BASE_RED_CAVE2    (6 | (57 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2  (7 | (57 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2   (8 | (57 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2 (9 | (57 << 8))
#define MAP_SECRET_BASE_TREE2        (10 | (57 << 8))
#define MAP_SECRET_BASE_SHRUB2       (11 | (57 << 8))
#define MAP_SECRET_BASE_RED_CAVE3    (12 | (57 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3  (13 | (57 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3   (14 | (57 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3 (15 | (57 << 8))
#define MAP_SECRET_BASE_TREE3        (16 | (57 << 8))
#define MAP_SECRET_BASE_SHRUB3       (17 | (57 << 8))
#define MAP_SECRET_BASE_RED_CAVE4    (18 | (57 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4  (19 | (57 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4   (20 | (57 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4 (21 | (57 << 8))
#define MAP_SECRET_BASE_TREE4        (22 | (57 << 8))
#define MAP_SECRET_BASE_SHRUB4       (23 | (57 << 8))

// Map Group 58
#define MAP_SOUTHERN_ISLAND_EXTERIOR (0 | (58 << 8))
#define MAP_SOUTHERN_ISLAND_INTERIOR (1 | (58 << 8))
#define MAP_FARAWAY_ISLAND_ENTRANCE  (2 | (58 << 8))
#define MAP_FARAWAY_ISLAND_INTERIOR  (3 | (58 << 8))
#define MAP_BIRTH_ISLAND_EXTERIOR    (4 | (58 << 8))
#define MAP_BIRTH_ISLAND_HARBOR      (5 | (58 << 8))
#define MAP_NAVEL_ROCK_EXTERIOR      (6 | (58 << 8))
#define MAP_NAVEL_ROCK_HARBOR        (7 | (58 << 8))
#define MAP_NAVEL_ROCK_ENTRANCE      (8 | (58 << 8))
#define MAP_NAVEL_ROCK_B1F           (9 | (58 << 8))
#define MAP_NAVEL_ROCK_FORK          (10 | (58 << 8))
#define MAP_NAVEL_ROCK_UP1           (11 | (58 << 8))
#define MAP_NAVEL_ROCK_UP2           (12 | (58 << 8))
#define MAP_NAVEL_ROCK_UP3           (13 | (58 << 8))
#define MAP_NAVEL_ROCK_UP4           (14 | (58 << 8))
#define MAP_NAVEL_ROCK_TOP           (15 | (58 << 8))
#define MAP_NAVEL_ROCK_DOWN01        (16 | (58 << 8))
#define MAP_NAVEL_ROCK_DOWN02        (17 | (58 << 8))
#define MAP_NAVEL_ROCK_DOWN03        (18 | (58 << 8))
#define MAP_NAVEL_ROCK_DOWN04        (19 | (58 << 8))
#define MAP_NAVEL_ROCK_DOWN05        (20 | (58 << 8))
#define MAP_NAVEL_ROCK_DOWN06        (21 | (58 << 8))
#define MAP_NAVEL_ROCK_DOWN07        (22 | (58 << 8))
#define MAP_NAVEL_ROCK_DOWN08        (23 | (58 << 8))
#define MAP_NAVEL_ROCK_DOWN09        (24 | (58 << 8))
#define MAP_NAVEL_ROCK_DOWN10        (25 | (58 << 8))
#define MAP_NAVEL_ROCK_DOWN11        (26 | (58 << 8))
#define MAP_NAVEL_ROCK_BOTTOM        (27 | (58 << 8))

// Map Group 59
#define MAP_SLATEPORT_CITY_BATTLE_TENT_LOBBY         (0 | (59 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_CORRIDOR      (1 | (59 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_BATTLE_ROOM   (2 | (59 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY        (3 | (59 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_CORRIDOR     (4 | (59 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM  (5 | (59 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY         (6 | (59 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_CORRIDOR      (7 | (59 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM   (8 | (59 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_1F             (9 | (59 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_B1F            (10 | (59 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_1F  (11 | (59 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_B1F (12 | (59 << 8))
#define MAP_ALTERING_CAVE                            (13 | (59 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_LOBBY              (14 | (59 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_HALL               (15 | (59 << 8))
#define MAP_CONTEST_HALL                             (16 | (59 << 8))
#define MAP_UNUSED_CONTEST_HALL1                     (17 | (59 << 8))
#define MAP_UNUSED_CONTEST_HALL2                     (18 | (59 << 8))
#define MAP_UNUSED_CONTEST_HALL3                     (19 | (59 << 8))
#define MAP_UNUSED_CONTEST_HALL4                     (20 | (59 << 8))
#define MAP_UNUSED_CONTEST_HALL5                     (21 | (59 << 8))
#define MAP_UNUSED_CONTEST_HALL6                     (22 | (59 << 8))
#define MAP_CONTEST_HALL_BEAUTY                      (23 | (59 << 8))
#define MAP_CONTEST_HALL_TOUGH                       (24 | (59 << 8))
#define MAP_CONTEST_HALL_COOL                        (25 | (59 << 8))
#define MAP_CONTEST_HALL_SMART                       (26 | (59 << 8))
#define MAP_CONTEST_HALL_CUTE                        (27 | (59 << 8))
#define MAP_TRAINER_HILL_ENTRANCE                    (28 | (59 << 8))
#define MAP_TRAINER_HILL_1F                          (29 | (59 << 8))
#define MAP_TRAINER_HILL_2F                          (30 | (59 << 8))
#define MAP_TRAINER_HILL_3F                          (31 | (59 << 8))
#define MAP_TRAINER_HILL_4F                          (32 | (59 << 8))
#define MAP_TRAINER_HILL_ROOF                        (33 | (59 << 8))
#define MAP_TRAINER_HILL_ELEVATOR                    (34 | (59 << 8))

#define MAP_GROUPS_COUNT 60

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
