#ifndef GUARD_CONSTANTS_PHONE_CONTACT_H
#define GUARD_PHONE_CONTACT_H

#define PHONE_CONTACT_MOM 0
#define PHONE_CONTACT_ELM 1
#define PHONE_CONTACT_BIKE_SHOP 2
#define PHONE_CONTACT_BILL 3

#define PHONE_CONTACT_NO_RANDOM_CALL_INDEX 3 //Mom, Elm, Bike Shop, Bill

#define PHONE_CONTACT_BUENA 4

#define PHONE_CONTACT_YOUNGSTER_JOEY 5
#define PHONE_CONTACT_BUG_CATCHER_WADE 6
#define PHONE_CONTACT_PICNICKER_LIZ 7
#define PHONE_CONTACT_FISHER_RALPH 8
#define PHONE_CONTACT_HIKER_ANTHONY 9
#define PHONE_CONTACT_CAMPER_TODD 10
#define PHONE_CONTACT_PICNICKER_GINA 11
#define PHONE_CONTACT_BUG_CATCHER_ARNIE 12
#define PHONE_CONTACT_JUGGLER_IRWIN 13
#define PHONE_CONTACT_SCHOOLBOY_JACK 14
#define PHONE_CONTACT_POKEFAN_BEVERLY 15
#define PHONE_CONTACT_SCHOOLBOY_ALAN 16
#define PHONE_CONTACT_LASS_DANA 17
#define PHONE_CONTACT_SCHOOLBOY_CHAD 18
#define PHONE_CONTACT_POKEFAN_DEREK 19
#define PHONE_CONTACT_SAILOR_HUEY 20
#define PHONE_CONTACT_FISHER_TULLY 21
#define PHONE_CONTACT_PICNICKER_TIFFANY 22
#define PHONE_CONTACT_POKEMANIAC_BRENT 23
#define PHONE_CONTACT_FISHER_WILTON 24
#define PHONE_CONTACT_BIRD_KEEPER_VANCE 25
#define PHONE_CONTACT_HIKER_PARRY 26
#define PHONE_CONTACT_BLACKBELT_KENJI 27
#define PHONE_CONTACT_PICNICKER_ERIN 28
#define PHONE_CONTACT_BIRD_KEEPER_JOSE 29
#define PHONE_CONTACT_COOLTRAINER_REENA 30
#define PHONE_CONTACT_COOLTRAINER_GAVEN 31
#define PHONE_CONTACT_COOLTRAINER_BETH 32

#define PHONE_CONTACT_COUNT 33

//#define PHONE_CONTACT_FISHER_CHRIS 33 // GS ONLY, Crystal replaced with Tully

#endif //GUARD_CONSTANTS_PHONE_CONTACT_H
