#ifndef GUARD_CONSTANTS_PHONE_CONTACT_H
#define GUARD_PHONE_CONTACT_H

#define PHONE_CONTACT_MOM 0
#define PHONE_CONTACT_ELM 1
#define PHONE_CONTACT_BIKE_SHOP 2
#define PHONE_CONTACT_BILL 3
#define PHONE_CONTACT_NON_TRAINERS_COUNT 4

#endif //GUARD_CONSTANTS_PHONE_CONTACT_H
