#ifndef GUARD_CONSTANTS_RADIO_H
#define GUARD_CONSTANTS_RADIO_H

#define STATION_POKEMON_CHANNEL     0
#define STATION_POKEMON_MUSIC       1
#define STATION_LUCKY_CHANNEL       2
#define STATION_BUENAS_PASSWORD     3
#define STATION_UNOWN_RADIO         4
#define STATION_EVOLUTION_RADIO     5

#endif // GUARD_CONSTANTS_RADIO_H
