#ifndef GUARD_REGIONMAPSEC_H
#define GUARD_REGIONMAPSEC_H

#define MAPSEC_NEW_BARK_TOWN                0x00
#define MAPSEC_CHERRYGROVE_CITY             0x01
#define MAPSEC_AZALEA_TOWN                  0x02
#define MAPSEC_CIANWOOD_CITY                0x03
#define MAPSEC_MAHOGANY_TOWN                0x04
#define MAPSEC_LAVENDER_RADIO_TOWER         0x05
#define MAPSEC_PACIFIDLOG_TOWN              0x06
#define MAPSEC_VIOLET_CITY                  0x07
#define MAPSEC_ECRUTEAK_CITY                0x08
#define MAPSEC_OLIVINE_CITY                 0x09
#define MAPSEC_GOLDENROD_CITY               0x0A
#define MAPSEC_FORTREE_CITY                 0x0B
#define MAPSEC_BLACKTHORN_CITY              0x0C
#define MAPSEC_BURNED_TOWER                 0x0D
#define MAPSEC_TOHJO_FALLS                  0x0E
#define MAPSEC_FAST_SHIP                    0x0F
#define MAPSEC_ROUTE_29                     0x10
#define MAPSEC_ROUTE_30                     0x11
#define MAPSEC_ROUTE_31                     0x12
#define MAPSEC_ROUTE_32                     0x13
#define MAPSEC_ROUTE_33                     0x14
#define MAPSEC_ROUTE_34                     0x15
#define MAPSEC_ROUTE_35                     0x16
#define MAPSEC_ROUTE_36                     0x17
#define MAPSEC_ROUTE_37                     0x18
#define MAPSEC_ROUTE_38                     0x19
#define MAPSEC_ROUTE_39                     0x1A
#define MAPSEC_ROUTE_40                     0x1B
#define MAPSEC_ROUTE_41                     0x1C
#define MAPSEC_ROUTE_42                     0x1D
#define MAPSEC_ROUTE_43                     0x1E
#define MAPSEC_ROUTE_44                     0x1F
#define MAPSEC_ROUTE_45                     0x20
#define MAPSEC_ROUTE_46                     0x21
#define MAPSEC_ROUTE_26                     0x22
#define MAPSEC_ROUTE_27                     0x23
#define MAPSEC_ROUTE_28                     0x24
#define MAPSEC_ROUTE_32_FLYDUP              0x25
#define MAPSEC_ROUTE_123                    0x26
#define MAPSEC_ROUTE_124                    0x27
#define MAPSEC_ROUTE_125                    0x28
#define MAPSEC_ROUTE_126                    0x29
#define MAPSEC_ROUTE_127                    0x2A
#define MAPSEC_ROUTE_128                    0x2B
#define MAPSEC_ROUTE_129                    0x2C
#define MAPSEC_ROUTE_130                    0x2D
#define MAPSEC_ROUTE_131                    0x2E
#define MAPSEC_ROUTE_132                    0x2F
#define MAPSEC_ROUTE_133                    0x30
#define MAPSEC_ROUTE_134                    0x31
#define MAPSEC_UNDERWATER_124               0x32
#define MAPSEC_UNDERWATER_126               0x33
#define MAPSEC_UNDERWATER_127               0x34
#define MAPSEC_UNDERWATER_128               0x35
#define MAPSEC_UNDERWATER_SOOTOPOLIS        0x36
#define MAPSEC_DARK_CAVE                    0x37
#define MAPSEC_SLOWPOKE_WELL                0x38
#define MAPSEC_SAFARI_ZONE                  0x39
#define MAPSEC_BATTLE_FRONTIER              0x3A
#define MAPSEC_ILEX_FOREST                  0x3B
#define MAPSEC_UNION_CAVE                   0x3C
#define MAPSEC_SPROUT_TOWER                 0x3D
#define MAPSEC_RUINS_OF_ALPH                0x3E
#define MAPSEC_ALPH_CHAMBERS                0x3F
#define MAPSEC_RADIO_TOWER                  0x40
#define MAPSEC_MT_MORTAR                    0x41
#define MAPSEC_AQUA_HIDEOUT_OLD             0x42
#define MAPSEC_LIGHTHOUSE                   0x43
#define MAPSEC_DRAGONS_DEN                  0x44
#define MAPSEC_UNDERWATER_SEAFLOOR_CAVERN   0x45
#define MAPSEC_VICTORY_ROAD                 0x46
#define MAPSEC_MIRAGE_ISLAND                0x47
#define MAPSEC_CAVE_OF_ORIGIN               0x48
#define MAPSEC_SOUTHERN_ISLAND              0x49
#define MAPSEC_LAKE_OF_RAGE                 0x4A
#define MAPSEC_NATIONAL_PARK                0x4B
#define MAPSEC_ICE_PATH                     0x4C
#define MAPSEC_SILVER_CAVE                  0x4D
#define MAPSEC_SEALED_CHAMBER               0x4E
#define MAPSEC_UNDERWATER_SEALED_CHAMBER    0x4F
#define MAPSEC_SCORCHED_SLAB                0x50
#define MAPSEC_WHIRL_ISLANDS                0x51
#define MAPSEC_TIN_TOWER                    0x52
#define MAPSEC_ANCIENT_TOMB                 0x53
#define MAPSEC_INSIDE_OF_TRUCK              0x54
#define MAPSEC_SKY_PILLAR                   0x55
#define MAPSEC_SECRET_BASE                  0x56
#define MAPSEC_DYNAMIC                      0x57
#define MAPSEC_PALLET_TOWN                  0x58
#define MAPSEC_VIRIDIAN_CITY                0x59
#define MAPSEC_PEWTER_CITY                  0x5A
#define MAPSEC_CERULEAN_CITY                0x5B
#define MAPSEC_LAVENDER_TOWN                0x5C
#define MAPSEC_VERMILION_CITY               0x5D
#define MAPSEC_CELADON_CITY                 0x5E
#define MAPSEC_FUCHSIA_CITY                 0x5F
#define MAPSEC_CINNABAR_ISLAND              0x60
#define MAPSEC_INDIGO_PLATEAU               0x61
#define MAPSEC_SAFFRON_CITY                 0x62
#define MAPSEC_ROUTE_3_FLYDUP               0x63
#define MAPSEC_ROUTE_10_FLYDUP              0x64
#define MAPSEC_ROUTE_1                      0x65
#define MAPSEC_ROUTE_2                      0x66
#define MAPSEC_ROUTE_3                      0x67
#define MAPSEC_ROUTE_4                      0x68
#define MAPSEC_ROUTE_5                      0x69
#define MAPSEC_ROUTE_6                      0x6A
#define MAPSEC_ROUTE_7                      0x6B
#define MAPSEC_ROUTE_8                      0x6C
#define MAPSEC_ROUTE_9                      0x6D
#define MAPSEC_ROUTE_10                     0x6E
#define MAPSEC_ROUTE_11                     0x6F
#define MAPSEC_ROUTE_12                     0x70
#define MAPSEC_ROUTE_13                     0x71
#define MAPSEC_ROUTE_14                     0x72
#define MAPSEC_ROUTE_15                     0x73
#define MAPSEC_ROUTE_16                     0x74
#define MAPSEC_ROUTE_17                     0x75
#define MAPSEC_ROUTE_18                     0x76
#define MAPSEC_ROUTE_19                     0x77
#define MAPSEC_ROUTE_20                     0x78
#define MAPSEC_ROUTE_21                     0x79
#define MAPSEC_ROUTE_22                     0x7A
#define MAPSEC_ROUTE_23                     0x7B
#define MAPSEC_ROUTE_24                     0x7C
#define MAPSEC_ROUTE_25                     0x7D
#define MAPSEC_VIRIDIAN_FOREST              0x7E
#define MAPSEC_MT_MOON                      0x7F
#define MAPSEC_S_S_ANNE                     0x80
#define MAPSEC_UNDERGROUND_PATH             0x81
#define MAPSEC_UNDERGROUND_PATH_2           0x82
#define MAPSEC_DIGLETTS_CAVE                0x83
#define MAPSEC_KANTO_VICTORY_ROAD           0x84
#define MAPSEC_ROCKET_HIDEOUT               0x85
#define MAPSEC_SILPH_CO                     0x86
#define MAPSEC_POKEMON_MANSION              0x87
#define MAPSEC_KANTO_SAFARI_ZONE            0x88
#define MAPSEC_POKEMON_LEAGUE               0x89
#define MAPSEC_ROCK_TUNNEL                  0x8A
#define MAPSEC_SEAFOAM_ISLANDS              0x8B
#define MAPSEC_POKEMON_TOWER                0x8C
#define MAPSEC_CERULEAN_CAVE                0x8D
#define MAPSEC_POWER_PLANT                  0x8E
#define MAPSEC_ONE_ISLAND                   0x8F
#define MAPSEC_TWO_ISLAND                   0x90
#define MAPSEC_THREE_ISLAND                 0x91
#define MAPSEC_FOUR_ISLAND                  0x92
#define MAPSEC_FIVE_ISLAND                  0x93
#define MAPSEC_SEVEN_ISLAND                 0x94
#define MAPSEC_SIX_ISLAND                   0x95
#define MAPSEC_KINDLE_ROAD                  0x96
#define MAPSEC_TREASURE_BEACH               0x97
#define MAPSEC_CAPE_BRINK                   0x98
#define MAPSEC_BOND_BRIDGE                  0x99
#define MAPSEC_THREE_ISLE_PORT              0x9A
#define MAPSEC_SEVII_ISLE_6                 0x9B
#define MAPSEC_SEVII_ISLE_7                 0x9C
#define MAPSEC_SEVII_ISLE_8                 0x9D
#define MAPSEC_SEVII_ISLE_9                 0x9E
#define MAPSEC_RESORT_GORGEOUS              0x9F
#define MAPSEC_WATER_LABYRINTH              0xA0
#define MAPSEC_FIVE_ISLE_MEADOW             0xA1
#define MAPSEC_MEMORIAL_PILLAR              0xA2
#define MAPSEC_OUTCAST_ISLAND               0xA3
#define MAPSEC_GREEN_PATH                   0xA4
#define MAPSEC_WATER_PATH                   0xA5
#define MAPSEC_RUIN_VALLEY                  0xA6
#define MAPSEC_TRAINER_TOWER                0xA7
#define MAPSEC_CANYON_ENTRANCE              0xA8
#define MAPSEC_SEVAULT_CANYON               0xA9
#define MAPSEC_TANOBY_RUINS                 0xAA
#define MAPSEC_SEVII_ISLE_22                0xAB
#define MAPSEC_SEVII_ISLE_23                0xAC
#define MAPSEC_SEVII_ISLE_24                0xAD
#define MAPSEC_NAVEL_ROCK_FRLG              0xAE
#define MAPSEC_MT_EMBER                     0xAF
#define MAPSEC_BERRY_FOREST                 0xB0
#define MAPSEC_ICEFALL_CAVE                 0xB1
#define MAPSEC_ROCKET_WAREHOUSE             0xB2
#define MAPSEC_TRAINER_TOWER_2              0xB3
#define MAPSEC_DOTTED_HOLE                  0xB4
#define MAPSEC_LOST_CAVE                    0xB5
#define MAPSEC_PATTERN_BUSH                 0xB6
#define MAPSEC_ALTERING_CAVE_FRLG           0xB7
#define MAPSEC_TANOBY_CHAMBERS              0xB8
#define MAPSEC_THREE_ISLE_PATH              0xB9
#define MAPSEC_TANOBY_KEY                   0xBA
#define MAPSEC_BIRTH_ISLAND_FRLG            0xBB
#define MAPSEC_MONEAN_CHAMBER               0xBC
#define MAPSEC_LIPTOO_CHAMBER               0xBD
#define MAPSEC_WEEPTH_CHAMBER               0xBE
#define MAPSEC_DILFORD_CHAMBER              0xBF
#define MAPSEC_SCUFIB_CHAMBER               0xC0
#define MAPSEC_RIXY_CHAMBER                 0xC1
#define MAPSEC_VIAPOIS_CHAMBER              0xC2
#define MAPSEC_EMBER_SPA                    0xC3
#define MAPSEC_SPECIAL_AREA                 0xC4
#define MAPSEC_AQUA_HIDEOUT                 0xC5
#define MAPSEC_MAGMA_HIDEOUT                0xC6
#define MAPSEC_MIRAGE_TOWER                 0xC7
#define MAPSEC_BIRTH_ISLAND                 0xC8
#define MAPSEC_FARAWAY_ISLAND               0xC9
#define MAPSEC_ARTISAN_CAVE                 0xCA
#define MAPSEC_MARINE_CAVE                  0xCB
#define MAPSEC_UNDERWATER_MARINE_CAVE       0xCC
#define MAPSEC_TERRA_CAVE                   0xCD
#define MAPSEC_UNDERWATER_105               0xCE
#define MAPSEC_UNDERWATER_125               0xCF
#define MAPSEC_UNDERWATER_129               0xD0
#define MAPSEC_DESERT_UNDERPASS             0xD1
#define MAPSEC_ALTERING_CAVE                0xD2
#define MAPSEC_NAVEL_ROCK                   0xD3
#define MAPSEC_TRAINER_HILL                 0xD4
#define MAPSEC_NONE                         0xD5

#define METLOC_SPECIAL_EGG                  0xFD
#define METLOC_IN_GAME_TRADE                0xFE
#define METLOC_FATEFUL_ENCOUNTER            0xFF

#define KANTO_MAPSEC_START  MAPSEC_PALLET_TOWN
#define KANTO_MAPSEC_END    MAPSEC_SPECIAL_AREA
#define KANTO_MAPSEC_COUNT (KANTO_MAPSEC_END - KANTO_MAPSEC_START + 1)

// Emerald mapsec defines (+0x100)
#define MAPSECEM_LITTLEROOT_TOWN            0x100
#define MAPSECEM_OLDALE_TOWN                0x101
#define MAPSECEM_DEWFORD_TOWN               0x102
#define MAPSECEM_LAVARIDGE_TOWN             0x103
#define MAPSECEM_FALLARBOR_TOWN             0x104
#define MAPSECEM_VERDANTURF_TOWN            0x105
#define MAPSECEM_PACIFIDLOG_TOWN            0x106
#define MAPSECEM_PETALBURG_CITY             0x107
#define MAPSECEM_SLATEPORT_CITY             0x108
#define MAPSECEM_MAUVILLE_CITY              0x109
#define MAPSECEM_RUSTBORO_CITY              0x10A
#define MAPSECEM_FORTREE_CITY               0x10B
#define MAPSECEM_LILYCOVE_CITY              0x10C
#define MAPSECEM_MOSSDEEP_CITY              0x10D
#define MAPSECEM_SOOTOPOLIS_CITY            0x10E
#define MAPSECEM_EVER_GRANDE_CITY           0x10F
#define MAPSECEM_ROUTE_101                  0x110
#define MAPSECEM_ROUTE_102                  0x111
#define MAPSECEM_ROUTE_103                  0x112
#define MAPSECEM_ROUTE_104                  0x113
#define MAPSECEM_ROUTE_105                  0x114
#define MAPSECEM_ROUTE_106                  0x115
#define MAPSECEM_ROUTE_107                  0x116
#define MAPSECEM_ROUTE_108                  0x117
#define MAPSECEM_ROUTE_109                  0x118
#define MAPSECEM_ROUTE_110                  0x119
#define MAPSECEM_ROUTE_111                  0x11A
#define MAPSECEM_ROUTE_112                  0x11B
#define MAPSECEM_ROUTE_113                  0x11C
#define MAPSECEM_ROUTE_114                  0x11D
#define MAPSECEM_ROUTE_115                  0x11E
#define MAPSECEM_ROUTE_116                  0x11F
#define MAPSECEM_ROUTE_117                  0x120
#define MAPSECEM_ROUTE_118                  0x121
#define MAPSECEM_ROUTE_119                  0x122
#define MAPSECEM_ROUTE_120                  0x123
#define MAPSECEM_ROUTE_121                  0x124
#define MAPSECEM_ROUTE_122                  0x125
#define MAPSECEM_ROUTE_123                  0x126
#define MAPSECEM_ROUTE_124                  0x127
#define MAPSECEM_ROUTE_125                  0x128
#define MAPSECEM_ROUTE_126                  0x129
#define MAPSECEM_ROUTE_127                  0x12A
#define MAPSECEM_ROUTE_128                  0x12B
#define MAPSECEM_ROUTE_129                  0x12C
#define MAPSECEM_ROUTE_130                  0x12D
#define MAPSECEM_ROUTE_131                  0x12E
#define MAPSECEM_ROUTE_132                  0x12F
#define MAPSECEM_ROUTE_133                  0x130
#define MAPSECEM_ROUTE_134                  0x131
#define MAPSECEM_UNDERWATER_124             0x132
#define MAPSECEM_UNDERWATER_125             0x133
#define MAPSECEM_UNDERWATER_126             0x134
#define MAPSECEM_UNDERWATER_127             0x135
#define MAPSECEM_UNDERWATER_SOOTOPOLIS      0x136
#define MAPSECEM_GRANITE_CAVE               0x137
#define MAPSECEM_MT_CHIMNEY                 0x138
#define MAPSECEM_SAFARI_ZONE                0x139
#define MAPSECEM_BATTLE_FRONTIER            0x13A
#define MAPSECEM_PETALBURG_WOODS            0x13B
#define MAPSECEM_RUSTURF_TUNNEL             0x13C
#define MAPSECEM_ABANDONED_SHIP             0x13D
#define MAPSECEM_NEW_MAUVILLE               0x13E
#define MAPSECEM_METEOR_FALLS               0x13F
#define MAPSECEM_METEOR_FALLS2              0x140
#define MAPSECEM_MT_PYRE                    0x141
#define MAPSECEM_AQUA_HIDEOUT_OLD           0x142
#define MAPSECEM_SHOAL_CAVE                 0x143
#define MAPSECEM_SEAFLOOR_CAVERN            0x144
#define MAPSECEM_UNDERWATER_128             0x145
#define MAPSECEM_VICTORY_ROAD               0x146
#define MAPSECEM_MIRAGE_ISLAND              0x147
#define MAPSECEM_CAVE_OF_ORIGIN             0x148
#define MAPSECEM_SOUTHERN_ISLAND            0x149
#define MAPSECEM_FIERY_PATH                 0x14A
#define MAPSECEM_FIERY_PATH2                0x14B
#define MAPSECEM_JAGGED_PASS                0x14C
#define MAPSECEM_JAGGED_PASS2               0x14D
#define MAPSECEM_SEALED_CHAMBER             0x14E
#define MAPSECEM_UNDERWATER_SEALED_CHAMBER  0x14F
#define MAPSECEM_SCORCHED_SLAB              0x150
#define MAPSECEM_ISLAND_CAVE                0x151
#define MAPSECEM_DESERT_RUINS               0x152
#define MAPSECEM_ANCIENT_TOMB               0x153
#define MAPSECEM_INSIDE_OF_TRUCK            0x154
#define MAPSECEM_SKY_PILLAR                 0x155
#define MAPSECEM_SECRET_BASE                0x156
#define MAPSECEM_DYNAMIC                    0x157
#define MAPSECEM_PALLET_TOWN                0x158
#define MAPSECEM_VIRIDIAN_CITY              0x159
#define MAPSECEM_PEWTER_CITY                0x15A
#define MAPSECEM_CERULEAN_CITY              0x15B
#define MAPSECEM_LAVENDER_TOWN              0x15C
#define MAPSECEM_VERMILION_CITY             0x15D
#define MAPSECEM_CELADON_CITY               0x15E
#define MAPSECEM_FUCHSIA_CITY               0x15F
#define MAPSECEM_CINNABAR_ISLAND            0x160
#define MAPSECEM_INDIGO_PLATEAU             0x161
#define MAPSECEM_SAFFRON_CITY               0x162
#define MAPSECEM_ROUTE_4_FLYDUP             0x163
#define MAPSECEM_ROUTE_10_FLYDUP            0x164
#define MAPSECEM_ROUTE_1                    0x165
#define MAPSECEM_ROUTE_2                    0x166
#define MAPSECEM_ROUTE_3                    0x167
#define MAPSECEM_ROUTE_4                    0x168
#define MAPSECEM_ROUTE_5                    0x169
#define MAPSECEM_ROUTE_6                    0x16A
#define MAPSECEM_ROUTE_7                    0x16B
#define MAPSECEM_ROUTE_8                    0x16C
#define MAPSECEM_ROUTE_9                    0x16D
#define MAPSECEM_ROUTE_10                   0x16E
#define MAPSECEM_ROUTE_11                   0x16F
#define MAPSECEM_ROUTE_12                   0x170
#define MAPSECEM_ROUTE_13                   0x171
#define MAPSECEM_ROUTE_14                   0x172
#define MAPSECEM_ROUTE_15                   0x173
#define MAPSECEM_ROUTE_16                   0x174
#define MAPSECEM_ROUTE_17                   0x175
#define MAPSECEM_ROUTE_18                   0x176
#define MAPSECEM_ROUTE_19                   0x177
#define MAPSECEM_ROUTE_20                   0x178
#define MAPSECEM_ROUTE_21                   0x179
#define MAPSECEM_ROUTE_22                   0x17A
#define MAPSECEM_ROUTE_23                   0x17B
#define MAPSECEM_ROUTE_24                   0x17C
#define MAPSECEM_ROUTE_25                   0x17D
#define MAPSECEM_VIRIDIAN_FOREST            0x17E
#define MAPSECEM_MT_MOON                    0x17F
#define MAPSECEM_S_S_ANNE                   0x180
#define MAPSECEM_UNDERGROUND_PATH           0x181
#define MAPSECEM_UNDERGROUND_PATH_2         0x182
#define MAPSECEM_DIGLETTS_CAVE              0x183
#define MAPSECEM_KANTO_VICTORY_ROAD         0x184
#define MAPSECEM_ROCKET_HIDEOUT             0x185
#define MAPSECEM_SILPH_CO                   0x186
#define MAPSECEM_POKEMON_MANSION            0x187
#define MAPSECEM_KANTO_SAFARI_ZONE          0x188
#define MAPSECEM_POKEMON_LEAGUE             0x189
#define MAPSECEM_ROCK_TUNNEL                0x18A
#define MAPSECEM_SEAFOAM_ISLANDS            0x18B
#define MAPSECEM_POKEMON_TOWER              0x18C
#define MAPSECEM_CERULEAN_CAVE              0x18D
#define MAPSECEM_POWER_PLANT                0x18E
#define MAPSECEM_ONE_ISLAND                 0x18F
#define MAPSECEM_TWO_ISLAND                 0x190
#define MAPSECEM_THREE_ISLAND               0x191
#define MAPSECEM_FOUR_ISLAND                0x192
#define MAPSECEM_FIVE_ISLAND                0x193
#define MAPSECEM_SEVEN_ISLAND               0x194
#define MAPSECEM_SIX_ISLAND                 0x195
#define MAPSECEM_KINDLE_ROAD                0x196
#define MAPSECEM_TREASURE_BEACH             0x197
#define MAPSECEM_CAPE_BRINK                 0x198
#define MAPSECEM_BOND_BRIDGE                0x199
#define MAPSECEM_THREE_ISLE_PORT            0x19A
#define MAPSECEM_SEVII_ISLE_6               0x19B
#define MAPSECEM_SEVII_ISLE_7               0x19C
#define MAPSECEM_SEVII_ISLE_8               0x19D
#define MAPSECEM_SEVII_ISLE_9               0x19E
#define MAPSECEM_RESORT_GORGEOUS            0x19F
#define MAPSECEM_WATER_LABYRINTH            0x1A0
#define MAPSECEM_FIVE_ISLE_MEADOW           0x1A1
#define MAPSECEM_MEMORIAL_PILLAR            0x1A2
#define MAPSECEM_OUTCAST_ISLAND             0x1A3
#define MAPSECEM_GREEN_PATH                 0x1A4
#define MAPSECEM_WATER_PATH                 0x1A5
#define MAPSECEM_RUIN_VALLEY                0x1A6
#define MAPSECEM_TRAINER_TOWER              0x1A7
#define MAPSECEM_CANYON_ENTRANCE            0x1A8
#define MAPSECEM_SEVAULT_CANYON             0x1A9
#define MAPSECEM_TANOBY_RUINS               0x1AA
#define MAPSECEM_SEVII_ISLE_22              0x1AB
#define MAPSECEM_SEVII_ISLE_23              0x1AC
#define MAPSECEM_SEVII_ISLE_24              0x1AD
#define MAPSECEM_NAVEL_ROCK_FRLG            0x1AE
#define MAPSECEM_MT_EMBER                   0x1AF
#define MAPSECEM_BERRY_FOREST               0x1B0
#define MAPSECEM_ICEFALL_CAVE               0x1B1
#define MAPSECEM_ROCKET_WAREHOUSE           0x1B2
#define MAPSECEM_TRAINER_TOWER_2            0x1B3
#define MAPSECEM_DOTTED_HOLE                0x1B4
#define MAPSECEM_LOST_CAVE                  0x1B5
#define MAPSECEM_PATTERN_BUSH               0x1B6
#define MAPSECEM_ALTERING_CAVE_FRLG         0x1B7
#define MAPSECEM_TANOBY_CHAMBERS            0x1B8
#define MAPSECEM_THREE_ISLE_PATH            0x1B9
#define MAPSECEM_TANOBY_KEY                 0x1BA
#define MAPSECEM_BIRTH_ISLAND_FRLG          0x1BB
#define MAPSECEM_MONEAN_CHAMBER             0x1BC
#define MAPSECEM_LIPTOO_CHAMBER             0x1BD
#define MAPSECEM_WEEPTH_CHAMBER             0x1BE
#define MAPSECEM_DILFORD_CHAMBER            0x1BF
#define MAPSECEM_SCUFIB_CHAMBER             0x1C0
#define MAPSECEM_RIXY_CHAMBER               0x1C1
#define MAPSECEM_VIAPOIS_CHAMBER            0x1C2
#define MAPSECEM_EMBER_SPA                  0x1C3
#define MAPSECEM_SPECIAL_AREA               0x1C4
#define MAPSECEM_AQUA_HIDEOUT               0x1C5
#define MAPSECEM_MAGMA_HIDEOUT              0x1C6
#define MAPSECEM_MIRAGE_TOWER               0x1C7
#define MAPSECEM_BIRTH_ISLAND               0x1C8
#define MAPSECEM_FARAWAY_ISLAND             0x1C9
#define MAPSECEM_ARTISAN_CAVE               0x1CA
#define MAPSECEM_MARINE_CAVE                0x1CB
#define MAPSECEM_UNDERWATER_MARINE_CAVE     0x1CC
#define MAPSECEM_TERRA_CAVE                 0x1CD
#define MAPSECEM_UNDERWATER_TERRA_CAVE      0x1CE
#define MAPSECEM_UNDERWATER_UNK1            0x1CF
#define MAPSECEM_UNDERWATER_129             0x1D0
#define MAPSECEM_DESERT_UNDERPASS           0x1D1
#define MAPSECEM_ALTERING_CAVE              0x1D2
#define MAPSECEM_NAVEL_ROCK                 0x1D3
#define MAPSECEM_TRAINER_HILL               0x1D4
#define MAPSECEM_NONE                       0x1D5

#define EMERALD_MAPSEC_START                MAPSECEM_LITTLEROOT_TOWN
#define EMERALD_MAPSEC_END                  MAPSECEM_NONE
#define NUM_NEW_MAPSECS 51
// For special CD Eggs handled in PrintEggMemo
#define METLOC_VIOLET_CITY                  0xD7
#define METLOC_GOLDENROD_CITY               0xD9

#endif //GUARD_REGIONMAPSEC_H
