#ifndef GUARD_ROOM_DECOR_H
#define GUARD_ROOM_DECOR_H

// X/Y Tile Positions
#define TILE_BED_START_X (0 + 7)
#define TILE_BED_START_Y (4 + 7)
#define TILE_PLANT_START_X (10 + 7)
#define TILE_PLANT_START_Y (7 + 7)
#define TILE_POSTER_START_X (9 + 7)
#define TILE_POSTER_START_Y (0 + 7)
#define TILE_CONSOLE_START_X (4 + 7)
#define TILE_CONSOLE_START_Y (2 + 7)
#define TILE_CARPET_START_X (4 + 7)
#define TILE_CARPET_START_Y (5 + 7)
#define TILE_DESK_START_X (5 + 7)
#define TILE_DESK_START_Y (6 + 7)

// Beds
#define BED_NONE 0
#define BED_FEATHERY 1
#define BED_PINK 2
#define BED_POLKADOT 3
#define BED_PIKACHU 4

// Carpets / Mats
#define CARPET_NONE 0
#define CARPET_RED 1
#define CARPET_BLUE 2
#define CARPET_YELLOW 3
#define CARPET_GREEN 4
#define CARPET_SURF 5
#define CARPET_THUNDER 6
#define CARPET_FIRE_BLAST 7
#define CARPET_POWDER_SNOW 8
#define CARPET_ATTRACT 9
#define CARPET_FISSURE 10
#define CARPET_SPIKES 11

// Plants
#define PLANT_NONE 0
#define PLANT_MAGNA 1
#define PLANT_TROPIC 2
#define PLANT_JUMBO 3
#define PLANT_RED 4
#define PLANT_TROPICAL 5
#define PLANT_PRETTY 6 // Pretty Flowers
#define PLANT_COLORFUL 7
#define PLANT_BIG 8
#define PLANT_GORGEOUS 9

// Posters
#define POSTER_NONE 0
#define POSTER_MAP 1
#define POSTER_CLEFAIRY 2
#define POSTER_PIKACHU 3
#define POSTER_JIGGLYPUFF 4
#define POSTER_BALL 5
#define POSTER_GREEN 6
#define POSTER_RED 7
#define POSTER_BLUE 8
#define POSTER_CUTE 9
#define POSTER_PIKA 10
#define POSTER_LONG 11
#define POSTER_SEA 12
#define POSTER_SKY 13
#define POSTER_KISS 14

// Game Consoles
#define CONSOLE_NONE 0
#define CONSOLE_NES 1
#define CONSOLE_SNES 2
#define CONSOLE_N64 3
#define CONSOLE_VIRTUALBOY 4
#define CONSOLE_GAMECUBE 5

// Desks
#define DESK_NONE 0
#define DESK_DEFAULT 1
#define DESK_HEAVY 2
#define DESK_RAGGED 3
#define DESK_COMFORT 4
#define DESK_PRETTY 5
#define DESK_BRICK 6
#define DESK_CAMP 7
#define DESK_HARD 8

// Cushions
#define CUSHION_NONE 0
#define CUSHION_PIKA 1
#define CUSHION_ROUND 2
#define CUSHION_KISS 3
#define CUSHION_ZIGZAG 4
#define CUSHION_SPIN 5
#define CUSHION_DIAMOND 6
#define CUSHION_BALL 7
#define CUSHION_GRASS 8
#define CUSHION_FIRE 9
#define CUSHION_WATER 10

// Big Doll
#define BIG_DOLL_NONE 0
#define BIG_DOLL_SNORLAX 1
#define BIG_DOLL_ONIX 2
#define BIG_DOLL_LAPRAS 3
#define BIG_DOLL_RHYDON 4
#define BIG_DOLL_VENUSAUR 5
#define BIG_DOLL_CHARIZARD 6
#define BIG_DOLL_BLASTOISE 7
#define BIG_DOLL_WAILMER 8
#define BIG_DOLL_REGIROCK 9
#define BIG_DOLL_REGICE 10
#define BIG_DOLL_REGISTEEL 11

// Ornaments / Dolls
#define DOLL_NONE 0
#define DOLL_PIKACHU 1
#define DOLL_SURF_PIKACHU 2
#define DOLL_CLEFAIRY 3
#define DOLL_JIGGLYPUFF 4
#define DOLL_BULBASAUR 5
#define DOLL_ODDISH 6
#define DOLL_GENGAR 7
#define DOLL_SHELLDER 8
#define DOLL_GRIMER 9
#define DOLL_VOLTORB 10
#define DOLL_WEEDLE 11
#define DOLL_MAGIKARP 12
#define DOLL_CHARMANDER 13
#define DOLL_SQUIRTLE 14
#define DOLL_POLIWAG 15
#define DOLL_DIGLETT 16
#define DOLL_STARYU 17
#define DOLL_TENTACOOL 18
#define DOLL_UNOWN 19
#define DOLL_GEODUDE 20
#define DOLL_MACHOP 21
#define DOLL_SILVER_TROPHY 22
#define DOLL_GOLD_TROPHY 23
#define DOLL_MAGNEMITE 24
#define DOLL_NATU 25
#define DOLL_PORYGON2 26
#define DOLL_WOOPER 27
#define DOLL_PICHU 28
#define DOLL_MARILL 29
#define DOLL_TOGEPI 30
#define DOLL_CYNDAQUIL 31
#define DOLL_CHIKORITA 32
#define DOLL_TOTODILE 33
#define DOLL_MEOWTH 34
#define DOLL_DITTO 35
#define DOLL_SMOOCHUM 36
#define DOLL_TREECKO 37
#define DOLL_TORCHIC 38
#define DOLL_MUDKIP 39
#define DOLL_DUSKULL 40
#define DOLL_WYNAUT 41
#define DOLL_BALTOY 42
#define DOLL_KECLEON 43
#define DOLL_AZURILL 44
#define DOLL_SKITTY 45
#define DOLL_SWABLU 46
#define DOLL_GULPIN 47
#define DOLL_LOTAD 48
#define DOLL_SEEDOT 49
#define DOLL_SILVER_SHIELD 50
#define DOLL_GOLD_SHIELD 51

#endif // GUARD_ROOM_DECOR_H