NationalParkContest_MapScripts::
	.byte 0


NationalParkContest_Nick::
	msgbox NationalParkContest_Text_Nick, MSGBOX_NPC
	end

NationalParkContest_William::
	msgbox NationalParkContest_Text_William, MSGBOX_NPC
	end

NationalParkContest_Samuel::
	msgbox NationalParkContest_Text_Samuel, MSGBOX_NPC
	end

NationalParkContest_Barry::
	msgbox NationalParkContest_Text_Barry, MSGBOX_NPC
	end

NationalParkContest_Ed::
	msgbox NationalParkContest_Text_Ed, MSGBOX_NPC
	end

NationalParkContest_Benny::
	msgbox NationalParkContest_Text_Benny, MSGBOX_NPC
	end

NationalParkContest_Josh::
	msgbox NationalParkContest_Text_Josh, MSGBOX_NPC
	end

NationalParkContest_Don::
	msgbox NationalParkContest_Text_Don, MSGBOX_NPC
	end

NationalParkContest_Kipp::
	msgbox NationalParkContest_Text_Kipp, MSGBOX_NPC
	end

NationalParkContest_Cindy::
	msgbox NationalParkContest_Text_Cindy, MSGBOX_NPC
	end

NationalParkContest_Text_Nick:
	.string "NICK: I'm raising fast POKéMON\n"
	.string "for battles.$"

NationalParkContest_Text_William::
	.string "WILLIAM: I'm not concerned about\n"
	.string "winning.\p"
	.string "I'm just looking for rare POKéMON.$"

NationalParkContest_Text_Samuel::
	.string "SAMUEL: If you've got the time to\n"
	.string "chat, go find some bug POKéMON.$"

NationalParkContest_Text_Barry::
	.string "BARRY: You should weaken bug\n"
	.string "POKéMON first, then throw a BALL.$"

NationalParkContest_Text_Ed::
	.string "ED: My PARASECT puts POKéMON to\n"
	.string "sleep with SPORE.$"

NationalParkContest_Text_Benny::
	.string "BENNY: Ssh! You'll scare off\n"
	.string "SCYTHER.\p"
	.string "I'll talk to you later.$"

NationalParkContest_Text_Josh::
	.string "JOSH: I've been collecting bug\n"
	.string "POKéMON since I was just a baby.\p"
	.string "Theres no way I'm going to lose!$"

NationalParkContest_Text_Don::
	.string "DON: I'm going to win!\n"
	.string "Don't bother me.$"

NationalParkContest_Text_Kipp::
	.string "KIPP: I've studied bug POKéMON a\n"
	.string "lot.\p"
	.string "I'm going to win for sure.$"

NationalParkContest_Text_Cindy::
	.string "CINDY: I love bug POKéMON.\p"
	.string "I guess you must like them, too.$"
