RuinsOfAlph_InnerChamber_MapScripts::
	.byte 0


RuinsOfAlph_InnerChamber_Coward::
	msgbox RuinsOfAlph_InnerChamber_Coward_Text_0, MSGBOX_NPC
	return


RuinsOfAlph_InnerChamber_Woman::
	msgbox RuinsOfAlph_InnerChamber_Woman_Text_0, MSGBOX_NPC
	return


RuinsOfAlph_InnerChamber_OldMan::
	msgbox RuinsOfAlph_InnerChamber_OldMan_Text_0, MSGBOX_NPC
	return


RuinsOfAlph_InnerChamber_Coward_Text_0:
	.string "This is a big room, but there's\n"
	.string "nothing here.$"

RuinsOfAlph_InnerChamber_Woman_Text_0:
	.string "This place has a mystical quality\n"
	.string "to it.\p"
	.string "It feels sort of ethereal, even.$"

RuinsOfAlph_InnerChamber_OldMan_Text_0:
	.string "Ancient buildings are often tombs\n"
	.string "of kings.\p"
	.string "Like the pyramids, for instance.$"
