gText_SetClock_WokeMeUp::
	.string "………………………………………………\n"
	.string "……………………………………………\p"
	.string "Zzz… Hm? Wha…?\n"
	.string "You woke me up!\p"
	.string "Will you check the clock for me?$"

gText_Birch_Welcome:: @ 82C897B
	.string "Hello! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is OAK.\p"
	.string "People affectionately refer to me\n"
	.string "as the POKéMON PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "This world…$"

gText_Birch_Pokemon2:: @ 82C89FB
	.string "…is inhabited far and wide by\n"
	.string "creatures that we call POKéMON.\p"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "People and POKéMON live together by\n"
	.string "supporting each other.\p"
	.string "Some people play with POKéMON,\n"
	.string "some battle with them.\p"
	.string "$"

gText_Oak_MainSpeech2::
	.string "But despite this, we don’t know\n"
	.string "everything about POKéMON yet.\p"
	.string "There are still many mysteries\n"
	.string "about POKéMON to solve.\p"
	.string "That’s why I study POKéMON\n"
	.string "as a profession every day.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "But first, tell me a little about\n"
	.string "yourself.\n"
	.string "$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "All right.\n"
	.string "What’s your name?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So it’s {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Ah, okay!\p"
	.string "You’re {PLAYER}{KUN} who’s moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I’ll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
