Underwater_SealedChamber_Braille_GoUpHere:
    brailleformat 4, 6, 26, 13, 7, 9
	.unown "GO UP HERE.$"

SealedChamber_OuterRoom_Braille_ABC:
	brailleformat 7, 6, 21, 13, 10, 9
	.unown "ABC$"

SealedChamber_OuterRoom_Braille_GHI:
	brailleformat 7, 6, 21, 13, 10, 9
	.unown "GHI$"

SealedChamber_OuterRoom_Braille_MNO:
	brailleformat 7, 6, 21, 13, 10, 9
	.unown "MNO$"

SealedChamber_OuterRoom_Braille_TUV:
	brailleformat 7, 6, 21, 13, 10, 9
	.unown "TUV$"

SealedChamber_OuterRoom_Braille_DEF:
	brailleformat 7, 6, 21, 13, 10, 9
	.unown "DEF$"

SealedChamber_OuterRoom_Braille_JKL:
	brailleformat 7, 6, 21, 13, 10, 9
	.unown "JKL$"

SealedChamber_OuterRoom_Braille_PQRS:
	brailleformat 7, 6, 21, 13, 10, 9
	.unown "PQRS$"

SealedChamber_OuterRoom_Braille_Period:
	brailleformat 9, 6, 19, 13, 12, 9
	.unown ".$"

SealedChamber_OuterRoom_Braille_WXYZ:
	brailleformat 7, 6, 21, 13, 10, 9
	.unown "WXYZ$"

SealedChamber_OuterRoom_Braille_Comma:
	brailleformat 9, 6, 19, 13, 12, 9
	.unown ",$"

SealedChamber_OuterRoom_Braille_DigHere:
	brailleformat 7, 4, 23, 15, 10, 7
	.unown "DIG HERE.$"

SealedChamber_InnerRoom_Braille_FirstWailordLastRelicanth:
	brailleformat 0, 0, 29, 19, 3, 3
	.unown "FIRST COMES\n"
	.unown "WAILORD.\n"
	.unown "LAST COMES\n"
	.unown "RELICANTH.$"

SealedChamber_InnerRoom_Braille_InThisCaveWeHaveLived:
	brailleformat 2, 0, 26, 19, 5, 3
	.unown "IN THIS\n"
	.unown "CAVE WE\n"
	.unown "HAVE\n"
	.unown "LIVED.$"

SealedChamber_InnerRoom_Braille_WeOweAllToThePokemon:
	brailleformat 7, 2, 23, 17, 10, 5
	.unown "WE OWE ALL\n"
	.unown "TO THE\n"
	.unown "POKEMON.$"

SealedChamber_InnerRoom_Braille_ButWeSealedThePokemonAway:
	brailleformat 3, 0, 25, 19, 6, 3
	.unown "BUT, WE\n"
	.unown "SEALED THE\n"
	.unown "POKEMON\n"
	.unown "AWAY.$"

SealedChamber_InnerRoom_Braille_WeFearedIt:
	brailleformat 5, 6, 25, 13, 8, 9
	.unown "WE FEARED IT.$"

SealedChamber_InnerRoom_Braille_ThoseWithCourageHope:
	brailleformat 6, 0, 24, 19, 9, 3
	.unown "THOSE WITH\n"
	.unown "COURAGE,\n"
	.unown "THOSE WITH\n"
	.unown "HOPE.$"

SealedChamber_InnerRoom_Braille_OpenDoorEternalPokemonWaits:
	brailleformat 3, 2, 27, 17, 6, 5
	.unown "OPEN A DOOR.\n"
	.unown "AN ETERNAL\n"
	.unown "POKEMON\n"
	.unown "WAITS.$"

DesertRuins_Braille_UseRockSmash:
	brailleformat 1, 0, 27, 19, 4, 3
	.unown "LEFT, LEFT,\n"
	.unown "DOWN, DOWN.\n"
	.unown "THEN, USE\n"
	.unown "ROCK SMASH.$"

IslandCave_Braille_RunLapAroundWall:
	brailleformat 5, 0, 25, 19, 8, 3
	.unown "STAY CLOSE\n"
	.unown "TO THE WALL.\n"
	.unown "RUN AROUND\n"
	.unown "ONE LAP.$"

AncientTomb_Braille_ShineInTheMiddle:
	brailleformat 3, 0, 25, 19, 6, 3
	.unown "THOSE WHO\n"
	.unown "INHERIT OUR\n"
	.unown "WILL, SHINE\n"
	.unown "IN THE MIDDLE.$"
