Underwater_SealedChamber_Braille_GoUpHere: @ 82A6B15
	.byte 4
	.byte 6
	.byte 26
	.byte 13
	.byte 7
	.byte 9
	.unown "GO UP HERE.$"

SealedChamber_OuterRoom_Braille_ABC: @ 82A6B27
	.byte 7
	.byte 6
	.byte 21
	.byte 13
	.byte 10
	.byte 9
	.unown "ABC$"

SealedChamber_OuterRoom_Braille_GHI: @ 82A6B31
	.byte 7
	.byte 6
	.byte 21
	.byte 13
	.byte 10
	.byte 9
	.unown "GHI$"

SealedChamber_OuterRoom_Braille_MNO: @ 82A6B3B
	.byte 7
	.byte 6
	.byte 21
	.byte 13
	.byte 10
	.byte 9
	.unown "MNO$"

SealedChamber_OuterRoom_Braille_TUV: @ 82A6B45
	.byte 7
	.byte 6
	.byte 21
	.byte 13
	.byte 10
	.byte 9
	.unown "TUV$"

SealedChamber_OuterRoom_Braille_DEF: @ 82A6B4F
	.byte 7
	.byte 6
	.byte 21
	.byte 13
	.byte 10
	.byte 9
	.unown "DEF$"

SealedChamber_OuterRoom_Braille_JKL: @ 82A6B59
	.byte 7
	.byte 6
	.byte 21
	.byte 13
	.byte 10
	.byte 9
	.unown "JKL$"

SealedChamber_OuterRoom_Braille_PQRS: @ 82A6B63
	.byte 7
	.byte 6
	.byte 21
	.byte 13
	.byte 10
	.byte 9
	.unown "PQRS$"

SealedChamber_OuterRoom_Braille_Period: @ 82A6B6E
	.byte 9
	.byte 6
	.byte 19
	.byte 13
	.byte 12
	.byte 9
	.unown ".$"

SealedChamber_OuterRoom_Braille_WXYZ: @ 82A6B76
	.byte 7
	.byte 6
	.byte 21
	.byte 13
	.byte 10
	.byte 9
	.unown "WXYZ$"

SealedChamber_OuterRoom_Braille_Comma: @ 82A6B81
	.byte 9
	.byte 6
	.byte 19
	.byte 13
	.byte 12
	.byte 9
	.unown ",$"

SealedChamber_OuterRoom_Braille_DigHere: @ 82A6B89
	.byte 7
	.byte 4
	.byte 23
	.byte 15
	.byte 10
	.byte 7
	.unown "DIG HERE.$"

SealedChamber_InnerRoom_Braille_FirstWailordLastRelicanth: @ 82A6B99
	.byte 0
	.byte 0
	.byte 29
	.byte 19
	.byte 3
	.byte 3
	.unown "FIRST COMES\n"
	.unown "WAILORD.\n"
	.unown "LAST COMES\n"
	.unown "RELICANTH.$"

SealedChamber_InnerRoom_Braille_InThisCaveWeHaveLived: @ 82A6BCA
	.byte 2
	.byte 0
	.byte 26
	.byte 19
	.byte 5
	.byte 3
	.unown "IN THIS\n"
	.unown "CAVE WE\n"
	.unown "HAVE\n"
	.unown "LIVED.$"

SealedChamber_InnerRoom_Braille_WeOweAllToThePokemon: @ 82A6BEC
	.byte 7
	.byte 2
	.byte 23
	.byte 17
	.byte 10
	.byte 5
	.unown "WE OWE ALL\n"
	.unown "TO THE\n"
	.unown "POKEMON.$"

SealedChamber_InnerRoom_Braille_ButWeSealedThePokemonAway: @ 82A6C0D
	.byte 3
	.byte 0
	.byte 25
	.byte 19
	.byte 6
	.byte 3
	.unown "BUT, WE\n"
	.unown "SEALED THE\n"
	.unown "POKEMON\n"
	.unown "AWAY.$"

SealedChamber_InnerRoom_Braille_WeFearedIt: @ 82A6C34
	.byte 5
	.byte 6
	.byte 25
	.byte 13
	.byte 8
	.byte 9
	.unown "WE FEARED IT.$"

SealedChamber_InnerRoom_Braille_ThoseWithCourageHope: @ 82A6C48
	.byte 6
	.byte 0
	.byte 24
	.byte 19
	.byte 9
	.byte 3
	.unown "THOSE WITH\n"
	.unown "COURAGE,\n"
	.unown "THOSE WITH\n"
	.unown "HOPE.$"

SealedChamber_InnerRoom_Braille_OpenDoorEternalPokemonWaits: @ 82A6C73
	.byte 3
	.byte 2
	.byte 27
	.byte 17
	.byte 6
	.byte 5
	.unown "OPEN A DOOR.\n"
	.unown "AN ETERNAL\n"
	.unown "POKEMON\n"
	.unown "WAITS.$"

DesertRuins_Braille_UseRockSmash: @ 82A6CA0
	.byte 1
	.byte 0
	.byte 27
	.byte 19
	.byte 4
	.byte 3
	.unown "LEFT, LEFT,\n"
	.unown "DOWN, DOWN.\n"
	.unown "THEN, USE\n"
	.unown "ROCK SMASH.$"

IslandCave_Braille_RunLapAroundWall: @ 82A6CD4
	.byte 5
	.byte 0
	.byte 25
	.byte 19
	.byte 8
	.byte 3
	.unown "STAY CLOSE\n"
	.unown "TO THE WALL.\n"
	.unown "RUN AROUND\n"
	.unown "ONE LAP.$"

AncientTomb_Braille_ShineInTheMiddle: @ 82A6D06
	.byte 3
	.byte 0
	.byte 25
	.byte 19
	.byte 6
	.byte 3
	.unown "THOSE WHO\n"
	.unown "INHERIT OUR\n"
	.unown "WILL, SHINE\n"
	.unown "IN THE MIDDLE.$"
