Text_ItsATV:
	.string "It's a TV.$"

Text_MyReflection:
	.string "My reflection!\n"
	.string "Lookin' good!$"

Text_AncientPokemonReplica:
	.string "It's a replica of an ancient\n"
	.string "POKéMON.$"

Text_DistinguishedStatue:
	.string "A POKéMON statue…\n"
	.string "It looks very distinguished.$"

Text_PictureBookShelf:
	.string "It's a whole collection of POKéMON\n"
	.string "picture books!$"

Text_BookShelf:
	.string "It's full of difficult books.$"

Text_PokemonCenterBookShelf:
	.string "POKéMON magazines!\n"
	.string "POKéMON PAL…\p"
	.string "POKéMON HANDBOOK…\n"
	.string "POKéMON GRAPH…$"

Text_Vase:
	.string "This vase looks expensive…\n"
	.string "Peered inside…\p"
	.string "But, it was empty.$"

Text_EmptyTrashCan:
	.string "It's empty.$"

Text_ShopShelf: @ 82A82BF
	.string "Lots of POKéMON merchandise!$"

Text_Blueprint:
	.string "A blueprint of some sort?\n"
	.string "It's too complicated!$"
