Text_ItsATV:
	.string "It's a TV.$"

Text_MyReflection:
	.string "My reflection!\n"
	.string "Lookin' good!$"

Text_DistinguishedStatue:
	.string "A POKéMON statue…\n"
	.string "It looks very distinguished.$"

Text_PictureBookShelf: @ 82A81E5
	.string "It's a whole collection of POKéMON\n"
	.string "picture books!$"

Text_BookShelf: @ 82A820D
	.string "It's filled with all sorts of books.$"

Text_DifficultBooks:
	.string "It's full of difficult books.$"

Text_PokemonCenterBookShelf: @ 82A8232
	.string "POKéMON magazines!\n"
	.string "POKéMON PAL…\p"
	.string "POKéMON HANDBOOK…\n"
	.string "POKéMON GRAPH…$"

Text_Vase: @ 82A8276
	.string "This vase looks expensive…\n"
	.string "Peered inside…\p"
	.string "But, it was empty.$"

Text_EmptyTrashCan: @ 82A82B3
	.string "It's empty.$"

Text_ShopShelf: @ 82A82BF
	.string "Lots of POKéMON merchandise!$"

Text_Blueprint: @ 82A82F7
	.string "A blueprint of some sort?\n"
	.string "It's too complicated!$"
