MatchCall_WildBattleText1::
	.string "Hi! {PLAYER}{KUN}, hello!\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I saw this {STR_VAR_2} a while back\n"
	.string "but I couldn't catch it.\p"
	.string "It was so close, too!\n"
	.string "Well, see you again!$"

MatchCall_WildBattleText2::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I tried to catch a nice {STR_VAR_2}\n"
	.string "a little while ago.\p"
	.string "But, it got away.\n"
	.string "I was sure disappointed!\p"
	.string "Okay, bye!$"

MatchCall_WildBattleText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I just took a shot at catching\n"
	.string "this {STR_VAR_2}, but it took off.\p"
	.string "I came oh so close, too!\p"
	.string "It spoiled my day…\n"
	.string "All right, see you!$"

MatchCall_WildBattleText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "You know the {POKEMON} {STR_VAR_2}?\n"
	.string "I came close to getting one.\p"
	.string "It was just a while back.\n"
	.string "I thought I had it but it escaped.\p"
	.string "If I see it again, I'll get it for\n"
	.string "sure, though.\p"
	.string "Okay, catch you later.$"

MatchCall_WildBattleText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\l"
	.string "Catching any {POKEMON} lately?\p"
	.string "A little while ago I came close to\n"
	.string "nabbing one, but it got loose.\p"
	.string "Right, take care!$"

MatchCall_WildBattleText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "Caught any {POKEMON} lately?\p"
	.string "I nearly nabbed one the other day.\n"
	.string "But it evaded me somehow.\p"
	.string "You take care.$"

MatchCall_WildBattleText7::
	.string "…Uh, {PLAYER}{KUN}?\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "Oh, wait! Wait!\n"
	.string "I can catch this {STR_VAR_2}…\p"
	.string "Aaarrrgh! It bolted loose!\n"
	.string "That wasn't just close!$"

MatchCall_WildBattleText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\p"
	.string "Have you had success catching\n"
	.string "{POKEMON} lately?\p"
	.string "I came very close a little while\n"
	.string "ago, but my target got free.\p"
	.string "I need to try harder!\n"
	.string "See you again!$"

MatchCall_WildBattleText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "So? Are you getting more {POKEMON}\n"
	.string "together?\p"
	.string "I'm having a rotten time of it!\n"
	.string "They all get away from me!\p"
	.string "See you!$"

MatchCall_WildBattleText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Listen, I came within a whisker of\n"
	.string "catching this {STR_VAR_2}…\p"
	.string "But, it gave me the slip…\p"
	.string "I need to try harder.\n"
	.string "See you around.$"

MatchCall_WildBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "How are things with you?\p"
	.string "I tried to catch a wild {STR_VAR_2}\n"
	.string "earlier, but it managed to flee.\p"
	.string "I feel defeated…$"

MatchCall_WildBattleText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you still catching {POKEMON}?\p"
	.string "I've been trying to catch them\n"
	.string "myself, but it's not so easy.\p"
	.string "The way of {POKEMON} is deep!$"

MatchCall_WildBattleText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "Have you been catching {POKEMON}?\p"
	.string "I've been trying to catch them\n"
	.string "myself, but with little success.\p"
	.string "The way of {POKEMON} is deep!$"

MatchCall_WildBattleText14::
	.string "Oh, hi, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Just now, I tried to catch a cute\n"
	.string "{STR_VAR_2}.\p"
	.string "It got away, though!\n"
	.string "Oh, you bet I was disappointed!\p"
	.string "Bye-bye!$"

MatchCall_WildBattleText15::
	.string "Hey, {PLAYER}!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I've been thinking about trying\n"
	.string "to catch me some {POKEMON}.\p"
	.string "But I can't seem to find any.\n"
	.string "It's a real puzzler for me!\p"
	.string "I'm at my wit's end!\n"
	.string "See you around!$"

MatchCall_NegativeBattleText1::
	.string "Hi! {PLAYER}{KUN}, hello!\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I tried battling another TRAINER,\n"
	.string "but I lost.\p"
	.string "It was really disappointing.\n"
	.string "Well, see you again!$"

MatchCall_NegativeBattleText2::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I challenged someone else after\n"
	.string "we battled.\p"
	.string "I came close, but I ended up\n"
	.string "losing. Oh, well!$"

MatchCall_NegativeBattleText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I just got cleaned in a battle.\p"
	.string "I guess I need to raise my team\n"
	.string "some more!$"

MatchCall_NegativeBattleText4::
	.string "Hey, {PLAYER}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I tried another battle yesterday,\n"
	.string "but I couldn't pull out the win.\p"
	.string "My team needs more raising.\n"
	.string "Okay, catch you later.$"

MatchCall_NegativeBattleText5::
	.string "Hiya, {PLAYER}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "How are things with you?\p"
	.string "I've been battling on,\n"
	.string "but I haven't won very often.\p"
	.string "I can't get it together.\n"
	.string "Right, take care!$"

MatchCall_NegativeBattleText6::
	.string "Hey, {PLAYER}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "How's it going for you?\p"
	.string "I've been battling hard lately,\n"
	.string "but to little success.\p"
	.string "I can't get into the groove.\n"
	.string "You take care.$"

MatchCall_NegativeBattleText7::
	.string "{STR_VAR_1} here.\n"
	.string "How's it going lately?\p"
	.string "I lost a battle yesterday,\n"
	.string "and it's filled my thoughts.\p"
	.string "I have to devise a plan…\n"
	.string "See you.$"

MatchCall_NegativeBattleText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\p"
	.string "How are your {POKEMON} doing?\n"
	.string "I lost a match the other day.\p"
	.string "I need to try harder!\n"
	.string "See you again!$"

MatchCall_NegativeBattleText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "Listen, listen, you have to hear\n"
	.string "this!\p"
	.string "I had a {POKEMON} battle earlier,\n"
	.string "but I lost at the last second.\p"
	.string "Oh, it burns me up!$"

MatchCall_NegativeBattleText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "A little earlier, I was in a battle.\n"
	.string "I lost, though.\p"
	.string "I need to raise my {POKEMON} more.\n"
	.string "See you around.$"

MatchCall_NegativeBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "How are your {POKEMON}?\p"
	.string "I just lost yet another battle.\p"
	.string "Well, see you!$"

MatchCall_NegativeBattleText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you still battling hard?\p"
	.string "As for me, I lost recently, so I've\n"
	.string "been training my team all over.\p"
	.string "Let's meet again.$"

MatchCall_NegativeBattleText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I hope you've been keeping well.\p"
	.string "I was in a battle just a little\n"
	.string "while before this.\p"
	.string "{PLAYER}{KUN}, try to be active like me.\n"
	.string "See you again!$"

MatchCall_NegativeBattleText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Are you doing good?\p"
	.string "You should go home every so often,\n"
	.string "though.\p"
	.string "Bye-bye!$"

MatchCall_PositiveBattleText1::
	.string "Hi! {PLAYER}{KUN}, hello!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I battled another TRAINER earlier.\n"
	.string "I won! I won!\p"
	.string "My {STR_VAR_2} really worked hard\n"
	.string "for me. This is so great!$"

MatchCall_PositiveBattleText2::
	.string "Hello, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}!\p"
	.string "I had a battle yesterday and\n"
	.string "I won! It's fantastic!$"

MatchCall_PositiveBattleText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}!\l"
	.string "How's your battling?\p"
	.string "Me, I had a battle the other day,\n"
	.string "and my {STR_VAR_2} came up huge!\p"
	.string "The next time I battle you,\n"
	.string "{PLAYER}, it won't be me losing!$"

MatchCall_PositiveBattleText4::
	.string "Hey, {PLAYER}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I had a match earlier.\n"
	.string "I managed to win, but it was close.\p"
	.string "My {STR_VAR_2} put on one\n"
	.string "inspired showing.$"

MatchCall_PositiveBattleText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "How are things with you?\n"
	.string "Battling much?\p"
	.string "I just won a while back!\n"
	.string "My {STR_VAR_2} was brilliant!\p"
	.string "You wait. I'm going to beat you\n"
	.string "next time! Right, take care!$"

MatchCall_PositiveBattleText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "How's it going for you?\p"
	.string "I've been riding a hot streak.\n"
	.string "Why, I just won a battle.\p"
	.string "When we have our next battle,\n"
	.string "I'm sure not going to lose!$"

MatchCall_PositiveBattleText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "My {STR_VAR_2} is a force!\n"
	.string "It won me another battle just now!\p"
	.string "I can't wait to have a rematch\n"
	.string "with you.$"

MatchCall_PositiveBattleText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\p"
	.string "I hope you've been well.\n"
	.string "I wanted to tell you I just won.\p"
	.string "My {STR_VAR_2} worked especially\n"
	.string "hard to get the win.\p"
	.string "See you again!$"

MatchCall_PositiveBattleText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "How are your {POKEMON} holding up?\n"
	.string "Mine just won a battle!\p"
	.string "My {STR_VAR_2} was spectacular,\n"
	.string "I must say!\p"
	.string "I wish I could've shown you!\n"
	.string "See you again!$"

MatchCall_PositiveBattleText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "How has life been treating you?\p"
	.string "My {POKEMON} appear to be charged\n"
	.string "with energy.\p"
	.string "I just won a battle with them.\n"
	.string "See you around.$"

MatchCall_PositiveBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Been in any battles lately?\n"
	.string "I just won another one today!\p"
	.string "I'm on a roll! Gahahaha!\n"
	.string "Well, see you!$"

MatchCall_PositiveBattleText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I trust you've been well?\n"
	.string "I'm still bursting with life!\p"
	.string "Why, just now, I won another match.\n"
	.string "I'm not stepping aside to you\l"
	.string "youngsters yet!$"

MatchCall_PositiveBattleText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I hope you've been keeping well.\n"
	.string "I still have a bounce in my step!\p"
	.string "Why, I just won a battle yet again.\n"
	.string "Oh, I won't lose to young people\l"
	.string "quite yet!\p"
	.string "See you again!$"

MatchCall_PositiveBattleText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I was in a battle recently, and my\n"
	.string "{STR_VAR_2} was exceptional!\p"
	.string "I wish you could have seen it,\n"
	.string "{PLAYER}{KUN}. Bye-bye!$"

MatchCall_SameRouteBattleRequestText1::
	.string "Hi! {PLAYER}, hello!\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Huh? Wait, you're near\n"
	.string "{STR_VAR_2}?\p"
	.string "Oh, wow, we have to battle, then!\n"
	.string "I'll be waiting! See you!$"

MatchCall_SameRouteBattleRequestText2::
	.string "Hello, {PLAYER}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "Oh? You happen to be around\n"
	.string "{STR_VAR_2} right now?\p"
	.string "Would you like to battle now?\n"
	.string "I'll wait for you! See you!$"

MatchCall_SameRouteBattleRequestText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "Oh, hey, are you near\n"
	.string "{STR_VAR_2} right now?\p"
	.string "How would you like to battle with\n"
	.string "me right now?\p"
	.string "I'm not losing again!\n"
	.string "I'll be waiting! Catch you soon!$"

MatchCall_SameRouteBattleRequestText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "Whereabouts are you now?\n"
	.string "Huh? {STR_VAR_2}?\p"
	.string "Want to battle now?\n"
	.string "I'll wait for you. See you!$"

MatchCall_SameRouteBattleRequestText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\l"
	.string "How are things with you?\p"
	.string "You're where now?\n"
	.string "{STR_VAR_2}?\p"
	.string "Well, how about we have a quick\n"
	.string "rematch right away?\p"
	.string "I'll keep an eye out for you.\n"
	.string "See you soon!$"

MatchCall_SameRouteBattleRequestText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "How are your {POKEMON} keeping?\p"
	.string "Oh, is that right? You're around\n"
	.string "{STR_VAR_2}?\p"
	.string "Well, then, we'd better have\n"
	.string "a rematch.\p"
	.string "I can wait, sure.\n"
	.string "See you!$"

MatchCall_SameRouteBattleRequestText7::
	.string "…Er, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here…\p"
	.string "Oh, you happen to be around\n"
	.string "{STR_VAR_2}?\p"
	.string "Then, let's battle.\n"
	.string "Right away, I mean.\p"
	.string "I'll show you my {POKEMON}.\n"
	.string "I'll wait for you.$"

MatchCall_SameRouteBattleRequestText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\p"
	.string "I hope you're doing well.\n"
	.string "Oh, you're near {STR_VAR_2}.\p"
	.string "Would you like to have a battle\n"
	.string "with me, then?\p"
	.string "I'll wait for you.\n"
	.string "See you soon!$"

MatchCall_SameRouteBattleRequestText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "Are you keeping up?\n"
	.string "Oh, you're near {STR_VAR_2}?\p"
	.string "Oh, well, then don't you think we\n"
	.string "should battle?\p"
	.string "Don't keep me waiting too long!$"

MatchCall_SameRouteBattleRequestText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "How are things with you?\n"
	.string "Oh, you're near {STR_VAR_2}.\p"
	.string "We should have a battle now, then.\p"
	.string "I'm ready and waiting.\n"
	.string "Be quick!$"

MatchCall_SameRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Ah, so where you are now is\n"
	.string "{STR_VAR_2}?\p"
	.string "Well, then, we just have to have\n"
	.string "a battle, don't you think?\p"
	.string "I'll wait around for you!\n"
	.string "See you real quick!$"

MatchCall_SameRouteBattleRequestText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Where might you be now?\p"
	.string "{STR_VAR_2}?\n"
	.string "That's quite close by!\p"
	.string "What do you say we have a battle\n"
	.string "now?\p"
	.string "I can wait.\n"
	.string "See you!$"

MatchCall_SameRouteBattleRequestText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I hope you've been keeping well.\n"
	.string "Oh, you're near {STR_VAR_2}?\p"
	.string "Since that's not very far away,\n"
	.string "come see me for a battle.\p"
	.string "I'll wait for you.\n"
	.string "Bye for now.$"

MatchCall_SameRouteBattleRequestText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You're what? …{STR_VAR_2}?\n"
	.string "That's very close.\p"
	.string "Don't you think we ought to have\n"
	.string "a battle?\p"
	.string "I'll be looking for you!\n"
	.string "Bye-bye!$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "Hi! {PLAYER}, hello!\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Want to have a battle with me?\p"
	.string "I'll be waiting for you around\n"
	.string "{STR_VAR_2}!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "Hello, {PLAYER}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "Would you like to have a battle\n"
	.string "with me again?\p"
	.string "You can find me around\n"
	.string "{STR_VAR_2}. I'll be waiting!$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "My {POKEMON} have grown a lot\n"
	.string "tougher since last time.\p"
	.string "I want to see how strong they've\n"
	.string "become with your {POKEMON}, {PLAYER}.\p"
	.string "So, let's have a battle!\p"
	.string "I'll be waiting for you around\n"
	.string "{STR_VAR_2}.$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "How are things with you?\p"
	.string "My {POKEMON} have grown pretty\n"
	.string "tough lately.\p"
	.string "Hey, how would you like to have\n"
	.string "another battle with me?\p"
	.string "Let's meet up around\n"
	.string "{STR_VAR_2}, okay?$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "My {POKEMON} are growing up in\n"
	.string "decent ways.\p"
	.string "I'd really like to have another\n"
	.string "battle with you.\p"
	.string "I'll keep an eye out for you around\n"
	.string "{STR_VAR_2}. See you soon!$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "I hope you're on top of things.\p"
	.string "I was thinking I'd like another\n"
	.string "battle with you. What do you say?\p"
	.string "If you feel like a battle,\n"
	.string "come to {STR_VAR_2}.\p"
	.string "See you!$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "…Er, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here…\l"
	.string "So? Are your {POKEMON} growing?\p"
	.string "Mine sure got stronger.\n"
	.string "I'd like to show you.\p"
	.string "I'll be around {STR_VAR_2}.\n"
	.string "Come see me for a match.\p"
	.string "See you around.$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\p"
	.string "I hope you're doing well.\n"
	.string "My {POKEMON} are very frisky.\p"
	.string "If you're ever in the area, please\n"
	.string "give me a rematch.\p"
	.string "I'll be around {STR_VAR_2}.\n"
	.string "Until then, good-bye!$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "How are your {POKEMON} doing?\p"
	.string "My {POKEMON} keep getting better.\n"
	.string "I'd like to show you, {PLAYER}{KUN}.\p"
	.string "I'm around {STR_VAR_2} now,\n"
	.string "so let's battle if you're close by.\p"
	.string "Hope I see you soon!$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\l"
	.string "So, how are things with you?\p"
	.string "My {POKEMON} have grown much\n"
	.string "stronger than before.\p"
	.string "I'd love another battle with you,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "I'll be around {STR_VAR_2}.\n"
	.string "Come see me if you're close.$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "Where might you be now?\p"
	.string "My {POKEMON} are full of life.\n"
	.string "They appear to be looking forward\l"
	.string "to seeing your {POKEMON}, {PLAYER}{KUN}.\p"
	.string "I'm around {STR_VAR_2} now.\n"
	.string "I hope you'll seek us out.$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I should tell you, my {POKEMON} have\n"
	.string "grown to be quite robust lately.\p"
	.string "I would like to see them in a battle\n"
	.string "with you, {PLAYER}{KUN}.\p"
	.string "We'll be around {STR_VAR_2}.\n"
	.string "Come see us anytime!$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "Are your {POKEMON} keeping well?\p"
	.string "My {POKEMON} have been so healthy,\n"
	.string "they don't look capable of losing!\p"
	.string "I would surely love to have another\n"
	.string "battle with you.\p"
	.string "If you're near {STR_VAR_2},\n"
	.string "do come see us.$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "Keeping well, I hope.\p"
	.string "Oh, yes! My {POKEMON} are\n"
	.string "much stronger than before.\p"
	.string "Don't you think we ought to have\n"
	.string "a battle, {PLAYER}{KUN}?\p"
	.string "We'll be waiting for you around\n"
	.string "{STR_VAR_2}.\p"
	.string "Come see us anytime, okay?$"

MatchCall_PersonalizedText1::
	.string "It's me, the mountain-loving\n"
	.string "{STR_VAR_1}!\p"
	.string "Well, since we met, have you grown\n"
	.string "to appreciate the mountains more?\p"
	.string "I rarely see you in the mountains…\p"
	.string "Next time, we'll meet somewhere\n"
	.string "around {STR_VAR_2}.$"

MatchCall_PersonalizedText2::
	.string "This is {STR_VAR_1}.\n"
	.string "Hello.\p"
	.string "I was just telling a new TRAINER\n"
	.string "about you.\p"
	.string "I told her about a strong TRAINER\n"
	.string "who raises {POKEMON} with care.\p"
	.string "I hope you'll become a TRAINER\n"
	.string "that everyone will admire.\p"
	.string "I hope we meet again!$"

MatchCall_PersonalizedText3::
	.string "Hello! It's {STR_VAR_1}.\p"
	.string "I love where I am now.\n"
	.string "It's pleasant with sweet aromas!\p"
	.string "I think someone planted BERRIES,\n"
	.string "and they burst into bloom.\p"
	.string "See you again sometime!$"

MatchCall_PersonalizedText4::
	.string "Hello! Thirty years of exploration,\n"
	.string "{STR_VAR_1} at your service!\p"
	.string "It seems that you're energetically\n"
	.string "traveling here and there.\p"
	.string "Have you discovered any new ruins?\n"
	.string "Please tell if you have!\p"
	.string "Now, if you'll excuse me,\n"
	.string "I have ruins to explore.$"

MatchCall_PersonalizedText5::
	.string "It's {STR_VAR_1}!\p"
	.string "Know what I'm doing today?\n"
	.string "Looking at waves from the beach!\p"
	.string "Sigh… The waves are all sparkly.\n"
	.string "The sea is the prettiest from here.\l"
	.string "I'm getting hungry, so bye-bye!$"

MatchCall_PersonalizedText6::
	.string "Munch-chew…\n"
	.string "Oh, hi, it's {STR_VAR_1}.\l"
	.string "I love eating on the beach.\p"
	.string "My {POKEMON} and I have been doing\n"
	.string "great. We're fully fueled!\l"
	.string "I'm going for a swim. Bye!$"

MatchCall_PersonalizedText7::
	.string "Hello, this is {STR_VAR_1}…\p"
	.string "I've grown a little jaded with this\n"
	.string "whole COOLTRAINER thing…\p"
	.string "Everyone thinks I'm a perfect\n"
	.string "TRAINER, and that makes me try to\l"
	.string "live up to that expectation.\p"
	.string "But I guess that goes with being\n"
	.string "a COOLTRAINER.\p"
	.string "I'll just have to buckle down…\n"
	.string "and grin and bear it.\p"
	.string "You're the only person that I could\n"
	.string "confide in like this.\p"
	.string "But when I see you next,\n"
	.string "don't worry, I won't whine!$"

MatchCall_PersonalizedText8::
	.string "Yahoo, it's {STR_VAR_1}!\n"
	.string "How do you do?\p"
	.string "I've been raising my {POKEMON} with\n"
	.string "you as the target.\p"
	.string "I don't intend to lose when we\n"
	.string "battle again.\p"
	.string "Isn't it great to have TRAINER\n"
	.string "friends? Let's meet again!$"

MatchCall_PersonalizedText9::
	.string "It's {STR_VAR_1}…\n"
	.string "Right now, behind you…\l"
	.string "Wasn't there something…?\p"
	.string "The power of the {POKEMON} that\n"
	.string "sleep here at MT. PYRE…\p"
	.string "It's telling me about you…\p"
	.string "You should walk away quickly and\n"
	.string "never once look back…\p"
	.string "Giggle…\n"
	.string "Farewell…$"

MatchCall_PersonalizedText10::
	.string "This is {STR_VAR_1}.\n"
	.string "How do you do?\p"
	.string "Isn't it convenient that we can\n"
	.string "chat like this at a distance?\p"
	.string "Before, if I wanted to speak with\n"
	.string "anyone, I had to have my father\l"
	.string "drive me…\p"
	.string "I should be going now.\n"
	.string "I'm glad we had this chat.$"

MatchCall_PersonalizedText11::
	.string "It's {STR_VAR_1}!\n"
	.string "Will you listen to this?\p"
	.string "I like the SAFARI ZONE a lot,\n"
	.string "but whenever I go, I get lost!\p"
	.string "All that tall grass!\n"
	.string "And it's much too spread out!\p"
	.string "I feel better getting that off\n"
	.string "my chest!\p"
	.string "I'm off to the SAFARI ZONE again!\n"
	.string "Catch you!$"

MatchCall_PersonalizedText12::
	.string "Hello, {STR_VAR_1} here.\n"
	.string "Yes, correct, I am rich, yes.\p"
	.string "I should tell you, my wealth has\n"
	.string "grown since we last met.\p"
	.string "What's more, my {POKEMON} have also\n"
	.string "grown stronger.\p"
	.string "I can't shake the feeling that\n"
	.string "this world exists for me!\p"
	.string "Oh, no need to say a word!\n"
	.string "Everyone knows it's true!\p"
	.string "Oh, you must excuse me, I have this\n"
	.string "formal dinner to attend.$"

MatchCall_PersonalizedText13::
	.string "Ufufufufu…\n"
	.string "It's me, {STR_VAR_1}…\p"
	.string "Can you guess what I'm seeing?\n"
	.string "A pair of {STR_VAR_2} in a battle.\p"
	.string "Maybe I'll try catching the winner…\n"
	.string "Ufufufufufu…\p"
	.string "I… I'm kind of busy now.\n"
	.string "I have to go.$"

MatchCall_PersonalizedText14::
	.string "Oh, it's {STR_VAR_1}!\p"
	.string "I was just thinking I'm getting\n"
	.string "bored of the ABANDONED SHIP.\p"
	.string "But since I'm already here,\n"
	.string "and I want to beat you once,\l"
	.string "I'll be sticking around a bit more.\p"
	.string "If you feel compelled, why don't\n"
	.string "you come see me?\p"
	.string "I think today will be the day that\n"
	.string "I finally challenge the man next\l"
	.string "door to a match.\p"
	.string "Be seeing you!$"

MatchCall_PersonalizedText15::
	.string "I'm {STR_VAR_1}!\n"
	.string "The man of the sea!\p"
	.string "You know what I think?\p"
	.string "The TRAINERS out at sea are\n"
	.string "the toughest of the tough!\p"
	.string "You should learn from me and train\n"
	.string "in the sea…\p"
	.string "Whoops, giant surf rising!\p"
	.string "It's a great training opportunity!\n"
	.string "Sorry, but I have to go!$"

MatchCall_PersonalizedText16::
	.string "It's {STR_VAR_1}! Listen, I've been\n"
	.string "teaching karate to my {POKEMON}.\p"
	.string "But now they're better than me!\n"
	.string "I've done nothing but lose to them!\p"
	.string "But even though I may lose to\n"
	.string "{POKEMON}, I won't lose to another\l"
	.string "TRAINER, no sir!\p"
	.string "We have to battle again!\n"
	.string "Ugwaah!$"

MatchCall_PersonalizedText17::
	.string "It's me, {STR_VAR_1}.\n"
	.string "How're your travels unwinding?\p"
	.string "…Whoa, is that right?\n"
	.string "Sounds awfully stimulating!\p"
	.string "I think I could write a song about\n"
	.string "one of your episodes.\p"
	.string "…Oh, hey, I'm feeling it.\n"
	.string "I hear the riffs in my head.\p"
	.string "I'd better get this tune properly\n"
	.string "written, so I've got to fly! Later!$"

MatchCall_PersonalizedText18::
	.string "This is {STR_VAR_1}…\n"
	.string "Hear my new song.\p"
	.string "Lalala, {STR_VAR_2}, {STR_VAR_2}!\n"
	.string "Why are you that {STR_VAR_2}?\l"
	.string "Why can't I be you, {STR_VAR_2}?\l"
	.string "Lala, {STR_VAR_2} and {STR_VAR_1},\l"
	.string "{STR_VAR_1} and {STR_VAR_2}…\p"
	.string "Repeat chorus, fade…$"

MatchCall_PersonalizedText19::
	.string "I'm {STR_VAR_1}, you know,\n"
	.string "the camping expert!\p"
	.string "When we battled, I couldn't help\n"
	.string "but lose to you.\p"
	.string "After all, my expertise is in\n"
	.string "camping.\p"
	.string "But win or lose, I like to battle\n"
	.string "when I'm camping.\p"
	.string "Battle with us again, okay?\n"
	.string "Oh, and let's go camping, too!$"

MatchCall_PersonalizedText20::
	.string "It's me, me, {STR_VAR_1}!\p"
	.string "I'd like to climb other mountains\n"
	.string "than this one, to be honest.\p"
	.string "But I'm not sure if there'd be any\n"
	.string "ladies like on MT. CHIMNEY.\p"
	.string "If you know any other mountain\n"
	.string "with ladies around, let me know!\p"
	.string "Ehehehe, see you around!$"

MatchCall_PersonalizedText21::
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "It's {STR_VAR_1}…\p"
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "That's all today…$"

MatchCall_PersonalizedText22::
	.string "This is {STR_VAR_1}. Today, I had\n"
	.string "this feeling I would chat with you.\p"
	.string "My desire to defeat you builds\n"
	.string "by day and by night.\p"
	.string "You have a rival like that, yes?\n"
	.string "I wish it were me…\p"
	.string "I'm glad you heard me out.\n"
	.string "See you!$"

MatchCall_PersonalizedText23::
	.string "It's {STR_VAR_1}.\p"
	.string "When there's a strong TRAINER\n"
	.string "nearby, I can sometimes sense that\l"
	.string "somehow.\p"
	.string "Did you pass close by, {PLAYER}{KUN}?\n"
	.string "Maybe it was you.\p"
	.string "I'll be waiting for your visit.\n"
	.string "Bye!$"

MatchCall_PersonalizedText24::
	.string "Hello, this is {STR_VAR_1}.\n"
	.string "You sound well, {PLAYER}{KUN}.\p"
	.string "I've traveled around the world,\n"
	.string "but I must say I've taken a great\l"
	.string "shine to this region.\p"
	.string "I plan to stay here a while.\n"
	.string "Perhaps we can meet again?\p"
	.string "I've not forgotten your dazzling\n"
	.string "techniques.\p"
	.string "I do hope for a rematch.$"

MatchCall_PersonalizedText25::
	.string "Snivel… It's… {STR_VAR_1}…\n"
	.string "…Sob…\p"
	.string "ROXANNE chewed me out in class\n"
	.string "today.\p"
	.string "But I don't dislike her or anything.\p"
	.string "ROXANNE tells me exactly what\n"
	.string "I did wrong so I can learn from it.\p"
	.string "You bet I'll be going to\n"
	.string "the TRAINER'S SCHOOL tomorrow!\p"
	.string "See you later!$"

MatchCall_PersonalizedText26::
	.string "It's {STR_VAR_1}!\p"
	.string "ROXANNE let me battle with her\n"
	.string "yesterday.\p"
	.string "The results…\n"
	.string "Terrible, like you needed to ask.\p"
	.string "But I was delighted that ROXANNE\n"
	.string "would even let me challenge her!\p"
	.string "You wouldn't believe how much\n"
	.string "more I admire her!\p"
	.string "I'm going to really focus and work!\n"
	.string "I'd better go!$"

MatchCall_PersonalizedText27::
	.string "Hi, it's ANNA! I'm with my junior\n"
	.string "partner MEG again today.\p"
	.string "I really love caring for MEG and\n"
	.string "{POKEMON}. They're so cute!\p"
	.string "I wish I could look after them\n"
	.string "as if they were my siblings!\p"
	.string "Oh, hi, MEG!\n"
	.string "Did you get the buns?\p"
	.string "Huh? No, no, I'm not treating you\n"
	.string "like my personal slave!\p"
	.string "You lost the match, so you have\n"
	.string "to go buy the bread as punishment!\p"
	.string "I wouldn't treat you like a slave,\n"
	.string "MEG! You're too special to me!\p"
	.string "I have to go now.\n"
	.string "It's time for our snack!$"

MatchCall_PersonalizedText28::
	.string "I love {POKEMON}!\n"
	.string "It's {STR_VAR_1} from the FAN CLUB!\p"
	.string "You have to hear this!\n"
	.string "My sweet {POKEMON}…\p"
	.string "Snort! Wahaha!\n"
	.string "I can't say any more! It's a secret!\l"
	.string "It's just too cute for words!\p"
	.string "Oh, my sweet {STR_VAR_2} is begging\n"
	.string "for a {POKEBLOCK}!\p"
	.string "It's the picture of cuteness!\p"
	.string "Sorry, but I can't talk now!\n"
	.string "You'll have to hear this next time!$"

MatchCall_PersonalizedText29::
	.string "Ohoho!\p"
	.string "This is {STR_VAR_1}! I can't wait to\n"
	.string "tell you about my darling {POKEMON}!\p"
	.string "Please, you must listen to this.\n"
	.string "It's about my darling {STR_VAR_2}.\p"
	.string "Whenever anyone picks it up,\n"
	.string "it leaps straight into my arms!\p"
	.string "Oh… Oh… Could there be anything\n"
	.string "more blissful?\p"
	.string "Oh, it feels so heavenly!\p"
	.string "I'm so glad I could share some of\n"
	.string "my happiness with you.\p"
	.string "Well, I must be going.\n"
	.string "Bye, now!$"

MatchCall_PersonalizedText30::
	.string "I am… {STR_VAR_1}.\n"
	.string "People call me an EXPERT.\p"
	.string "But there is one thing I know.\n"
	.string "I could not be an EXPERT on my own\l"
	.string "power.\p"
	.string "Only with the help of {POKEMON} can\n"
	.string "a TRAINER become an EXPERT.\p"
	.string "Humph! I believe I may have said\n"
	.string "something deep and profound!\p"
	.string "I shall leave you in good spirits!$"

MatchCall_PersonalizedText31::
	.string "It's {STR_VAR_1}.\n"
	.string "I'm glad to chat with you!\p"
	.string "I am feeling alive and refreshed\n"
	.string "soaking in this hot-spring tub.\p"
	.string "I've been battling young TRAINERS\n"
	.string "since we met, but you're still\l"
	.string "the best of the lot.\p"
	.string "I imagine you'll become an EXPERT\n"
	.string "in your old age! Ohohoho…$"

MatchCall_PersonalizedText32::
	.string "Yay! This is {STR_VAR_1}!\n"
	.string "What's up?\p"
	.string "I might be imagining this, but when\n"
	.string "I win battles, my shorts seem to\l"
	.string "feel, like, better. Materially.\p"
	.string "What do I mean by that?\n"
	.string "It's kind of hard to explain, but…\l"
	.string "How would I say this now…\l"
	.string "My shorts feel silkier!\p"
	.string "And when I battled you, {PLAYER}{KUN},\n"
	.string "my shorts felt icky and coarse.\p"
	.string "… … … … … …\n"
	.string "You didn't really believe that?\l"
	.string "Ehehehe, that's all! Bye now!$"

MatchCall_PersonalizedText33::
	.string "Ahoy!\n"
	.string "{STR_VAR_1} here!\p"
	.string "As always, I'm fishing with wild\n"
	.string "abandon!\p"
	.string "Are there other places I can fish\n"
	.string "than the sea and rivers?\p"
	.string "I get these powerful urges to\n"
	.string "fish just about anywhere!\p"
	.string "Oh, gosh, darn it!\n"
	.string "My line's tangled up!\p"
	.string "Gotta go!\n"
	.string "Find me some new fishing spots!$"

MatchCall_PersonalizedText34::
	.string "Hey, there! It's {STR_VAR_1}.\n"
	.string "Are you taking it casually?\p"
	.string "Ever since I was a kid, you know,\n"
	.string "I've always been placid, huh?\p"
	.string "I never was much for getting all\n"
	.string "stressed or rushing things.\p"
	.string "But wouldn't you know it,\n"
	.string "I'm now a TRIATHLETE.\p"
	.string "You just can't tell where life will\n"
	.string "take you, if you get my drift.\p"
	.string "You're a TRAINER now, but who\n"
	.string "knows what the future holds, huh?\p"
	.string "Imagine yourself as a teacher,\n"
	.string "or maybe an artist. Cool, huh?\p"
	.string "But, hey, be cool. Take it casual.\n"
	.string "See you around.$"

MatchCall_PersonalizedText35::
	.string "This is {STR_VAR_1}!\n"
	.string "I'm cycling right now.\p"
	.string "I love swimming and running,\n"
	.string "but cycling is my first love!\p"
	.string "It makes my whole body feel as if\n"
	.string "I'm one with the wind.\p"
	.string "It exhilarates me as if I were\n"
	.string "flying!\p"
	.string "Okay! Today, I'm going to set a new\n"
	.string "CYCLING ROAD record!\p"
	.string "You should make the challenge, too!\n"
	.string "See you!$"

MatchCall_PersonalizedText36::
	.string "Yo, this is {STR_VAR_1}! I'm smack\n"
	.string "in the middle of a triathlon!\p"
	.string "But, hey, I've always got time to\n"
	.string "shoot the breeze!\p"
	.string "Working out with {POKEMON} feels\n"
	.string "mighty good!\p"
	.string "Without exchanging words, we synch\n"
	.string "as if we shared a heart.\p"
	.string "It's inspiring!\p"
	.string "Gasp… Chatting while running…\n"
	.string "I'm getting run down…\l"
	.string "Gasp… Have…to…go…$"

MatchCall_PersonalizedText37::
	.string "Hi, it's {STR_VAR_1}.\n"
	.string "If you want to improve endurance,\l"
	.string "high-altitude training is it!\p"
	.string "Try running on a mountaintop.\n"
	.string "You'll be gasping in no time!\p"
	.string "I'm getting oxygen starved, too!\n"
	.string "See you!$"

MatchCall_PersonalizedText38::
	.string "Oh, it's {STR_VAR_1}, hello.\p"
	.string "I've been swimming a lot but I still\n"
	.string "can't seem to reach EVERGRANDE.\p"
	.string "Maybe I'm just going in circles.\p"
	.string "No, no, that can't be possible.\n"
	.string "Wahahaha.\l"
	.string "Take care!$"

MatchCall_PersonalizedText39::
	.string "Hey, it's {STR_VAR_1}…\n"
	.string "Whoops!\p"
	.string "Splash!\p"
	.string "Blug-blug-blug-blug…\p"
	.string "Sploosh!\p"
	.string "Whiff-whiff! Whiff-whiff!\p"
	.string "Hey! Sorry about that!\n"
	.string "I just put on some suntan oil.\p"
	.string "So my {POKE}NAV went whoopsy\n"
	.string "out of my hand into the water!\p"
	.string "But, boy, DEVON's {POKE}NAV is built\n"
	.string "tough. It survived that dunking!\p"
	.string "Anyways, I'm busy sunbathing,\n"
	.string "so let's chat another time.$"

MatchCall_PersonalizedText40::
	.string "Hello, this is {STR_VAR_1}.\p"
	.string "Out of the three triathlon events,\n"
	.string "I like swimming best.\p"
	.string "But if I stay in the sea too long,\n"
	.string "won't I get all prune-like?\p"
	.string "Ooh, triathlon is such a grueling\n"
	.string "test of human endurance! Bye!$"

MatchCall_PersonalizedText41::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "How are your {POKEMON} doing?\p"
	.string "My DRAGON {POKEMON} appear to be\n"
	.string "in peak form. Bye for now.$"

MatchCall_PersonalizedText42::
	.string "{STR_VAR_1} here.\p"
	.string "My {STR_VAR_2} has grown even more\n"
	.string "tough than that last time.\p"
	.string "I'm not going to lose again to you.\n"
	.string "You wait till next time!\p"
	.string "See you around!$"

MatchCall_PersonalizedText43::
	.string "It is {STR_VAR_1} here.\p"
	.string "I have continued with my studies\n"
	.string "in the art of concealment.\p"
	.string "But I have been too successful.\n"
	.string "No one has been able to find me.\l"
	.string "My success makes me lonely…\p"
	.string "Like smoke I disappear!\n"
	.string "Farewell!$"

MatchCall_PersonalizedText44::
	.string "This is {STR_VAR_1}.\n"
	.string "I kept up my training since we met.\p"
	.string "My {STR_VAR_2} is getting pretty\n"
	.string "tough.\p"
	.string "Training on a beach is effective,\n"
	.string "just as I thought. Bye now!$"

MatchCall_PersonalizedText45::
	.string "How do you do?\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I wonder when this yucky volcanic\n"
	.string "ash will stop falling?\p"
	.string "If it gets too deep, it will cover\n"
	.string "up the pattern on my parasol…\p"
	.string "Let's promise to meet again!$"

MatchCall_PersonalizedText46::
	.string "Hi, {STR_VAR_1} here.\p"
	.string "Did you know that it's easier to\n"
	.string "float in the sea than a pool?\p"
	.string "Just by lying still, your body will\n"
	.string "float on its own.\p"
	.string "But if you float for too long,\n"
	.string "watch that you don't get carried\l"
	.string "off too far out.\p"
	.string "…Where am I, anyway?\n"
	.string "I'd better go!$"

MatchCall_PersonalizedText47::
	.string "Oh, {PLAYER}{KUN}, hello!\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I'm up in the mountains now.\p"
	.string "But the ground is too bumpy.\n"
	.string "I can't pitch my tent here…\p"
	.string "Oh, I had a brilliant idea!\p"
	.string "Maybe I can get my {POKEMON} to tamp\n"
	.string "the ground flat here!\p"
	.string "I'm going to try that!\n"
	.string "Bye-bye!$"

MatchCall_PersonalizedText48::
	.string "Oh, hi, hi, this is {STR_VAR_1}!\p"
	.string "I'm raising {POKEMON} with LIV!\n"
	.string "We're trying very hard!\p"
	.string "If we try harder, can we become\n"
	.string "number one? Bye-bye!$"

MatchCall_PersonalizedText49::
	.string "{STR_VAR_1} here!\p"
	.string "I'm a SAILOR, but I'm not on a boat\n"
	.string "now.\p"
	.string "It makes me wonder--what should\n"
	.string "a SAILOR on land be called?\p"
	.string "That's what I've been thinking\n"
	.string "while staring out across the waves.\p"
	.string "All right, next time!$"

MatchCall_PersonalizedText50::
	.string "It's {STR_VAR_1}.\n"
	.string "So? Get any more {POKEMON}?\p"
	.string "If you catch a new {POKEMON},\n"
	.string "you have to come show me.\p"
	.string "I won't whine for it, honest.\n"
	.string "I'll be waiting. See you.$"

MatchCall_PersonalizedText51::
	.string "This is {STR_VAR_1}.\p"
	.string "Are you raising your {POKEMON}\n"
	.string "in the optimal way?\p"
	.string "The air is clean where I am.\n"
	.string "It's the perfect environment for\l"
	.string "raising {POKEMON}.\p"
	.string "If you're going to focus on raising\n"
	.string "{POKEMON}, you should come out to\l"
	.string "{STR_VAR_2}. Take care now.$"

MatchCall_PersonalizedText52::
	.string "Hi, this is {STR_VAR_1}.\p"
	.string "I gave a {POKEBLOCK} to my {STR_VAR_2}.\n"
	.string "It seemed to enjoy it very much.\p"
	.string "It looks like {POKEMON} have their\n"
	.string "likes and dislikes with {POKEBLOCK}S.\p"
	.string "I find that quite fascinating.\n"
	.string "Please do take care.$"

MatchCall_PersonalizedText53::
	.string "{STR_VAR_1} here.\p"
	.string "If you cooperate with {POKEMON},\n"
	.string "one can be comfortable in the wild.\p"
	.string "Everyone should realize that and\n"
	.string "cooperate with {POKEMON} more.\p"
	.string "That would be ideal.\n"
	.string "I really think so.\p"
	.string "I think you're on the right track!\n"
	.string "Catch you later!$"

MatchCall_PersonalizedText54::
	.string "Hi, it's {STR_VAR_1}. You know,\n"
	.string "the TRAINER who's always prepared!\p"
	.string "{PLAYER}{KUN}, do you have enough items?\n"
	.string "Are your {POKEMON} fit for action?\p"
	.string "Keeping everything perfect around\n"
	.string "you all the time is the secret to\l"
	.string "keeping your journey going.\p"
	.string "I'd better go check my own\n"
	.string "supplies! Be vigilant!$"

MatchCall_PersonalizedText55::
	.string "It's {STR_VAR_1}!\n"
	.string "It's {STR_VAR_1}!\p"
	.string "{STR_VAR_2} is a very busy\n"
	.string "thoroughfare, so I get challenged\l"
	.string "by all kinds of TRAINERS every day.\p"
	.string "Today, I won five battles and lost\n"
	.string "only three!\p"
	.string "How did you do today?\n"
	.string "Tell me about it next time, okay?$"

MatchCall_PersonalizedText56::
	.string "It's me, {STR_VAR_1}.\p"
	.string "I'm popular because I have lots\n"
	.string "of BUG {POKEMON}, right?\p"
	.string "Well, I took a bunch of my fave\n"
	.string "bugs to school today.\p"
	.string "This girl I like started crying!\n"
	.string "Go ahead and laugh if you want.\p"
	.string "I have to try teaching her what\n"
	.string "makes BUG {POKEMON} so appealing.\p"
	.string "Snivel…\n"
	.string "See you!$"

MatchCall_PersonalizedText57::
	.string "Hah! Hah! Hah! Hah!\p"
	.string "Hi! It's {STR_VAR_1}! Hah! Hah!\p"
	.string "Trying to chat…\n"
	.string "While climbing…\l"
	.string "Is harsh exercise… Hah! Hah!\p"
	.string "Urgh! Oof…\n"
	.string "It's steeper now…\l"
	.string "We'll chat…another time…\l"
	.string "Hah! Hah! Hah!$"

MatchCall_PersonalizedText58::
	.string "Oh, hi!\p"
	.string "I'm still searching for treasures\n"
	.string "with KIRA!\p"
	.string "Maybe there isn't any treasure\n"
	.string "here at all…\p"
	.string "But the important thing is for me\n"
	.string "to search alongside KIRA.\p"
	.string "Oh, hey, KIRA!\n"
	.string "Wh-why are you angry?\p"
	.string "I'm not ignoring you, honey!\n"
	.string "You're my one and only!\p"
	.string "…{PLAYER}, I have to go, bye!$"

MatchCall_PersonalizedText59::
	.string "This is {STR_VAR_1}!\p"
	.string "I went to DEWFORD's GYM again\n"
	.string "for training.\p"
	.string "BRAWLY, the GYM LEADER, seems\n"
	.string "to be tougher now.\p"
	.string "Something about being toughened\n"
	.string "by the wild waves…\p"
	.string "But he's still as cool as ever.\n"
	.string "The ladies adore him!\l"
	.string "It makes me envious, frankly.\p"
	.string "I wonder… Is his friend BRUNO\n"
	.string "the same way as BRAWLY?\p"
	.string "You know, all sweaty or smelly,\n"
	.string "and prone to calling people\l"
	.string "“big wave,” that sort of thing.\p"
	.string "But, hey, this jealousy thing isn't\n"
	.string "very seemly, is it?\p"
	.string "Forget this chat ever happened,\n"
	.string "how about it? So long!$"

MatchCall_PersonalizedText60::
	.string "It's a pleasure to chat with\n"
	.string "a young TRAINER like you.\p"
	.string "I imagine that you will continue to\n"
	.string "enjoy {POKEMON} whatever your age.\p"
	.string "Wouldn't it be good if you had\n"
	.string "a partnership like ours?\p"
	.string "Of course, {PLAYER}{KUN}, you already\n"
	.string "enjoy the trust and companionship\l"
	.string "of your {POKEMON} now.\p"
	.string "You have the makings of long and\n"
	.string "enduring relationships already!\p"
	.string "Hahaha!\n"
	.string "Never be discouraged!$"

MatchCall_PersonalizedText61::
	.string "Hi, this is {STR_VAR_1}!\n"
	.string "We just won a battle!\p"
	.string "We don't win often, but it was this\n"
	.string "cool SWIMMER guy.\p"
	.string "My sister was steamed!\p"
	.string "She wanted to pretend that she\n"
	.string "was weak to make an impression!\p"
	.string "She always chews me out whether\n"
	.string "we win or lose!\p"
	.string "{PLAYER}{KUN}, can you say something\n"
	.string "to her next time?\p"
	.string "Okay, see you!$"

MatchCall_PersonalizedText62::
	.string "{STR_VAR_1} here, yes.\n"
	.string "I headed out to sea yesterday.\p"
	.string "I had been hoping to find a new\n"
	.string "ruin to explore.\p"
	.string "But the tides somehow seemed to\n"
	.string "carry me back where I started.\p"
	.string "I'm still weak at battling, too…\n"
	.string "Feel free to mock me…\l"
	.string "But I won't give up.\p"
	.string "My day will come when I discover\n"
	.string "a new ruin!\p"
	.string "That's all I have to say!\n"
	.string "Farewell for now!$"

MatchCall_PersonalizedText63::
	.string "Ahoy there!\n"
	.string "It's me, {STR_VAR_1}!\l"
	.string "I'm out on ROUTE 108 now!\l"
	.string "In other words, where I always am!\p"
	.string "Today, a gorgeous SWIMMER \n"
	.string "swam by me!\p"
	.string "So I startled her with a shout!\p"
	.string "And she gave me a nasty glare!\p"
	.string "That's all from ROUTE 108!\n"
	.string "Brought to you by {STR_VAR_1}!$"

MatchCall_PersonalizedText64::
	.string "It's {STR_VAR_1}!\p"
	.string "I'm kind of busy, but I figured\n"
	.string "I should let you know that I've\l"
	.string "beaten five TRAINERS again today.\p"
	.string "If I keep this pace up, I can\n"
	.string "probably beat you next time.\p"
	.string "I think we'll be good rivals,\n"
	.string "you and I. Good-bye for now!$"

MatchCall_BattleFrontierStreakText1::
	.string "Hi! This is {STR_VAR_1}.\n"
	.string "I heard the news!\p"
	.string "They say you did excellent at\n"
	.string "the {STR_VAR_2}.\p"
	.string "It's awesome, {STR_VAR_3} straight wins?\n"
	.string "See you!$"

MatchCall_BattleFrontierStreakText2::
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "That's special! I should try\n"
	.string "harder, too! See you!$"

MatchCall_BattleFrontierStreakText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I heard you went on a tear at\n"
	.string "the {STR_VAR_2}!\p"
	.string "A big {STR_VAR_3}-win streak…\n"
	.string "That is a big record, isn't it?\p"
	.string "I'd better get it together, too!\n"
	.string "Catch you soon!$"

MatchCall_BattleFrontierStreakText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. What's up?\p"
	.string "There's a rumor going around that\n"
	.string "you strung together {STR_VAR_3} straight\l"
	.string "wins at the {STR_VAR_2}.\p"
	.string "I'd better step it up, too.\n"
	.string "See you!$"

MatchCall_BattleFrontierStreakText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won {STR_VAR_3} battles in a row?\l"
	.string "Isn't that something!\p"
	.string "I'd better work on my {POKEMON} more.\n"
	.string "See you soon!$"

MatchCall_BattleFrontierStreakText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you pulled off\n"
	.string "the feat of {STR_VAR_3} straight wins at\l"
	.string "the {STR_VAR_2}.\p"
	.string "That inspires me to focus on\n"
	.string "raising my team.$"

MatchCall_BattleFrontierStreakText7::
	.string "…Er, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here…\p"
	.string "Oh, yeah, you were over at\n"
	.string "the {STR_VAR_2}, right?\p"
	.string "And you won {STR_VAR_3} battles in a row.\p"
	.string "Oh, there goes a rare {POKEMON}!\n"
	.string "I have to go!$"

MatchCall_BattleFrontierStreakText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\p"
	.string "Oh, but, you are. I've heard that\n"
	.string "you won {STR_VAR_3} matches in a row at\l"
	.string "the {STR_VAR_2}.\p"
	.string "That's very impressive!\n"
	.string "I hope you stay successful.$"

MatchCall_BattleFrontierStreakText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! Your {STR_VAR_3}-win streak at\n"
	.string "the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattleFrontierStreakText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won {STR_VAR_3} straight battles at\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattleFrontierStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You won, what, {STR_VAR_3} matches in\n"
	.string "a row?\p"
	.string "You're good, you.\n"
	.string "I wonder how many I can win?$"

MatchCall_BattleFrontierStreakText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "Someone passed on word about you.\n"
	.string "How you won {STR_VAR_3} straight battles\l"
	.string "at a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattleFrontierStreakText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattleFrontierStreakText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I heard about you!\n"
	.string "Didn't you just win {STR_VAR_3} battles in\l"
	.string "a row at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "Bye-bye!$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "Hi! This is {STR_VAR_1}.\n"
	.string "I heard the news!\p"
	.string "They say you did excellent at\n"
	.string "the {STR_VAR_2}.\p"
	.string "It's awesome--{STR_VAR_3} straight wins?\n"
	.string "See you!$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "That's special! I should try\n"
	.string "harder, too! See you!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I heard you went on a tear at\n"
	.string "the {STR_VAR_2}!\p"
	.string "A big {STR_VAR_3}-win streak…\n"
	.string "That is a big record, isn't it?\p"
	.string "I'd better get it together, too!\n"
	.string "Catch you soon!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. What's up?\p"
	.string "There's a rumor going around that\n"
	.string "you strung together {STR_VAR_3} straight\l"
	.string "wins at the {STR_VAR_2}.\p"
	.string "I'd better step it up, too.\n"
	.string "See you!$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won {STR_VAR_3} battles in a row?\l"
	.string "Isn't that something!\p"
	.string "Me? I'd say I'm coming along.\n"
	.string "See you soon!$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you pulled off\n"
	.string "the feat of {STR_VAR_3} straight wins at\l"
	.string "the {STR_VAR_2}.\p"
	.string "I'd better try harder myself!\n"
	.string "See you soon!$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "…Er, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here…\p"
	.string "Oh, yeah, you were over at\n"
	.string "the {STR_VAR_2}, right?\p"
	.string "And you won {STR_VAR_3} battles in a row.\p"
	.string "Oh, there goes a rare {POKEMON}!\n"
	.string "I have to go!$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\p"
	.string "Oh, but, you are. I've heard that\n"
	.string "you won {STR_VAR_3} matches in a row at\l"
	.string "the {STR_VAR_2}.\p"
	.string "That's very impressive!\n"
	.string "I'd better work on my {POKEMON}, too!$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! Your {STR_VAR_3}-win streak at\n"
	.string "the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won {STR_VAR_3} straight battles at\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You won, what, {STR_VAR_3} matches in\n"
	.string "a row?\p"
	.string "You're good, you.\n"
	.string "I wonder how many I can win?$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "Someone passed on word about you.\n"
	.string "How you won {STR_VAR_3} straight battles\l"
	.string "at a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you just win {STR_VAR_3} battles in\n"
	.string "a row at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "Bye-bye!$"

MatchCall_BattleDomeText1::
	.string "Hi! {PLAYER}?\n"
	.string "Hello, this is {STR_VAR_1}!\l"
	.string "I heard the news!\p"
	.string "You became the champion at\n"
	.string "the {STR_VAR_2} {STR_VAR_3} times?\p"
	.string "It's awesome! I have to do better!\n"
	.string "See you!$"

MatchCall_BattleDomeText2::
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won {STR_VAR_3} titles\n"
	.string "at the {STR_VAR_2}.\p"
	.string "That's super! I wonder if I can\n"
	.string "become a champion?$"

MatchCall_BattleDomeText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "How's it going?\p"
	.string "I heard you won events {STR_VAR_3} times\n"
	.string "at the {STR_VAR_2}!\p"
	.string "Make it one more next time!\n"
	.string "Catch you soon!$"

MatchCall_BattleDomeText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I heard you became the champion\n"
	.string "at the {STR_VAR_2} {STR_VAR_3} times.\p"
	.string "Sounds like you're working hard.\n"
	.string "I'll try to keep up!$"

MatchCall_BattleDomeText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I heard you won {STR_VAR_3} times\n"
	.string "outright at the {STR_VAR_2}.\p"
	.string "I'd better get with it, too!\n"
	.string "See you soon!$"

MatchCall_BattleDomeText6::
	.string "Hey, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you became\n"
	.string "the champion {STR_VAR_3} times at\l"
	.string "the {STR_VAR_2}.\p"
	.string "I'd better raise my {POKEMON} before\n"
	.string "you pull farther ahead.$"

MatchCall_BattleDomeText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and became the champ {STR_VAR_3} times?\p"
	.string "That's neat. By the way, have you\n"
	.string "caught any rare {POKEMON} lately?\p"
	.string "Oh, is that right.\n"
	.string "Okay, bye.$"

MatchCall_BattleDomeText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\l"
	.string "Oh, but, you are.\p"
	.string "I've heard that you won {STR_VAR_3} titles\n"
	.string "at the {STR_VAR_2}.\p"
	.string "I must raise my {POKEMON} like you.\n"
	.string "See you again.$"

MatchCall_BattleDomeText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! You took the title\n"
	.string "{STR_VAR_3} times at the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattleDomeText10::
	.string "Oh, {PLAYER}{KUN}, hello.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won {STR_VAR_3} straight times at\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattleDomeText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You won, what, {STR_VAR_3} straight times\n"
	.string "now?\p"
	.string "I wonder if I can ever become\n"
	.string "a champion?\p"
	.string "…Pretty well impossible?\n"
	.string "Well, see you!$"

MatchCall_BattleDomeText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "You've won {STR_VAR_3} events at a place\n"
	.string "named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattleDomeText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won {STR_VAR_3} events\n"
	.string "at the {STR_VAR_2}?\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattleDomeText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you win {STR_VAR_3} titles\n"
	.string "at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "See you again!$"

MatchCall_BattlePikeText1::
	.string "Hi! {PLAYER}?\n"
	.string "Hello, this is {STR_VAR_1}!\l"
	.string "I heard the news!\p"
	.string "You got through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}!\p"
	.string "That's awesome!\n"
	.string "See you!$"

MatchCall_BattlePikeText2::
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won your way through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}.\p"
	.string "I have to try much harder!\n"
	.string "Bye!$"

MatchCall_BattlePikeText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "How's it going?\p"
	.string "I heard you won through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}!\p"
	.string "Try to do even better next time!\n"
	.string "Catch you soon!$"

MatchCall_BattlePikeText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I heard you blew through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}.\p"
	.string "I'd better train my {POKEMON} and\n"
	.string "try to keep up!$"

MatchCall_BattlePikeText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I heard you got past {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}.\p"
	.string "I'd better get with it, too!\n"
	.string "See you soon!$"

MatchCall_BattlePikeText6::
	.string "Hey, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you got through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}.\p"
	.string "I'd better raise my {POKEMON} before\n"
	.string "you pull further ahead.$"

MatchCall_BattlePikeText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won your way past {STR_VAR_3} rooms?\p"
	.string "That's wicked.\p"
	.string "Oh, there goes a rare {POKEMON}!\n"
	.string "Okay, bye.$"

MatchCall_BattlePikeText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\l"
	.string "Oh, but, you are.\p"
	.string "I've heard that you got through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}.\p"
	.string "That's quite impressive!\n"
	.string "I must raise my {POKEMON} like you.\l"
	.string "See you again.$"

MatchCall_BattlePikeText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! You won your way through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattlePikeText10::
	.string "Oh, {PLAYER}{KUN}, hello.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won your way past {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattlePikeText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You got through, what, {STR_VAR_3} rooms?\n"
	.string "That's gotta count for something.\p"
	.string "I wonder if I can ever become\n"
	.string "a champion?\p"
	.string "…Pretty well impossible?\n"
	.string "Well, see you!$"

MatchCall_BattlePikeText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "You've won through {STR_VAR_3} rooms at\n"
	.string "a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattlePikeText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won in {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}?\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattlePikeText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you get through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "See you again!$"

MatchCall_BattlePyramidText1::
	.string "Hi! {PLAYER}?\n"
	.string "Hello, this is {STR_VAR_1}!\l"
	.string "I heard the news!\p"
	.string "You climbed {STR_VAR_3} floors inside\n"
	.string "the {STR_VAR_2}, right?\p"
	.string "That's awesome!\n"
	.string "I should try that challenge.$"

MatchCall_BattlePyramidText2::
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won your way through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}.\p"
	.string "Wow, that's fantastic!\n"
	.string "I'd better raise my {POKEMON}, too!$"

MatchCall_BattlePyramidText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "How's it going?\p"
	.string "I heard you climbed {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}!\p"
	.string "Try to do even better next time!\n"
	.string "Catch you soon!$"

MatchCall_BattlePyramidText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I heard you scaled {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}.\p"
	.string "I'd better work hard and try\n"
	.string "to keep up!$"

MatchCall_BattlePyramidText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I heard you climbed {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}.\p"
	.string "I'd better get with it, too!\n"
	.string "See you soon!$"

MatchCall_BattlePyramidText6::
	.string "Hey, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you got through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}.\p"
	.string "I'd better raise my {POKEMON} before\n"
	.string "you pull further ahead.$"

MatchCall_BattlePyramidText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won your way up {STR_VAR_3} floors?\p"
	.string "Neat. Were there any rare {POKEMON}\n"
	.string "there?\p"
	.string "No, huh?\n"
	.string "Okay, bye.$"

MatchCall_BattlePyramidText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\l"
	.string "Oh, but, you are.\p"
	.string "I've heard that you got through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}.\p"
	.string "That's quite impressive!\n"
	.string "I must raise my {POKEMON} like you.\l"
	.string "See you again.$"

MatchCall_BattlePyramidText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! You won your way through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattlePyramidText10::
	.string "Oh, {PLAYER}{KUN}, hello.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You climbed {STR_VAR_3} floors inside\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattlePyramidText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You rose through, what, {STR_VAR_3} floors?\n"
	.string "That's gotta count for something.\p"
	.string "I wonder if I can ever become\n"
	.string "a champion?\p"
	.string "…Pretty well impossible?\n"
	.string "Well, see you!$"

MatchCall_BattlePyramidText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "You've won through {STR_VAR_3} floors in\n"
	.string "a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattlePyramidText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you climbed {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}?\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattlePyramidText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you get through {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "See you again!$"

MatchCall_Text_Mom1::
	.string "MOM: Your father and you…\n"
	.string "Everyone is captivated by {POKEMON}.\p"
	.string "What is the charm of {POKEMON}?\p"
	.string "Me?\n"
	.string "I adore {POKEMON} that help me with\l"
	.string "my everyday chores.$"

MatchCall_Text_Mom2::
	.string "MOM: Hi, {PLAYER}!\n"
	.string "Your father keeps himself locked\l"
	.string "away in the PETALBURG GYM.\p"
	.string "He comes home every so often.\n"
	.string "But he goes back to the GYM when\l"
	.string "he's eaten everything he can.\p"
	.string "I'm guessing that losing to you\n"
	.string "was a big blow to his pride!$"

MatchCall_Text_Mom3::
	.string "MOM: {PLAYER}…\n"
	.string "Don't worry about me or the house.\p"
	.string "Wear those RUNNING SHOES until\n"
	.string "they fall apart, honey!$"

MatchCall_Text_Roxanne1::
	.string "ROXANNE: Oh, hello, {PLAYER}!\p"
	.string "I've been hard at work retraining\n"
	.string "since we met.\p"
	.string "I will still need some more time\n"
	.string "before I can reopen the GYM.\p"
	.string "But when I do, please visit my GYM\n"
	.string "for a rematch!$"

MatchCall_Text_Roxanne2::
	.string "ROXANNE: Is this {PLAYER}?\n"
	.string "Congratulations!\l"
	.string "I've been hearing about you!\p"
	.string "As for me, I need some more time\n"
	.string "before I can reopen the GYM.\p"
	.string "But when I do, please visit my GYM\n"
	.string "for a rematch!$"

MatchCall_Text_Roxanne3::
	.string "ROXANNE: {PLAYER}!\n"
	.string "My GYM is ready!\p"
	.string "Please visit RUSTBORO whenever\n"
	.string "you can!$"

MatchCall_Text_Roxanne4::
	.string "ROXANNE: At the RUSTBORO GYM,\n"
	.string "the fact that we battled, {PLAYER},\l"
	.string "is a matter of pride.$"

MatchCall_Text_Brawly1::
	.string "BRAWLY: Hey, there, {PLAYER}{KUN}!\p"
	.string "I learned a lot from the battle we\n"
	.string "had together.\p"
	.string "I intend to do my training over,\n"
	.string "then reopen the GYM.\p"
	.string "It's going to take some time before\n"
	.string "I'm ready to run the GYM again.\p"
	.string "But if I can reopen the GYM,\n"
	.string "I want you to challenge us again.$"

MatchCall_Text_Brawly2::
	.string "BRAWLY: Hey, {PLAYER}{KUN}!\n"
	.string "Congratulations!\p"
	.string "Word about your exploits arrived\n"
	.string "on tidal winds!\p"
	.string "It appears as if I need to work on\n"
	.string "my training some more.\p"
	.string "It's going to take some time before\n"
	.string "I'm ready to run the GYM again.\p"
	.string "But if I can reopen the GYM,\n"
	.string "I want you to challenge us again.$"

MatchCall_Text_Brawly3::
	.string "BRAWLY: Hey, {PLAYER}{KUN}!\n"
	.string "My GYM's ready for action!\p"
	.string "Come back to DEWFORD anytime\n"
	.string "for another challenge!$"

MatchCall_Text_Brawly4::
	.string "BRAWLY: {PLAYER}{KUN}, I don't think\n"
	.string "I'll ever get bored of battling you!$"

MatchCall_Text_Wattson1::
	.string "WATTSON: Oh, it's you!\p"
	.string "After you left, I've been redoing\n"
	.string "my training from scratch.\p"
	.string "I'd say I could use a wee bit more\n"
	.string "time to reopen my GYM.\p"
	.string "You'll have to wait till then!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson2::
	.string "WATTSON: Wahahahaha!\p"
	.string "You've really done it, haven't you?\n"
	.string "I've been getting word about you!\p"
	.string "It seems I need to retrain some\n"
	.string "more still.\p"
	.string "I'd say I could use a wee bit more\n"
	.string "time to reopen my GYM.\p"
	.string "You'll have to wait till then!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson3::
	.string "WATTSON: Oh, it's you!\n"
	.string "My GYM's ready!\p"
	.string "Visit MAUVILLE anytime!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson4::
	.string "WATTSON: Wahahaha!\p"
	.string "A battle with you is always charged\n"
	.string "with shocking power!$"

MatchCall_Text_Flannery1::
	.string "FLANNERY: {PLAYER}…\p"
	.string "When we battled, I learned exactly\n"
	.string "how immature I was.\p"
	.string "But I'm not done yet!\p"
	.string "I'm going to redo my training and\n"
	.string "reopen the GYM.\p"
	.string "When the time comes, {PLAYER},\n"
	.string "please challenge us again.$"

MatchCall_Text_Flannery2::
	.string "FLANNERY: Hello, {PLAYER}?\n"
	.string "Congratulations!\p"
	.string "Word of your success has reached\n"
	.string "us like the heat of a volcano!\p"
	.string "Our training is coming along very\n"
	.string "well here.\p"
	.string "When the GYM's ready, a mark will\n"
	.string "appear beside my name in the\l"
	.string "MATCH CALL list.$"

MatchCall_Text_Flannery3::
	.string "FLANNERY: Oh, {PLAYER}?\n"
	.string "Our GYM's ready!\p"
	.string "Come to LAVARIDGE for a soak\n"
	.string "in the hot spring and a challenge!$"

MatchCall_Text_Flannery4::
	.string "FLANNERY: {PLAYER}…\n"
	.string "I'm positive that you keep getting\l"
	.string "better at training every time.$"

MatchCall_Text_Winona1::
	.string "WINONA: Hello, {PLAYER}!\p"
	.string "Thanks to our battle, I've come\n"
	.string "to understand my weak points!\p"
	.string "When I reopen the GYM, I won't go\n"
	.string "down in defeat again!$"

MatchCall_Text_Winona2::
	.string "WINONA: You've done it, {PLAYER}!\p"
	.string "News about the new CHAMPION\n"
	.string "has reached us in FORTREE!\p"
	.string "But… The next time we battle,\n"
	.string "it's not going to end the same way.$"

MatchCall_Text_Winona3::
	.string "WINONA: Is this {PLAYER}?\n"
	.string "Our GYM is back in operation!\p"
	.string "We're waiting for you in FORTREE!$"

MatchCall_Text_Winona4::
	.string "WINONA: {PLAYER}…\n"
	.string "Though I have lost, my wings will\l"
	.string "never break.\p"
	.string "Yes, in exactly the same way that\n"
	.string "you never lost sight of your dream.$"

MatchCall_Text_TateLiza1::
	.string "TATE: Oh! You're…\n"
	.string "LIZA: {PLAYER}!\p"
	.string "TATE: We're in training again…\n"
	.string "LIZA: So we can reopen our GYM!\p"
	.string "TATE: When our GYM is ready…\n"
	.string "LIZA: When our GYM is ready…\p"
	.string "TATE: A mark'll appear by our name…\n"
	.string "LIZA: On the MATCH CALL list.$"

MatchCall_Text_TateLiza2::
	.string "TATE: {PLAYER}, congratulations!\n"
	.string "LIZA: {PLAYER}, congratulations!\p"
	.string "TATE: The two of us are…\n"
	.string "LIZA: Still in training!\p"
	.string "TATE: We need some more time, but…\n"
	.string "LIZA: When our GYM is ready…\p"
	.string "TATE: A mark'll appear by our name…\n"
	.string "LIZA: On the MATCH CALL list.$"

MatchCall_Text_TateLiza3::
	.string "TATE: {PLAYER}!\n"
	.string "LIZA: {PLAYER}!\p"
	.string "TATE: Our GYM is ready!\n"
	.string "LIZA: Our GYM is ready!\p"
	.string "TATE: Please come visit…\n"
	.string "LIZA: MOSSDEEP anytime!$"

MatchCall_Text_TateLiza4::
	.string "TATE: {PLAYER}, the battle we had…\n"
	.string "LIZA: Is an invaluable experience.\p"
	.string "TATE: It would be nice if…\n"
	.string "LIZA: We could all battle again!$"

MatchCall_Text_Juan1::
	.string "JUAN: Hmm…\n"
	.string "{PLAYER}{KUN}… Was it?\p"
	.string "Our battle together--it brought\n"
	.string "to me memories of when I first\l"
	.string "encountered WALLACE.\p"
	.string "Perhaps you are a genius who may\n"
	.string "yet surpass WALLACE!$"

MatchCall_Text_Juan2::
	.string "JUAN: Fufu… {PLAYER}{KUN}…\n"
	.string "You've finally achieved your goal.\p"
	.string "My eye for appraising talent wasn't\n"
	.string "mistaken…\p"
	.string "I wish for another chance to meet\n"
	.string "you, for you have scaled the peak\l"
	.string "of power and prestige.$"

MatchCall_Text_Juan3::
	.string "JUAN: Hoho… {PLAYER}{KUN}…\p"
	.string "Our SOOTOPOLIS GYM has finally\n"
	.string "reopened.\p"
	.string "If you wish to see me, you are\n"
	.string "welcome to visit anytime.$"

MatchCall_Text_Juan4::
	.string "JUAN: {PLAYER}{KUN}…\p"
	.string "Like the finest music, the battles\n"
	.string "we wage together strike chords\l"
	.string "of inspiration in my heart…\p"
	.string "When I close my eyes, I see visions\n"
	.string "of you soaring with the melody…$"

MatchCall_Text_Sidney::
	.string "SIDNEY: Yo, {PLAYER}!\p"
	.string "If you want to battle with me\n"
	.string "again, you come on back whenever\l"
	.string "you like to the {POKEMON} LEAGUE.\p"
	.string "I'll always be here!\n"
	.string "I'll be waiting!$"

MatchCall_Text_Phoebe::
	.string "PHOEBE: Hi, {PLAYER}!\p"
	.string "How about coming back here again\n"
	.string "sometime?\p"
	.string "I'd like to see how much tighter\n"
	.string "your bond has grown with your\l"
	.string "{POKEMON}.$"

MatchCall_Text_Glacia::
	.string "GLACIA: Hello, {PLAYER}.\p"
	.string "I trust you haven't become\n"
	.string "complacent with your power?\p"
	.string "If you feel the need to cool your\n"
	.string "hot emotions just a little, do come\l"
	.string "to the {POKEMON} LEAGUE…$"

MatchCall_Text_Drake::
	.string "DRAKE: That voice… {PLAYER}, is it?\n"
	.string "You sound well…\p"
	.string "I understand that there is now\n"
	.string "a facility called the BATTLE\l"
	.string "FRONTIER that tests the skills of\l"
	.string "TRAINERS.\p"
	.string "However, if you wish to have real\n"
	.string "battles, there is no substitute for\l"
	.string "the {POKEMON} LEAGUE!\p"
	.string "Don't you agree, {PLAYER}?$"

MatchCall_Text_Wallace::
	.string "WALLACE: Hello, {PLAYER}{KUN}.\n"
	.string "Have you met STEVEN?\p"
	.string "He is…\n"
	.string "Actually incredibly skilled.\p"
	.string "However, he's an odd soul who\n"
	.string "rarely battles.\p"
	.string "Instead, he would rather look for\n"
	.string "rare stones.\p"
	.string "I'm sure he's digging in a cave or\n"
	.string "a craggy mountain somewhere.\p"
	.string "But what is a rare stone exactly?\n"
	.string "All I can think of is a METEORITE…$"

MatchCall_Text_MayRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Beep!\p"
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "I was just in PACIFIDLOG a little\n"
	.string "while ago.\p"
	.string "I saw a giant green {POKEMON}\n"
	.string "flying high in the sky.\p"
	.string "I…\n"
	.string "I've never seen anything like it.\p"
	.string "I wonder what it was.\n"
	.string "Is this maybe a major discovery?\p"
	.string "… … … … … …\n"
	.string "… … … … … Click!$"

MatchCall_Text_BrendanRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Beep!\p"
	.string "BRENDAN: Hey, {PLAYER}!\n"
	.string "I was in PACIFIDLOG just now.\p"
	.string "I saw this huge green {POKEMON}\n"
	.string "flying across the sky.\p"
	.string "I've never seen anything that\n"
	.string "amazing before.\p"
	.string "I wish you could've seen it,\n"
	.string "{PLAYER}.\p"
	.string "… … … … … …\n"
	.string "… … … … … Click!$"

MatchCall_Text_May1::
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "MR. BRINEY retired as a SAILOR,\n"
	.string "but I still see him out on the sea\l"
	.string "with his pet PEEKO sometimes.\p"
	.string "He must love the sea still.$"

MatchCall_Text_May2::
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "You know how little towns like\n"
	.string "PETALBURG and DEWFORD have GYMS?\p"
	.string "For some reason, the big port of\n"
	.string "SLATEPORT doesn't have a GYM.\p"
	.string "When they finally build a GYM there,\n"
	.string "I should apply to be the LEADER.$"

MatchCall_Text_May3::
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "Do you remember a man named\n"
	.string "the CUTTER in RUSTBORO?\l"
	.string "He had a house there, remember?\p"
	.string "Well, I found out his younger\n"
	.string "brother lives in MAUVILLE.\p"
	.string "Can you guess his name?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "The ROCK SMASH GUY!$"

MatchCall_Text_May4::
	.string "MAY: {PLAYER}{KUN}?\p"
	.string "RUSTURF TUNNEL…\n"
	.string "They named it that because it\l"
	.string "joins RUSTBORO and VERDANTURF.$"

MatchCall_Text_May5::
	.string "MAY: {PLAYER}{KUN}, how are you?\p"
	.string "I'm out on ROUTE 111 now.\p"
	.string "I'm going to get a rest at an old\n"
	.string "lady's house.\p"
	.string "She lives just north of\n"
	.string "the desert.$"

MatchCall_Text_May6::
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "Did you know about the MIRAGE\n"
	.string "TOWER in the desert?\p"
	.string "They say, like a mirage, it seems\n"
	.string "to mysteriously come and go.\p"
	.string "I wish I could see it.$"

MatchCall_Text_May7::
	.string "MAY: {PLAYER}{KUN}, yahoo!\n"
	.string "I'm on ROUTE 119 now.\p"
	.string "There's a big river here, and\n"
	.string "it often rains.\p"
	.string "I got soaked!$"

MatchCall_Text_May8::
	.string "MAY: {PLAYER}{KUN}, hi.\p"
	.string "MT. PYRE is a memorial to {POKEMON}\n"
	.string "whose lives have ended.\p"
	.string "Maybe as a result, it's infested\n"
	.string "with many GHOST-type {POKEMON}!$"

MatchCall_Text_May9::
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "I was thinking of going to the hot\n"
	.string "spring in LAVARIDGE.\p"
	.string "But on the way, around JAGGED\n"
	.string "PASS, I ran into some bad-looking\l"
	.string "characters. The mood was ugly!$"

MatchCall_Text_May10::
	.string "MAY: Hi, {PLAYER}{KUN}!\n"
	.string "Did you see the news?\p"
	.string "They say CAPT. STERN discovered\n"
	.string "the SEAFLOOR CAVERN while on his\l"
	.string "submarine expedition.$"

MatchCall_Text_May11::
	.string "MAY: Hi, {PLAYER}{KUN}!\n"
	.string "Don't you think it's neat?\p"
	.string "Even if you don't have a boat,\n"
	.string "you can cross the sea using\l"
	.string "a {POKEMON}'s move.\p"
	.string "Did you know there's more?\p"
	.string "There's a {POKEMON} move that lets\n"
	.string "you go to the bottom of the sea.$"

MatchCall_Text_May12::
	.string "MAY: Hi, {PLAYER}{KUN}!\n"
	.string "Hope things are okay!\p"
	.string "Have you been on the sea and\n"
	.string "found your way to the other side\l"
	.string "blocked?\p"
	.string "Try diving deep underwater and\n"
	.string "following trenches.\p"
	.string "When you get to the other side,\n"
	.string "come up to the surface. Easy!$"

MatchCall_Text_May13::
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "How's it going?\n"
	.string "Are you filling your {POKEDEX}?\p"
	.string "I heard a rumor that there are\n"
	.string "super-ancient {POKEMON} out there.\l"
	.string "And there are three of them!\p"
	.string "I would love to see even one…$"

MatchCall_Text_May14::
	.string "MAY: {PLAYER}{KUN}!\n"
	.string "I heard the rumors!\p"
	.string "You beat the SOOTOPOLIS GYM\n"
	.string "LEADER?\p"
	.string "That means you don't have far\n"
	.string "to go, do you?$"

MatchCall_Text_May15::
	.string "MAY: There isn't a single TRAINER\n"
	.string "left in HOENN who doesn't know who\l"
	.string "you are, {PLAYER}{KUN}!\p"
	.string "When I tell people that I'm friends\n"
	.string "with you, {PLAYER}{KUN}, they're all\l"
	.string "surprised!$"

MatchCall_Text_Brendan1::
	.string "BRENDAN: Hey, {PLAYER}!\p"
	.string "MR. BRINEY retired as a SAILOR,\n"
	.string "but I still see him out on the sea\l"
	.string "with his pet PEEKO sometimes.\p"
	.string "I guess he must love\n"
	.string "the sea still.$"

MatchCall_Text_Brendan2::
	.string "BRENDAN: Hey, {PLAYER}!\p"
	.string "I don't get how little towns like\n"
	.string "PETALBURG and DEWFORD have GYMS.\p"
	.string "I mean, not when the big port of\n"
	.string "SLATEPORT doesn't have a GYM.\p"
	.string "When they finally build a GYM there,\n"
	.string "I should apply to be the LEADER.$"

MatchCall_Text_Brendan3::
	.string "BRENDAN: Yo, {PLAYER}!\p"
	.string "Do you remember a guy named\n"
	.string "the CUTTER in RUSTBORO?\l"
	.string "He had a house there, right?\p"
	.string "Well, it turns out his little\n"
	.string "brother lives in MAUVILLE.\p"
	.string "Can you guess his name?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "The ROCK SMASH GUY!$"

MatchCall_Text_Brendan4::
	.string "BRENDAN: This voice… {PLAYER}?\p"
	.string "They gave RUSTURF TUNNEL its name\n"
	.string "because it joins RUSTBORO and\l"
	.string "VERDANTURF.\p"
	.string "Did you know that?$"

MatchCall_Text_Brendan5::
	.string "BRENDAN: {PLAYER}, what's up?\p"
	.string "Hey, I'm out on ROUTE 111 now.\p"
	.string "I'm going to rest up at an old\n"
	.string "lady's house north of the desert.\p"
	.string "If you're in the area, you should\n"
	.string "visit her, too.$"

MatchCall_Text_Brendan6::
	.string "BRENDAN: Hey, {PLAYER}!\p"
	.string "Did you know about the MIRAGE\n"
	.string "TOWER in the desert?\p"
	.string "They say, like a mirage, it can be\n"
	.string "seen only sometimes.\p"
	.string "I'd like to see that!$"

MatchCall_Text_Brendan7::
	.string "BRENDAN: Who's this? Oh, {PLAYER}?\n"
	.string "Guess what? I'm on ROUTE 119 now.\p"
	.string "There's a big river here, and\n"
	.string "it rains all the time.\p"
	.string "I got soaked to the bone!$"

MatchCall_Text_Brendan8::
	.string "BRENDAN: {PLAYER}!\p"
	.string "MT. PYRE is a memorial to {POKEMON}\n"
	.string "whose lives have ended.\p"
	.string "That's probably why it's infested\n"
	.string "with many GHOST-type {POKEMON}!$"

MatchCall_Text_Brendan9::
	.string "BRENDAN: Hey there, {PLAYER}.\p"
	.string "I was on my way back to the hot\n"
	.string "spring in LAVARIDGE.\p"
	.string "But around JAGGED PASS, I ran into\n"
	.string "some nasty-looking characters.\p"
	.string "Those creeps…\n"
	.string "I think they were TEAM MAGMA.$"

MatchCall_Text_Brendan10::
	.string "BRENDAN: Hi, {PLAYER}!\n"
	.string "Did you catch the news?\p"
	.string "They say CAPT. STERN discovered\n"
	.string "the SEAFLOOR CAVERN while on his\l"
	.string "submarine expedition.$"

MatchCall_Text_Brendan11::
	.string "BRENDAN: Hey there, {PLAYER}!\n"
	.string "Don't you think it's awesome?\p"
	.string "Even if you don't have a boat,\n"
	.string "you can cross the sea using\l"
	.string "a {POKEMON}'s move.\p"
	.string "And, there's a move that lets you\n"
	.string "travel to the bottom of the sea.\p"
	.string "Man, {POKEMON} can do anything!$"

MatchCall_Text_Brendan12::
	.string "BRENDAN: Howdy, {PLAYER}!\n"
	.string "How are you holding up?\p"
	.string "Ever found your way to the other\n"
	.string "side blocked while on the sea?\p"
	.string "Try diving deep underwater and\n"
	.string "following trenches at the bottom.\p"
	.string "When you get to the other side,\n"
	.string "come up to the surface. Simple!$"

MatchCall_Text_Brendan13::
	.string "BRENDAN: Hey there, {PLAYER}!\p"
	.string "How's it going? Filling up your\n"
	.string "{POKEDEX} successfully?\p"
	.string "I heard a rumor that there are\n"
	.string "super-ancient {POKEMON} out there.\l"
	.string "And not just one--three!\p"
	.string "I'd love to catch even one…$"

MatchCall_Text_Brendan14::
	.string "BRENDAN: {PLAYER}!\n"
	.string "I heard the rumors!\p"
	.string "You beat the SOOTOPOLIS GYM\n"
	.string "LEADER? Awesome!\p"
	.string "You're getting awful close now!$"

MatchCall_Text_Brendan15::
	.string "BRENDAN: There isn't a TRAINER in\n"
	.string "all of HOENN who doesn't know who\l"
	.string "you are, {PLAYER}!\p"
	.string "When I tell people that I'm friends\n"
	.string "with you, {PLAYER}, they get pretty\l"
	.string "envious!$"

MatchCall_Text_Wally1::
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "I've been getting healthier and\n"
	.string "more physically fit.\p"
	.string "I hope I can become a TRAINER like\n"
	.string "you soon, {PLAYER}!$"

MatchCall_Text_Wally2::
	.string "WALLY: {PLAYER}, hello!\p"
	.string "After RUSTURF TUNNEL went\n"
	.string "through, WANDA's been very happy!$"

MatchCall_Text_Wally3::
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "I… I left my uncle's place in\n"
	.string "VERDANTURF without telling anyone.\p"
	.string "I wonder if he's furious with me…\p"
	.string "{PLAYER}, you understand how\n"
	.string "I feel, don't you?$"

MatchCall_Text_Wally4::
	.string "WALLY: {PLAYER}?\n"
	.string "It's me, WALLY!\p"
	.string "The world of TRAINERS is amazing!\p"
	.string "When I have my {POKEMON} with me,\n"
	.string "all sorts of people say hi!\p"
	.string "It's as if everyone's getting\n"
	.string "connected through {POKEMON}!$"

MatchCall_Text_Wally5::
	.string "WALLY: {PLAYER}? It's awesome!\n"
	.string "That RALTS we caught together?\l"
	.string "It evolved, {PLAYER}!\p"
	.string "Maybe I'm talented…\p"
	.string "Oh, but I shouldn't get a big head\n"
	.string "like that!\p"
	.string "After all, it's the {POKEMON} that\n"
	.string "should be praised!$"

MatchCall_Text_Wally6::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "WALLY appears to be out of\n"
	.string "the {POKE}NAV's service area…$"

MatchCall_Text_Wally7::
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "Before I met you, I hardly ever\n"
	.string "left my house…\p"
	.string "But now, I'm on an adventure with\n"
	.string "my very own {POKEMON}…\p"
	.string "{PLAYER}…\n"
	.string "Thank you…$"

MatchCall_Text_Scott1::
	.string "SCOTT: Howdy, {PLAYER}{KUN}!\p"
	.string "You know how {POKEMON} can be found\n"
	.string "everywhere?\p"
	.string "Like in the mountains, in the sea,\n"
	.string "in tall grass anywhere?\p"
	.string "Just like {POKEMON}, you can find\n"
	.string "TRAINERS everywhere, too.\p"
	.string "As a result, I have to hurry\n"
	.string "everywhere, too. Busy, busy!$"

MatchCall_Text_Scott2::
	.string "SCOTT: I'm on ROUTE 119 right now.\n"
	.string "It's teeming with TRAINERS!\p"
	.string "It's also overgrown with tall grass\n"
	.string "everywhere, it seems.\p"
	.string "Walking around in shorts here\n"
	.string "makes me all ticklish!$"

MatchCall_Text_Scott3::
	.string "SCOTT: Hi, hi, {PLAYER}{KUN}!\p"
	.string "Have you had the chance to climb\n"
	.string "MT. PYRE?\p"
	.string "The place is a memorial to {POKEMON}\n"
	.string "that have passed away.\p"
	.string "It's somewhere every TRAINER\n"
	.string "should climb to the top of once.$"

MatchCall_Text_Scott4::
	.string "SCOTT: Hi, {PLAYER}{KUN}!\p"
	.string "I've been hearing about these odd\n"
	.string "gangs being a nuisance.\p"
	.string "TEAM MAGMA and TEAM AQUA,\n"
	.string "I think they were.\p"
	.string "I would think there'd be some\n"
	.string "skilled TRAINERS among them.\p"
	.string "…But if they're thugs…$"

MatchCall_Text_Scott5::
	.string "SCOTT: Oh, hi, {PLAYER}{KUN}.\p"
	.string "Might there be tough TRAINERS\n"
	.string "at the bottom of the sea?\p"
	.string "I can't go check for myself.\n"
	.string "I can't swim, for one.\l"
	.string "And I don't raise {POKEMON}…$"

MatchCall_Text_Scott6::
	.string "SCOTT: Hi, hi, {PLAYER}{KUN}!\p"
	.string "You know that you can challenge\n"
	.string "the {POKEMON} LEAGUE when you've\l"
	.string "collected all the GYM BADGES?\p"
	.string "With your talent, becoming the\n"
	.string "CHAMPION isn't a pipe dream.\p"
	.string "But did you know?\n"
	.string "There's somewhere even better.\p"
	.string "But, that's all I'm willing to say\n"
	.string "for the time being.\p"
	.string "It's something you can look\n"
	.string "forward to.\p"
	.string "When you've won your way through\n"
	.string "the {POKEMON} LEAGUE into the HALL\l"
	.string "OF FAME!$"

MatchCall_Text_Scott7::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "SCOTT appears to be out of\n"
	.string "the {POKE}NAV's service area…$"

MatchCall_Text_Norman1::
	.string "DAD: In RUSTBORO, there's a man\n"
	.string "that goes by the odd name of\l"
	.string "the CUTTER.\p"
	.string "If you're in the area, you should\n"
	.string "pay him a visit.$"

MatchCall_Text_Norman2::
	.string "DAD: Hm… Little by little, but also\n"
	.string "very surely, you're getting\l"
	.string "tougher, {PLAYER}.\p"
	.string "The stronger you get, the farther\n"
	.string "and higher you soar from Mother\l"
	.string "and me…\p"
	.string "This feeling is hard to explain.$"

MatchCall_Text_Norman3::
	.string "DAD: I see…\n"
	.string "You've collected four GYM BADGES…\p"
	.string "There's no avoiding it now.\n"
	.string "We will battle like I promised.\p"
	.string "Come anytime.\n"
	.string "We'll all be waiting for you!$"

MatchCall_Text_Norman4::
	.string "DAD: {PLAYER}! You'd better go visit\n"
	.string "Mother every so often.\p"
	.string "I'm going to remain here and\n"
	.string "redouble my training.\p"
	.string "The way of battling is deep\n"
	.string "and unforgiving!$"

MatchCall_Text_Norman5::
	.string "DAD: Oh, hi, {PLAYER}!\p"
	.string "What's that? MAGMA EMBLEM?\n"
	.string "I don't know what that's about.\p"
	.string "But with a name like that, it may\n"
	.string "be somehow linked to a volcano!$"

MatchCall_Text_Norman6::
	.string "DAD: Hiyah! Haah! Dwah!\p"
	.string "…Oh? {PLAYER}!\p"
	.string "You caught me right in the middle\n"
	.string "of a {POKEMON} training session!$"

MatchCall_Text_Norman7::
	.string "DAD: {PLAYER}!\p"
	.string "Who would've thought you'd become\n"
	.string "the {POKEMON} LEAGUE CHAMPION…\p"
	.string "Okay!\n"
	.string "I won't be left behind!$"

MatchCall_Text_Norman8::
	.string "DAD: Hm? {PLAYER}?\n"
	.string "What good timing!\p"
	.string "This time, I'm going to challenge\n"
	.string "you to battle.\p"
	.string "I'm waiting in the PETALBURG GYM.\n"
	.string "Accept my challenge anytime!$"

MatchCall_Text_Norman9::
	.string "DAD: …You amaze me, {PLAYER}.\n"
	.string "How much higher will you soar?$"

MatchCall_Text_Steven1::
	.string "STEVEN: Hi, {PLAYER}{KUN}!\p"
	.string "Have you been to MAUVILLE\n"
	.string "already?\p"
	.string "You should visit the BIKE SHOP\n"
	.string "and get a MACH BIKE.\p"
	.string "Then, try exploring the GRANITE\n"
	.string "CAVE thoroughly.\p"
	.string "You may make a new discovery\n"
	.string "there.$"

MatchCall_Text_Steven2::
	.string "STEVEN: Hi, {PLAYER}{KUN}!\p"
	.string "I've met a lot of different\n"
	.string "TRAINERS so far.\p"
	.string "But you're one of a kind.\n"
	.string "You're not like anyone else.$"

MatchCall_Text_Steven3::
	.string "STEVEN: Hi, {PLAYER}{KUN}!\p"
	.string "When you're on an adventure with\n"
	.string "your {POKEMON}, what do you think?\p"
	.string "Do you consider them to be strong\n"
	.string "partners?\p"
	.string "Do you think of them as fun\n"
	.string "companions?\p"
	.string "Depending on how you think, your\n"
	.string "adventure's significance changes.$"

MatchCall_Text_Steven4::
	.string "STEVEN: Hello?\n"
	.string "{PLAYER}{KUN}?\p"
	.string "I'm involved in a spot of trouble\n"
	.string "at the SPACE CENTER.\p"
	.string "I'm sorry, but I can't talk now.\n"
	.string "Bye!$"

MatchCall_Text_Steven5::
	.string "STEVEN: Oh!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "There's no need to talk.\n"
	.string "It's past time for talking.\p"
	.string "You have to believe in yourself\n"
	.string "and do what's right.$"

MatchCall_Text_Steven6::
	.string "… … … … … …\p"
	.string "STEVEN appears not to be getting\n"
	.string "the call…$"

MatchCall_Text_Steven7::
	.string "STEVEN: {PLAYER}{KUN}… Congratulations\n"
	.string "for entering the HALL OF FAME.\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "I hope we can meet again\n"
	.string "somewhere!$"

MatchCall_Text_BirchRegisterCall:
	.string "PROF. BIRCH: Oh, {PLAYER}{KUN}!\n"
	.string "I've already heard about you!\p"
	.string "It seems your {POKE}NAV's been\n"
	.string "upgraded with MATCH CALL.\p"
	.string "Well, I should register, too!\p"
	.string "That way, I'd be able to examine\n"
	.string "your {POKEDEX} even while you're\l"
	.string "out in the field.\p"
	.string "… … … … … …$"

MatchCall_Text_RegisteredBirch:
	.string "Registered PROF. BIRCH\n"
	.string "in the {POKE}NAV.$"

MatchCall_Text_UnusedProfBirch:
	.string "PROF. BIRCH: When one has both\n"
	.string "the {POKEDEX} and {POKE}NAV, studying\l"
	.string "{POKEMON} becomes more fun, eh?$"

MatchCall_Text_MrStone1::
	.string "MR. STONE: Oh? {PLAYER}{KUN}!\p"
	.string "Since you called me, the {POKE}NAV\n"
	.string "must be working properly!\p"
	.string "Other people will be registered,\n"
	.string "so try calling them up, too!\p"
	.string "Good! Good!\n"
	.string "You seem to be quite happy!\p"
	.string "Hm…\n"
	.string "How could I know that?\p"
	.string "It's because I'm looking down at\n"
	.string "you from my office window!\p"
	.string "Wahahaha!\n"
	.string "See you again!$"

MatchCall_Text_MrStone2::
	.string "MR. STONE: Oh? {PLAYER}{KUN}!\p"
	.string "What's wrong? Have you forgotten\n"
	.string "about that little errand of mine?\p"
	.string "I need you to deliver my letter\n"
	.string "to STEVEN in DEWFORD.\p"
	.string "After that, deliver our parcel to\n"
	.string "CAPT. STERN in SLATEPORT.\p"
	.string "You remember, don't you?\p"
	.string "Now, since I am a busy PRESIDENT,\n"
	.string "I have to go! Bye-bye!$"

MatchCall_Text_MrStone3::
	.string "MR. STONE: Oh! {PLAYER}{KUN}!\p"
	.string "Ah, so you've met STEVEN!\n"
	.string "I'd better reward you, then!\p"
	.string "When you visit RUSTBORO again,\n"
	.string "come see me at my office.\p"
	.string "I'll be waiting for you!$"

MatchCall_Text_MrStone4::
	.string "MR. STONE: Oh! {PLAYER}{KUN}!\p"
	.string "Did you know that DEVON was\n"
	.string "digging the RUSTURF TUNNEL?\p"
	.string "But we shut down the operation to\n"
	.string "protect the {POKEMON} in the area.\p"
	.string "It's a no-brainer, really.\p"
	.string "It's more important to let {POKEMON}\n"
	.string "live in peace than worry about our\l"
	.string "own convenience.$"

MatchCall_Text_MrStone5::
	.string "MR. STONE: Hello, hello, {PLAYER}{KUN}!\p"
	.string "I heard from someone in PETALBURG\n"
	.string "that you're NORMAN's child!\p"
	.string "No wonder you're such a capable\n"
	.string "being!$"

MatchCall_Text_MrStone6::
	.string "MR. STONE: What's that?\p"
	.string "You battled your own father and\n"
	.string "defeated him?\p"
	.string "That's astounding!\p"
	.string "I had no idea that I befriended\n"
	.string "someone so special! Wahaha!$"

MatchCall_Text_MrStone7::
	.string "Hello!\n"
	.string "This is DEVON CORPORATI…\l"
	.string "Oh, hello, {PLAYER}!\p"
	.string "Our PRESIDENT was here a little\n"
	.string "while ago, but he's gone out.\p"
	.string "Our PRESIDENT is busy, but you\n"
	.string "seem to be just as busy, {PLAYER}.$"

MatchCall_Text_MrStone8::
	.string "…Huh? …What's that?\p"
	.string "GROU… Yes? …DON?\p"
	.string "You're breaking up…\n"
	.string "…can't hear…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone9::
	.string "…Huh? …What's that?\p"
	.string "Seaflo… Yes? …Caver…?\p"
	.string "You're breaking up…\n"
	.string "…can't hear…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone10::
	.string "MR. STONE: {PLAYER}{KUN}! It's me!\p"
	.string "You were apparently involved in all\n"
	.string "sorts of things, but I, being busy,\l"
	.string "haven't a clue exactly what!\p"
	.string "However, I urge you to take\n"
	.string "the road you believe in and walk it.\p"
	.string "I'll always be in your corner!\n"
	.string "Take care!$"

MatchCall_Text_MrStone11::
	.string "MR. STONE: … … … … … …\n"
	.string "Is this maybe {PLAYER}{KUN}?\p"
	.string "Your voice is so full of confidence,\n"
	.string "I didn't recognize you right off!\p"
	.string "Hm! You must come visit us at DEVON\n"
	.string "sometime!$"

Matchcall_Alan_Answer_Morn::
	.string  "Yup, it's {STR_VAR_1}!\n"
	.string "Is this {PLAYER}?\l"
	.string "Good morning!$"

Matchcall_Alan_Answer_Day::
	.string  "Yup, it's {STR_VAR_1}!\n"
	.string "Is that {PLAYER}?$"

Matchcall_Alan_Answer_Night::
	.string  "Yup, it's {STR_VAR_1}!\n"
	.string "Is that {PLAYER}?\l"
	.string "Good evening!$"

Matchcall_Alan_Call::
	.string "Hello! It's me, {STR_VAR_1}!$"

Matchcall_Alan_Generic5::
	.string "{PLAYER}, are you raising\n"
	.string "your {POKEMON} properly?\p"
	.string "I read in a book that you should raise\n"
	.string "any {POKEMON} you catch with love\l"
	.string "and care.$"

Matchcall_Alan_Generic4::
	.string "My {STR_VAR_2}'s getting stronger\n"
	.string "exactly as I calculated!$"

Matchcall_Alan_Generic3::
	.string  "By the way, we knocked out a wild\n"
	.string "{STR_VAR_2} just the other day.\l"
	.string "Studying up in advance worked!$"

Matchcall_Alan_Generic2::
	.string  "By the way, a wild {STR_VAR_2}\n"
	.string "escaped on me yesterday.\p"
	.string "A computational error on my part…$"


Matchcall_Alan_Rematch::
	.string "I've studied quite a bit since then,\n"
	.string "and I've gotten a lot better!\p"
	.string "I'm hanging out on {STR_VAR_2}.\n"
	.string "Can you come down for a battle?$"


Matchcall_Alan_Hangup::
	.string  "See you later!$"


Matchcall_Alan_Gift::
	.string "Hehehe, I picked up something nice!\n"
	.string "You can have it!\p"
	.string "Why don't you come to {STR_VAR_2}\n"
	.string "and pick it up?$"

Matchcall_Alan_Generic1::
	.string  "I haven't picked up anything yet.\n"
	.string "I'll call you if I find something.$"


Matchcall_Alan_Remind_Rematch::
	.string  "If we don't battle soon, I'll forget\n"
	.string "my strategy!\p"
	.string "I'm waiting on {STR_VAR_2}!$"


Matchcall_Alan_Remind_Gift::
	.string  "I have to do my homework, so can you\n"
	.string "come get your gift right away?\p"

	.string "I'm waiting on {STR_VAR_2}!$"


Matchcall_Anthony_Answer_Morn::
	.string  "Yeah, {STR_VAR_1} the HIKER here.\n"
	.string "Ah, {PLAYER}!$"


Matchcall_Anthony_Answer_Day::
	.string  "Yeah, {STR_VAR_1} the HIKER here.\n"
	.string "Ah, {PLAYER}, right?$"


Matchcall_Anthony_Answer_Night::
	.string  "Yeah, {STR_VAR_1} the HIKER here.\n"
	.string "Ah, {PLAYER}, isn't it?$"


Matchcall_Anthony_Call_Morn::
	.string  "Yo, {PLAYER}?\n"
	.string "This is {STR_VAR_1} the HIKER!$"


Matchcall_Anthony_Call_Day::
	.string  "Hey, is this {PLAYER}?\n"
	.string "This is {STR_VAR_1} the HIKER!$"


Matchcall_Anthony_Call_Night::
	.string  "{PLAYER}, you still awake?\n"
	.string "This is {STR_VAR_1} the HIKER!$"


Matchcall_Anthony_Generic5::
	.string  "Are your {POKEMON} as feisty as ever?\p"

	.string "My {STR_VAR_2} and me, we have energy\n"
	.string "to burn.\p"
	.string "We hike up mountains every day\n"
	.string "to work out all our energy.$"



Matchcall_Anthony_Generic4::
	.string  "The other day, I was watching\n"
	.string "my {STR_VAR_2} eat some BERRIES.\p"

	.string "It looked like it was enjoying\n"
	.string "its meal, so I decided to try some.\p"

	.string "I'm not sure if people should eat\n"

	.string "that stuff, but it was delicious!$"


Matchcall_Anthony_Generic3::
	.string  "Lately, I've been running across\n"

	.string "wild {STR_VAR_2} quite often.\l"

	.string "They're easily taken care of.$"


Matchcall_Anthony_Generic2::
	.string  "Oh yeah, I was battling this\n"

	.string "{STR_VAR_2} the other day…\l"

	.string "It took off when I got distracted\l"
	.string "by a passing BEAUTY.\p"

	.string "Learn from my mistake, always always\n"
	.string "stay focused on the job at hand!$"


Matchcall_Anthony_Rematch::
	.string  "Come on--let's battle right now!\n"

	.string "{STR_VAR_2} is where I am.\l"

	.string "Come on down if you feel up to it!$"


Matchcall_Anthony_Hangup::
	.string  "All right then!\n"
	.string "Be good!$"


Matchcall_Anthony_Swarm::
	.string  "{PLAYER}! It's mind-blowing!\p"

	.string "I took a hike in DARK CAVE yesterday,\n"
	.string "see?\p"

	.string "Well, there were tons of DUNSPARCE\n"
	.string "around! You have to see it!\p"

	.string "I get this feeling that DUNSPARCE\n"
	.string "may be timid.\l"
	.string "I didn't see any where there are\l"
	.string "strong {POKEMON}.$"


Matchcall_Anthony_Generic1::
	.string  "Rare {POKEMON}?\n"
	.string "Hey, sorry!\p"
	.string "I was too focused on my hike, so I\n"

	.string "wasn't paying attention.$"


Matchcall_Anthony_Remind_Rematch::
	.string  "Hello!\p"
	.string "You haven't forgotten about our battle,\n"
	.string "have you?\p"
	.string "{STR_VAR_2}! I'm waiting!$"


Matchcall_Anthony_Remind_Swarm::
	.string  "Hello? What? Where is DUNSPARCE?\n"

	.string "DARK CAVE! Hurry!\p"

	.string "I know I've said it before, but\n"
	.string "DUNSPARCE don't appear when there\l"

	.string "are strong {POKEMON} around.$"


Matchcall_Arnie_Answer_Morn::
	.string  "Yeah, hello.\n"
	.string "This is {STR_VAR_1}.\l"

	.string "…Huh, {PLAYER}? Yo!$"


Matchcall_Arnie_Answer_Day::
	.string  "Yeah, hello, you got {STR_VAR_1}.\n"

	.string "…Huh, {PLAYER}? Yo!$"


Matchcall_Arnie_Answer_Night::
	.string  "Yeah, hello, you got {STR_VAR_1}.\n"

	.string "…Huh, {PLAYER}? Yo!$"


Matchcall_Arnie_Call_Morn::
	.string  "Yeah, hello?\n"
	.string "{STR_VAR_1} calling.\l"

	.string "What are you up to, {PLAYER}?$"


Matchcall_Arnie_Call_Day::
	.string  "Yeah, hello?\n"
	.string "{STR_VAR_1} calling.\l"

	.string "Where are you now, {PLAYER}?$"


Matchcall_Arnie_Call_Night::
	.string  "Yeah, hello?\n"
	.string "{STR_VAR_1} calling.\l"

	.string "Are you awake now, {PLAYER}?$"


Matchcall_Arnie_Generic5::
	.string  "I bet your {POKEMON} are a lot\n"
	.string "stronger than before.$"


Matchcall_Arnie_Generic4::
	.string  "I'm always with my {STR_VAR_2}!\n"

	.string "It's so cute!\l"
	.string "I just love it!$"


Matchcall_Arnie_Generic3::
	.string  "Changing the topic here.\p"
	.string "I saw this {STR_VAR_2} for the\n"
	.string  "first time.\l"

	.string "It was easy to beat, actually.$"


Matchcall_Arnie_Generic2::
	.string  "I was wondering, do you happen\n"
	.string "to have {STR_VAR_2}?\p"

	.string "I can't seem to catch one.\n"
	.string "What is its weakness, I wonder.$"


Matchcall_Arnie_Rematch::
	.string  "Hey, let's battle our {POKEMON}!\n"

	.string "I won't lose to you battling\l"

	.string "or in the Bug-Catching Contest!\p"

	.string "I'll be here on {STR_VAR_2}!$"


Matchcall_Arnie_Hangup::
	.string  "Let's talk again, huh?$"


Matchcall_Arnie_Swarm::
	.string  "Boy, am I glad I caught you!\p"

	.string "A whole bunch of YANMA have appeared\n"

	.string "around {STR_VAR_2}!\l"

	.string "You have to see this!$"


Matchcall_Arnie_Generic1::
	.string  "I haven't had any luck seeing rare\n"
	.string "{POKEMON} lately…\p"

	.string "But I know they're out there!$"


Matchcall_Arnie_Remind_Rematch::
	.string  "Hey, where are you now?\n"

	.string "Let's battle.\p"
	.string "I'll be waiting for you on\n"
	.string "{STR_VAR_2}!$"


Matchcall_Arnie_Remind_Swarm::
	.string  "Hello? Are you coming or what?\n"

	.string "You're missing out on seeing YANMA!\l"

	.string "Get down to {STR_VAR_2} right now!$"


Matchcall_Beth_Answer_Morn::
	.string  "Hello, this is {STR_VAR_1}.\n"

	.string "Oh, {PLAYER}. Good morning.$"


Matchcall_Beth_Answer_Day::
	.string  "Hello, this is {STR_VAR_1}.\n"
	.string  "Oh. Hi, {PLAYER}.$"


Matchcall_Beth_Answer_Night::
	.string  "Hello, this is {STR_VAR_1}.\n"
	.string "Oh, {PLAYER}. Good evening.$"


Matchcall_Beth_Call_Morn::
	.string  "Good morning, {PLAYER}!\n"

	.string "This is {STR_VAR_1}.\l"
	.string "Were you sleeping?$"


Matchcall_Beth_Call_Day::
	.string  "{PLAYER}, hi!\n"
	.string "This is {STR_VAR_1}.\l"

	.string "Do you have some time?$"


Matchcall_Beth_Call_Night::
	.string  "Hi, {PLAYER}. Good evening.\n"

	.string "This is {STR_VAR_1}.\l"

	.string "I hope you were awake.$"


Matchcall_Beth_Generic5::
	.string  "Are you the kind of person\n"
	.string "who goes to {POKEMON} CENTERS often?\l"

	.string "I go every day.\p"
	.string "Watching out for the health of your\n"
	.string "{POKEMON} is a basic part of being\l"

	.string "a {POKEMON} trainer.$"


Matchcall_Beth_Generic4::
	.string  "Do you remember my sweet {STR_VAR_2}?\n"

	.string "{STR_VAR_2} runs very fast.\l"

	.string "It's exhilarating to ride on its back\l"

	.string "when it really gets going.$"


Matchcall_Beth_Generic3::
	.string  "Oh, have you ever seen a {STR_VAR_2}\n"
	.string "before?\p"

	.string "I just battled one…\n"

	.string "It was much faster than I expected.\l"

	.string "I was a little shocked.\l"

	.string "I still won, of course.$"


Matchcall_Beth_Generic2::
	.string  "Oh, I just saw a wild {STR_VAR_2}.\n"

	.string "I was trying to catch it when I\l"

	.string "noticed that I was all out of BALLS.\p"

	.string "If you don't check your items,\n"

	.string "you may run out at the worst time.\l"

	.string "I hope you learn from my mistake.$"


Matchcall_Beth_Rematch::
	.string  "Do you want to battle?\n"
	.string "I'm going to win this time!\p"

	.string "I'll be waiting for you around\n"

	.string "{STR_VAR_2}.\l"
	.string "Look for me, OK?$"


Matchcall_Beth_Hangup::
	.string  "OK, bye-bye!$"


Matchcall_Beth_Generic1::
	.string  "Let's battle again sometime!$"


Matchcall_Beth_Remind_Gift::
	.string  "Um… {PLAYER}? What's wrong?\n"

	.string "Did you forget our deal?\l"

	.string "{STR_VAR_2}.\l"

	.string "That's where I'm waiting.$"


Matchcall_Beverly_Answer_Morn::
	.string  "Hello, this is {STR_VAR_1}.\n"

	.string "Oh! Good morning, {PLAYER}.$"


Matchcall_Beverly_Answer_Day::
	.string  "Hello, this is {STR_VAR_1}.\n"

	.string "Oh! Good day, {PLAYER}.$"


Matchcall_Beverly_Answer_Night::
	.string  "Hello, this is {STR_VAR_1}.\n"

	.string "Oh! Good evening, {PLAYER}.$"


Matchcall_Beverly_Call_Morn::
	.string  "Hello, {PLAYER}. Good morning.\n"

	.string "This is {STR_VAR_1}.\l"
	.string "Were you asleep?$"


Matchcall_Beverly_Call_Day::
	.string  "Hi, {PLAYER}.\n"
	.string "This is {STR_VAR_1}.\l"

	.string "How are you doing?$"


Matchcall_Beverly_Call_Night::
	.string  "Hi, {PLAYER}.\n"
	.string "This is {STR_VAR_1}.\l"

	.string "Were you awake?$"


Matchcall_Beverly_Generic5::
	.string  "Keeping your {POKEMON} happy?\n"

	.string "My {STR_VAR_2} is healthy.\l"
	.string "It eats a lot every day.$"


Matchcall_Beverly_Generic4::
	.string  "I fancied up my {STR_VAR_2}\n"
	.string "and made it even cuter than before!$"


Matchcall_Beverly_Generic3::
	.string  "I happened to come across a wild\n"
	.string "{STR_VAR_2} recently.\p"

	.string "My {STR_VAR_2}, I assure you,\n"

	.string "was far cuter than the wild one.$"


Matchcall_Beverly_Generic2::
	.string  "I happened to see\n"
	.string "a wild MARILL the other day.\l"
	.string "Or so I thought.\p"

	.string "A closer look showed it was\n"

	.string "{STR_VAR_2}. I was quite miffed.$"


Matchcall_Beverly_Hangup::
	.string  "You can expect a call from me.$"


Matchcall_Beverly_Gift::
	.string  "My husband got some NUGGETS.\n"

	.string "If you'd like, you could have one\l"
	.string "as thanks for helping me out.\p"

	.string "I'll be at {STR_VAR_2}.\n"

	.string "Please come see me when you can.$"


Matchcall_Beverly_Generic1::
	.string  "Are your {POKEMON} in prime form?\n"

	.string "Let's chat about {POKEMON} again.$"


Matchcall_Beverly_Remind_Gift::
	.string  "Pardon? Oh, the NUGGET?\n"

	.string "There's no need to hurry.\p"
	.string "Come see me in {STR_VAR_2} when\n"
	.string "you can.$"


Matchcall_Brent_Answer::
	.string  "Yes? {STR_VAR_1} here…\n"

	.string "Ah, {PLAYER}.\l"
	.string "What can I do for you?$"

Matchcall_Brent_Call::
	.string  "Hiya, {PLAYER}. How are you doing?\n"

	.string "Hey! It's me, {STR_VAR_1}.$"

Matchcall_Brent_Generic15::
	.string  "Oh yeah, I saw you coming out of a\n"

	.string "{POKEMON} CENTER the other day.\p"

	.string "You heal your {POKEMON} regularly,\n"
	.string "don't you? I'm impressed.\p"

	.string "Heh, my {STR_VAR_2} is so tough,\n"
	.string "it doesn't need to go to {POKEMON}\l"
	.string "CENTERS often. Heheh!$"


Matchcall_Brent_Generic14::
	.string  "Oh yeah, I got an extremely rare\n"

	.string "{POKEMON} in a trade a while back.\l"

	.string "Do you want to know what it is?\l"

	.string "Hehe, I'm keeping it a secret!$"


Matchcall_Brent_Generic13::
	.string  "Oh yeah, I took down this wild\n"

	.string "{STR_VAR_2}.\p"
	.string "It wasn't rare enough to bother\ncatching.$"


Matchcall_Brent_Generic12::
	.string  "Oh yeah, I saw a rare {POKEMON} about\n"
	.string "an hour ago.\l"

	.string "It was my first sighting.\l"
	.string "But I didn't have any BALLS…\l"

	.string "Would BILL laugh at my mistakes?$"


Matchcall_Brent_Rematch::
	.string  "You've got time like usual, right?\n"

	.string "Feel like having a battle?\p"

	.string "It'll be a chance to see my rare\n"
	.string "{POKEMON}.\l"
	.string "It'll be worth your time!\p"

	.string "You know where--{STR_VAR_2}.$"


Matchcall_Brent_Hangup::
	.string  "So that's it then.$"


Matchcall_Brent_Generic11::
	.string "Did you know…?\p"
	.string "BILL's father is supposed to be\n"
	.string "a great {POKE}MANIAC.$"


Matchcall_Brent_Generic10::
	.string  "Did you know…?\p"
	.string "Apparently BILL's grandpa isn't a\n"
	.string "{POKE}MANIAC.$"


Matchcall_Brent_Generic9::
	.string  "Did you know…?\p"
	.string "BILL's originally from GOLDENROD.$"


Matchcall_Brent_Generic8::
	.string  "Did you know…?\p"
	.string "BILL evidently lives on ROUTE 25\n"
	.string "in KANTO.$"


Matchcall_Brent_Generic7::
	.string  "Did you know…?\p"
	.string "ABRA was the first {POKEMON} that\n"

	.string "BILL ostensibly caught.$"


Matchcall_Brent_Generic6::
	.string  "Did you know…?\p"
	.string "BILL's younger sister apparently\n"
	.string "can't wink.$"


Matchcall_Brent_Generic5::
	.string  "Did you know…?\p"
	.string "BILL supposedly hates milk and\n"
	.string "can't drink it.$"


Matchcall_Brent_Generic4::
	.string  "Did you know…?\p"
	.string "Evidently, BILL isn't very good\n"
	.string "at battling.$"


Matchcall_Brent_Generic3::
	.string  "Did you know…?\p"
	.string "BILL appears to like the lady\n"

	.string "at the FLOWER SHOP.$"


Matchcall_Brent_Generic2::
	.string  "Did you know…?\p"
	.string "BILL's mother is said to have\n"

	.string "been a KIMONO GIRL.$"


Matchcall_Brent_Generic1::
	.string  "You wanted to hear about BILL?\n"

	.string "Sorry, but I'm too busy for you.\l"

	.string "I'll call when I have time.$"


Matchcall_Brent_Remind_Rematch::
	.string  "You want to see my rare {POKEMON}?\n"

	.string "Hurry over to {STR_VAR_2}.$"


Matchcall_Chad_Answer_Morn::
	.string  "Hello, this is {STR_VAR_1}…\n"

	.string "Hi, {PLAYER}! Good morning!$"


Matchcall_Chad_Answer_Day::
	.string  "Hello, this is {STR_VAR_1}…\n"

	.string "Hi, {PLAYER}, good day!$"


Matchcall_Chad_Answer_Night::
	.string  "Hello, this is {STR_VAR_1}…\n"

	.string "Hi, {PLAYER}, good evening!$"


Matchcall_Chad_Call_Morn::
	.string  "Hi, {PLAYER}, good morning!\n"

	.string "It's {STR_VAR_1}.\l"
	.string "How are you?$"


Matchcall_Chad_Call_Day::
	.string  "Hi, {PLAYER}, good day!\n"

	.string "It's {STR_VAR_1}.\l"
	.string "How are you?$"


Matchcall_Chad_Call_Night::
	.string  "Hi, {PLAYER}, good evening!\n"

	.string "It's {STR_VAR_1}.\l"
	.string "How are you?$"


Matchcall_Chad_Generic15::
	.string  "How are your {POKEMON} doing?\n"

	.string "You know PROF.OAK, so of course\l"
	.string "your {POKEMON} are fine!\l"

	.string "My {POKEMON} are doing well too.\p"

	.string "But then, I am trying to become\n"
	.string "become a {POKEMON} professor, so that\l"
	.string "shouldn't be a big surprise.$"


Matchcall_Chad_Generic14::
	.string  "I recently began observing wild\n"
	.string "{STR_VAR_2}.\p"

	.string "I've been learning all sorts of new\n"

	.string "things through my observations.\p"

	.string "I wish I could become a {POKEMON}\n"

	.string "researcher like PROF.OAK soon.$"


Matchcall_Chad_Generic13::
	.string  "Oh yes, I managed to knock out a\n"

	.string "wild {STR_VAR_2} a while back.\p"

	.string "Well, considering all the studying I\n"

	.string "do every day, it was inevitable.$"


Matchcall_Chad_Generic12::
	.string  "Oh yes, I came close to catching\n"

	.string "a wild {STR_VAR_2}, but it got away.\p"

	.string "For the longest time, I've been\n"

	.string "wanting to observe {STR_VAR_2}.\lRats…$"


Matchcall_Chad_Rematch::
	.string  "Want to battle?\n"
	.string "I have to battle every so often\l"

	.string "to avoid rusting out.\p"

	.string "I'll be on {STR_VAR_2}!$"


Matchcall_Chad_Hangup::
	.string  "See you later!$"


Matchcall_Chad_Generic11::
	.string  "Do you know BLUE?\p"

	.string "He's PROF.OAK's grandson and\n"
	.string "a former {POKEMON} LEAGUE CHAMPION!\l"

	.string "He's one super {POKEMON} trainer!$"


Matchcall_Chad_Generic10::
	.string  "PROF.OAK has a granddaughter\n"
	.string "named DAISY.\p"

	.string "When she's around, even the most\n"
	.string "ferocious {POKEMON} calm right down.$"


Matchcall_Chad_Generic9::
	.string  "Everyone's talking about PROF.ELM.\p"

	.string "He used to be an assistant to the\n"
	.string "great PROF.OAK!\l"

	.string "That is so cool!\l"
	.string "I envy him!$"


Matchcall_Chad_Generic8::
	.string  "PROF.OAK's dream is to compile a\n"

	.string "comprehensive {POKEDEX}.\p"

	.string "I envy you for taking part in\n"
	.string "that project…$"


Matchcall_Chad_Generic7::
	.string  "Do you know KURT, the BALL creator?\n"

	.string "He and PROF.OAK go back a long way.\p"

	.string "I guess great people attract\none another!$"


Matchcall_Chad_Generic6::
	.string  "{POKEMON} LEAGUE is the great\n"
	.string "gathering place for all trainers\l"

	.string "who wish to become CHAMP.\p"

	.string "PROF.OAK acts as an advisor to the\n"

	.string "{POKEMON} LEAGUE's headquarters.\l"

	.string "He really is a great man.$"


Matchcall_Chad_Generic5::
	.string  "PROF.OAK'S {POKEMON} TALK is a popular\n"
	.string "radio show, right?\p"

	.string "Did you know that he was going to\n"

	.string "turn down the show at first?\p"

	.string "But MARY's energy and persistence\n"
	.string "wore him down.\l"

	.string "So we have MARY to thank for it!$"


Matchcall_Chad_Generic4::
	.string  "PROF.OAK used to be a trainer a\n"
	.string "long time ago.\p"

	.string "But rather than battling, he found\n"
	.string "{POKEMON} themselves to be interesting.\p"

	.string "So he abandoned his training to focus\n"

	.string "on becoming a researcher.$"


Matchcall_Chad_Generic3::
	.string  "PROF.OAK has a granddaughter\nnamed DAISY.\p"

	.string "She has tea every day for an hour\n"

	.string "from three in the afternoon.\p"

	.string "I wish I could join her for tea\n"

	.string "and chat about PROF.OAK.$"


Matchcall_Chad_Generic2::
	.string  "Did you know?\p"
	.string "PROF.OAK traveled all over the world\n"
	.string "when he was young.\p"

	.string "While traveling, he must've learned\n"

	.string "about {POKEMON} naturally.\l"

	.string "I envy him…\p"
	.string "I'd like to travel and learn about\nthings too…$"


Matchcall_Chad_Generic1::
	.string  "I'm going to study hard so PROF.OAK\n"

	.string "will make me his assistant!$"


Matchcall_Chad_Remind_Rematch::
	.string  "Do you remember about our battle?\n"

	.string "The place is {STR_VAR_2}.\l"

	.string "Hurry over--I'm waiting.$"


Matchcall_Dana_Answer_Morn::
	.string  "Hi, {STR_VAR_1} on the line.\n"

	.string "Hey! It's {PLAYER}!$"


Matchcall_Dana_Answer_Day::
	.string  "Hi, {STR_VAR_1} on the line.\n"

	.string "I know! It's {PLAYER}!$"


Matchcall_Dana_Answer_Night::
	.string  "Hi, {STR_VAR_1} on the line.\n"

	.string "{PLAYER}? What's up?$"


Matchcall_Dana_Call::
	.string  "Uh, {PLAYER}?\n"

	.string "It's me!\l"
	.string "It's me, {STR_VAR_1}!$"


Matchcall_Dana_Generic5::
	.string  "My {STR_VAR_2} is so full of\n"
	.string "energy, it's a little scary.\l"

	.string "How are your {POKEMON} doing?$"


Matchcall_Dana_Generic4::
	.string  "My {STR_VAR_2} is getting prettier!\n"

	.string "I've been taking photos galore!$"


Matchcall_Dana_Generic3::
	.string  "It took only an instant to KO a wild\n"
	.string "{STR_VAR_2}.\p"

	.string "It must be because you gave me some\n"

	.string "battling tips last time.$"


Matchcall_Dana_Generic2::
	.string  "You know what?\p"
	.string "A wild {STR_VAR_2} got away from me\n"
	.string "again.\l"

	.string "It was so close!\p"
	.string "Really, just a little bit more, and\n"
	.string "I would've…$"


Matchcall_Dana_Rematch::
	.string  "Right now, I'm on {STR_VAR_2}.\n"

	.string "If you're close by, let's battle!\l"

	.string "I'll be waiting for you!$"


Matchcall_Dana_Hangup::
	.string  "See you!$"


Matchcall_Dana_Gift::
	.string  "You know what?\n"
	.string "I got a good gift!\l"

	.string "As I promised, it's yours!\l"

	.string "I'm sure you'd like it. Come get it!\l"

	.string "I'm waiting on {STR_VAR_2}!$"


Matchcall_Dana_Generic1::
	.string  "Oh! You wanted a gift, right?\n"

	.string "I got one, but I want to keep this.\l"

	.string "Can you wait a bit longer?$"


Matchcall_Dana_Remind_Rematch::
	.string "Hi!\p"
	.string "You haven't forgotten about your\n"

	.string "promise to battle me?\l"

	.string "I'm waiting on {STR_VAR_2}!$"


Matchcall_Dana_Remind_Gift::
	.string  "Hello?\p"

	.string "If you don't come get your present\n"

	.string "soon, I'll give it to someone else.\l"

	.string "I'm waiting on {STR_VAR_2}!$"


Matchcall_Derek_Answer_Morn::
	.string  "Hi, {PLAYER}?\n"

	.string "Good morning pika.\l"
	.string "What's up pika?$"


Matchcall_Derek_Answer_Day::
	.string  "Hi, {PLAYER}?\p"
	.string "Good day pika,\n"
	.string "what's up pika?$"


Matchcall_Derek_Answer_Night::
	.string  "Hi, {PLAYER}?\p"

	.string "Good evening pika,\n"
	.string "what's up pika?$"


Matchcall_Derek_Call_Morn::
	.string  "{PLAYER} pika, good morning!\n"

	.string "It's {STR_VAR_1}, how pika are you?$"


Matchcall_Derek_Call_Day::
	.string  "{PLAYER} pika, good pika day!\n"

	.string "It's {STR_VAR_1}, how pika are you?$"


Matchcall_Derek_Call_Night::
	.string  "{PLAYER} pika, good evening!\n"

	.string "It's {STR_VAR_1}. Were you pika awake?$"


Matchcall_Derek_Generic5::
	.string  "You have to hear this!\p"
	.string "My lovable {STR_VAR_2} looked at me\n"
	.string "and grinned!\p"

	.string "It must be because our hearts\n"
	.string "beat together as one!$"


Matchcall_Derek_Generic4::
	.string  "Listen to this.\p"
	.string "My {STR_VAR_2} grins happily when I\n"
	.string "pinch its cheek.\l"

	.string "But it never grins for anyone else.\l"

	.string "I must be special.$"


Matchcall_Derek_Generic3::
	.string  "Oh, and recently my PIKACHU beat a\n"
	.string "wild {STR_VAR_2}!\l"

	.string "A wild {STR_VAR_2}, I tell you!\l"

	.string "Don't you think that's astounding?\l"

	.string "My PIKACHU is awesome!\l"

	.string "My PIKACHU is the greatest!$"


Matchcall_Derek_Generic2::
	.string  "Oh, and I saw a wild {STR_VAR_2}\n"
	.string  "a little while ago.\l"

	.string "But it wasn't very cute, so I left it…\l"
	.string "{POKEMON} have to be cute.\l"
	.string "They're no good otherwise.$"


Matchcall_Derek_Hangup::
	.string  "Well, let's talk again!$"

Matchcall_Derek_Gift::
	.string  "I'd like you to have a NUGGET.\n"

	.string "My PIKACHU just loves it.\p"

	.string "I'm certain your PIKACHU will love\n"
	.string "it too!$"


Matchcall_Derek_Generic1::
	.string  "How is your PIKACHU doing?\p"

	.string "Let's get together and brag about\n"
	.string "our PIKACHU!$"


Matchcall_Derek_Remind_Gift::
	.string  "What's wrong?\n"

	.string "I'm waiting on {STR_VAR_2}.\l"

	.string "Come pick this up anytime.$"


Matchcall_Erin_Answer_Morn::
	.string  "Yes, this is {STR_VAR_2}…\n"

	.string "Oh. Hi, {PLAYER}!\l"
	.string "Good morning!$"


Matchcall_Erin_Answer_Day::
	.string  "Yes, this is {STR_VAR_1}…\n"

	.string "Oh, hi, {PLAYER}!\l"
	.string "Yahoo!$"


Matchcall_Erin_Answer_Night::
	.string  "Yes, this is {STR_VAR_1}…\n"

	.string "Oh, hi, {PLAYER}!$"


Matchcall_Erin_Call_Morn::
	.string  "{PLAYER}!\n"

	.string "It's {STR_VAR_1}!\l"
	.string "Good morning!$"


Matchcall_Erin_Call_Day::
	.string  "{PLAYER}!\n"

	.string "It's {STR_VAR_1}!\l"
	.string "Working hard?$"


Matchcall_Erin_Call_Night::
	.string  "{PLAYER}!\n"

	.string "It's {STR_VAR_1}!\l"
	.string "Were you up?$"


Matchcall_Erin_Generic5::
	.string  "Are you raising your {POKEMON}?\n"

	.string "Hey, {STR_VAR_1}'s {STR_VAR_2}\l"
	.string  "is looking good!$"


Matchcall_Erin_Generic4::
	.string "{STR_VAR_1}'s {STR_VAR_2}\n"
	.string "is much stronger than before!$"


Matchcall_Erin_Generic3::
	.string  "And, and…\n"
	.string "I just battled and beat {STR_VAR_2}!\l"

	.string "I've raised my {POKEMON} properly!$"


Matchcall_Erin_Generic2::
	.string  "But, but…\p"

	.string "A wild {STR_VAR_2} got away from me\n"
	.string "again.\l"

	.string "It's just not fair!$"


Matchcall_Erin_Rematch::
	.string  "I'm {STR_VAR_1}. Want to battle me again?\n"

	.string "I won't lose this time!\l"

	.string "I'll be waiting on {STR_VAR_2}!$"


Matchcall_Erin_Hangup::
	.string  "See you. Bye-bye!$"


Matchcall_Erin_Generic1::
	.string  "I'm working hard to raise my {POKEMON}!\n"

	.string "Come back for another battle!$"


Matchcall_Erin_Remind_Rematch::
	.string  "Oh, {PLAYER}!\n"
	.string "Come battle {STR_VAR_1}!\l"

	.string "I'll be waiting on {STR_VAR_2}!$"


Matchcall_Gaven_Answer_Morn::
	.string  "Hello, this is {STR_VAR_1} speaking…\n"

	.string "Hi, {PLAYER}!\l"
	.string "Good morning!$"


Matchcall_Gaven_Answer_Day::
	.string  "Hello, this is {STR_VAR_1} speaking…\n"

	.string "Hi, {PLAYER}!$"


Matchcall_Gaven_Answer_Night::
	.string  "Hello, this is {STR_VAR_1} speaking…\n"

	.string "Hi, {PLAYER}!\l"
	.string "Good evening!$"


Matchcall_Gaven_Call_Morn::
	.string  "{PLAYER}, good morning!\n"

	.string "It's me, {STR_VAR_1}.\l"
	.string "How are you doing?$"


Matchcall_Gaven_Call_Day::
	.string  "Hi, {PLAYER}!\n"

	.string "It's me, {STR_VAR_1}.\l"
	.string "How are you doing?$"


Matchcall_Gaven_Call_Night::
	.string  "{PLAYER}, good evening!\n"

	.string "It's me, {STR_VAR_1}.\l"
	.string "How are you doing?$"


Matchcall_Gaven_Generic5::
	.string  "How are your {POKEMON} doing?\p"

	.string "My {STR_VAR_2}'s doing as great\n"
	.string "as ever.\p"

	.string "Let's keep at it and become\n"
	.string "{POKEMON} CHAMPS!$"


Matchcall_Gaven_Generic4::
	.string  "My {STR_VAR_2} might be greater\n"
	.string "than I imagined.\p"

	.string "I doubt I'll see a {STR_VAR_1}\n"
	.string  "that's better than mine.$"


Matchcall_Gaven_Generic3::
	.string  "Oh, and I managed to barely defeat\n"

	.string "{STR_VAR_2} the other day.\p"

	.string "I've never seen a {STR_VAR_2}\n"
	.string  "get that strong…\p"

	.string "You shouldn't let your guard down\n"

	.string "even against a {POKEMON} you're used\l"
	.string "to seeing.$"


Matchcall_Gaven_Generic2::
	.string  "And a while back, I tried to catch\n"
	.string "a wild {STR_VAR_2}.\l"

	.string "But it managed to elude me.\p"

	.string "One wrong decision could mean total\n"

	.string "failure… You ought to be careful too.$"


Matchcall_Gaven_Rematch::
	.string  "Let's battle!\n"

	.string "I'll be waiting on {STR_VAR_2}.\l"

	.string "Give me a shout when you're close.$"


Matchcall_Gaven_Hangup::
	.string  "OK, I'll talk to you soon!$"


Matchcall_Gaven_Generic1::
	.string  "I obsess over how to beat you.$"


Matchcall_Gaven_Remind_Rematch::
	.string  "{PLAYER}, why aren't you here?\n"

	.string "I'll take you down with {STR_VAR_2}!$"


Matchcall_Gina_Answer_Morn::
	.string  "Hello? This is {STR_VAR_1}…\n"

	.string "Oh, {PLAYER}!\l"
	.string "Good morning!$"


Matchcall_Gina_Answer_Day::
	.string  "Hello? This is {STR_VAR_1}…\n"

	.string "Oh, {PLAYER}!\l"
	.string "Hi, how are you?$"


Matchcall_Gina_Answer_Night::
	.string  "Hello? This is {STR_VAR_1}…\n"

	.string "Oh, {PLAYER}!\l"
	.string "Good evening!$"


Matchcall_Gina_Call_Morn::
	.string  "{PLAYER}?\n"

	.string "It's {STR_VAR_1}.\l"
	.string "Good morning!$"


Matchcall_Gina_Call_Day::
	.string  "{PLAYER}?\n"

	.string "It's {STR_VAR_1}.\l"
	.string "Is this a bad time?$"


Matchcall_Gina_Call_Night::
	.string  "{PLAYER}?\n"

	.string "It's {STR_VAR_1}.\l"
	.string "Got time to chat?$"


Matchcall_Gina_Generic5::
	.string  "Are your {POKEMON} still tough?\n"

	.string "I train every day with {STR_VAR_2}.$"


Matchcall_Gina_Generic4::
	.string  "My {STR_VAR_2} and I are getting\n"
	.string "more in sync with each other.$"


Matchcall_Gina_Generic3::
	.string  "We battled a wild {STR_VAR_2}\n"
	.string "and managed to drop it in a\l"
	.string "close match.\l"

	.string "We're getting into the groove!$"


Matchcall_Gina_Generic2::
	.string  "But, you know?\n"

	.string "I still haven't caught {STR_VAR_2}.\l"

	.string "It's getting past frustrating…$"


Matchcall_Gina_Rematch::
	.string  "Would you be my practice partner\n"
	.string "again sometime?\l"

	.string "I'll be waiting on {STR_VAR_2}.\p"

	.string "…Could you take it a little easier\n"
	.string "on me next time?$"


Matchcall_Gina_Hangup::
	.string  "Bye! Let's chat again!$"

Matchcall_Gina_Gift::
	.string  "I picked up something nice today.\n"

	.string "I want you to have it, so I called!\l"

	.string "You will come for it, won't you?\l"

	.string "{STR_VAR_2} is where I am.$"


Matchcall_Gina_Generic1::
	.string  "Sorry, I haven't found anything useful\n"

	.string "yet…\p"
	.string "I promise, if I find anything, you\n"
	.string "can have it!$"


Matchcall_Gina_Remind_Rematch::
	.string  "Oh, {PLAYER}!\p"
	.string "How soon can I expect to see you\n"
	.string "for our battle?\l"

	.string "Don't forget, {STR_VAR_1}!$"


Matchcall_Gina_Remind_Gift::
	.string  "I'm getting really impatient\n"
	.string "waiting to give you my present!\l"

	.string "Hurry over to {STR_VAR_2}!$"


Matchcall_Huey_Answer::
	.string  "Yeah, this is {STR_VAR_1}.\n"

	.string "Huh? What's up, {PLAYER}?$"


Matchcall_Huey_Call_Morn::
	.string  "Yo, {PLAYER}!\n"
	.string "You awake?\l"

	.string "It's me, {STR_VAR_1}!\l"
	.string "How's it going?$"


Matchcall_Huey_Call_Day::
	.string  "Yo, {PLAYER}!\n"
	.string "You free right now?\l"

	.string "It's me, {STR_VAR_1}!\l"
	.string "How's it going?$"


Matchcall_Huey_Call_Night::
	.string  "Yo, {PLAYER}!\n"
	.string "Were you asleep?\l"

	.string "It's me, {STR_VAR_1}!\l"
	.string "How's it going?$"


Matchcall_Huey_Rematch::
	.string  "Hey, I challenge you to a battle!\n"

	.string "It won't be like last time!\p"

	.string "{STR_VAR_2}'s where I'm waiting for you.\l"
	.string "Hustle over here pronto!$"


Matchcall_Huey_Hangup::
	.string  "See ya!$"


Matchcall_Huey_Generic1::
	.string  "We have to battle again sometime.\p"

	.string "You can bet I'm going to keep\n"

	.string "challenging you till I win.$"


Matchcall_Huey_Remind_Rematch::
	.string  "Hey, you'd better not have forgotten\n"
	.string "about our battle!\l"

	.string "{STR_VAR_2}!\l"

	.string "Hustle over quick!\l"
	.string "I'm waiting!$"


Matchcall_Jack_Answer_Morn::
	.string  "Hello. This is {STR_VAR_1}…\n"

	.string "Good morning, {PLAYER}!$"


Matchcall_Jack_Answer_Day::
	.string  "Hello. This is {STR_VAR_1}…\n"

	.string "How's it going, {PLAYER}?$"


Matchcall_Jack_Answer_Night::
	.string  "Hello. This is {STR_VAR_1}…\n"

	.string "Good evening, {PLAYER}!$"


Matchcall_Jack_Call_Morn::
	.string  "{PLAYER}, good morning!\n"

	.string "It's me, {STR_VAR_1}.\l"
	.string "How are you doing?$"


Matchcall_Jack_Call_Day::
	.string  "{PLAYER}, howdy!\n"

	.string "It's me, {STR_VAR_1}.\l"
	.string "Isn't it nice out?$"


Matchcall_Jack_Call_Night::
	.string  "{PLAYER}, good evening!\n"

	.string "It's me, {STR_VAR_1}.\l"
	.string "Got a minute?$"


Matchcall_Jack_Generic16::
	.string  "How are your {POKEMON} doing?\p"

	.string "My {STR_VAR_2} is so curious, it's a\n"
	.string "problem.\l"

	.string "Maybe it's like me…$"


Matchcall_Jack_Generic15::
	.string  "My {STR_VAR_2}'s intelligence keeps\n"

	.string "rising.\l"
	.string "It might be smarter than yours!$"


Matchcall_Jack_Generic14::
	.string  "The other day, I easily defeated\n"
	.string "a {STR_VAR_2}.\p"

	.string "I think swapping tips with you is\n"
	.string "starting to help.$"


Matchcall_Jack_Generic13::
	.string  "Oh, and listen.\p"
	.string "I missed catching a {STR_VAR_2} by\n"
	.string  "just a tiny bit.\p"

	.string "If I'd been a bit more informed, I'm\n"

	.string "sure I would've caught it…$"


Matchcall_Jack_Rematch::
	.string  "Do you want to battle?\p"
	.string "I'll show you how to battle\n"
	.string "logically.\l"

	.string "I'll be in {STR_VAR_2}.\l"

	.string "Give me a shout if you're nearby.$"


Matchcall_Jack_Hangup::
	.string  "See you later!$"


Matchcall_Jack_Generic12::
	.string  "Did you know?\p"

	.string "When it's raining, THUNDER is\n"
	.string "sure to strike.$"


Matchcall_Jack_Generic11::
	.string  "Did you know…?\p"

	.string "If you use DEFENSE CURL, ROLLOUT's\n"
	.string "power goes way up past normal.$"


Matchcall_Jack_Generic10::
	.string  "Did you know…?\p"

	.string "If the sunlight is harsh, SOLARBEAM\n"
	.string "doesn't need to be charged up.$"


Matchcall_Jack_Generic9::
	.string  "Did you know…?\p"

	.string "If the opponent uses MINIMIZE, your\n"

	.string "STOMP becomes more powerful.$"


Matchcall_Jack_Generic8::
	.string  "Did you know…?\p"

	.string "If your opponent is FLYing, your\n"

	.string "GUST becomes much more powerful.$"


Matchcall_Jack_Generic7::
	.string  "Did you know…?\p"

	.string "If your opponent is FLYing, TWISTER\n"

	.string "becomes more powerful.$"


Matchcall_Jack_Generic6::
	.string  "Did you know…?\p"

	.string "If your opponent uses DIG, your\n"

	.string "EARTHQUAKE becomes more powerful.$"


Matchcall_Jack_Generic5::
	.string  "Did you know…?\p"

	.string "If your opponent uses DIG your\n"
	.string "MAGNITUDE becomes more powerful.$"


Matchcall_Jack_Generic4::
	.string  "Did you know…?\p"

	.string "The rock, ground, and steel types\n"
	.string "can't be hurt by SANDSTORM.$"


Matchcall_Jack_Generic3::
	.string  "Did you know…?\p"

	.string "If the sunlight is harsh, water-type\n"
	.string "moves become much weaker.$"


Matchcall_Jack_Generic2::
	.string  "Did you know…?\p"

	.string "When it's raining, fire-type moves\n"
	.string "become much weaker than usual.$"


Matchcall_Jack_Generic1::
	.string  "My friend heard some great tips.\n"

	.string "He's going to let me in on some.\p"

	.string "When he tells me, I'll call right\n"
	.string "away and tell you.$"


Matchcall_Jack_Remind_Rematch::
	.string  "Hey, {PLAYER}!\n"

	.string "Do you remember your promise?\l"

	.string "We have to battle soon!\l"

	.string "I'll be at {STR_VAR_2}.$"


Matchcall_Joey_Answer::
	.string  "Hi, {STR_VAR_1} here!\n"

	.string "Oh, {PLAYER}?\l"
	.string "You doing well?$"


Matchcall_Joey_Call_Morn::
	.string  "Yo, {PLAYER}!\n"
	.string "How're you doing?\l"

	.string "This is {STR_VAR_1}, got a minute?$"


Matchcall_Joey_Call_Day::
	.string  "Yo, {PLAYER}!\n"
	.string "How's it going?\l"

	.string "This is {STR_VAR_1}, got a minute?$"


Matchcall_Joey_Call_Night::
	.string  "Yo, {PLAYER}!\n"
	.string "How're you doing?\l"

	.string "This is {STR_VAR_1}, got a minute?$"


Matchcall_Joey_Generic5::
	.string  "How are your {POKEMON} doing?\p"

	.string "My {STR_VAR_2}'s raring to go, just\n"
	.string "like always.\l"

	.string "It's the only one I have.\p"

	.string "I'm going to become a great trainer\n"
	.string "with it!$"


Matchcall_Joey_Generic4::
	.string  "My {STR_VAR_2}'s looking sharper\n"
	.string "than before!\p"

	.string "I doubt there's a {POKEMON} as cool\n"
	.string "as this guy in your party!$"


Matchcall_Joey_Generic3::
	.string  "Oh yeah, I took down a {STR_VAR_2}\n"
	.string "in the wild the other day.\l"

	.string "It was a cakewalk.\p"
	.string "Well, I guess it can't be helped, us\n"
	.string "being so tough.$"


Matchcall_Joey_Generic2::
	.string  "Oh yeah, I saw a wild {STR_VAR_2}!\p"

	.string "I thought about going for it, but\n"

	.string "I decided to work with my one-and-only\l"
	.string "right to the extreme end.$"


Matchcall_Joey_Rematch::
	.string  "Let's get together and battle!\n"

	.string "I promise things will be different!\l"

	.string "{STR_VAR_2}'s where I'll be.\l"

	.string "Give me a shout when you come.$"


Matchcall_Joey_Hangup::
	.string  "All right. Later!$"


Matchcall_Joey_Generic1::
	.string  "I'm checking out {STR_VAR_2}'s moves\n"

	.string "and devising some strategies.\p"

	.string "When I come up with a good one, let's\n"
	.string "let's battle!$"


Matchcall_Joey_Remind_Rematch::
	.string  "What's keeping you, {PLAYER}!\n"

	.string "Let's get down and battle already!\l"

	.string "I'm waiting on {STR_VAR_2}!$"


Matchcall_Jose_Answer_Morn::
	.string  "Hello, this is {STR_VAR_1}…\n"

	.string "Oh, {PLAYER}?\l"
	.string "Good morning!$"


Matchcall_Jose_Answer_Day::
	.string  "Hello, this is {STR_VAR_1}…\n"

	.string "Oh, {PLAYER}? Hi!$"


Matchcall_Jose_Answer_Night::
	.string  "Hello, this is {STR_VAR_1}…\n"

	.string "Oh, {PLAYER}?\l"
	.string "Good evening!$"


Matchcall_Jose_Call::
	.string  "Oh, {PLAYER}?\n"

	.string "Tweet! Yeah, it's me, {STR_VAR_1}.$"


Matchcall_Jose_Generic5::
	.string  "Are your {POKEMON} still cooking?\n"

	.string "My {STR_VAR_2} has too much energy.\p"

	.string "Once it takes off, it won't come back\n"
	.string "for a while.$"


Matchcall_Jose_Generic4::
	.string  "Hey listen, my FARFETCH'D's stick\n"

	.string "has this really delicious aroma.\l"

	.string "That aroma gets my appetite going!$"


Matchcall_Jose_Generic3::
	.string  "A while ago, my FARFETCH'D KO'd\n"
	.string "this {STR_VAR_2}.\p"

	.string "You should have seen FARFETCH'D\n"

	.string "wield that stick.\l"
	.string "Amazing stuff!$"


Matchcall_Jose_Generic2::
	.string  "I ran into a wild {STR_VAR_2}…\p"

	.string "I was trying to catch it, but\n"

	.string "but it took off faster than I thought\l"

	.string "it would. It was a bit disappointing.$"


Matchcall_Jose_Rematch::
	.string  "Want to battle again?\p"

	.string "For some reason, my FARFETCH'D is\n"

	.string "all worked up and raring to go.\l"

	.string "{STR_VAR_2}'s where I'm at.\l"

	.string "Keep an eye out for me, OK?$"


Matchcall_Jose_Hangup::
	.string  "Be seeing you!$"


Matchcall_Jose_Gift::
	.string  "My FARFETCH'D had something pretty\n"
	.string "in its beak.\l"

	.string "Like I promised, you can have it.\p"

	.string "Catch up to me on {STR_VAR_2}, and\n"
	.string  "I'll let you have it.$"


Matchcall_Jose_Generic1::
	.string  "I haven't gotten what I promised you\n"
	.string "yet.\p"

	.string "I'll call you as soon as I get it, so\n"

	.string "could you wait a little longer?$"


Matchcall_Jose_Remind_Rematch::
	.string  "{PLAYER}, could you hurry over?\n"

	.string "FARFETCH'D is agitated.\p"

	.string "If you don't come soon, it\n"
	.string "might smack me with its stick!\l"

	.string "{STR_VAR_2}!\l"

	.string "Please come as soon as you can!$"


Matchcall_Jose_Remind_Gift::
	.string  "What's wrong?\n"

	.string "Don't you want this gift?\p"

	.string "Catch up to me on {STR_VAR_2}, and\n"

	.string "I'll let you have it.$"

Matchcall_Liz_Answer_Morn::
	.string  "Hello, {STR_VAR_1} speaking.\n"

	.string "Oh, {PLAYER}.\l"
	.string "Good morning.$"


Matchcall_Liz_Answer_Day::
	.string  "Hello, {STR_VAR_1} speaking.\n"

	.string "Oh, {PLAYER}.\l"
	.string "How are you?$"


Matchcall_Liz_Answer_Night::
	.string  "Hello, {STR_VAR_1} speaking.\n"

	.string "Oh, {PLAYER}.\l"
	.string "Good evening.$"


Matchcall_Liz_Call_Morn::
	.string  "Good morning, {PLAYER}.\n"

	.string "This is {STR_VAR_1}.\l"
	.string "Were you sleeping?$"


Matchcall_Liz_Call_Day::
	.string  "Hi, {PLAYER}.\n"
	.string "This is {STR_VAR_1}.\l"

	.string "How are things going for you?$"


Matchcall_Liz_Call_Night::
	.string  "Good evening, {PLAYER}.\n"

	.string "This is {STR_VAR_1}.\l"
	.string "Are you awake?$"


Matchcall_Liz_Generic16::
	.string  "I had some time, so I called you.\n"

	.string "So anyway, how are your {POKEMON}?\p"

	.string "Me, I take my {STR_VAR_2} to the\n"

	.string "{POKEMON} CENTER in VIOLET every day,\l"

	.string "so it's doing just fantastic!\l"

	.string "I'm friends with the receptionist!$"


Matchcall_Liz_Generic15::
	.string  "Oh, you have to hear this.\n"

	.string "My {STR_VAR_2} is so adorable!\l"

	.string "It always wants to nuzzle me!$"


Matchcall_Liz_Generic14::
	.string  "And, and! Um…\p"

	.string "We beat a wild {STR_VAR_2} with just\n"

	.string "one hit a little while ago.\l"

	.string "We felt sorry for it, though.$"


Matchcall_Liz_Generic13::
	.string  "And, and! Uh…\p"

	.string "We just saw a really gorgeous\n{STR_VAR_2}.\p"

	.string "But I was on the phone, so it got\n"

	.string "away.\l"
	.string "It made us really angry!$"


Matchcall_Liz_Rematch::
	.string  "Hi! Do you have some free time?\n"

	.string "I've got all sorts of time.\p"

	.string "If you're free, would you like to\n"
	.string "battle?\l"

	.string "I'll be waiting on {STR_VAR_2}.\l"

	.string "Let me know when you get here!$"


Matchcall_Liz_Generic12::
	.string  "Hi, TANIA. How are you?\n"
	.string "This is {STR_VAR_1}.\l"

	.string "I'm fine, but I'm bored silly!\l"

	.string "Huh… Wrong number?\l"
	.string "Oops! Sorry!$"


Matchcall_Liz_Hangup::
	.string  "OK, I'll call you later!$"


Matchcall_Liz_Generic11::
	.string  "Listen, listen!\p"

	.string "I was listening to the radio in the\n"

	.string "RUINS OF ALPH when an odd broadcast\l"

	.string "suddenly cut it on the regular show.\l"

	.string "I wonder what it was.\l"
	.string "So strange!$"


Matchcall_Liz_Generic10::
	.string  "Listen, listen!\p"

	.string "Don't you think FALKNER of VIOLET\n"
	.string "GYM is cool and handsome?\p"

	.string "But they say his dad, who's out\n"

	.string "training on the road, is even more\l"

	.string "cool and handsome than FALKNER.\l"

	.string "I wish I could meet him!$"


Matchcall_Liz_Generic9::
	.string  "Listen, listen!\p"

	.string "Do you know EARL, the teacher\n"
	.string "who runs the {POKEMON} ACADEMY\l"
	.string "in VIOLET?\p"

	.string "I saw him doing pirouettes while he\n"

	.string "was running.\l"
	.string "It was wildly funny!$"


Matchcall_Liz_Generic8::
	.string "Listen, listen!\n"

	.string "I collect {POKEMON} plush dolls.\p"

	.string "But I can't seem to get a hold of a\n"

	.string "SURF PIKACHU DOLL.\l"
	.string "None of my friends have it.\l"

	.string "It must be totally rare!\p"

	.string "You could really brag about it if\n"
	.string "you had one.$"


Matchcall_Liz_Generic7::
	.string "Listen, listen!\n"

	.string "Do you know about MOOMOO MILK?\l"

	.string "You can buy it at MOOMOO FARM.\l"

	.string "It's supposed to be good for health\l"

	.string "and beauty.\l"
	.string "I really want to try some.\l"

	.string "I bet it's delicious!$"


Matchcall_Liz_Generic6::
	.string "Listen, listen!\p"

	.string "There's a {POKEMON} SALON in GOLDENROD\n"

	.string "that's run by two brothers.\p"

	.string "The older brother is good, but\n"

	.string "but the younger one really isn't.\p"

	.string "But sometimes the younger one does a\n"

	.string "better job than his brother.\p"

	.string "Every time I go, I have a hard time\n"

	.string "trying to decide whom I should use…$"


Matchcall_Liz_Generic5::
	.string "Listen, listen!\p"

	.string "GOLDENROD GYM's WHITNEY began\n"

	.string "battling only a little while ago!\p"

	.string "But the {POKEMON} LEAGUE chose her\n"
	.string "as a GYM LEADER!\l"

	.string "I bet she must be totally talented.$"


Matchcall_Liz_Generic4::
	.string "Listen, listen!\p"

	.string "Have you ever taken part in the\n"

	.string "Bug-Catching Contest at the\lNATIONAL PARK?\p"

	.string "I did once, but all I could catch\n"
	.string "was a CATERPIE.\l"

	.string "But guess what!\l"

	.string "I won with that CATERPIE.\l"
	.string "Isn't that great?$"


Matchcall_Liz_Generic3::
	.string "Listen, listen!\n"

	.string "I saw a beautiful {STR_VAR_2}!\l"

	.string "I wish I could become a beautiful\l"
	.string "{STR_VAR_2} too.$"


Matchcall_Liz_Generic2::
	.string "Listen, listen!\n"

	.string "Uh… Um… Whoops!\l"

	.string "I forgot what I was going to say!$"


Matchcall_Liz_Generic1::
	.string "Listen, listen!\n"

	.string "My {STR_VAR_2}…\l"
	.string "it… so pretty…\l"

	.string "and… giggle… so awesome…\l"
	.string "yes… but…\l"

	.string "very much… eeek!\l"
	.string "And… lovely…\l"

	.string "Just ravishing…\l"
	.string "Oh, too much!\l"

	.string "…Hug it… sleeping… That's right…\l"

	.string "pretty… sigh… So nice… Cute…\l"

	.string "…Oops! Look at the time!\l"
	.string "I chatted too long!\p"

	.string "I'm sorry I took so much of your\n"

	.string "time!\l"
	.string "I love chatting!$"


Matchcall_Liz_Remind_Rematch::
	.string  "I've got too much time on my hands!\n"

	.string "Let's battle right away!\l"

	.string "I'll be waiting on {STR_VAR_2}!$"


Matchcall_Parry_Answer::
	.string  "Yup, yup!\n"
	.string "It's {STR_VAR_1}!\l"

	.string "Hah, and here's {PLAYER}!$"


Matchcall_Parry_Call_Morn::
	.string  "{PLAYER}, it's {STR_VAR_1}!\n"

	.string "Have you had a proper breakfast?$"


Matchcall_Parry_Call_Day::
	.string  "{PLAYER}, it's {STR_VAR_1}!\n"

	.string "Have you had a proper lunch?$"


Matchcall_Parry_Call_Night::
	.string  "{PLAYER}, it's {STR_VAR_1}!\n"

	.string "Have you had a proper dinner?$"


Matchcall_Parry_Generic5::
	.string  "Are your {POKEMON} looking good?\p"

	.string "My {STR_VAR_2} and me, we're\n"
	.string "looking mighty dandy!\l"
	.string "Hahahah!$"


Matchcall_Parry_Generic4::
	.string  "Nothing can match my {STR_VAR_2} now.$"


Matchcall_Parry_Generic3::
	.string  "Yeah, we KO'd a wild {STR_VAR_2}!\n"

	.string "That was OK, but I wanted to get it…$"


Matchcall_Parry_Generic2::
	.string  "And yesterday, we spotted a wild\n"

	.string "{STR_VAR_2}.\p"
	.string "We were debating whether to catch it\n"
	.string "or beat it.\p"

	.string "When along came another guy who\ncaught it!\l"
	.string "How about that!$"


Matchcall_Parry_Rematch::
	.string  "You're thinking you'd like to battle me.\n"

	.string "Am I right or what?\l"

	.string "Yep! We'll meet on {STR_VAR_2}!\l"


Matchcall_Parry_Hangup::
	.string  "OK, give me a call again!$"


Matchcall_Parry_Generic1::
	.string  "You'll battle with me again, right?$"


Matchcall_Parry_Remind_Rematch::
	.string  "Haven't you gotten to {STR_VAR_2}?\p"

	.string "Waiting here isn't bad, but I'd sure\n"
	.string "like to battle!$"


Matchcall_Ralph_Answer::
	.string  "Yes? Ah, {PLAYER}.\p"

	.string "You're courteous enough to state\n"

	.string "your name when you call on the\l"
	.string "phone.$"

Matchcall_Ralph_Call::
	.string  "Hiya, it's Uncle {STR_VAR_1}.$"


Matchcall_Ralph_Generic5::
	.string  "Are you taking good care of your\n"

	.string "{POKEMON}?\l"
	.string "You have to be good to your partners!$"


Matchcall_Ralph_Generic4::
	.string  "I've been spending more time with\n"
	.string "my {STR_VAR_2} than I have with my\l"
	.string "kids.\l"

	.string "That's a bit sad, actually.$"


Matchcall_Ralph_Generic3::
	.string  "I just beat a wild {STR_VAR_2}.\p"

	.string "I told my kid, but he scoffed\n"
	.string "that he could do the same thing\l"

	.string "easily.\l"

	.string "Boy, has he gotten cocky…$"


Matchcall_Ralph_Generic2::
	.string  "Yesterday a wild {STR_VAR_2} slipped\n"

	.string "away from me, in front of my kid.\p"

	.string "I was feeling down about it until he\n"

	.string "shared his {POKE}BALLS with me.\l"

	.string "Hahah, that sure made my day!$"


Matchcall_Ralph_Rematch::
	.string  "What do you say to a battle with me?\n"

	.string "Good, you're going to do it!\l"

	.string "For a kid, you're quite agreeable.\l"

	.string "{STR_VAR_2} is the spot!$"


Matchcall_Ralph_Hangup::
	.string  "You call your mom sometimes too!$"


Matchcall_Ralph_Swarm::
	.string  "Listen, I… Yowch!\p"

	.string "Uh, sorry! See, QWILFISH are\n"

	.string "biting like there is no tomorrow\l"

	.string "over here on {STR_VAR_2}!\l"

	.string "Aiyee! Ouch!\l"
	.string "One jabbed me!\l"

	.string "Heh, they're some kind of feisty!\p"

	.string "{PLAYER}, you have to see this rare\n"

	.string "sight!\l"
	.string "Get ready to fish!$"


Matchcall_Ralph_Generic1::
	.string  "Yeah, I know.\n"

	.string "You're looking for rare {POKEMON}.\p"

	.string "Recently, all I've been catching are\n"
	.string "MAGIKARP, though…$"


Matchcall_Ralph_Remind_Rematch::
	.string  "So where are you?\p"
	.string "I'm waiting for you to show up\n"
	.string "on {STR_VAR_2}.\l"

	.string "You shouldn't make your elders wait!$"


Matchcall_Ralph_Remind_Swarm::
	.string  "Hey, what's the matter with you?\p"

	.string "Aren't you coming over to fish for\n"
	.string "QWILFISH?\l"

	.string "I'm on {STR_VAR_2}, so hurry up!$"


Matchcall_Reena_Answer::
	.string  "Hello, this is {STR_VAR_1}…\n"

	.string "Oh. Hi, {PLAYER}.\l"
	.string "What's up?$"

Matchcall_Reena_Call::
	.string  "You're slow!\n"
	.string "Hurry up and answer!\l"

	.string "It's me, {STR_VAR_1}!$"


Matchcall_Reena_Generic5::
	.string  "Hey, how are your {POKEMON} doing?\n"

	.string "What? Great?\l"
	.string "I see…\l"

	.string "What? My {POKEMON}?\l"

	.string "Of course they're doing great!\l"

	.string "What kind of a question is that?$"


Matchcall_Reena_Generic4::
	.string  "Listen, dear…\n"

	.string "Do you recall my {STR_VAR_2}?\l"

	.string "Yes, exactly. That lovely {STR_VAR_2}.\p"

	.string "Wouldn't you agree it's a perfect\n"
	.string "match for me?$"


Matchcall_Reena_Generic3::
	.string  "Have I ever faced a wild {STR_VAR_2}?\n"

	.string "You need to ask?\p"

	.string "{STR_VAR_2} I've beaten on numerous\n"
	.string "occasions!$"


Matchcall_Reena_Generic2::
	.string  "Have I ever failed to catch a wild\n"
	.string "{POKEMON}?\l"

	.string "You need to ask?\p"

	.string "I would never fail to catch a wild\n"

	.string "{STR_VAR_2}…\l"
	.string "Oh! Never mind!$"


Matchcall_Reena_Rematch::
	.string  "We are going to battle\n"

	.string "The place shall be {STR_VAR_2}!\l"

	.string "Don't make me wait! Got it?$"


Matchcall_Reena_Hangup::
	.string  "Fine, you may go.$"


Matchcall_Reena_Generic1::
	.string  "Don't be too proud just because you\n"

	.string "happened to beat me…\l"

	.string "It was a fluke!$"


Matchcall_Reena_Remind_Rematch::
	.string  "What are you doing?\p"

	.string "I told you that the place was\n"

	.string "{STR_VAR_2}!\l"
	.string "Don't try to run!$"


Matchcall_Tiffany_Answer_Morn::
	.string  "Yes? This is {STR_VAR_1}.\n"

	.string "Oh, {PLAYER}.\l"
	.string "Good morning.$"


Matchcall_Tiffany_Answer_Day::
	.string  "Yes? This is {STR_VAR_1}.\n"

	.string "Oh, {PLAYER}.\l"
	.string "Hello.$"


Matchcall_Tiffany_Answer_Night::
	.string  "Yes? This is {STR_VAR_1}.\n"

	.string "Oh, {PLAYER}.\l"
	.string "Good evening.$"


Matchcall_Tiffany_Call_Morn::
	.string  "Is this {PLAYER}?\n"

	.string "Good morning.\l"
	.string "This is {STR_VAR_1}.$"


Matchcall_Tiffany_Call_Day::
	.string  "Is this {PLAYER}?\n"

	.string "Hi, it's {STR_VAR_1}.$"


Matchcall_Tiffany_Call_Night::
	.string  "Is this {PLAYER}?\n"

	.string "Good evening. This is {STR_VAR_1}.$"


Matchcall_Tiffany_Generic5::
	.string  "Are your {POKEMON} doing well?\n"

	.string "I hope you take them to a {POKEMON}\l"
	.string "CENTER every day.\l"

	.string "Don't push them too hard.\p"

	.string "My {STR_VAR_2} is cute and lively\n"

	.string "precisely because I take it to a\l"

	.string "{POKEMON} CENTER every day.$"


Matchcall_Tiffany_Generic4::
	.string  "My {STR_VAR_2}'s adorable, don't\n"
	.string "you think so?\p"
	.string "I always sleep with it, it's\n"

	.string "so fluffy and warm!$"


Matchcall_Tiffany_Generic3::
	.string  "Oh, and we had to battle a wild\n"

	.string "{STR_VAR_2} a while ago…\l"

	.string "My {STR_VAR_3} came close to fainting!\l"

	.string "Isn't that awful?\l"

	.string "I hate those nasty {STR_VAR_2}!$"

Matchcall_Tiffany_Generic2::
	.string  "Oh, and we had to battle a wild\n"

	.string "{STR_VAR_2} a while ago…\p"

	.string "My {STR_VAR_3} got frightened,\n"

	.string "so we ran away as fast as we could!\p"

	.string "I just can't help feeling protective\n"
	.string "of my {STR_VAR_3}.$"


Matchcall_Tiffany_Rematch::
	.string  "I know this might surprise you,\n"
	.string "but would you like to battle?\p"

	.string "I'll be waiting with CLEFAIRY on\n{STR_VAR_2}.$"


Matchcall_Tiffany_Generic1::
	.string "{PLAYER}!\n"

	.string "It's awful.\l"
	.string "My {STR_VAR_2}…\l"

	.string "Huh? {PLAYER}?\l"

	.string "Oh, sorry!\l"
	.string "I was in a hurry, and I…\l"

	.string "I have to go!\l"
	.string "Bye-bye!$"


Matchcall_Tiffany_Hangup::
	.string  "Bye-bye!$"


Matchcall_Tiffany_Gift::
	.string  "I bought some cute scarves at GOLDENROD\n"
	.string "DEPT.STORE for my CLEFAIRY.\p"

	.string "I got too many, so I'll give you\n"
	.string "one!\l"

	.string "Come collect it on {STR_VAR_2}.$"


Matchcall_Tiffany_Generic6::
	.string  "I love dressing up my CLEFAIRY!$"


Matchcall_Tiffany_Remind_Battle::
	.string  "What's wrong?\n"
	.string "Can't you visit?\l"

	.string "CLEFAIRY got tired and fell asleep.\l"

	.string "I'm not sure if I can wake it up…\l"

	.string "Please hurry to {STR_VAR_2}!$"


Matchcall_Tiffany_Remind_Gift::
	.string  "What's wrong?\n"
	.string "Can't you visit?\p"

	.string "I'm sure this will look good on your\n"
	.string "CLEFAIRY.\l"

	.string "Please hurry to {STR_VAR_2}!$"


Matchcall_Tully_Answer_Morn::
	.string  "Hello, this is {STR_VAR_1}…\n"

	.string "Oh, Good morning, {PLAYER}.$"


Matchcall_Tully_Answer_Day::
	.string  "Hello, this is {STR_VAR_1}…\n"


	.string "That voice…\l"
	.string "{PLAYER}, right?$"


Matchcall_Tully_Answer_Night::
	.string  "Hello, this is {STR_VAR_1}…\n"


	.string "This must be {PLAYER}!$"


Matchcall_Tully_Call_Morn::
	.string  "Hello! {STR_VAR_1} here…\n"

	.string "Good morning! The weather's great!$"


Matchcall_Tully_Call_Day::
	.string  "Hello! {STR_VAR_1} here…\n"


	.string "What a perfect day for fishing!$"


Matchcall_Tully_Call_Night::
	.string  "Hello! {STR_VAR_1} here…\n"


	.string "It's a great night for fishing!$"


Matchcall_Tully_Generic5::
	.string  "How's your trip coming along?\n"

	.string "I can't complain about my fishing!$"


Matchcall_Tully_Generic4::
	.string  "My {STR_VAR_2} has grown again.\p"

	.string "It was only about so big when I\n"

	.string "caught it, but now it's way bigger.$"


Matchcall_Tully_Generic3::
	.string  "Oh yeah, I KO'd a wild {STR_VAR_2}.\n"

	.string "It was huge, like this big even.\p"

	.string "Heh, I guess you can't tell over\n"
	.string "the phone…$"


Matchcall_Tully_Generic2::
	.string  "Oh yeah, I lost a wild {STR_VAR_2}.\n"

	.string "It was huge, like this big even.\l"

	.string "Heh, I guess you can't tell\l"
	.string "over the phone…$"


Matchcall_Tully_Rematch::
	.string  "We should get a battle going!\n"

	.string "I'll be fishing on {STR_VAR_2}.\l"

	.string "Swing by if you have the time.$"


Matchcall_Tully_Hangup::
	.string  "Well, I'll be seeing you.$"


Matchcall_Tully_Gift::
	.string  "I picked up a good little thing at\n"
	.string "the water's edge.\l"

	.string "Like I promised, it's yours.\l"

	.string "I'll be waiting on {STR_VAR_2}.$"


Matchcall_Tully_Generic1::
	.string  "Have I found anything good?\n"

	.string "Nope, not yet.\l"

	.string "It's like fishing, you need patience.$"


Matchcall_Tully_Remind_Rematch::
	.string  "Yup, {STR_VAR_1} here…\n"

	.string "{PLAYER}? What?\l"
	.string "You're lost?\l"

	.string "Our battle will be on {STR_VAR_2}.$"


Matchcall_Tully_Remind_Gift::
	.string  "I've got something good for you.\n"

	.string "Hustle over to {STR_VAR_2}.$"


Matchcall_Vance_Answer_Morn::
	.string  "Yes, hello? {STR_VAR_1} here!\n"

	.string "Morning, {PLAYER}!\l"

	.string "Are you using bird {POKEMON}?$"


Matchcall_Vance_Answer_Day::
	.string  "Yes, hello? {STR_VAR_1} here!\n"


	.string "Hi, {PLAYER}!\l"

	.string "Are your bird {POKEMON} flying?$"


Matchcall_Vance_Answer_Night::
	.string  "Yes, hello? {STR_VAR_1} here!\n"


	.string "Evening, {PLAYER}!\p"
	.string "Are you letting your bird {POKEMON}\n"
	.string "see some action?$"


Matchcall_Vance_Call_Morn::
	.string  "Good morning, {PLAYER}!\n"

	.string "It's {STR_VAR_1}!\l"
	.string "Good morning!$"


Matchcall_Vance_Call_Day::
	.string  "Hi, {PLAYER}!\n"

	.string "It's {STR_VAR_1}!\l"

	.string "Remember me?$"


Matchcall_Vance_Call_Night::
	.string  "Good evening, {PLAYER}!\n"

	.string "It's {STR_VAR_1}!\l"

	.string "Are you free now?$"


Matchcall_Vance_Generic5::
	.string  "Are you and your {POKEMON} fine?\p"

	.string "My {STR_VAR_2} looks like it will\n"

	.string "get tough enough to face and beat\l"

	.string "the legendary bird {POKEMON}!$"


Matchcall_Vance_Generic4::
	.string  "My {STR_VAR_2}'s become tougher.\n"

	.string "We've achieved liftoff!$"


Matchcall_Vance_Generic3::
	.string  "We can easily beat {STR_VAR_2}!\n"

	.string "…Huh? You too?\l"
	.string "Isn't that great?$"


Matchcall_Vance_Generic2::
	.string  "But get this, a wild {STR_VAR_2}\n"
	.string "just barely eluded us.$"

	.string "I wanted to FLY after it…$"


Matchcall_Vance_Rematch::
	.string  "Right now, I'm on {STR_VAR_2}.\n"

	.string "You know, where I first met you?\l"

	.string "Want to battle?\l"
	.string "I'll wait here.$"


Matchcall_Vance_Hangup::
	.string  "OK, bye for now!$"


Matchcall_Vance_Generic1::
	.string  "I'll be looking forward to our next\nbattle!$"


Matchcall_Vance_Remind_Rematch::
	.string  "Oh, {PLAYER}!\n"
	.string "Hurry, hurry!\l"

	.string "{STR_VAR_2}!\l"
	.string "FLY over now!$"


Matchcall_Wade_Answer_Morn::
	.string  "Hello? This is {STR_VAR_1} speaking.\n"

	.string "Oh. Hi, {PLAYER}!\l"
	.string "Good morning!$"


Matchcall_Wade_Answer_Day::
	.string  "Hello? This is {STR_VAR_1} speaking.\n"

	.string "Oh. Hi, {PLAYER}!$"


Matchcall_Wade_Answer_Night::
	.string  "Hello? This is {STR_VAR_1} speaking.\n"

	.string "Oh. Hi, {PLAYER}!\l"
	.string "Good evening!$"


Matchcall_Wade_Call_Morn::
	.string  "{PLAYER}, good morning!\n"

	.string "It's me, {STR_VAR_1}.\l"
	.string "Isn't it nice out?$"


Matchcall_Wade_Call_Day::
	.string  "{PLAYER}, howdy!\n"

	.string "It's me, {STR_VAR_1}.\l"
	.string "Isn't it nice out?$"


Matchcall_Wade_Call_Night::
	.string  "Good evening, {PLAYER}!\n"

	.string "It's me, {STR_VAR_1}.\l"
	.string "Were you awake?$"


Matchcall_Wade_Generic5::
	.string  "How are your {POKEMON} doing?\p"

	.string "My {POKEMON} have too much energy\nto burn.\l"

	.string "It gets to be a problem.\p"

	.string "Of all my {POKEMON}, {STR_VAR_2}\n"
	.string "is the hardest to handle.\l"

	.string "Working with it is exhausting.$"


Matchcall_Wade_Generic4::
	.string  "Are your {POKEMON} growing?\p"

	.string "My {POKEMON} are growing a bit too\n"

	.string "quickly for me.\l"
	.string "It's overwhelming!\l"

	.string "{STR_VAR_2}'s growing especially quickly.\l"

	.string "I think it'll get tough.$"


Matchcall_Wade_Generic3::
	.string  "Oh yeah, we KO'd a wild {STR_VAR_2}\n"
	.string "with one hit a while back.\p"

	.string "It went down so easily, I felt a\n"
	.string "little sorry for the poor thing.$"


Matchcall_Wade_Generic2::
	.string  "Oh yeah, a wild {STR_VAR_2} got\n"

	.string "away from me at the last second.\l"

	.string "I know it's a common {POKEMON}…\p"

	.string "But it does annoy me that it got away\n"

	.string "when I almost had it.$"


Matchcall_Wade_Rematch::
	.string  "Do you feel like a {POKEMON} battle?\n"

	.string "It won't be like last time!\l"

	.string "{STR_VAR_2}'s where I'll be.\l"

	.string "Let me know when you get there.$"


Matchcall_Wade_Hangup::
	.string  "See you later!$"

Matchcall_Wade_Gift::
	.string  "I found all kinds of BERRIES.\n"
	.string "If you want, I'll share some with you.\l"

	.string "I'll be waiting on {STR_VAR_2}.$"


Matchcall_Wade_Generic1::
	.string  "Huh? BERRIES?\n"

	.string "Sorry, I haven't found any yet.\l"

	.string "I'll call you if I find any.\l"
	.string "Will you please wait?$"


Matchcall_Wade_Remind_Rematch::
	.string  "Let's battle already!\n"

	.string "{STR_VAR_2} is where I am.\l"

	.string "Please get here as soon as you can!$"


Matchcall_Wade_Remind_Gift::
	.string  "How come you're not here yet?\n"

	.string "{STR_VAR_2} is where I am.\l"

	.string "Please get here as soon as you can!$"


Matchcall_Wilton_Answer_Morn::
	.string  "Hello, you have reached {STR_VAR_1}…\n"

	.string "Ah, {PLAYER}.$"


Matchcall_Wilton_Answer_Day::
	.string  "Hello, you have reached {STR_VAR_1}…\n"


	.string "Ah, {PLAYER}, is it?$"


Matchcall_Wilton_Answer_Night::
	.string  "Hello, you have reached {STR_VAR_1}…\n"


	.string "Ah, if it isn't {PLAYER}.$"


Matchcall_Wilton_Call_Morn::
	.string  "Ah, it's {STR_VAR_1}…\n"

	.string "Have you got a moment?$"


Matchcall_Wilton_Call_Day::
	.string  "Ah, it's {STR_VAR_1}…\n"


	.string "Can you talk now?$"


Matchcall_Wilton_Call_Night::
	.string  "Ah, it's {STR_VAR_1}…\n"


	.string "Sorry for calling so late.$"


Matchcall_Wilton_Generic2::
	.string  "Have your {POKEMON} grown any?\n"

	.string "My {STR_VAR_2} has grown quite a bit.$"


Matchcall_Wilton_Generic5::
	.string  "My {STR_VAR_2}'s grown impressive!\n"

	.string "My fishing skills have improved too!$"


Matchcall_Wilton_Generic4::
	.string  "We beat a wild {STR_VAR_2}…\p"

	.string "You know, I have more fun fishing\n"

	.string "than beating wild {POKEMON}.$"


Matchcall_Wilton_Generic3::
	.string  "But a while back, we came this close\n"
	.string "to landing a wild {STR_VAR_2}.\l"

	.string "I tell you, it was huge. Believe me.$"


Matchcall_Wilton_Rematch::
	.string  "I'm fishing on {STR_VAR_2}, but\n"

	.string "nothing's biting today.\p"

	.string "Help me while my time away, come\n"
	.string "over for a battle.$"


Matchcall_Wilton_Hangup::
	.string  "All right, later.$"


Matchcall_Wilton_Gift::
	.string  "I snagged an item while fishing.\n"

	.string "Come pick it up on {STR_VAR_2}.$"


Matchcall_Wilton_Generic1::
	.string  "Nah, I haven't found anything that's\n"

	.string "worth your time.\l"

	.string "You have to have patience.$"


Matchcall_Wilton_Remind_Rematch::
	.string  "Sigh…\p"
	.string "They're not biting like before on\n"
	.string "{STR_VAR_2}…\l"

	.string "You have to come for a battle!$"


Matchcall_Wilton_Remind_Gift::
	.string  "Don't you want this item?\n"

	.string "Hah? You don't know where?\l"

	.string "{STR_VAR_2}…\p"
	.string "Just head from MAHOGANY toward\n"
	.string "BLACKTHORN!$"

Matchcall_Todd_Answer_Morn::
	.string "Yes? This is {STR_VAR_1} speaking.\n"


	.string "Hey, {PLAYER}!$"


Matchcall_Todd_Answer_Day::
	.string "Yes? This is {STR_VAR_1} speaking.\n"


	.string "This must be {PLAYER}.$"


Matchcall_Todd_Answer_Night::
	.string "Yes? This is {STR_VAR_1} speaking.\n"

	.string "Ah, {PLAYER}!$"


Matchcall_Todd_Call_Morn::
	.string "Hello, this is {STR_VAR_1}.\n"

	.string "{PLAYER}, right?$"


Matchcall_Todd_Call_Day::
	.string "Hello, this is {STR_VAR_1}.\n"

	.string "{PLAYER}, what are you doing?$"


Matchcall_Todd_Call_Night::
	.string "Hello, this is {STR_VAR_1}.\n"

	.string "{PLAYER}, sorry to call you so late.$"


Matchcall_Todd_Generic1::
	.string "How do you raise your {POKEMON}?\p"

	.string "I do all sorts of things, like\n"
	.string "leaving them in DAY-CARE and\l"
	.string "toughening them up with items.$"


Matchcall_Todd_Generic2::
	.string "My {STR_VAR_2} is looking more\n"
	.string "and more like me.\l"
	.string "It's getting cuter!$"


Matchcall_Todd_Generic3::
	.string "And, you know?\n"

	.string "Now we can KO {STR_VAR_2} easily.\p"

	.string "I should challenge the GOLDENROD\nGYM.$"


Matchcall_Todd_Generic4::
	.string "And, you know?\p"
	.string "We just failed to beat {STR_VAR_2}\n"
	.string	"by a tiny margin.\p"

	.string "I'm guessing my {POKEMON}'s levels\n"

	.string "aren't high enough yet…$"


Matchcall_Todd_Rematch::
	.string "You must be a lot better now, huh?\n"

	.string "How about showing me your technique\l"

	.string "in a real battle with me?\l"

	.string "I'll be waiting on {STR_VAR_2}.$"


Matchcall_Todd_Hangup::
	.string "See you later!$"

Matchcall_Todd_Generic5::
	.string "I'm saving up for the next bargain sale\n"

	.string "When's the next one?$"


Matchcall_Todd_Remind_Rematch::
	.string "Where are you?\n"

	.string "Let's have our battle soon!\l"

	.string "I'll be waiting on {STR_VAR_2}.$"

