gText_SetClock_WokeMeUp::
	.string "………………………………………………\n"
	.string "………………………………………………\p"
	.string "Zzz… Hm? Wha…?\n"
	.string "You woke me up!\p"
	.string "Will you check the clock for me?$"

gText_Oak_Welcome:: @ 82C897B
	.string "Hello! Sorry to keep you waiting!\p"
	.string "Welcome to the world of {POKEMON}!\p"
	.string "My name is OAK.\p"
	.string "People affectionately refer to me\n"
	.string "as the {POKEMON} PROFESSOR.\p"
	.string "$"

gText_Oak_Pokemon::
	.string "This world…$"

gText_Oak_Pokemon2::
	.string "…is inhabited far and wide by\n"
	.string "creatures that we call {POKEMON}.\p"
	.string "$"

gText_Oak_MainSpeech::
	.string "People and {POKEMON} live together by\n"
	.string "supporting each other.\p"
	.string "Some people play with {POKEMON},\n"
	.string "some battle with them.\p"
	.string "$"

gText_Oak_MainSpeech2::
	.string "But despite this, we don't know\n"
	.string "everything about {POKEMON} yet.\p"
	.string "There are still many mysteries\n"
	.string "surrounding them to solve.\p"
	.string "That's why I study {POKEMON} as a\n"
	.string "profession every day.\p"
	.string "Now, enough about me.\n"
	.string "Tell me a little about yourself.\p"
	.string "$"

gText_Oak_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Oak_WhatsYourName::
	.string "Now, what did you say your name\n"
	.string "was again?\p"
	.string "$"

gText_Oak_SoItsPlayer::
	.string "Right…\n"
	.string "So your name is {PLAYER}.$"

gText_Oak_AreYouReady::
	.string "{PLAYER}, are you ready?\p"
	.string "Your very own {POKEMON} story is\n"
	.string "about to unfold.\p"
	.string "You'll face fun times and tough\n"
	.string "challenges.\p"
	.string "A world of dreams and adventures\n"
	.string "with {POKEMON} awaits! Let's go!\p"
	.string "I'll be seeing you later!$"
