Text_Pokegear_Mom_Start::
	.string "Hello?\n"
	.string "Oh, hi, {PLAYER}!\p"
	.string "Wasn't PROF. ELM waiting for you?$"

Text_Pokegear_Mom_GotMon::
	.string "Hello?\n"
	.string "Oh, hi, {PLAYER}!\p"
	.string "You're on a big mission for\n"
	.string "PROF. ELM? Be good!$"

Text_Pokegear_Mom_GaveEggToElm::
	.string "Hello?\n"
	.string "Oh, hi, {PLAYER}!\p"
	.string "If you're done with your errand,\n"
	.string "come on home, dear.$"

Text_Pokegear_Mom_PhoneBankingPlaceholder::
	.string "Hello?\n"
	.string "…… {PLAYER}?\p"
	.string "I heard from PROF. ELM that you\n"
	.string "went on a long trip.\p"
	.string "I wish you would have told me…\p"
	.string "What about money?\n"
	.string "Do you want me to save it?\p"
	.string "…insert yesno box here…\p"
	.string "Okay. I'll save your money.\p"
	.string "Okay. I won't save your money.\p"
	.string "{PLAYER}, keep it up!\n"
	.string "I'm rooting for you, baby!$"

Text_Pokegear_Mom_RegularCallPlaceholder::
	.string "Hello?\n"
	.string "Oh, hi, {PLAYER}! Working hard?\p"
	.string "…insert location stuff here…\p"
	.string "…insert money stuff here…\p"
	.string "{PLAYER}, keep it up!\n"
	.string "I'm rooting for you, baby!$"

Text_Pokegear_Elm_Start::
	.string "Hello, {PLAYER}?\n"
	.string "Try not to overdo it.\p"
	.string "Be sure to heal your POKéMON if\n"
	.string "they are hurt.$"

Text_Pokegear_Elm_SawMrPokemon::
	.string "Hello, {PLAYER}?\n"
	.string "Did you meet MR. POKéMON?\p"
	.string "Great!\n"
	.string "Come back safely!$"

Text_Pokegear_Elm_MonWasStolen::
	.string "{PLAYER}?\n"
	.string "I'm very upset right now.\p"
	.string "We had a POKéMON stolen from\n"
	.string "here. How could anyone do that?$"

Text_Pokegear_Elm_CheckingEgg::
	.string "Hello, {PLAYER}?\n"
	.string "We're checking the EGG now.\p"
	.string "It does appear to be a POKéMON\n"
	.string "EGG.$"
