gText_NurseIntro_Morning::
	.string "Good morning!\n"
	.string "Welcome to our {POKEMON} CENTER.\p$"

gText_NurseIntro_Day::
	.string "Hello!\n"
	.string "Welcome to our {POKEMON} CENTER.\p$"

gText_NurseIntro_Night::
	.string "Good evening! You're out late.\n"
	.string "Welcome to our {POKEMON} CENTER.\p$"

gText_NurseIntro_Common::
	.string "We can heal your {POKEMON} to\n"
	.string "perfect health.\p"
	.string "Shall we heal your {POKEMON}?$"

gText_IllTakeYourPkmn::
	.string "Okay, may I see your {POKEMON}?$"

gText_RestoredPkmnToFullHealth::
	.string "Thank you for waiting.\n"
	.string "Your {POKEMON} are fully healed.$"

gText_WeHopeToSeeYouAgain::
    .string "We hope to see you again!$"

gText_WelcomeCutShort::
	.string "Hello!\n"
	.string "Welcome to our {POKEMON} CENTER.\p"
	.string "We can heal your {POKEMON} to\n"
	.string "perfect health.\p"
	.string "Shall we…$"

gText_NoticesGoldCard::
    .string "Th-that card…\n"
    .string "Could it be… The GOLD CARD?!\p"
    .string "Oh, the gold color is brilliant!\n"
    .string "The four stars seem to sparkle!\p"
    .string "I've seen several TRAINERS with\n"
    .string "a SILVER CARD before, but, {PLAYER},\l"
    .string "you're the first TRAINER I've ever\l"
    .string "seen with a GOLD CARD!\p"
    .string "Okay, {PLAYER}, please allow me\n"
    .string "the honor of resting your {POKEMON}!$"

gText_YouWantTheUsual::
    .string "I'm delighted to see you, {PLAYER}!\n"
    .string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2::
    .string "Okay, I'll take your {POKEMON}\n"
    .string "for a few seconds.$"

gText_ThankYouForWaiting::
    .string "Thank you for waiting.$"

gText_WeHopeToSeeYouAgain2::
    .string "We hope to see you again!$"
