gText_NurseIntro_Morning::
	.string "Good morning!\n"
	.string "Welcome to our POKéMON CENTER.\p"
	.string "We can heal your POKéMON to\n"
	.string "perfect health.\p"
	.string "Shall we heal your POKéMON?$"

gText_NurseIntro_Day::
	.string "Hello!\n"
	.string "Welcome to our POKéMON CENTER.\p"
	.string "We can heal your POKéMON to\n"
	.string "perfect health.\p"
	.string "Shall we heal your POKéMON?$"

gText_NurseIntro_Night::
	.string "Good evening! You're out late.\n"
	.string "Welcome to our POKéMON CENTER.\p"
	.string "We can heal your POKéMON to\n"
	.string "perfect health.\p"
	.string "Shall we heal your POKéMON?$"

gText_IllTakeYourPkmn:: @ 8272768
	.string "Okay, may I see your POKéMON?$"

gText_RestoredPkmnToFullHealth:: @ 8272798
	.string "Thank you for waiting.\n"
	.string "Your POKéMON are fully healed.$"

gText_WeHopeToSeeYouAgain:: @ 82727DB
    .string "We hope to see you again!$"

gText_WelcomeCutShort:: @ 82727F5
	.string "Hello!\n"
	.string "Welcome to our POKéMON CENTER.\p"
	.string "We can heal your POKéMON to\n"
	.string "perfect health.\p"
	.string "Shall we…$"

gText_NoticesGoldCard:: @ 8272860
    .string "Th-that card…\n"
    .string "Could it be… The GOLD CARD?!\p"
    .string "Oh, the gold color is brilliant!\n"
    .string "The four stars seem to sparkle!\p"
    .string "I've seen several TRAINERS with\n"
    .string "a SILVER CARD before, but, {PLAYER},\l"
    .string "you're the first TRAINER I've ever\l"
    .string "seen with a GOLD CARD!\p"
    .string "Okay, {PLAYER}, please allow me\n"
    .string "the honor of resting your POKéMON!$"

gText_YouWantTheUsual:: @ 8272982
    .string "I'm delighted to see you, {PLAYER}!\n"
    .string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2:: @ 82729C0
    .string "Okay, I'll take your POKéMON\n"
    .string "for a few seconds.$"

gText_ThankYouForWaiting:: @ 82729F0
    .string "Thank you for waiting.$"

gText_WeHopeToSeeYouAgain2:: @ 8272A07
    .string "We hope to see you again!$"
