gPokedexRatingText_AreYouCurious:: @ 82A5C9C
	.string "OAK: Good to see you!\n"
	.string "How is your POKéDEX coming along?\p"
	.string "Here, let me take a look.$"

gPokedexRatingText_SoYouveSeenAndCaught:: @ 82A5D2C
	.string "The amount of progress you've made\n"
	.string "on your POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.\p"
	.string "PROF. OAK's rating:$"

gPokedexRatingText_LessThan10:: @ 82A5D6C
	.string "Go into every patch of grass you\n"
	.string "see and look for POKéMON!$"

gPokedexRatingText_LessThan20:: @ 82A5DAB
	.string "Good work. I see you understand\n"
	.string "the basics of using POKé BALLS.$"

gPokedexRatingText_LessThan35:: @ 82A5DF1
	.string "You're getting good at filling\n"
	.string "your POKéDEX.\p"
	.string "However, you still have a long way\n"
	.string "to go until completion.$"

gPokedexRatingText_LessThan50:: @ 82A5E34
	.string "You need to give it your all to\n"
	.string "fill up the POKéDEX.\p"
	.string "Go and catch many different kinds\n"
	.string "of POKéMON!$"

gPokedexRatingText_LessThan65:: @ 82A5E83
	.string "It's apparent that you're trying--\n"
	.string "I can see that.\p"
	.string "Your POKéDEX looks like it's starting\n"
	.string "to come together.$"

gPokedexRatingText_LessThan80:: @ 82A5EB9
	.string "To evolve, some POKéMON grow.\n"
	.string "Others use the effects of STONES.$"

gPokedexRatingText_LessThan95:: @ 82A5EF4
	.string "Have you gotten yourself a fishing\n"
	.string "ROD, by any chance?\p"
	.string "You can catch a variety of POKéMON\n"
	.string "by fishing in bodies of water.$"

gPokedexRatingText_LessThan110:: @ 82A5F39
	.string "Excellent! You seem to like\n"
	.string "collecting things!$"

gPokedexRatingText_LessThan125:: @ 82A5F82
	.string "Some POKéMON only appear during\n"
	.string "certain times of the day.$"

gPokedexRatingText_LessThan140:: @ 82A5FB9
	.string "Your POKéDEX is filling up.\n"
	.string "Keep up the good work!$"

gPokedexRatingText_LessThan155:: @ 82A6018
	.string "I'm impressed. You're evolving\n"
	.string "POKéMON, not just catching them.$"

gPokedexRatingText_LessThan170:: @ 82A6061
	.string "Have you met KURT of AZALEA TOWN?\n"
	.string "His custom BALLS should help.$"

gPokedexRatingText_LessThan185:: @ 82A609C
	.string "Wow. You've found more POKéMON than\n"
	.string "the last POKéDEX research project.$"

gPokedexRatingText_LessThan200:: @ 82A60D5
	.string "Are you trading your POKéMON with\n"
	.string "other TRAINERS?\p"
	.string "It's tough to do this alone!$"

gPokedexRatingText_LessThan215:: @ 82A6124
	.string "Wow! You've hit 200 species!\n"
	.string "Your POKéDEX is looking great!$"

gPokedexRatingText_LessThan230:: @ 82A616F
	.string "Magnificent! You could become a\n"
	.string "POKéMON PROFESSOR right now!$"

gPokedexRatingText_LessThan249:: @ 82A61D6
	.string "Your POKéDEX is amazing!\n"
	.string "You're ready to turn professional!$"

gPokedexRatingText_DexCompleted:: @ 82A623A
	.string "Whoa! A perfect POKéDEX!\n"
	.string "I've dreamt about this!\p"
	.string "Congratulations!!$"

gPokedexRatingText_OnANationwideBasis:: @ 82A633D
	.string "And your NATIONAL POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.$"

PokedexRating_Text_LookForwardToFilledNationalDex:: @ 81A71EE
	.string "I'll be looking forward to seeing\n"
	.string "you fill the NATIONAL POKéDEX!$"

PokedexRating_Text_YouveCompletedDex:: @ 81A722F
	.string "Finally…\p"
	.string "You've finally completed the\n"
	.string "POKéDEX!\p"
	.string "It's magnificent!\n"
	.string "Truly, this is a fantastic feat!$"
