gPokedexRatingText_AreYouCurious::
	.string "OAK: Good to see you!\n"
	.string "How is your {POKEDEX} coming along?\p"
	.string "Here, let me take a look.$"

gPokedexRatingText_SoYouveSeenAndCaught::
	.string "The amount of progress you've made\n"
	.string "on your {POKEDEX} is:\p"
	.string "{STR_VAR_1} {POKEMON} seen and\n"
	.string "{STR_VAR_2} {POKEMON} owned.\p"
	.string "PROF. OAK's rating:$"

gPokedexRatingText_LessThan10::
	.string "Go into every patch of grass you\n"
	.string "see and look for {POKEMON}!$"

gPokedexRatingText_LessThan20::
	.string "Good work. I see you understand\n"
	.string "the basics of using {POKE} BALLS.$"

gPokedexRatingText_LessThan35::
	.string "You're getting good at filling\n"
	.string "your {POKEDEX}.\p"
	.string "However, you still have a long way\n"
	.string "to go until completion.$"

gPokedexRatingText_LessThan50::
	.string "You need to give it your all to\n"
	.string "fill up the {POKEDEX}.\p"
	.string "Go and catch many different kinds\n"
	.string "of {POKEMON}!$"

gPokedexRatingText_LessThan65::
	.string "It's apparent that you're trying--\n"
	.string "I can see that.\p"
	.string "Your {POKEDEX} looks like it's starting\n"
	.string "to come together.$"

gPokedexRatingText_LessThan80::
	.string "To evolve, some {POKEMON} grow.\n"
	.string "Others use the effects of STONES.$"

gPokedexRatingText_LessThan95::
	.string "Have you gotten yourself a fishing\n"
	.string "ROD, by any chance?\p"
	.string "You can catch a variety of {POKEMON}\n"
	.string "by fishing in bodies of water.$"

gPokedexRatingText_LessThan110::
	.string "Excellent! You seem to like\n"
	.string "collecting things!$"

gPokedexRatingText_LessThan125::
	.string "Some {POKEMON} only appear during\n"
	.string "certain times of the day.$"

gPokedexRatingText_LessThan140::
	.string "Your {POKEDEX} is filling up.\n"
	.string "Keep up the good work!$"

gPokedexRatingText_LessThan155::
	.string "I'm impressed. You're evolving\n"
	.string "{POKEMON}, not just catching them.$"

gPokedexRatingText_LessThan170::
	.string "Have you met KURT of AZALEA TOWN?\n"
	.string "His custom BALLS should help.$"

gPokedexRatingText_LessThan185::
	.string "Wow. You've found more {POKEMON} than\n"
	.string "the last {POKEDEX} research project.$"

gPokedexRatingText_LessThan200::
	.string "Are you trading your {POKEMON} with\n"
	.string "other TRAINERS?\p"
	.string "It's tough to do this alone!$"

gPokedexRatingText_LessThan215::
	.string "Wow! You've hit 200 species!\n"
	.string "Your {POKEDEX} is looking great!$"

gPokedexRatingText_LessThan230::
	.string "Magnificent! You could become a\n"
	.string "{POKEMON} PROFESSOR right now!$"

gPokedexRatingText_LessThan249::
	.string "Your {POKEDEX} is amazing!\n"
	.string "You're ready to turn professional!$"

gPokedexRatingText_DexCompleted::
	.string "Whoa! A perfect {POKEDEX}!\n"
	.string "I've dreamt about this!\p"
	.string "Congratulations!!$"

gPokedexRatingText_OnANationwideBasis::
	.string "And your NATIONAL {POKEDEX} is:\p"
	.string "{STR_VAR_1} {POKEMON} seen and\n"
	.string "{STR_VAR_2} {POKEMON} owned.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "I'll be looking forward to seeing\n"
	.string "you fill the NATIONAL {POKEDEX}!$"

PokedexRating_Text_YouveCompletedDex::
	.string "Finally…\p"
	.string "You've finally completed the\n"
	.string "{POKEDEX}!\p"
	.string "It's magnificent!\n"
	.string "Truly, this is a fantastic feat!$"
