EcruteakCity_House1_MapScripts::
	.byte 0


EcruteakCity_House1_Eventscript_OldMan::
	msgbox EcruteakCity_House1_Eventscript_OldMan_Text_0, MSGBOX_NPC
	end


EcruteakCity_House1_Eventscript_Boy::
	msgbox EcruteakCity_House1_Eventscript_Boy_Text_0, MSGBOX_NPC
	end


EcruteakCity_House1_Eventscript_OldMan_Text_0:
	.string "This happened when I was young.\pThe sky suddenly turned black. A\ngiant flying POKéMON was blocking\lout the sun.\pI wonder what that POKéMON was?\nIt was like a bird and a dragon.$"

EcruteakCity_House1_Eventscript_Boy_Text_0:
	.string "Is there really a POKéMON that big?\nIf it exists, it must be powerful.$"
