Route41_MapScripts::
	.byte 0


Route41_Eventscript_SwimmerKaylee::
	trainerbattle_single TRAINER_KAYLEE, Route41_Eventscript_SwimmerKaylee_Text_0, Route41_Eventscript_SwimmerKaylee_Text_1
	msgbox Route41_Eventscript_SwimmerKaylee_Text_2, MSGBOX_AUTOCLOSE
	end


Route41_Eventscript_SwimmerCharlie::
	trainerbattle_single TRAINER_CHARLIE, Route41_Eventscript_SwimmerCharlie_Text_0, Route41_Eventscript_SwimmerCharlie_Text_1
	msgbox Route41_Eventscript_SwimmerCharlie_Text_2, MSGBOX_AUTOCLOSE
	end


Route41_Eventscript_SwimmerGeorge::
	trainerbattle_single TRAINER_GEORGE, Route41_Eventscript_SwimmerGeorge_Text_0, Route41_Eventscript_SwimmerGeorge_Text_1
	msgbox Route41_Eventscript_SwimmerGeorge_Text_2, MSGBOX_AUTOCLOSE
	end


Route41_Eventscript_SwimmerSusie::
	trainerbattle_single TRAINER_SUSIE, Route41_Eventscript_SwimmerSusie_Text_0, Route41_Eventscript_SwimmerSusie_Text_1
	msgbox Route41_Eventscript_SwimmerSusie_Text_2, MSGBOX_AUTOCLOSE
	end


Route41_Eventscript_SwimmerBerke::
	trainerbattle_single TRAINER_BERKE, Route41_Eventscript_SwimmerBerke_Text_0, Route41_Eventscript_SwimmerBerke_Text_1
	msgbox Route41_Eventscript_SwimmerBerke_Text_2, MSGBOX_AUTOCLOSE
	end


Route41_Eventscript_SwimmerKirk::
	trainerbattle_single TRAINER_KIRK, Route41_Eventscript_SwimmerKirk_Text_0, Route41_Eventscript_SwimmerKirk_Text_1
	msgbox Route41_Eventscript_SwimmerKirk_Text_2, MSGBOX_AUTOCLOSE
	end


Route41_Eventscript_SwimmerKara::
	trainerbattle_single TRAINER_KARA, Route41_Eventscript_SwimmerKara_Text_0, Route41_Eventscript_SwimmerKara_Text_1
	msgbox Route41_Eventscript_SwimmerKara_Text_2, MSGBOX_AUTOCLOSE
	end


Route41_Eventscript_SwimmerDenise::
	trainerbattle_single TRAINER_DENISE, Route41_Eventscript_SwimmerDenise_Text_0, Route41_Eventscript_SwimmerDenise_Text_1
	msgbox Route41_Eventscript_SwimmerDenise_Text_2, MSGBOX_AUTOCLOSE
	end


Route41_Eventscript_SwimmerMathew::
	trainerbattle_single TRAINER_MATHEW, Route41_Eventscript_SwimmerMathew_Text_0, Route41_Eventscript_SwimmerMathew_Text_1
	msgbox Route41_Eventscript_SwimmerMathew_Text_2, MSGBOX_AUTOCLOSE
	end


Route41_Eventscript_SwimmerWendy::
	trainerbattle_single TRAINER_WENDY, Route41_Eventscript_SwimmerWendy_Text_0, Route41_Eventscript_SwimmerWendy_Text_1
	msgbox Route41_Eventscript_SwimmerWendy_Text_2, MSGBOX_AUTOCLOSE
	end


Route41_Eventscript_SwimmerKaylee_Text_0:
	.string "I'm on my way to the WHIRL ISLANDS.\nI'm going exploring with friends.$"

Route41_Eventscript_SwimmerKaylee_Text_1:
	.string "Is that how you do it?$"

Route41_Eventscript_SwimmerKaylee_Text_2:
	.string "There's supposed to be a big POKéMON\ndeep beneath the WHIRL ISLANDS.\pI wonder what it could be?$"

Route41_Eventscript_SwimmerCharlie_Text_0:
	.string "The water's warm here.\nI'm loose and limber.\pSure, I'll take you on!$"

Route41_Eventscript_SwimmerCharlie_Text_1:
	.string "Yikes! I've got prune skin!$"

Route41_Eventscript_SwimmerCharlie_Text_2:
	.string "Isn't it relaxing just floating like\nthis?$"

Route41_Eventscript_SwimmerGeorge_Text_0:
	.string "I'm a bit tired.\nIf I win, lend me your POKéMON.$"

Route41_Eventscript_SwimmerGeorge_Text_1:
	.string "Pant, pant…$"

Route41_Eventscript_SwimmerGeorge_Text_2:
	.string "It's so far to CIANWOOD, but it's no\neasy return trip to OLIVINE either.\pWhat should I do?$"

Route41_Eventscript_SwimmerSusie_Text_0:
	.string "You look so elegant, riding your\nPOKéMON.$"

Route41_Eventscript_SwimmerSusie_Text_1:
	.string "I'm crushed…$"

Route41_Eventscript_SwimmerSusie_Text_2:
	.string "Wasn't there a hit song about a boy\nriding a LAPRAS?$"

Route41_Eventscript_SwimmerBerke_Text_0:
	.string "See those islands that are blocked\nby whirlpools?\pThere just has to be a secret inside!$"

Route41_Eventscript_SwimmerBerke_Text_1:
	.string "What's the secret to your strength?$"

Route41_Eventscript_SwimmerBerke_Text_2:
	.string "It was a dark and stormy night…\pI saw this giant POKéMON flying from\nthe islands.\pIt was scattering feathers from its\nsilver wings.$"

Route41_Eventscript_SwimmerKirk_Text_0:
	.string "The waves are wild here.\nThey tire you out while you swim.$"

Route41_Eventscript_SwimmerKirk_Text_1:
	.string "I'm beat!$"

Route41_Eventscript_SwimmerKirk_Text_2:
	.string "The currents keep me from reaching\nthat island.$"

Route41_Eventscript_SwimmerKara_Text_0:
	.string "If you need to rest, just tread\nwater.\pYou'll get your wind back so you can\nkeep on going strong.$"

Route41_Eventscript_SwimmerKara_Text_1:
	.string "Oh! You have more energy than I do.$"

Route41_Eventscript_SwimmerKara_Text_2:
	.string "I heard roars from deep inside the\nISLANDS.$"

Route41_Eventscript_SwimmerDenise_Text_0:
	.string "The weather is so beautiful, I'm in\na daze!$"

Route41_Eventscript_SwimmerDenise_Text_1:
	.string "Ohhh!$"

Route41_Eventscript_SwimmerDenise_Text_2:
	.string "A sunburn is the worst for skin, but\nI don't use sunblock.\pI won't pollute the water.$"

Route41_Eventscript_SwimmerMathew_Text_0:
	.string "Are you seeking the secrets of the\nWHIRL ISLANDS?$"

Route41_Eventscript_SwimmerMathew_Text_1:
	.string "Ooh, you've got great endurance!$"

Route41_Eventscript_SwimmerMathew_Text_2:
	.string "A secret about the WHIRL ISLANDS…\nIt's pitch-black inside!$"

Route41_Eventscript_SwimmerWendy_Text_0:
	.string "At night, STARYU gather near the\nwater's surface.$"

Route41_Eventscript_SwimmerWendy_Text_1:
	.string "Oh, dear…$"

Route41_Eventscript_SwimmerWendy_Text_2:
	.string "The clusters of STARYU light up at\nthe same time.\pIts so beautiful, it's scary.$"
