VioletCity_House2_MapScripts:: @ 82078F2
	.byte 0

VioletCity_House2_EventScript_2078F3:: @ 82078F3
	msgbox VioletCity_House2_Text_207905, MSGBOX_NPC
	end

VioletCity_House2_EventScript_2078FC:: @ 82078FC
	msgbox VioletCity_House2_Text_207969, MSGBOX_NPC
	end

VioletCity_House2_Text_207905: @ 8207905
	.string "NORMAN became our town's new\n"
	.string "GYM LEADER.\p"
	.string "I think he called his family over from\n"
	.string "somewhere far away.$"

VioletCity_House2_Text_207969: @ 8207969
	.string "I battled NORMAN once, but, whew,\n"
	.string "he was way too strong.\p"
	.string "How would I put it?\p"
	.string "I just got the feeling that he\n"
	.string "lives for POKéMON.$"

