GoldenrodCity_Underground_NorthEntrance_MapScripts::
	.byte 0


GoldenrodCity_Underground_NorthEntrance_EventScript_ScaredWoman::
	msgbox GoldenrodCity_Underground_NorthEntrance_EventScript_ScaredWoman_Text_0, MSGBOX_NPC
	return


GoldenrodCity_Underground_NorthEntrance_EventScript_ScaredWoman_Text_0:
	.string "There are some shops downstairs…\n"
	.string "But there are also TRAINERS.\p"
	.string "I'm scared to go down there.$"
