MahoganyTown_MapScripts::
	.byte 0


MahoganyTown_Eventscript_TownSign::
	msgbox MahoganyTown_Eventscript_TownSign_Text_0, MSGBOX_SIGN
	end


MahoganyTown_Eventscript_ShopSign::
	msgbox MahoganyTown_Eventscript_ShopSign_Text_0, MSGBOX_SIGN
	end


MahoganyTown_Eventscript_GymSign::
	msgbox MahoganyTown_Eventscript_GymSign_Text_0, MSGBOX_SIGN
	end


MahoganyTown_Eventscript_ShopGirl::
	msgbox MahoganyTown_Eventscript_ShopGirl_Text_0, MSGBOX_NPC
	end


MahoganyTown_Eventscript_GymBlocker::
	msgbox MahoganyTown_Eventscript_GymBlocker_Text_0, MSGBOX_NPC
	end


MahoganyTown_Eventscript_TownSign_Text_0:
	.string "MAHOGANY TOWN\nWelcome to the Home of the Ninja$"

MahoganyTown_Eventscript_ShopSign_Text_0:
	.string "While visiting MAHOGANY TOWN, try a\nRAGECANDYBAR!$"

MahoganyTown_Eventscript_GymSign_Text_0:
	.string "MAHOGANY TOWN POKéMON GYM\nLEADER: PRYCE\pThe Teacher of Winter's Harshness$"

MahoganyTown_Eventscript_ShopGirl_Text_0:
	.string "Visit Grandma's shop. She sells\nstuff that nobody else has.$"

MahoganyTown_Eventscript_GymBlocker_Text_0:
	.string "Since you came this far, take the\ntime to do some sightseeing.\pYou should head north and check out\nthe LAKE OF RAGE right now.$"
