MahoganyTown_PokemonCenter_1F_MapScripts::
	.byte 0


MahoganyTown_PokemonCenter_1F_Eventscript_Boy::
	msgbox MahoganyTown_PokemonCenter_1F_Eventscript_Boy_Text_0, MSGBOX_NPC
	end


MahoganyTown_PokemonCenter_1F_Eventscript_Girl::
	msgbox MahoganyTown_PokemonCenter_1F_Eventscript_Girl_Text_0, MSGBOX_NPC
	end


MahoganyTown_PokemonCenter_1F_Eventscript_Man::
	msgbox MahoganyTown_PokemonCenter_1F_Eventscript_Man_Text_0, MSGBOX_NPC
	end


MahoganyTown_PokemonCenter_1F_Eventscript_Boy_Text_0:
	.string "I stop POKéMON from evolving too\nearly.\pI make them learn certain moves\nbefore I let them evolve.$"

MahoganyTown_PokemonCenter_1F_Eventscript_Girl_Text_0:
	.string "POKéMON do become stronger when they\nevolve, but they also learn moves\lmore slowly.$"

MahoganyTown_PokemonCenter_1F_Eventscript_Man_Text_0:
	.string "What's this?\nTEAM ROCKET has come back?\pI saw some men in black at the LAKE\nOF RAGE…$"
