NewBarkTown_NeighborsHouse_EventObjects::
	object_event 1, EVENT_OBJ_GFX_GIRL_1, 0, 4, 4, 3, MOVEMENT_TYPE_FACE_RIGHT, 0, 0, FALSE, 0, NewBarkTown_NeighborsHouse_EventScript_Girl, 0
	object_event 2, EVENT_OBJ_GFX_WOMAN_4, 0, 7, 4, 3, MOVEMENT_TYPE_FACE_LEFT, 0, 0, FALSE, 0, NewBarkTown_NeighborsHouse_EventScript_Woman, 0

NewBarkTown_NeighborsHouse_MapWarps::
	warp_def 4, 7, 0, 2, MAP_NEW_BARK_TOWN

NewBarkTown_NeighborsHouse_MapEvents::
	map_events NewBarkTown_NeighborsHouse_EventObjects, NewBarkTown_NeighborsHouse_MapWarps, 0x0, 0x0
