Route29_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route30_EventScript_ItemAntidote::
	finditem ITEM_ANTIDOTE
	end

Route31_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route31_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

DarkCave_South_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

DarkCave_South_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

DarkCave_South_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

DarkCave_South_EventScript_ItemDireHit::
	finditem ITEM_DIRE_HIT
	end

VioletCity_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

VioletCity_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

SproutTower_1F_EventScript_ItemParalyzeHeal::
	finditem ITEM_PARALYZE_HEAL
	end

SproutTower_2F_EventScript_ItemXAccuracy::
	finditem ITEM_X_ACCURACY
	end

SproutTower_3F_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

SproutTower_3F_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

Route32_EventScript_ItemRepel::
	finditem ITEM_REPEL
	end

Route32_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

UnionCave_1F_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

UnionCave_1F_EventScript_ItemXAttack::
	finditem ITEM_X_ATTACK
	end

UnionCave_1F_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

UnionCave_1F_EventScript_ItemAwakening::
	finditem ITEM_AWAKENING
	end

UnionCave_B1F_EventScript_ItemTM43::
	finditem ITEM_TM43
	end

UnionCave_B1F_EventScript_ItemXDefend::
	finditem ITEM_X_DEFEND
	end

IlexForest_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

IlexForest_EventScript_ItemXAttack::
	finditem ITEM_X_ATTACK
	end

IlexForest_EventScript_ItemAntidote::
	finditem ITEM_ANTIDOTE
	end

IlexForest_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

SlowpokeWell_B1F_EventScript_ItemSuperPotion::
	finditem ITEM_SUPER_POTION
	end

Route34_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

GoldenrodCity_Underground_EventScript_ItemCoinCase::
	finditem ITEM_COIN_CASE
	end

GoldenrodCity_DeptStore_B1F_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

GoldenrodCity_DeptStore_B1F_EventScript_ItemAmuletCoin::
	finditem ITEM_AMULET_COIN
	end

GoldenrodCity_DeptStore_B1F_EventScript_ItemBurnHeal::
	finditem ITEM_BURN_HEAL
	end

GoldenrodCity_DeptStore_B1F_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

Route35_EventScript_ItemTM39::
	finditem ITEM_TM39_ROCK_TOMB
	end

NationalPark_EventScript_ItemParalyzeHeal::
	finditem ITEM_PARALYZE_HEAL
	end

NationalPark_EventScript_ItemTM28::
	finditem ITEM_TM28_DIG
	end

Route36_EventScript_ItemStarPiece:: @ 8290D4D
	finditem ITEM_STAR_PIECE
	end

Route109_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route109_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route110_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route110_EventScript_ItemDireHit::
	finditem ITEM_DIRE_HIT
	end

Route110_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route111_EventScript_ItemTM37::
	finditem ITEM_TM37
	end

Route111_EventScript_ItemStardust::
	finditem ITEM_STARDUST
	end

Route111_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

Route111_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route112_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

Route113_EventScript_ItemMaxEther::
	finditem ITEM_MAX_ETHER
	end

Route113_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

Route113_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route114_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route114_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

Route114_EventScript_ItemEnergyPowder::
	finditem ITEM_ENERGY_POWDER
	end

Route115_EventScript_ItemSuperPotion::
	finditem ITEM_SUPER_POTION
	end

Route115_EventScript_ItemTM01::
	finditem ITEM_TM01
	end

Route115_EventScript_ItemIron::
	finditem ITEM_IRON
	end

Route115_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

Route115_EventScript_ItemHealPowder::
	finditem ITEM_HEAL_POWDER
	end

Route115_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route116_EventScript_ItemXSpecial::
	finditem ITEM_X_SPECIAL
	end

Route116_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

Route116_EventScript_ItemRepel::
	finditem ITEM_REPEL
	end

Route116_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

Route116_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route45_EventScript_ItemGreatBall:: @ 8290EB9
	finditem ITEM_GREAT_BALL
	end

Route45_EventScript_ItemRevive:: @ 8290EC6
	finditem ITEM_REVIVE
	end

Route46_EventScript_ItemXSpeed::
	finditem ITEM_X_SPEED
	end

Route119_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

Route119_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

Route119_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route119_EventScript_ItemLeafStone::
	finditem ITEM_LEAF_STONE
	end

Route119_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route119_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route119_EventScript_ItemHyperPotion2::
	finditem ITEM_HYPER_POTION
	end

Route119_EventScript_ItemElixir2::
	finditem ITEM_ELIXIR
	end

Route120_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

Route120_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

Route120_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route120_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

Route120_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

Route121_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

Route121_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

Route121_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

Route123_EventScript_ItemCalcium::
	finditem ITEM_CALCIUM
	end

Route123_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

Route123_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route123_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route123_EventScript_ItemRevivalHerb::
	finditem ITEM_REVIVAL_HERB
	end

Route124_EventScript_ItemRedShard::
	finditem ITEM_RED_SHARD
	end

Route124_EventScript_ItemBlueShard::
	finditem ITEM_BLUE_SHARD
	end

Route124_EventScript_ItemYellowShard::
	finditem ITEM_YELLOW_SHARD
	end

Route125_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

Route126_EventScript_ItemGreenShard::
	finditem ITEM_GREEN_SHARD
	end

Route127_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

Route127_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

Route127_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route132_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route132_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

Route133_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

Route133_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

Route133_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

Route134_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

Route134_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

MauvilleCity_EventScript_ItemXSpeed:: @ 82910CE
	finditem ITEM_X_SPEED
	end

GoldenrodCity_EventScript_ItemXDefend:: @ 82910DB
	finditem ITEM_X_DEFEND
	end

LilycoveCity_EventScript_ItemMaxRepel::
	finditem ITEM_MAX_REPEL
	end

MossdeepCity_EventScript_ItemNetBall::
	finditem ITEM_NET_BALL
	end

DarkCave_South_EventScript_ItemEscapeRope:: @ 8291150
	finditem ITEM_ESCAPE_ROPE
	end

DarkCave_B1F_EventScript_ItemPokeBall:: @ 829115D
	finditem ITEM_POKE_BALL
	end

JaggedPass_EventScript_ItemBurnHeal:: @ 8291184
	finditem ITEM_BURN_HEAL
	end

FieryPath_EventScript_ItemFireStone::
	finditem ITEM_FIRE_STONE
	end

FieryPath_EventScript_ItemTM06::
	finditem ITEM_TM06
	end

RadioTower_1F_EventScript_ItemTM23:: @ 82911AB
	finditem ITEM_TM23
	end

RadioTower_1F_EventScript_ItemFullHeal:: @ 82911B8
	finditem ITEM_FULL_HEAL
	end

RadioTower_1F_EventScript_ItemMoonStone:: @ 82911C5
	finditem ITEM_MOON_STONE
	end

RadioTower_1F_EventScript_ItemPPUP:: @ 82911D2
	finditem ITEM_PP_UP
	end

RadioTower_4F_EventScript_ItemTM02:: @ 82911DF
	finditem ITEM_TM02
	end

RuinsOfAlph_InnerChamber_EventScript_ItemUltraRope:: @ 82911EC
	finditem ITEM_ULTRA_BALL
	end

RuinsOfAlph_InnerChamber_EventScript_ItemEscapeRope:: @ 82911F9
	finditem ITEM_ESCAPE_ROPE
	end

RuinsOfAlph_InnerChamber_EventScript_ItemThunderStone:: @ 8291206
	finditem ITEM_THUNDER_STONE
	end

RuinsOfAlph_InnerChamber_EventScript_ItemFullHeal:: @ 8291213
	finditem ITEM_FULL_HEAL
	end

RuinsOfAlph_InnerChamber_EventScript_ItemParalyzeHeal:: @ 8291220
	finditem ITEM_PARALYZE_HEAL
	end

SproutTower_3F_EventScript_ItemHarborMail:: @ 829122D
	finditem ITEM_HARBOR_MAIL
	end

RuinsOfAlph_KabutoChamber_EventScript_ItemEscapeRope:: @ 829123A
	finditem ITEM_ESCAPE_ROPE
	end

RuinsOfAlph_AerodactylChamber_EventScript_ItemDiveBall:: @ 8291247
	finditem ITEM_DIVE_BALL
	end

RuinsOfAlph_HoOhChamber_EventScript_ItemTM13:: @ 8291254
	finditem ITEM_TM13
	end

RuinsOfAlph_KabutoItemRoom_EventScript_ItemOranBerry::
	finditem ITEM_ORAN_BERRY
	end

RuinsOfAlph_KabutoItemRoom_EventScript_ItemPechaBerry::
	finditem ITEM_PECHA_BERRY
	end

RuinsOfAlph_KabutoItemRoom_EventScript_ItemHealPowder::
	finditem ITEM_HEAL_POWDER
	end

RuinsOfAlph_KabutoItemRoom_EventScript_ItemEnergyPowder::
	finditem ITEM_ENERGY_POWDER
	end

RuinsOfAlph_AerodactylItemRoom_EventScript_ItemStorageKey:: @ 829126E
	finditem ITEM_STORAGE_KEY
	end

RuinsOfAlph_KabutoWordRoom_EventScript_ItemLuxuryBall:: @ 829127B
	finditem ITEM_LUXURY_BALL
	end

RuinsOfAlph_KabutoWordRoom_EventScript_ItemScanner:: @ 8291288
	finditem ITEM_SCANNER
	end

RuinsOfAlph_KabutoWordRoom_EventScript_ItemWaterStone:: @ 8291295
	finditem ITEM_WATER_STONE
	end

RuinsOfAlph_KabutoWordRoom_EventScript_ItemTM18:: @ 82912A2
	finditem ITEM_TM18
	end

ScorchedSlab_EventScript_ItemTM11::
	finditem ITEM_TM11
	end

SafariZone_Northwest_EventScript_ItemTM22::
	finditem ITEM_TM22
	end

SafariZone_North_EventScript_ItemCalcium::
	finditem ITEM_CALCIUM
	end

SafariZone_Southwest_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

SafariZone_Northeast_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

SafariZone_Southeast_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

MtPyre_2F_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

MtPyre_3F_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

MtPyre_4F_EventScript_ItemSeaIncense::
	finditem ITEM_SEA_INCENSE
	end

MtPyre_5F_EventScript_ItemLaxIncense::
	finditem ITEM_LAX_INCENSE
	end

MtPyre_6F_EventScript_ItemTM30::
	finditem ITEM_TM30
	end

MtPyre_Exterior_EventScript_ItemMaxPotion::
	finditem ITEM_MAX_POTION
	end

MtPyre_Exterior_EventScript_ItemTM48::
	finditem ITEM_TM48
	end

AquaHideout_B1F_EventScript_ItemMasterBall::
	finditem ITEM_MASTER_BALL
	end

AquaHideout_B1F_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

AquaHideout_B1F_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

AquaHideout_B2F_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

AquaHideout_B2F_EventScript_ItemMasterBall::
	finditem ITEM_MASTER_BALL      // Unused
	end

Route119_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

Route119_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

Route119_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

ShoalCave_LowTideEntranceRoom_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

ShoalCave_LowTideInnerRoom_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

ShoalCave_LowTideStairsRoom_EventScript_ItemIceHeal::
	finditem ITEM_ICE_HEAL
	end

ShoalCave_LowTideIceRoom_EventScript_ItemTM07::
	finditem ITEM_TM07
	end

ShoalCave_LowTideIceRoom_EventScript_ItemNeverMeltIce::
	finditem ITEM_NEVER_MELT_ICE
	end

SeafloorCavern_Room9_EventScript_ItemTM26::
	finditem ITEM_TM26
	end

Route110_TrickHousePuzzle1_EventScript_ItemOrangeMail::
	finditem ITEM_ORANGE_MAIL
	end

Route110_TrickHousePuzzle2_EventScript_ItemHarborMail::
	finditem ITEM_HARBOR_MAIL
	end

Route110_TrickHousePuzzle2_EventScript_ItemWaveMail::
	finditem ITEM_WAVE_MAIL
	end

Route110_TrickHousePuzzle3_EventScript_ItemShadowMail::
	finditem ITEM_SHADOW_MAIL
	end

Route110_TrickHousePuzzle3_EventScript_ItemWoodMail::
	finditem ITEM_WOOD_MAIL
	end

Route110_TrickHousePuzzle4_EventScript_ItemMechMail::
	finditem ITEM_MECH_MAIL
	end

Route110_TrickHousePuzzle6_EventScript_ItemGlitterMail::
	finditem ITEM_GLITTER_MAIL
	end

Route110_TrickHousePuzzle7_EventScript_ItemTropicMail::
	finditem ITEM_TROPIC_MAIL
	end

Route110_TrickHousePuzzle8_EventScript_ItemBeadMail::
	finditem ITEM_BEAD_MAIL
	end

VictoryRoad_1F_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

VictoryRoad_1F_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

VictoryRoad_B1F_EventScript_ItemTM29::
	finditem ITEM_TM29
	end

VictoryRoad_B1F_EventScript_ItemFullRestore::
	finditem ITEM_FULL_RESTORE
	end

VictoryRoad_B2F_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

ArtisanCave_B1F_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

ArtisanCave_1F_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

MagmaHideout_1F_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

MagmaHideout_2F_2R_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

MagmaHideout_2F_2R_EventScript_ItemFullRestore::
	finditem ITEM_FULL_RESTORE
	end

MagmaHideout_3F_1R_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

MagmaHideout_3F_2R_EventScript_ItemPPMax::
	finditem ITEM_PP_MAX
	end

MagmaHideout_4F_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

MagmaHideout_3F_3R_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end
