EcruteakCity_MapScripts::
	.byte 0


EcruteakCity_Eventscript_CitySign::
	msgbox EcruteakCity_Eventscript_CitySign_Text_0, MSGBOX_SIGN
	end


EcruteakCity_Eventscript_DanceTheaterSign::
	msgbox EcruteakCity_Eventscript_DanceTheaterSign_Text_0, MSGBOX_SIGN
	end


EcruteakCity_Eventscript_GymSign::
	msgbox EcruteakCity_Eventscript_GymSign_Text_0, MSGBOX_SIGN
	end


EcruteakCity_Eventscript_BurnedTowerSign::
	msgbox EcruteakCity_Eventscript_BurnedTowerSign_Text_0, MSGBOX_SIGN
	end


EcruteakCity_Eventscript_TinTowerSign::
	msgbox EcruteakCity_Eventscript_TinTowerSign_Text_0, MSGBOX_SIGN
	end


EcruteakCity_Eventscript_OldMan1::
	msgbox EcruteakCity_Eventscript_OldMan1_Text_0, MSGBOX_NPC
	end


EcruteakCity_Eventscript_Boy::
	msgbox EcruteakCity_Eventscript_Boy_Text_0, MSGBOX_NPC
	end


EcruteakCity_Eventscript_OldMan2::
	msgbox EcruteakCity_Eventscript_OldMan2_Text_0, MSGBOX_NPC
	end


EcruteakCity_Eventscript_OldMan3::
	msgbox EcruteakCity_Eventscript_OldMan3_Text_0, MSGBOX_NPC
	end


EcruteakCity_Eventscript_Girl2::
	msgbox EcruteakCity_Eventscript_Girl2_Text_0, MSGBOX_NPC
	end


EcruteakCity_Eventscript_CitySign_Text_0:
	.string "ECRUTEAK CITY\pA Historical City Where the Past\nMeets the Present$"

EcruteakCity_Eventscript_DanceTheaterSign_Text_0:
	.string "ECRUTEAK DANCE THEATER$"

EcruteakCity_Eventscript_GymSign_Text_0:
	.string "ECRUTEAK CITY POKéMON GYM\nLEADER: MORTY\pThe Mystic Seer of the Future$"

EcruteakCity_Eventscript_BurnedTowerSign_Text_0:
	.string "BURNED TOWER\nIt was destroyed by a mysterious\lfire.\pPlease stay away, as it is unsafe.$"

EcruteakCity_Eventscript_TinTowerSign_Text_0:
	.string "TIN TOWER\pA legendary POKéMON is said to roost\nhere.$"

EcruteakCity_Eventscript_OldMan1_Text_0:
	.string "In the distant past…\pThis tower burned in a fire. Three\nnameless POKéMON perished in it.\pA rainbow-colored POKéMON descended\nfrom the sky and resurrected them…\pIt's a legend that has been passed\ndown by ECRUTEAK GYM LEADERS.\pMe? I was a TRAINER way back when.\nHohoho!$"

EcruteakCity_Eventscript_Boy_Text_0:
	.string "I hear POKéMON are rampaging at the\nLAKE OF RAGE. I'd like to see that!$"

EcruteakCity_Eventscript_OldMan2_Text_0:
	.string "ECRUTEAK used to have two towers:\none each in the east and west.$"

EcruteakCity_Eventscript_OldMan3_Text_0:
	.string "Ah, child. Have you learned to dance\nlike the KIMONO GIRLS?\pIf you go to their DANCE THEATER, an\nodd old man will give you something\lnice, I hear.$"

EcruteakCity_Eventscript_Girl2_Text_0:
	.string "I'm going to practice at the DANCE\nTHEATER. Care to join me?$"
