BlackthornCity_PokemonCenter_1F_MapScripts::
	.byte 0


BlackthornCity_PokemonCenter_1F_Eventscript_Gentleman::
	msgbox BlackthornCity_PokemonCenter_1F_Eventscript_Gentleman_Text_0, MSGBOX_NPC
	end


BlackthornCity_PokemonCenter_1F_Eventscript_LittleGirl::
	msgbox BlackthornCity_PokemonCenter_1F_Eventscript_LittleGirl_Text_0, MSGBOX_NPC
	end


BlackthornCity_PokemonCenter_1F_Eventscript_Gentleman_Text_0:
	.string "Deep inside far-off INDIGO PLATEAU\nis the POKéMON LEAGUE.\pI hear the best TRAINERS gather\nthere from around the country.$"

BlackthornCity_PokemonCenter_1F_Eventscript_LittleGirl_Text_0:
	.string "There was this move I just had to\nteach my POKéMON.\pSo I got the MOVE DELETER to make it\nforget an HM move.$"
