GoldenrodCity_Underground_SouthEntrance_MapScripts::
	.byte 0


GoldenrodCity_Underground_SouthEntrance_EventScript_RoughNerd::
	msgbox GoldenrodCity_Underground_SouthEntrance_EventScript_RoughNerd_Text_0, MSGBOX_NPC
	return


GoldenrodCity_Underground_SouthEntrance_EventScript_RoughNerd_Text_0:
	.string "I was challenged to a battle\n"
	.string "downstairs.\p"
	.string "It's rough down there.\n"
	.string "You'd better be careful.$"
