OlivineCity_House3_MapScripts::
	.byte 0


OlivineCity_House3_Eventscript_Man::
	msgbox OlivineCity_House3_Eventscript_Man_Text_0, MSGBOX_NPC
	end


OlivineCity_House3_Eventscript_Girl::
	msgbox OlivineCity_House3_Eventscript_Girl_Text_0, MSGBOX_NPC
	end


OlivineCity_House3_Eventscript_Man_Text_0:
	.string "Along the way to CIANWOOD, there are\nfour deserted islands.\pBad kids are taken to the islands as\npunishment!$"

OlivineCity_House3_Eventscript_Girl_Text_0:
	.string "Whenever I get in trouble, Daddy\nalways scares me.$"
