RuinsOfAlph_AerodactylChamber_MapScripts:: @ 8238024
	.byte 0

RuinsOfAlph_AerodactylChamber_EventScript_Camper:: @ 8238025
	msgbox RuinsOfAlph_AerodactylChamber_Text_PerfectPlaceToGoExploring, MSGBOX_NPC
	end

RuinsOfAlph_AerodactylChamber_Text_PerfectPlaceToGoExploring: @ 823802E
	.string "This is a perfect place to go exploring!\n"
	.string "It's exciting here!\p"
	.string "I bet there're amazing treasures on\n"
	.string "board.$"

