NewBarkTown_ElmsHouse:
	.4byte NewBarkTown_ElmsHouse_Layout
	.4byte NewBarkTown_ElmsHouse_MapEvents
	.4byte NewBarkTown_ElmsHouse_MapScripts
	.4byte 0x0
	.2byte MUS_NEWBARK
	.2byte LAYOUT_NEW_BARK_TOWN_ELMS_HOUSE
	.byte MAPSEC_NEW_BARK_TOWN
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_INDOOR
	.2byte 0
	map_header_flags allow_bike=0, allow_escape_rope=0, allow_run=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

