EcruteakCity_PokemonCenter_1F_MapScripts::
	.byte 0


EcruteakCity_Mart_Eventscript_Girl::
	msgbox EcruteakCity_Mart_Eventscript_Girl_Text_0, MSGBOX_NPC
	end


EcruteakCity_Mart_Eventscript_Man::
	msgbox EcruteakCity_Mart_Eventscript_Man_Text_0, MSGBOX_NPC
	end


EcruteakCity_Mart_Eventscript_Hiker::
	msgbox EcruteakCity_Mart_Eventscript_Hiker_Text_0, MSGBOX_NPC
	end


EcruteakCity_Mart_Eventscript_Girl_Text_0:
	.string "MORTY, the GYM LEADER, is soooo cool.\nHis POKéMON are really tough too.$"

EcruteakCity_Mart_Eventscript_Man_Text_0:
	.string "The LAKE OF RAGE…\nThe appearance of a GYARADOS swarm…\pI smell a conspiracy.\nI know it!$"

EcruteakCity_Mart_Eventscript_Hiker_Text_0:
	.string "The way the KIMONO GIRLS dance is\nmarvelous. Just like the way they\luse their POKéMON.$"
