Route36_RuinsOfAlphGatehouse_MapScripts::
	.byte 0


Route36_RuinsOfAlphGatehouse_EventScript_Officer::
	msgbox Route36_RuinsOfAlphGatehouse_EventScript_Officer_Text_0, MSGBOX_NPC
	return


Route36_RuinsOfAlphGatehouse_EventScript_OldMan::
	msgbox Route36_RuinsOfAlphGatehouse_EventScript_OldMan_Text_0, MSGBOX_NPC
	return


Route36_RuinsOfAlphGatehouse_EventScript_Officer_Text_0:
	.string "Don't you wonder who'd make\n"
	.string "something like this? And why?$"

Route36_RuinsOfAlphGatehouse_EventScript_OldMan_Text_0:
	.string "Did you see that strange tree\n"
	.string "in the road?\p"
	.string "That may explain why fewer people\n"
	.string "are visiting the RUINS OF ALPH.$"
