VictoryRoad_Gatehouse_MapScripts::
	.byte 0


VictoryRoad_Gatehouse_Eventscript_BadgeCheckGuard::
	msgbox VictoryRoad_Gatehouse_Eventscript_BadgeCheckGuard_Text_0, MSGBOX_NPC
	end


VictoryRoad_Gatehouse_Eventscript_LeftBlackBelt::
	msgbox VictoryRoad_Gatehouse_Eventscript_LeftBlackBelt_Text_0, MSGBOX_NPC
	end


VictoryRoad_Gatehouse_Eventscript_RightBlackBelt::
	msgbox VictoryRoad_Gatehouse_Eventscript_RightBlackBelt_Text_0, MSGBOX_NPC
	end


VictoryRoad_Gatehouse_Eventscript_BadgeCheckGuard_Text_0:
	.string "Only TRAINERS who have proven\nthemselves may pass.\pOh! The eight BADGES of JOHTO!\nPlease, go right on through!$"

VictoryRoad_Gatehouse_Eventscript_LeftBlackBelt_Text_0:
	.string "This way leads to MT. SILVER. You'll\nsee scary-strong POKéMON out there.$"

VictoryRoad_Gatehouse_Eventscript_RightBlackBelt_Text_0:
	.string "Off to the POKéMON LEAGUE, are you?\pThe ELITE FOUR are so strong it's\nscary, and they're ready for you!$"
