BlackthornCity_Gym_2F_MapScripts::
	.byte 0


BlackthornCity_Gym_2F_Eventscript_CooltrainerCody::
	trainerbattle_single TRAINER_CODY, BlackthornCity_Gym_2F_Eventscript_CooltrainerCody_Text_0, BlackthornCity_Gym_2F_Eventscript_CooltrainerCody_Text_1
	msgbox BlackthornCity_Gym_2F_Eventscript_CooltrainerCody_Text_2, MSGBOX_AUTOCLOSE
	end


BlackthornCity_Gym_2F_Eventscript_CooltrainerFran::
	trainerbattle_single TRAINER_FRAN, BlackthornCity_Gym_2F_Eventscript_CooltrainerFran_Text_0, BlackthornCity_Gym_2F_Eventscript_CooltrainerFran_Text_1
	msgbox BlackthornCity_Gym_2F_Eventscript_CooltrainerFran_Text_2, MSGBOX_AUTOCLOSE
	end


BlackthornCity_Gym_2F_Eventscript_CooltrainerCody_Text_0:
	.string "It's not as if we all use DRAGON-\ntype POKéMON.$"

BlackthornCity_Gym_2F_Eventscript_CooltrainerCody_Text_1:
	.string "Rats! If only I had a dragon!$"

BlackthornCity_Gym_2F_Eventscript_CooltrainerCody_Text_2:
	.string "Members of our dragon-user clan can\nuse dragon POKéMON only after our\lMASTER allows it.$"

BlackthornCity_Gym_2F_Eventscript_CooltrainerFran_Text_0:
	.string "I can't allow a nameless TRAINER\npast me!\pCLAIR would be livid if I did!$"

BlackthornCity_Gym_2F_Eventscript_CooltrainerFran_Text_1:
	.string "Awww… I lost…$"

BlackthornCity_Gym_2F_Eventscript_CooltrainerFran_Text_2:
	.string "Uh-oh… CLAIR is going to be mad…$"
