#ifndef GUARD_TRAINER_REMATCH_H
#define GUARD_TRAINER_REMATCH_H

enum {
    REMATCH_JOEY,
    REMATCH_WADE,
    REMATCH_LIZ,
    REMATCH_RALPH,
    REMATCH_ANTHONY,
    REMATCH_TODD,
    REMATCH_GINA,
    REMATCH_ARNIE,
    REMATCH_JACK,
    REMATCH_ALAN,
    REMATCH_DANA,
    REMATCH_CHAD,
    REMATCH_HUEY,
    REMATCH_TULLY,
    REMATCH_TIFFANY,
    REMATCH_BRENT,
    REMATCH_WILTON,
    REMATCH_VANCE,
    REMATCH_PARRY,
    REMATCH_ERIN,
    REMATCH_JOSE,
    REMATCH_REENA,
    REMATCH_GAVEN,
    REMATCH_BETH,
    REMATCH_TABLE_ENTRIES // The total number of rematch entries. Must be last in enum
};

void UpdateGymLeaderRematch(void);

#endif //GUARD_TRAINER_REMATCH_H
