#ifndef GUARD_POKEGEAR_H
#define GUARD_POKEGEAR_H

enum
{
    INPUT_EVENT_NONE,
    INPUT_EVENT_MOVE_START,
    INPUT_EVENT_MOVE_CONT,
    INPUT_EVENT_MOVE_END,
    INPUT_EVENT_A_BUTTON,
    INPUT_EVENT_B_BUTTON,
};

#endif //GUARD_POKEGEAR_H
