#ifndef GUARD_RADIO_H
#define GUARD_RADIO_H

#define RADIO_FREQ(a) (u8)(a * 2 - 1)

enum {
    OAKS_POKEMON_TALK,
    POKEDEX_SHOW,
    POKEMON_MUSIC,
    LUCKY_CHANNEL,
    BUENAS_PASSWORD,
    PLACES_AND_PEOPLE,
    LETS_ALL_SING,
    ROCKET_RADIO,
    POKE_FLUTE_RADIO,
    UNOWN_RADIO,
    EVOLUTION_RADIO,
    OAKS_POKEMON_TALK_2,
    OAKS_POKEMON_TALK_3,
    OAKS_POKEMON_TALK_4,
    OAKS_POKEMON_TALK_5,
    OAKS_POKEMON_TALK_6,
    OAKS_POKEMON_TALK_7,
    OAKS_POKEMON_TALK_8,
    OAKS_POKEMON_TALK_9,
    POKEDEX_SHOW_2,
    POKEDEX_SHOW_3,
    POKEDEX_SHOW_4,
    POKEMON_MUSIC_2,
    POKEMON_MUSIC_3,
    POKEMON_MUSIC_4,
    POKEMON_MUSIC_5,
    POKEMON_MUSIC_6,
    POKEMON_MUSIC_7,
    LETS_ALL_SING_2,
    LUCKY_NUMBER_SHOW_2,
    LUCKY_NUMBER_SHOW_3,
    LUCKY_NUMBER_SHOW_4,
    LUCKY_NUMBER_SHOW_5,
    LUCKY_NUMBER_SHOW_6,
    LUCKY_NUMBER_SHOW_7,
    LUCKY_NUMBER_SHOW_8,
    LUCKY_NUMBER_SHOW_9,
    LUCKY_NUMBER_SHOW_10,
    LUCKY_NUMBER_SHOW_11,
    LUCKY_NUMBER_SHOW_12,
    LUCKY_NUMBER_SHOW_13,
    LUCKY_NUMBER_SHOW_14,
    LUCKY_NUMBER_SHOW_15,
    PLACES_AND_PEOPLE_2,
    PLACES_AND_PEOPLE_3,
    PLACES_AND_PEOPLE_4,
    PLACES_AND_PEOPLE_5,
    ROCKET_RADIO_2,
    ROCKET_RADIO_3,
    ROCKET_RADIO_4,
    ROCKET_RADIO_5,
    ROCKET_RADIO_6,
    ROCKET_RADIO_7,
    ROCKET_RADIO_8,
    ROCKET_RADIO_9,
    ROCKET_RADIO_10,
    PKMN_CHANNEL_INTERLUDE_1,
    PKMN_CHANNEL_INTERLUDE_2,
    PKMN_CHANNEL_INTERLUDE_3,
    BUENAS_PASSWORD_2,
    BUENAS_PASSWORD_3,
    BUENAS_PASSWORD_4,
    BUENAS_PASSWORD_5,
    BUENAS_PASSWORD_6,
    BUENAS_PASSWORD_7,
    BUENAS_PASSWORD_8,
    BUENAS_PASSWORD_9,
    BUENAS_PASSWORD_10,
    BUENAS_PASSWORD_11,
    BUENAS_PASSWORD_12,
    BUENAS_PASSWORD_13,
    BUENAS_PASSWORD_14,
    BUENAS_PASSWORD_15,
    BUENAS_PASSWORD_16,
    BUENAS_PASSWORD_17,
    BUENAS_PASSWORD_18,
    BUENAS_PASSWORD_19,
    BUENAS_PASSWORD_20,
    BUENAS_PASSWORD_21,
    RADIO_SCROLL,
    POKEDEX_SHOW_6,
    POKEDEX_SHOW_7,
    POKEDEX_SHOW_8,
    NO_RADIO_SHOW,
};

struct RadioStation{
    u8 frequency;
    u8 region;
    u8 (*loadFunc)(void);
};

extern const struct RadioStation gRadioStationData[];
extern const u8 *const gRadioShowNames[];

void Task_PlayRadioShow(u8 taskId);

#endif
