CherrygroveCity_House2_MapScripts:: @ 81FBF5A
	.byte 0

CherrygroveCity_House2_EventScript_1FBF5B:: @ 81FBF5B
	msgbox CherrygroveCity_House2_Text_1FBF6D, MSGBOX_NPC
	end

CherrygroveCity_House2_EventScript_1FBF64:: @ 81FBF64
	msgbox CherrygroveCity_House2_Text_1FBFB0, MSGBOX_NPC
	end

CherrygroveCity_House2_Text_1FBF6D: @ 81FBF6D
	.string "When POKéMON battle, they eventually\n"
	.string "level up and become stronger.$"

CherrygroveCity_House2_Text_1FBFB0: @ 81FBFB0
	.string "If the POKéMON with you become\n"
	.string "stronger, you'll be able to go farther\l"
	.string "away from here.$"

