GoldenrodCity_DeptStore_1F_MapScripts::
	.byte 0


GoldenrodCity_DeptStore_1F_EventScript_Receptionist::
	msgbox GoldenrodCity_DeptStore_1F_EventScript_Receptionist_Text_0, MSGBOX_NPC
	return


GoldenrodCity_DeptStore_1F_EventScript_RaringWoman::
	msgbox GoldenrodCity_DeptStore_1F_EventScript_RaringWoman_Text_0, MSGBOX_NPC
	return


GoldenrodCity_DeptStore_1F_EventScript_ProudChild::
	msgbox GoldenrodCity_DeptStore_1F_EventScript_ProudChild_Text_0, MSGBOX_NPC
	return


GoldenrodCity_DeptStore_1F_EventScript_Gentleman::
	msgbox GoldenrodCity_DeptStore_1F_EventScript_Gentleman_Text_0, MSGBOX_NPC
	return


GoldenrodCity_DeptStore_1F_EventScript_Directory::
	msgbox GoldenrodCity_DeptStore_1F_EventScript_Directory_Text_0, MSGBOX_SIGN
	return


GoldenrodCity_DeptStore_1F_EventScript_ServiceCounter::
	msgbox GoldenrodCity_DeptStore_1F_EventScript_ServiceCounter_Text_0, MSGBOX_SIGN
	return


GoldenrodCity_DeptStore_1F_EventScript_Receptionist_Text_0:
	.string "Welcome to GOLDENROD DEPT. STORE.$"

GoldenrodCity_DeptStore_1F_EventScript_RaringWoman_Text_0:
	.string "I'm raring to shop again today!$"

GoldenrodCity_DeptStore_1F_EventScript_ProudChild_Text_0:
	.string "Mom's good at bargain hunting.\n"
	.string "She always buys stuff at lower\l"
	.string "prices.$"

GoldenrodCity_DeptStore_1F_EventScript_Gentleman_Text_0:
	.string "The DEPT. STORE has a decent\n"
	.string "selection.\p"
	.string "But some items are only available\n"
	.string "as GAME CORNER prizes.$"

GoldenrodCity_DeptStore_1F_EventScript_Directory_Text_0:
	.string "1F SERVICE COUNTER\p"
	.string "2F TRAINER'S MARKET\p"
	.string "3F BATTLE COLLECTION\p"
	.string "4F MEDICINE BOX\p"
	.string "5F TM CORNER\p"
	.string "6F TRANQUIL SQUARE\p"
	.string "ROOFTOP LOOKOUT$"

GoldenrodCity_DeptStore_1F_EventScript_ServiceCounter_Text_0:
	.string "1F SERVICE COUNTER$"
