#include "global.h"
#include "battle_setup.h"
#include "pokegear_phone.h"
#include "constants/flags.h"

static bool8 IsAvailable_Always(s8 dayOfWeek, s8 hour);

static const u8 sPhoneContactName_Mom[] = _("MOM");
static const u8 sPhoneContactName_ProfessorElm[] = _("PROF. ELM");

const struct PhoneContact gPhoneContacts[PHONE_CONTACT_COUNT] =
{
    [PHONE_CONTACT_MOM] ={
        .customDisplayName = sPhoneContactName_Mom,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_MOM,
        .rematchTrainerId = 0xFF,
        .isPermanent = TRUE,
    },
    [PHONE_CONTACT_ELM] ={
        .customDisplayName = sPhoneContactName_ProfessorElm,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_ELM,
        .rematchTrainerId = 0xFF,
        .isPermanent = TRUE,
    },
    [PHONE_CONTACT_ROSE] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_ROSE,
        .rematchTrainerId = REMATCH_TRAINER_ROSE,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_ANDRES] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_ANDRES,
        .rematchTrainerId = REMATCH_TRAINER_ANDRES,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_DUSTY] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_DUSTY,
        .rematchTrainerId = REMATCH_TRAINER_DUSTY,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_LOLA] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_LOLA,
        .rematchTrainerId = REMATCH_TRAINER_LOLA,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_RICKY] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_RICKY,
        .rematchTrainerId = REMATCH_TRAINER_RICKY,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_LILA_AND_ROY] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_LILA_AND_ROY,
        .rematchTrainerId = REMATCH_TRAINER_LILA_AND_ROY,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_CRISTIN] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_CRISTIN,
        .rematchTrainerId = REMATCH_TRAINER_CRISTIN,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_BROOKE] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_BROOKE,
        .rematchTrainerId = REMATCH_TRAINER_BROOKE,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_WILTON] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_WILTON,
        .rematchTrainerId = REMATCH_TRAINER_WILTON,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_VALERIE] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_VALERIE,
        .rematchTrainerId = REMATCH_TRAINER_VALERIE,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_CINDY] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_CINDY,
        .rematchTrainerId = REMATCH_TRAINER_CINDY,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_THALIA] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_THALIA,
        .rematchTrainerId = REMATCH_TRAINER_THALIA,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_JESSICA] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_JESSICA,
        .rematchTrainerId = REMATCH_TRAINER_JESSICA,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_WINSTON] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_WINSTON,
        .rematchTrainerId = REMATCH_TRAINER_WINSTON,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_STEVE] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_STEVE,
        .rematchTrainerId = REMATCH_TRAINER_STEVE,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_TONY] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_TONY,
        .rematchTrainerId = REMATCH_TRAINER_TONY,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_NOB] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_NOB,
        .rematchTrainerId = REMATCH_TRAINER_NOB,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_KOJI] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_KOJI,
        .rematchTrainerId = REMATCH_TRAINER_KOJI,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_FERNANDO] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_FERNANDO,
        .rematchTrainerId = REMATCH_TRAINER_FERNANDO,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_DALTON] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_DALTON,
        .rematchTrainerId = REMATCH_TRAINER_DALTON,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_BERNIE] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_BERNIE,
        .rematchTrainerId = REMATCH_TRAINER_BERNIE,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_ETHAN] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_ETHAN,
        .rematchTrainerId = REMATCH_TRAINER_ETHAN,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_JOHN_AND_JAY] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_JOHN_AND_JAY,
        .rematchTrainerId = REMATCH_TRAINER_JOHN_AND_JAY,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_JEFFREY] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_JEFFREY,
        .rematchTrainerId = REMATCH_TRAINER_JEFFREY,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_CAMERON] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_CAMERON,
        .rematchTrainerId = REMATCH_TRAINER_CAMERON,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_JACKI] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_JACKI,
        .rematchTrainerId = REMATCH_TRAINER_JACKI,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_WALTER] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_WALTER,
        .rematchTrainerId = REMATCH_TRAINER_WALTER,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_KAREN] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_KAREN,
        .rematchTrainerId = REMATCH_TRAINER_KAREN,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_JERRY] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_JERRY,
        .rematchTrainerId = REMATCH_TRAINER_JERRY,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_ANNA_AND_MEG] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_ANNA_AND_MEG,
        .rematchTrainerId = REMATCH_TRAINER_ANNA_AND_MEG,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_ISABEL] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_ISABEL,
        .rematchTrainerId = REMATCH_TRAINER_ISABEL,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_MIGUEL] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_MIGUEL,
        .rematchTrainerId = REMATCH_TRAINER_MIGUEL,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_TIMOTHY] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_TIMOTHY,
        .rematchTrainerId = REMATCH_TRAINER_TIMOTHY,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_SHELBY] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_SHELBY,
        .rematchTrainerId = REMATCH_TRAINER_SHELBY,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_CALVIN] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_CALVIN,
        .rematchTrainerId = REMATCH_TRAINER_CALVIN,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_ELLIOT] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_ELLIOT,
        .rematchTrainerId = REMATCH_TRAINER_ELLIOT,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_ISAIAH] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_ISAIAH,
        .rematchTrainerId = REMATCH_TRAINER_ISAIAH,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_MARIA] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_MARIA,
        .rematchTrainerId = REMATCH_TRAINER_MARIA,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_ABIGAIL] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_ABIGAIL,
        .rematchTrainerId = REMATCH_TRAINER_ABIGAIL,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_DYLAN] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_DYLAN,
        .rematchTrainerId = REMATCH_TRAINER_DYLAN,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_KATELYN] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_KATELYN,
        .rematchTrainerId = REMATCH_TRAINER_KATELYN,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_BENJAMIN] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_BENJAMIN,
        .rematchTrainerId = REMATCH_TRAINER_BENJAMIN,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_PABLO] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_PABLO,
        .rematchTrainerId = REMATCH_TRAINER_PABLO,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_NICOLAS] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_NICOLAS,
        .rematchTrainerId = REMATCH_TRAINER_NICOLAS,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_ROBERT] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_ROBERT,
        .rematchTrainerId = REMATCH_TRAINER_ROBERT,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_LAO] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_LAO,
        .rematchTrainerId = REMATCH_TRAINER_LAO,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_CYNDY] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_CYNDY,
        .rematchTrainerId = REMATCH_TRAINER_CYNDY,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_MADELINE] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_MADELINE,
        .rematchTrainerId = REMATCH_TRAINER_MADELINE,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_JENNY] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_JENNY,
        .rematchTrainerId = REMATCH_TRAINER_JENNY,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_DIANA] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_DIANA,
        .rematchTrainerId = REMATCH_TRAINER_DIANA,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_AMY_AND_LIV] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_AMY_AND_LIV,
        .rematchTrainerId = REMATCH_TRAINER_AMY_AND_LIV,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_ERNEST] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_ERNEST,
        .rematchTrainerId = REMATCH_TRAINER_ERNEST,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_CORY] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_CORY,
        .rematchTrainerId = REMATCH_TRAINER_CORY,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_EDWIN] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_EDWIN,
        .rematchTrainerId = REMATCH_TRAINER_EDWIN,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_LYDIA] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_LYDIA,
        .rematchTrainerId = REMATCH_TRAINER_LYDIA,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_ISAAC] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_ISAAC,
        .rematchTrainerId = REMATCH_TRAINER_ISAAC,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_GABRIELLE] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_GABRIELLE,
        .rematchTrainerId = REMATCH_TRAINER_GABRIELLE,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_CATHERINE] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_CATHERINE,
        .rematchTrainerId = REMATCH_TRAINER_CATHERINE,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_JACKSON] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_JACKSON,
        .rematchTrainerId = REMATCH_TRAINER_JACKSON,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_HALEY] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_HALEY,
        .rematchTrainerId = REMATCH_TRAINER_HALEY,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_JAMES] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_JAMES,
        .rematchTrainerId = REMATCH_TRAINER_JAMES,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_TRENT] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_TRENT,
        .rematchTrainerId = REMATCH_TRAINER_TRENT,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_SAWYER] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_SAWYER,
        .rematchTrainerId = REMATCH_TRAINER_SAWYER,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_KIRA_AND_DAN] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_KIRA_AND_DAN,
        .rematchTrainerId = REMATCH_TRAINER_KIRA_AND_DAN,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_WALLY] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_WALLY,
        .rematchTrainerId = REMATCH_TRAINER_WALLY,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_ROXANNE] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_ROXANNE,
        .rematchTrainerId = REMATCH_TRAINER_ROXANNE,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_BRAWLY] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_BRAWLY,
        .rematchTrainerId = REMATCH_TRAINER_BRAWLY,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_WATTSON] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_WATTSON,
        .rematchTrainerId = REMATCH_TRAINER_WATTSON,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_FLANNERY] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_FLANNERY,
        .rematchTrainerId = REMATCH_TRAINER_FLANNERY,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_NORMAN] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_NORMAN,
        .rematchTrainerId = REMATCH_TRAINER_NORMAN,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_WINONA] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_WINONA,
        .rematchTrainerId = REMATCH_TRAINER_WINONA,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_TATE_AND_LIZA] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_TATE_AND_LIZA,
        .rematchTrainerId = REMATCH_TRAINER_TATE_AND_LIZA,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_JUAN] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_JUAN,
        .rematchTrainerId = REMATCH_TRAINER_JUAN,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_SIDNEY] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_SIDNEY,
        .rematchTrainerId = REMATCH_TRAINER_SIDNEY,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_PHOEBE] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_PHOEBE,
        .rematchTrainerId = REMATCH_TRAINER_PHOEBE,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_GLACIA] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_GLACIA,
        .rematchTrainerId = REMATCH_TRAINER_GLACIA,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_DRAKE] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_DRAKE,
        .rematchTrainerId = REMATCH_TRAINER_DRAKE,
        .isPermanent = FALSE,
    },
    [PHONE_CONTACT_WALLACE] = {
        .customDisplayName = NULL,
        .updateState = NULL,
        .isAvailable = IsAvailable_Always,
        .canAcceptRematch = NULL,
        .registeredFlag = FLAG_PHONE_CARD_WALLACE,
        .rematchTrainerId = REMATCH_TRAINER_WALLACE,
        .isPermanent = FALSE,
    },
};

static bool8 IsAvailable_Always(s8 dayOfWeek, s8 hour)
{
    return TRUE;
}
