Route34_IlexEastGatehouse_MapScripts::
	.byte 0


Route34_IlexEastGatehouse_EventScript_Officer::
	msgbox Route34_IlexEastGatehouse_EventScript_Officer_Text_0, MSGBOX_NPC
	return


Route34_IlexEastGatehouse_EventScript_OldWoman::
	msgbox Route34_IlexEastGatehouse_EventScript_OldWoman_Text_0, MSGBOX_NPC
	return


Route34_IlexEastGatehouse_EventScript_Officer_Text_0:
	.string "ILEX FOREST is big. Be careful!\n"
	.string "Don't get lost.$"

Route34_IlexEastGatehouse_EventScript_OldWoman_Text_0:
	.string "The FOREST is watched over by\n"
	.string "its protector.\l"
	.string "Stay out of mischief!$"
