	.align 2
gTilesetTiles_NewBark::
	.incbin "data/tilesets/secondary/new_bark/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_NewBark::
	.incbin "data/tilesets/secondary/new_bark/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/15.gbapal"

	.align 2
gTilesetTiles_Goldenrod::
	.incbin "data/tilesets/secondary/goldenrod/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Rustboro::
	.incbin "data/tilesets/secondary/goldenrod/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/15.gbapal"

	.align 2
gTilesetTiles_Violet::
	.incbin "data/tilesets/secondary/violet/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Violet::
	.incbin "data/tilesets/secondary/violet/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/15.gbapal"

	.align 2
gTilesetTiles_Slateport::
	.incbin "data/tilesets/secondary/slateport/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Slateport::
	.incbin "data/tilesets/secondary/slateport/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/15.gbapal"

	.align 2
gTilesetTiles_Mauville::
	.incbin "data/tilesets/secondary/mauville/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Mauville::
	.incbin "data/tilesets/secondary/mauville/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/15.gbapal"

	.align 2
gTilesetTiles_Azalea::
	.incbin "data/tilesets/secondary/azalea/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Azalea::
	.incbin "data/tilesets/secondary/azalea/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/15.gbapal"

	.align 2
gTilesetTiles_Fallarbor::
	.incbin "data/tilesets/secondary/fallarbor/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Fallarbor::
	.incbin "data/tilesets/secondary/fallarbor/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/15.gbapal"

	.align 2
gTilesetTiles_Fortree::
	.incbin "data/tilesets/secondary/fortree/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Fortree::
	.incbin "data/tilesets/secondary/fortree/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/15.gbapal"

	.align 2
gTilesetTiles_Lilycove::
	.incbin "data/tilesets/secondary/lilycove/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Lilycove::
	.incbin "data/tilesets/secondary/lilycove/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/15.gbapal"

	.align 2
gTilesetTiles_Mossdeep::
	.incbin "data/tilesets/secondary/mossdeep/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Mossdeep::
	.incbin "data/tilesets/secondary/mossdeep/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/15.gbapal"

	.align 2
gTilesetTiles_EverGrande::
	.incbin "data/tilesets/secondary/ever_grande/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_EverGrande::
	.incbin "data/tilesets/secondary/ever_grande/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/15.gbapal"

	.align 2
gTilesetTiles_Pacifidlog::
	.incbin "data/tilesets/secondary/pacifidlog/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Pacifidlog::
	.incbin "data/tilesets/secondary/pacifidlog/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/15.gbapal"

	.align 2
gTilesetTiles_Sootopolis::
	.incbin "data/tilesets/secondary/sootopolis/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Sootopolis::
	.incbin "data/tilesets/secondary/sootopolis/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontierOutsideWest::
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontierOutsideWest::
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontierOutsideEast::
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontierOutsideEast::
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/15.gbapal"

	.align 2
gTilesetTiles_InsideBuilding::
	.incbin "data/tilesets/primary/building/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_InsideBuilding::
	.incbin "data/tilesets/primary/building/palettes/00.gbapal"
	.incbin "data/tilesets/primary/building/palettes/01.gbapal"
	.incbin "data/tilesets/primary/building/palettes/02.gbapal"
	.incbin "data/tilesets/primary/building/palettes/03.gbapal"
	.incbin "data/tilesets/primary/building/palettes/04.gbapal"
	.incbin "data/tilesets/primary/building/palettes/05.gbapal"
	.incbin "data/tilesets/primary/building/palettes/06.gbapal"
	.incbin "data/tilesets/primary/building/palettes/07.gbapal"
	.incbin "data/tilesets/primary/building/palettes/08.gbapal"
	.incbin "data/tilesets/primary/building/palettes/09.gbapal"
	.incbin "data/tilesets/primary/building/palettes/10.gbapal"
	.incbin "data/tilesets/primary/building/palettes/11.gbapal"
	.incbin "data/tilesets/primary/building/palettes/12.gbapal"
	.incbin "data/tilesets/primary/building/palettes/13.gbapal"
	.incbin "data/tilesets/primary/building/palettes/14.gbapal"
	.incbin "data/tilesets/primary/building/palettes/15.gbapal"

	.align 2
gTilesetTiles_Shop::
	.incbin "data/tilesets/secondary/shop/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Shop::
	.incbin "data/tilesets/secondary/shop/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonCenter::
	.incbin "data/tilesets/secondary/pokemon_center/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonCenter::
	.incbin "data/tilesets/secondary/pokemon_center/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/15.gbapal"

	.align 2
gTilesetTiles_Cave::
	.incbin "data/tilesets/secondary/cave/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Cave::
	.incbin "data/tilesets/secondary/cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonSchool::
	.incbin "data/tilesets/secondary/pokemon_school/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonSchool::
	.incbin "data/tilesets/secondary/pokemon_school/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/15.gbapal"

	.align 2
gTilesetTiles_RadioTower::
	.incbin "data/tilesets/secondary/radio_tower/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_RadioTower::
	.incbin "data/tilesets/secondary/radio_tower/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/15.gbapal"

	.align 2
gTilesetTiles_Gatehouse::
	.incbin "data/tilesets/secondary/gatehouse/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Gatehouse::
	.incbin "data/tilesets/secondary/gatehouse/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/15.gbapal"

	.align 2
gTilesetTiles_RockTunnel::
	.incbin "data/tilesets/secondary/rock_tunnel/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_RockTunnel::
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/15.gbapal"

	.align 2
gTilesetTiles_Underground::
	.incbin "data/tilesets/secondary/underground/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Underground::
	.incbin "data/tilesets/secondary/underground/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/15.gbapal"

	.align 2
gTilesetTiles_CableClub::
	.incbin "data/tilesets/secondary/cable_club/tiles.4bpp"

	.align 2
	.incbin "data/tilesets/secondary/cable_club/unknown_tiles.4bpp"

	.align 2
gTilesetPalettes_CableClub::
	.incbin "data/tilesets/secondary/cable_club/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/15.gbapal"

	.align 2
gTilesetTiles_PagodaTower::
	.incbin "data/tilesets/secondary/pagoda_tower/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PagodaTower::
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/15.gbapal"

	.align 2
gTilesetTiles_RuinsOfAlph::
	.incbin "data/tilesets/secondary/ruins_of_alph/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_RuinsOfAlph::
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonDayCare::
	.incbin "data/tilesets/secondary/pokemon_day_care/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonDayCare::
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/15.gbapal"

	.align 2
gTilesetTiles_Facility::
	.incbin "data/tilesets/secondary/facility/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Facility::
	.incbin "data/tilesets/secondary/facility/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/15.gbapal"

	.align 2
gTilesetTiles_BikeShop::
	.incbin "data/tilesets/secondary/bike_shop/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BikeShop::
	.incbin "data/tilesets/secondary/bike_shop/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/15.gbapal"

	.align 2
gTilesetTiles_Forest::
	.incbin "data/tilesets/secondary/forest/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Forest::
	.incbin "data/tilesets/secondary/forest/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/brown_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseBrownCave::
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/tree/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseTree::
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/shrub/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseShrub::
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/blue_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseBlueCave::
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseYellowCave::
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/red_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseRedCave::
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/15.gbapal"

	.align 2
gTilesetTiles_SecretBaseBrownCave::
	.incbin "data/tilesets/secondary/secret_base/brown_cave/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseTree::
	.incbin "data/tilesets/secondary/secret_base/tree/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseShrub::
	.incbin "data/tilesets/secondary/secret_base/shrub/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseBlueCave::
	.incbin "data/tilesets/secondary/secret_base/blue_cave/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseYellowCave::
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseRedCave::
	.incbin "data/tilesets/secondary/secret_base/red_cave/tiles.4bpp"

	.align 2
gTilesetTiles_MagnetTrain::
	.incbin "data/tilesets/secondary/magnet_train/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MagnetTrain::
	.incbin "data/tilesets/secondary/magnet_train/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/15.gbapal"

	.align 2
gTilesetTiles_Contest::
	.incbin "data/tilesets/secondary/contest/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Contest::
	.incbin "data/tilesets/secondary/contest/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/15.gbapal"

	.align 2
gTilesetTiles_LilycoveMuseum::
	.incbin "data/tilesets/secondary/lilycove_museum/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_LilycoveMuseum::
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/15.gbapal"

	.align 2
gTilesetTiles_PlayersHouse::
	.incbin "data/tilesets/secondary/players_house/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PlayersHouse::
	.incbin "data/tilesets/secondary/players_house/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/15.gbapal"

	.align 2
gTilesetTiles_Lab::
	.incbin "data/tilesets/secondary/lab/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Lab::
	.incbin "data/tilesets/secondary/lab/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/15.gbapal"

	.align 2
gTilesetTiles_Underwater::
	.incbin "data/tilesets/secondary/underwater/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Underwater::
	.incbin "data/tilesets/secondary/underwater/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/15.gbapal"

	.align 2
gTilesetTiles_GenericBuilding::
	.incbin "data/tilesets/secondary/generic_building/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_GenericBuilding::
	.incbin "data/tilesets/secondary/generic_building/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/15.gbapal"

	.align 2
gTilesetTiles_GameCorner::
	.incbin "data/tilesets/secondary/game_corner/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_GameCorner::
	.incbin "data/tilesets/secondary/game_corner/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/15.gbapal"

	.align 2
gTilesetTiles_DepartmentStore::
	.incbin "data/tilesets/secondary/department_store/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_DepartmentStore::
	.incbin "data/tilesets/secondary/department_store/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/15.gbapal"

	.align 2
gTilesetTiles_GoldenrodGym::
	.incbin "data/tilesets/secondary/goldenrod_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_GoldenrodGym::
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_AzaleaGym::
	.incbin "data/tilesets/secondary/azalea_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_AzaleaGym::
	.incbin "data/tilesets/secondary/azalea_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_MauvilleGym::
	.incbin "data/tilesets/secondary/mauville_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MauvilleGym::
	.incbin "data/tilesets/secondary/mauville_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_LavaridgeGym::
	.incbin "data/tilesets/secondary/lavaridge_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_LavaridgeGym::
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_BurnedTower::
	.incbin "data/tilesets/secondary/burned_tower/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BurnedTower::
	.incbin "data/tilesets/secondary/burned_tower/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/burned_tower/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/burned_tower/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/burned_tower/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/burned_tower/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/burned_tower/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/burned_tower/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/burned_tower/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/burned_tower/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/burned_tower/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/burned_tower/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/burned_tower/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/burned_tower/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/burned_tower/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/burned_tower/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/burned_tower/palettes/15.gbapal"

	.align 2
gTilesetTiles_FortreeGym::
	.incbin "data/tilesets/secondary/fortree_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_FortreeGym::
	.incbin "data/tilesets/secondary/fortree_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_MossdeepGym::
	.incbin "data/tilesets/secondary/mossdeep_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MossdeepGym::
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_SootopolisGym::
	.incbin "data/tilesets/secondary/sootopolis_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SootopolisGym::
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_TrickHousePuzzle::
	.incbin "data/tilesets/secondary/trick_house_puzzle/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_TrickHousePuzzle::
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/15.gbapal"

	.align 2
gTilesetTiles_InsideShip::
	.incbin "data/tilesets/secondary/inside_ship/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_InsideShip::
	.incbin "data/tilesets/secondary/inside_ship/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/15.gbapal"

	.align 2
gTilesetTiles_SecretBase::
	.incbin "data/tilesets/primary/secret_base/tiles.4bpp"

	.align 2
	.incbin "data/tilesets/primary/secret_base/unknown_tiles.4bpp"

	.align 2
gTilesetPalettes_SecretBase::
	.incbin "data/tilesets/primary/secret_base/palettes/00.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/01.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/02.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/03.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/04.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/05.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/06.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/07.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/08.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/09.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/10.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/11.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/12.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/13.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/14.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/15.gbapal"

	.align 2
gTilesetTiles_EliteFour::
	.incbin "data/tilesets/secondary/elite_four/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_EliteFour::
	.incbin "data/tilesets/secondary/elite_four/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontier::
	.incbin "data/tilesets/secondary/battle_frontier/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontier::
	.incbin "data/tilesets/secondary/battle_frontier/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattlePalace::
	.incbin "data/tilesets/secondary/battle_palace/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattlePalace::
	.incbin "data/tilesets/secondary/battle_palace/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleDome::
	.incbin "data/tilesets/secondary/battle_dome/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleDome::
	.incbin "data/tilesets/secondary/battle_dome/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFactory::
	.incbin "data/tilesets/secondary/battle_factory/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFactory::
	.incbin "data/tilesets/secondary/battle_factory/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattlePike::
	.incbin "data/tilesets/secondary/battle_pike/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattlePike::
	.incbin "data/tilesets/secondary/battle_pike/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleArena::
	.incbin "data/tilesets/secondary/battle_arena/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleArena::
	.incbin "data/tilesets/secondary/battle_arena/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattlePyramid::
	.incbin "data/tilesets/secondary/battle_pyramid/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattlePyramid::
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/15.gbapal"

	.align 2
gTilesetTiles_MirageTower::
	.incbin "data/tilesets/secondary/mirage_tower/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MirageTower::
	.incbin "data/tilesets/secondary/mirage_tower/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/15.gbapal"

	.align 2
gTilesetTiles_MossdeepGameCorner::
	.incbin "data/tilesets/secondary/mossdeep_game_corner/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MossdeepGameCorner::
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/15.gbapal"

	.align 2
gTilesetTiles_IslandHarbor::
	.incbin "data/tilesets/secondary/island_harbor/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_IslandHarbor::
	.incbin "data/tilesets/secondary/island_harbor/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/15.gbapal"

	.align 2
gTilesetTiles_TrainerHill::
	.incbin "data/tilesets/secondary/trainer_hill/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_TrainerHill::
	.incbin "data/tilesets/secondary/trainer_hill/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/15.gbapal"

	.align 2
gTilesetTiles_NavelRock::
	.incbin "data/tilesets/secondary/navel_rock/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_NavelRock::
	.incbin "data/tilesets/secondary/navel_rock/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontierRankingHall::
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontierRankingHall::
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleTent::
	.incbin "data/tilesets/secondary/battle_tent/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleTent::
	.incbin "data/tilesets/secondary/battle_tent/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/15.gbapal"

	.align 2
gTilesetTiles_MysteryEventsHouse::
	.incbin "data/tilesets/secondary/mystery_events_house/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MysteryEventsHouse::
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/15.gbapal"

	.align 2
gTilesetPalettes_UnionRoom::
	.incbin "data/tilesets/secondary/union_room/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/15.gbapal"

	.align 2
gTilesetTiles_UnionRoom::
	.incbin "data/tilesets/secondary/union_room/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_NationalPark::
	.incbin "data/tilesets/secondary/national_park/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/15.gbapal"

	.align 2
gTilesetTiles_NationalPark::
	.incbin "data/tilesets/secondary/national_park/tiles.4bpp.lz"

	.align 2
gTilesetPalOverride_General02::
	.incbin "data/tilesets/primary/general/palettes/02_over.gbapal"

	.align 2
gTilesetPalOverride_General07::
	.incbin "data/tilesets/primary/general/palettes/07_over.gbapal"

	.align 2
gTilesetPalOverride_NewBark08::
	.incbin "data/tilesets/secondary/new_bark/palettes/08_over.gbapal"

	.align 2
gTilesetPalOverride_Violet08::
	.incbin "data/tilesets/secondary/violet/palettes/08_over.gbapal"

	.align 2
gTilesetPalOverride_Violet09::
	.incbin "data/tilesets/secondary/violet/palettes/09_over.gbapal"

	.align 2
gTilesetPalOverride_Azalea09::
	.incbin "data/tilesets/secondary/azalea/palettes/09_over.gbapal"

	.align 2
gTilesetPalOverride_Goldenrod08::
	.incbin "data/tilesets/secondary/goldenrod/palettes/08_over.gbapal"

	.align 2
gTilesetPalOverride_Goldenrod09::
	.incbin "data/tilesets/secondary/goldenrod/palettes/09_over.gbapal"

	.align 2
gTilesetPalOverride_Goldenrod10::
	.incbin "data/tilesets/secondary/goldenrod/palettes/10_over.gbapal"

	.align 2
gTilesetPalOverride_Goldenrod12::
	.incbin "data/tilesets/secondary/goldenrod/palettes/12_over.gbapal"

	.align 2
gTilesetPalOverride_DeptStore09NoWin::
	.incbin "data/tilesets/secondary/department_store/palettes/09_over_nowin.gbapal"

	.align 2
gTilesetPalOverride_DeptStore09Win::
	.incbin "data/tilesets/secondary/department_store/palettes/09_over_win.gbapal"

gTilesetPalOverride_EcruteakCity09::
	.incbin "data/tilesets/secondary/ecruteakcity/palettes/09_over.gbapal"

gTilesetPalOverride_Olivine12::
	.incbin "data/tilesets/secondary/olivinecity/palettes/12_over.gbapal"

gTilesetPalOverride_Olivine10::
	.incbin "data/tilesets/secondary/olivinecity/palettes/10_over.gbapal"

gTilesetPalOverrides_VermilionCity11::
	.incbin "data/tilesets/secondary/vermilioncity/palettes/11_over.gbapal"

gTilesetPalOverrides_IndigoPlateau10::
	.incbin "data/tilesets/secondary/indigoplateau/palettes/10_over.gbapal"

gTilesetPalOverride_Saffron08::
	.incbin "data/tilesets/secondary/saffroncity/palettes/08_over.gbapal"

gTilesetPalOverride_Saffron11::
	.incbin "data/tilesets/secondary/saffroncity/palettes/11_over.gbapal"

gTilesetPalOverride_Saffron12::
	.incbin "data/tilesets/secondary/saffroncity/palettes/12_over.gbapal"

gTilesetPalOverride_Pallet08::
	.incbin "data/tilesets/secondary/pallettown/palettes/08_over.gbapal"

gTilesetPalOverride_Viridian12::
	.incbin "data/tilesets/secondary/viridiancity/palettes/12_over.gbapal"

gTilesetPalOverride_Fuchsia08::
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/08_over.gbapal"

gTilesetPalOverride_Pewter08::
	.incbin "data/tilesets/secondary/pewtercity/palettes/08_over.gbapal"

gTilesetPalOverride_Pewter11::
	.incbin "data/tilesets/secondary/pewtercity/palettes/11_over.gbapal"

gTilesetPalOverride_Lavender11::
	.incbin "data/tilesets/secondary/lavendertown/palettes/11_over.gbapal"

gTilesetPalOverride_CeladonMansion07::
	.incbin "data/tilesets/secondary/celadonmansion/palettes/07_over.gbapal"

gTilesetPalOverride_DragonsDen_Shrine08::
	.incbin "data/tilesets/secondary/dragonsden_shrine/palettes/08_over.gbapal"

gTilesetPalOverride_DragonsDen_Shrine09::
	.incbin "data/tilesets/secondary/dragonsden_shrine/palettes/09_over.gbapal"

	.align 2
gTilesetPalettes_PalletTown::
	.incbin "data/tilesets/secondary/pallettown/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/12.gbapal"

	.align 2
gTilesetTiles_PalletTown::
	.incbin "data/tilesets/secondary/pallettown/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_ViridianCity::
	.incbin "data/tilesets/secondary/viridiancity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/12.gbapal"

	.align 2
gTilesetTiles_ViridianCity::
	.incbin "data/tilesets/secondary/viridiancity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PewterCity::
	.incbin "data/tilesets/secondary/pewtercity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/12.gbapal"

	.align 2
gTilesetTiles_PewterCity::
	.incbin "data/tilesets/secondary/pewtercity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeruleanCity::
	.incbin "data/tilesets/secondary/ceruleancity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/12.gbapal"

	.align 2
gTilesetTiles_CeruleanCity::
	.incbin "data/tilesets/secondary/ceruleancity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_LavenderTown::
	.incbin "data/tilesets/secondary/lavendertown/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/12.gbapal"

	.align 2
gTilesetTiles_LavenderTown::
	.incbin "data/tilesets/secondary/lavendertown/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_VermilionCity::
	.incbin "data/tilesets/secondary/vermilioncity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/12.gbapal"

	.align 2
gTilesetTiles_VermilionCity::
	.incbin "data/tilesets/secondary/vermilioncity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeladonCity::
	.incbin "data/tilesets/secondary/celadoncity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/12.gbapal"

	.align 2
gTilesetTiles_CeladonCity::
	.incbin "data/tilesets/secondary/celadoncity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_FuchsiaCity::
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/12.gbapal"

	.align 2
gTilesetTiles_FuchsiaCity::
	.incbin "data/tilesets/secondary/fuchsiacity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_IndigoPlateau::
	.incbin "data/tilesets/secondary/indigoplateau/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/12.gbapal"

	.align 2
gTilesetTiles_IndigoPlateau::
	.incbin "data/tilesets/secondary/indigoplateau/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SaffronCity::
	.incbin "data/tilesets/secondary/saffroncity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/12.gbapal"

	.align 2
gTilesetTiles_SaffronCity::
	.incbin "data/tilesets/secondary/saffroncity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_GeneralKanto::
	.incbin "data/tilesets/primary/generalkanto/palettes/00.gbapal"
	.incbin "data/tilesets/primary/generalkanto/palettes/01.gbapal"
	.incbin "data/tilesets/primary/generalkanto/palettes/02.gbapal"
	.incbin "data/tilesets/primary/generalkanto/palettes/03.gbapal"
	.incbin "data/tilesets/primary/generalkanto/palettes/04.gbapal"
	.incbin "data/tilesets/primary/generalkanto/palettes/05.gbapal"
	.incbin "data/tilesets/primary/generalkanto/palettes/06.gbapal"
	.incbin "data/tilesets/primary/generalkanto/palettes/07.gbapal"
	.incbin "data/tilesets/primary/generalkanto/palettes/08.gbapal"
	.incbin "data/tilesets/primary/generalkanto/palettes/09.gbapal"
	.incbin "data/tilesets/primary/generalkanto/palettes/10.gbapal"
	.incbin "data/tilesets/primary/generalkanto/palettes/11.gbapal"
	.incbin "data/tilesets/primary/generalkanto/palettes/12.gbapal"

	.align 2
gTilesetTiles_GeneralKanto::
	.incbin "data/tilesets/primary/generalkanto/tiles.4bpp.lz"


	.align 2
gTilesetPalettes_RedsHouse::
	.incbin "data/tilesets/secondary/redshouse/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/redshouse/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/redshouse/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/redshouse/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/redshouse/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/redshouse/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/redshouse/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/redshouse/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/redshouse/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/redshouse/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/redshouse/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/redshouse/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/redshouse/palettes/12.gbapal"

	.align 2
gTilesetTiles_RedsHouse::
	.incbin "data/tilesets/secondary/redshouse/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_ViridianGym::
	.incbin "data/tilesets/secondary/viridiangym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/viridiangym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/viridiangym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/viridiangym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/viridiangym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/viridiangym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/viridiangym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/viridiangym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/viridiangym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/viridiangym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/viridiangym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/viridiangym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/viridiangym/palettes/12.gbapal"

	.align 2
gTilesetTiles_ViridianGym::
	.incbin "data/tilesets/secondary/viridiangym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PewterGym::
	.incbin "data/tilesets/secondary/pewtergym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pewtergym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pewtergym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pewtergym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pewtergym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pewtergym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pewtergym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pewtergym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pewtergym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pewtergym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pewtergym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pewtergym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pewtergym/palettes/12.gbapal"

	.align 2
gTilesetTiles_PewterGym::
	.incbin "data/tilesets/secondary/pewtergym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PewterMuseum::
	.incbin "data/tilesets/secondary/pewtermuseum/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pewtermuseum/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pewtermuseum/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pewtermuseum/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pewtermuseum/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pewtermuseum/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pewtermuseum/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pewtermuseum/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pewtermuseum/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pewtermuseum/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pewtermuseum/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pewtermuseum/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pewtermuseum/palettes/12.gbapal"

	.align 2
gTilesetTiles_PewterMuseum::
	.incbin "data/tilesets/secondary/pewtermuseum/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeruleanGym::
	.incbin "data/tilesets/secondary/ceruleangym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ceruleangym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ceruleangym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ceruleangym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ceruleangym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ceruleangym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ceruleangym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ceruleangym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ceruleangym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ceruleangym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ceruleangym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ceruleangym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ceruleangym/palettes/12.gbapal"

	.align 2
gTilesetTiles_CeruleanGym::
	.incbin "data/tilesets/secondary/ceruleangym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_VermilionGym::
	.incbin "data/tilesets/secondary/vermiliongym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/vermiliongym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/vermiliongym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/vermiliongym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/vermiliongym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/vermiliongym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/vermiliongym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/vermiliongym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/vermiliongym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/vermiliongym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/vermiliongym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/vermiliongym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/vermiliongym/palettes/12.gbapal"

	.align 2
gTilesetTiles_VermilionGym::
	.incbin "data/tilesets/secondary/vermiliongym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SoulHouse::
	.incbin "data/tilesets/secondary/soulhouse/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/soulhouse/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/soulhouse/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/soulhouse/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/soulhouse/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/soulhouse/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/soulhouse/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/soulhouse/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/soulhouse/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/soulhouse/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/soulhouse/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/soulhouse/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/soulhouse/palettes/12.gbapal"

	.align 2
gTilesetTiles_SoulHouse::
	.incbin "data/tilesets/secondary/soulhouse/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_RestaurantHotel::
	.incbin "data/tilesets/secondary/restauranthotel/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/restauranthotel/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/restauranthotel/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/restauranthotel/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/restauranthotel/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/restauranthotel/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/restauranthotel/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/restauranthotel/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/restauranthotel/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/restauranthotel/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/restauranthotel/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/restauranthotel/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/restauranthotel/palettes/12.gbapal"

	.align 2
gTilesetTiles_RestaurantHotel::
	.incbin "data/tilesets/secondary/restauranthotel/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeladonMansion::
	.incbin "data/tilesets/secondary/celadonmansion/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/celadonmansion/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/celadonmansion/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/celadonmansion/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/celadonmansion/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/celadonmansion/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/celadonmansion/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/celadonmansion/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/celadonmansion/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/celadonmansion/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/celadonmansion/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/celadonmansion/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/celadonmansion/palettes/12.gbapal"

	.align 2
gTilesetTiles_CeladonMansion::
	.incbin "data/tilesets/secondary/celadonmansion/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SaffronGym::
	.incbin "data/tilesets/secondary/saffrongym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/saffrongym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/saffrongym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/saffrongym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/saffrongym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/saffrongym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/saffrongym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/saffrongym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/saffrongym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/saffrongym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/saffrongym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/saffrongym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/saffrongym/palettes/12.gbapal"

	.align 2
gTilesetTiles_SaffronGym::
	.incbin "data/tilesets/secondary/saffrongym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SafariZoneHouse::
	.incbin "data/tilesets/secondary/safarizonehouse/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/safarizonehouse/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/safarizonehouse/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/safarizonehouse/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/safarizonehouse/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/safarizonehouse/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/safarizonehouse/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/safarizonehouse/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/safarizonehouse/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/safarizonehouse/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/safarizonehouse/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/safarizonehouse/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/safarizonehouse/palettes/12.gbapal"

	.align 2
gTilesetTiles_SafariZoneHouse::
	.incbin "data/tilesets/secondary/safarizonehouse/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_FuchsiaGym::
	.incbin "data/tilesets/secondary/fuchsiagym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fuchsiagym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fuchsiagym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fuchsiagym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fuchsiagym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fuchsiagym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fuchsiagym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fuchsiagym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fuchsiagym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fuchsiagym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fuchsiagym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fuchsiagym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fuchsiagym/palettes/12.gbapal"

	.align 2
gTilesetTiles_FuchsiaGym::
	.incbin "data/tilesets/secondary/fuchsiagym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_HallOfFame::
	.incbin "data/tilesets/secondary/halloffame/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/halloffame/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/halloffame/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/halloffame/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/halloffame/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/halloffame/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/halloffame/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/halloffame/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/halloffame/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/halloffame/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/halloffame/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/halloffame/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/halloffame/palettes/12.gbapal"

	.align 2
gTilesetTiles_HallOfFame::
	.incbin "data/tilesets/secondary/halloffame/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PowerPlant::
	.incbin "data/tilesets/secondary/powerplant/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/powerplant/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/powerplant/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/powerplant/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/powerplant/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/powerplant/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/powerplant/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/powerplant/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/powerplant/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/powerplant/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/powerplant/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/powerplant/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/powerplant/palettes/12.gbapal"

	.align 2
gTilesetTiles_PowerPlant::
	.incbin "data/tilesets/secondary/powerplant/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_DiglettsCave::
	.incbin "data/tilesets/secondary/diglettscave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/12.gbapal"

	.align 2
gTilesetTiles_DiglettsCave::
	.incbin "data/tilesets/secondary/diglettscave/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BlackthornCity::
	.incbin "data/tilesets/secondary/blackthorncity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/blackthorncity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/blackthorncity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/blackthorncity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/blackthorncity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/blackthorncity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/blackthorncity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/blackthorncity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/blackthorncity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/blackthorncity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/blackthorncity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/blackthorncity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/blackthorncity/palettes/12.gbapal"

	.align 2
gTilesetTiles_BlackthornCity::
	.incbin "data/tilesets/secondary/blackthorncity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MahoganyTown::
	.incbin "data/tilesets/secondary/mahoganytown/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mahoganytown/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mahoganytown/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mahoganytown/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mahoganytown/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mahoganytown/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mahoganytown/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mahoganytown/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mahoganytown/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mahoganytown/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mahoganytown/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mahoganytown/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mahoganytown/palettes/12.gbapal"

	.align 2
gTilesetTiles_MahoganyTown::
	.incbin "data/tilesets/secondary/mahoganytown/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_EcruteakCity::
	.incbin "data/tilesets/secondary/ecruteakcity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ecruteakcity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ecruteakcity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ecruteakcity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ecruteakcity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ecruteakcity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ecruteakcity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ecruteakcity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ecruteakcity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ecruteakcity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ecruteakcity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ecruteakcity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ecruteakcity/palettes/12.gbapal"

	.align 2
gTilesetTiles_EcruteakCity::
	.incbin "data/tilesets/secondary/ecruteakcity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_OlivineCity::
	.incbin "data/tilesets/secondary/olivinecity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/olivinecity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/olivinecity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/olivinecity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/olivinecity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/olivinecity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/olivinecity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/olivinecity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/olivinecity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/olivinecity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/olivinecity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/olivinecity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/olivinecity/palettes/12.gbapal"

	.align 2
gTilesetTiles_OlivineCity::
	.incbin "data/tilesets/secondary/olivinecity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Lighthouse::
	.incbin "data/tilesets/secondary/lighthouse/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lighthouse/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lighthouse/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lighthouse/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lighthouse/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lighthouse/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lighthouse/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lighthouse/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lighthouse/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lighthouse/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lighthouse/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lighthouse/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lighthouse/palettes/12.gbapal"

	.align 2
gTilesetTiles_Lighthouse::
	.incbin "data/tilesets/secondary/lighthouse/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_RocketHideout::
	.incbin "data/tilesets/secondary/rockethideout/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/rockethideout/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/rockethideout/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/rockethideout/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/rockethideout/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/rockethideout/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/rockethideout/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/rockethideout/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/rockethideout/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/rockethideout/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/rockethideout/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/rockethideout/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/rockethideout/palettes/12.gbapal"

	.align 2
gTilesetTiles_RocketHideout::
	.incbin "data/tilesets/secondary/rockethideout/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_IcePath::
	.incbin "data/tilesets/secondary/icepath/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/icepath/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/icepath/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/icepath/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/icepath/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/icepath/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/icepath/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/icepath/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/icepath/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/icepath/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/icepath/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/icepath/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/icepath/palettes/12.gbapal"

	.align 2
gTilesetTiles_IcePath::
	.incbin "data/tilesets/secondary/icepath/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_WhirlIslands::
	.incbin "data/tilesets/secondary/whirlislands/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/whirlislands/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/whirlislands/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/whirlislands/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/whirlislands/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/whirlislands/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/whirlislands/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/whirlislands/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/whirlislands/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/whirlislands/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/whirlislands/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/whirlislands/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/whirlislands/palettes/12.gbapal"

	.align 2
gTilesetTiles_WhirlIslands::
	.incbin "data/tilesets/secondary/whirlislands/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonLeague::
	.incbin "data/tilesets/secondary/pokemonleague/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemonleague/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemonleague/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemonleague/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemonleague/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemonleague/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemonleague/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemonleague/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemonleague/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemonleague/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemonleague/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemonleague/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemonleague/palettes/12.gbapal"

	.align 2
gTilesetTiles_PokemonLeague::
	.incbin "data/tilesets/secondary/pokemonleague/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_ChampionsRoom::
	.incbin "data/tilesets/secondary/championsroom/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/championsroom/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/championsroom/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/championsroom/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/championsroom/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/championsroom/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/championsroom/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/championsroom/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/championsroom/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/championsroom/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/championsroom/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/championsroom/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/championsroom/palettes/12.gbapal"

	.align 2
gTilesetTiles_ChampionsRoom::
	.incbin "data/tilesets/secondary/championsroom/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BlackthornGym::
	.incbin "data/tilesets/secondary/blackthorngym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/blackthorngym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/blackthorngym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/blackthorngym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/blackthorngym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/blackthorngym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/blackthorngym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/blackthorngym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/blackthorngym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/blackthorngym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/blackthorngym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/blackthorngym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/blackthorngym/palettes/12.gbapal"

	.align 2
gTilesetTiles_BlackthornGym::
	.incbin "data/tilesets/secondary/blackthorngym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontierPrimary::
	.incbin "data/tilesets/primary/battlefrontierprimary/palettes/00.gbapal"
	.incbin "data/tilesets/primary/battlefrontierprimary/palettes/01.gbapal"
	.incbin "data/tilesets/primary/battlefrontierprimary/palettes/02.gbapal"
	.incbin "data/tilesets/primary/battlefrontierprimary/palettes/03.gbapal"
	.incbin "data/tilesets/primary/battlefrontierprimary/palettes/04.gbapal"
	.incbin "data/tilesets/primary/battlefrontierprimary/palettes/05.gbapal"
	.incbin "data/tilesets/primary/battlefrontierprimary/palettes/06.gbapal"
	.incbin "data/tilesets/primary/battlefrontierprimary/palettes/07.gbapal"
	.incbin "data/tilesets/primary/battlefrontierprimary/palettes/08.gbapal"
	.incbin "data/tilesets/primary/battlefrontierprimary/palettes/09.gbapal"
	.incbin "data/tilesets/primary/battlefrontierprimary/palettes/10.gbapal"
	.incbin "data/tilesets/primary/battlefrontierprimary/palettes/11.gbapal"
	.incbin "data/tilesets/primary/battlefrontierprimary/palettes/12.gbapal"

	.align 2
gTilesetTiles_BattleFrontierPrimary::
	.incbin "data/tilesets/primary/battlefrontierprimary/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SilphCo::
	.incbin "data/tilesets/secondary/silphco/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/silphco/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/silphco/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/silphco/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/silphco/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/silphco/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/silphco/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/silphco/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/silphco/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/silphco/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/silphco/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/silphco/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/silphco/palettes/12.gbapal"

	.align 2
gTilesetTiles_SilphCo::
	.incbin "data/tilesets/secondary/silphco/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SaffronGeneral::
	.incbin "data/tilesets/primary/saffrongeneral/palettes/00.gbapal"
	.incbin "data/tilesets/primary/saffrongeneral/palettes/01.gbapal"
	.incbin "data/tilesets/primary/saffrongeneral/palettes/02.gbapal"
	.incbin "data/tilesets/primary/saffrongeneral/palettes/03.gbapal"
	.incbin "data/tilesets/primary/saffrongeneral/palettes/04.gbapal"
	.incbin "data/tilesets/primary/saffrongeneral/palettes/05.gbapal"
	.incbin "data/tilesets/primary/saffrongeneral/palettes/06.gbapal"
	.incbin "data/tilesets/primary/saffrongeneral/palettes/07.gbapal"
	.incbin "data/tilesets/primary/saffrongeneral/palettes/08.gbapal"
	.incbin "data/tilesets/primary/saffrongeneral/palettes/09.gbapal"
	.incbin "data/tilesets/primary/saffrongeneral/palettes/10.gbapal"
	.incbin "data/tilesets/primary/saffrongeneral/palettes/11.gbapal"
	.incbin "data/tilesets/primary/saffrongeneral/palettes/12.gbapal"

	.align 2
gTilesetTiles_SaffronGeneral::
	.incbin "data/tilesets/primary/saffrongeneral/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PlayersRoom::
	.incbin "data/tilesets/primary/playersroom/palettes/00.gbapal"
	.incbin "data/tilesets/primary/playersroom/palettes/01.gbapal"
	.incbin "data/tilesets/primary/playersroom/palettes/02.gbapal"
	.incbin "data/tilesets/primary/playersroom/palettes/03.gbapal"
	.incbin "data/tilesets/primary/playersroom/palettes/04.gbapal"
	.incbin "data/tilesets/primary/playersroom/palettes/05.gbapal"
	.incbin "data/tilesets/primary/playersroom/palettes/06.gbapal"
	.incbin "data/tilesets/primary/playersroom/palettes/07.gbapal"
	.incbin "data/tilesets/primary/playersroom/palettes/08.gbapal"
	.incbin "data/tilesets/primary/playersroom/palettes/09.gbapal"
	.incbin "data/tilesets/primary/playersroom/palettes/10.gbapal"
	.incbin "data/tilesets/primary/playersroom/palettes/11.gbapal"
	.incbin "data/tilesets/primary/playersroom/palettes/12.gbapal"

	.align 2
gTilesetTiles_PlayersRoom::
	.incbin "data/tilesets/primary/playersroom/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PlayersRoom2::
	.incbin "data/tilesets/secondary/playersroom2/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/playersroom2/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/playersroom2/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/playersroom2/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/playersroom2/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/playersroom2/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/playersroom2/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/playersroom2/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/playersroom2/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/playersroom2/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/playersroom2/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/playersroom2/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/playersroom2/palettes/12.gbapal"

	.align 2
gTilesetTiles_PlayersRoom2::
	.incbin "data/tilesets/secondary/playersroom2/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_VioletGym::
	.incbin "data/tilesets/secondary/violetgym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/violetgym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/violetgym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/violetgym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/violetgym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/violetgym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/violetgym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/violetgym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/violetgym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/violetgym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/violetgym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/violetgym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/violetgym/palettes/12.gbapal"

	.align 2
gTilesetTiles_VioletGym::
	.incbin "data/tilesets/secondary/violetgym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_DragonsDen_Shrine::
	.incbin "data/tilesets/secondary/dragonsden_shrine/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/dragonsden_shrine/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/dragonsden_shrine/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/dragonsden_shrine/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/dragonsden_shrine/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/dragonsden_shrine/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/dragonsden_shrine/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/dragonsden_shrine/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/dragonsden_shrine/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/dragonsden_shrine/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/dragonsden_shrine/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/dragonsden_shrine/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/dragonsden_shrine/palettes/12.gbapal"

	.align 2
gTilesetTiles_DragonsDen_Shrine::
	.incbin "data/tilesets/secondary/dragonsden_shrine/tiles.4bpp.lz"
