	.align 2
gTilesetTiles_NewBark:: @ 8339E08
	.incbin "data/tilesets/secondary/new_bark/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_NewBark:: @ 833A704
	.incbin "data/tilesets/secondary/new_bark/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/new_bark/palettes/15.gbapal"

	.align 2
gTilesetTiles_Goldenrod:: @ 833A904
	.incbin "data/tilesets/secondary/goldenrod/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Rustboro:: @ 833BEC0
	.incbin "data/tilesets/secondary/goldenrod/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/goldenrod/palettes/15.gbapal"

	.align 2
gTilesetTiles_Violet:: @ 833C0C0
	.incbin "data/tilesets/secondary/violet/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Violet:: @ 833D540
	.incbin "data/tilesets/secondary/violet/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/violet/palettes/15.gbapal"

	.align 2
gTilesetTiles_Slateport:: @ 833D740
	.incbin "data/tilesets/secondary/slateport/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Slateport:: @ 833F708
	.incbin "data/tilesets/secondary/slateport/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/15.gbapal"

	.align 2
gTilesetTiles_Mauville:: @ 833F908
	.incbin "data/tilesets/secondary/mauville/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Mauville:: @ 834172C
	.incbin "data/tilesets/secondary/mauville/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/15.gbapal"

	.align 2
gTilesetTiles_Azalea:: @ 834192C
	.incbin "data/tilesets/secondary/azalea/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Azalea:: @ 8342E28
	.incbin "data/tilesets/secondary/azalea/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/azalea/palettes/15.gbapal"

	.align 2
gTilesetTiles_Fallarbor:: @ 8343028
	.incbin "data/tilesets/secondary/fallarbor/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Fallarbor:: @ 83447A0
	.incbin "data/tilesets/secondary/fallarbor/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/15.gbapal"

	.align 2
gTilesetTiles_Fortree:: @ 83449A0
	.incbin "data/tilesets/secondary/fortree/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Fortree:: @ 8346020
	.incbin "data/tilesets/secondary/fortree/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/15.gbapal"

	.align 2
gTilesetTiles_Lilycove:: @ 8346220
	.incbin "data/tilesets/secondary/lilycove/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Lilycove:: @ 83475C0
	.incbin "data/tilesets/secondary/lilycove/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/15.gbapal"

	.align 2
gTilesetTiles_Mossdeep:: @ 83477C0
	.incbin "data/tilesets/secondary/mossdeep/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Mossdeep:: @ 8348E10
	.incbin "data/tilesets/secondary/mossdeep/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/15.gbapal"

	.align 2
gTilesetTiles_EverGrande:: @ 8349010
	.incbin "data/tilesets/secondary/ever_grande/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_EverGrande:: @ 8349C28
	.incbin "data/tilesets/secondary/ever_grande/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/15.gbapal"

	.align 2
gTilesetTiles_Pacifidlog:: @ 8349E28
	.incbin "data/tilesets/secondary/pacifidlog/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Pacifidlog:: @ 834B5B4
	.incbin "data/tilesets/secondary/pacifidlog/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/15.gbapal"

	.align 2
gTilesetTiles_Sootopolis:: @ 834B7B4
	.incbin "data/tilesets/secondary/sootopolis/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Sootopolis:: @ 834C6B4
	.incbin "data/tilesets/secondary/sootopolis/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontierOutsideWest:: @ 834C8B4
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontierOutsideWest:: @ 834E3E4
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontierOutsideEast:: @ 834E5E4
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontierOutsideEast:: @ 834F984
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/15.gbapal"

	.align 2
gTilesetTiles_InsideBuilding:: @ 834FB84
	.incbin "data/tilesets/primary/building/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_InsideBuilding:: @ 83508BC
	.incbin "data/tilesets/primary/building/palettes/00.gbapal"
	.incbin "data/tilesets/primary/building/palettes/01.gbapal"
	.incbin "data/tilesets/primary/building/palettes/02.gbapal"
	.incbin "data/tilesets/primary/building/palettes/03.gbapal"
	.incbin "data/tilesets/primary/building/palettes/04.gbapal"
	.incbin "data/tilesets/primary/building/palettes/05.gbapal"
	.incbin "data/tilesets/primary/building/palettes/06.gbapal"
	.incbin "data/tilesets/primary/building/palettes/07.gbapal"
	.incbin "data/tilesets/primary/building/palettes/08.gbapal"
	.incbin "data/tilesets/primary/building/palettes/09.gbapal"
	.incbin "data/tilesets/primary/building/palettes/10.gbapal"
	.incbin "data/tilesets/primary/building/palettes/11.gbapal"
	.incbin "data/tilesets/primary/building/palettes/12.gbapal"
	.incbin "data/tilesets/primary/building/palettes/13.gbapal"
	.incbin "data/tilesets/primary/building/palettes/14.gbapal"
	.incbin "data/tilesets/primary/building/palettes/15.gbapal"

	.align 2
gTilesetTiles_Shop:: @ 8350ABC
	.incbin "data/tilesets/secondary/shop/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Shop:: @ 83520DC
	.incbin "data/tilesets/secondary/shop/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonCenter:: @ 83522DC
	.incbin "data/tilesets/secondary/pokemon_center/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonCenter:: @ 8353574
	.incbin "data/tilesets/secondary/pokemon_center/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/15.gbapal"

	.align 2
gTilesetTiles_Cave:: @ 8353774
	.incbin "data/tilesets/secondary/cave/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Cave:: @ 8355260
	.incbin "data/tilesets/secondary/cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonSchool:: @ 8355460
	.incbin "data/tilesets/secondary/pokemon_school/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonSchool:: @ 8355BA8
	.incbin "data/tilesets/secondary/pokemon_school/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/15.gbapal"

	.align 2
gTilesetTiles_RadioTower:: @ 8355DA8
	.incbin "data/tilesets/secondary/radio_tower/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_RadioTower:: @ 83566D4
	.incbin "data/tilesets/secondary/radio_tower/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/radio_tower/palettes/15.gbapal"

	.align 2
gTilesetTiles_Gatehouse:: @ 83568D4
	.incbin "data/tilesets/secondary/gatehouse/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Gatehouse:: @ 8356920
	.incbin "data/tilesets/secondary/gatehouse/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/gatehouse/palettes/15.gbapal"

	.align 2
gTilesetTiles_RockTunnel:: @ 8356B20
	.incbin "data/tilesets/secondary/rock_tunnel/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_RockTunnel:: @ 8358840
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/15.gbapal"

	.align 2
gTilesetTiles_Underground:: @ 8358A40
	.incbin "data/tilesets/secondary/underground/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Underground:: @ 83599CC
	.incbin "data/tilesets/secondary/underground/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/underground/palettes/15.gbapal"

	.align 2
gTilesetTiles_CableClub:: @ 8359BCC
	.incbin "data/tilesets/secondary/cable_club/tiles.4bpp"

	.align 2
	.incbin "data/tilesets/secondary/cable_club/unknown_tiles.4bpp"

	.align 2
gTilesetPalettes_CableClub:: @ 835EACC
	.incbin "data/tilesets/secondary/cable_club/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/15.gbapal"

	.align 2
gTilesetTiles_PagodaTower:: @ 835ECCC
	.incbin "data/tilesets/secondary/pagoda_tower/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PagodaTower:: @ 835F5A8
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pagoda_tower/palettes/15.gbapal"

	.align 2
gTilesetTiles_RuinsOfAlph:: @ 835F7A8
	.incbin "data/tilesets/secondary/ruins_of_alph/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_RuinsOfAlph:: @ 83603A0
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/ruins_of_alph/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonDayCare:: @ 83605A0
	.incbin "data/tilesets/secondary/pokemon_day_care/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonDayCare:: @ 8360FDC
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/15.gbapal"

	.align 2
gTilesetTiles_Facility:: @ 83611DC
	.incbin "data/tilesets/secondary/facility/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Facility:: @ 8362E90
	.incbin "data/tilesets/secondary/facility/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/15.gbapal"

	.align 2
gTilesetTiles_BikeShop:: @ 8363090
	.incbin "data/tilesets/secondary/bike_shop/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BikeShop:: @ 83643C0
	.incbin "data/tilesets/secondary/bike_shop/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/15.gbapal"

	.align 2
gTilesetTiles_Forest:: @ 83645C0
	.incbin "data/tilesets/secondary/forest/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Forest:: @ 8365008
	.incbin "data/tilesets/secondary/forest/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/forest/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/brown_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseBrownCave:: @ 8365788
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/tree/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseTree:: @ 8365EAC
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/shrub/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseShrub:: @ 8366614
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/blue_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseBlueCave:: @ 8366C30
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseYellowCave:: @ 8367368
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/red_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseRedCave:: @ 83679A0
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/15.gbapal"

	.align 2
gTilesetTiles_SecretBaseBrownCave:: @ 8367BA0
	.incbin "data/tilesets/secondary/secret_base/brown_cave/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseTree:: @ 8368600
	.incbin "data/tilesets/secondary/secret_base/tree/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseShrub:: @ 8369060
	.incbin "data/tilesets/secondary/secret_base/shrub/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseBlueCave:: @ 8369AC0
	.incbin "data/tilesets/secondary/secret_base/blue_cave/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseYellowCave:: @ 836A520
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseRedCave:: @ 836AF80
	.incbin "data/tilesets/secondary/secret_base/red_cave/tiles.4bpp"

	.align 2
gTilesetTiles_MagnetTrain:: @ 836B9E0
	.incbin "data/tilesets/secondary/magnet_train/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MagnetTrain:: @ 836BC3C
	.incbin "data/tilesets/secondary/magnet_train/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/magnet_train/palettes/15.gbapal"

	.align 2
gTilesetTiles_Contest:: @ 836BE3C
	.incbin "data/tilesets/secondary/contest/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Contest:: @ 836C990
	.incbin "data/tilesets/secondary/contest/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/15.gbapal"

	.align 2
gTilesetTiles_LilycoveMuseum:: @ 836CB90
	.incbin "data/tilesets/secondary/lilycove_museum/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_LilycoveMuseum:: @ 836DEAC
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/15.gbapal"

	.align 2
gTilesetTiles_PlayersHouse:: @ 836E0AC
	.incbin "data/tilesets/secondary/players_house/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PlayersHouse:: @ 836F178
	.incbin "data/tilesets/secondary/players_house/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/players_house/palettes/15.gbapal"

	.align 2
gTilesetTiles_Lab:: @ 836F378
	.incbin "data/tilesets/secondary/lab/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Lab:: @ 83703DC
	.incbin "data/tilesets/secondary/lab/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/15.gbapal"

	.align 2
gTilesetTiles_Underwater:: @ 83705DC
	.incbin "data/tilesets/secondary/underwater/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Underwater:: @ 8371798
	.incbin "data/tilesets/secondary/underwater/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/15.gbapal"

	.align 2
gTilesetTiles_GenericBuilding:: @ 8371998
	.incbin "data/tilesets/secondary/generic_building/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_GenericBuilding:: @ 83733C4
	.incbin "data/tilesets/secondary/generic_building/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/15.gbapal"

	.align 2
gTilesetTiles_GameCorner:: @ 83735C4
	.incbin "data/tilesets/secondary/game_corner/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_GameCorner:: @ 8374288
	.incbin "data/tilesets/secondary/game_corner/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/15.gbapal"

	.align 2
gTilesetTiles_DepartmentStore:: @ 8374488
	.incbin "data/tilesets/secondary/department_store/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_DepartmentStore:: @ 83749B0
	.incbin "data/tilesets/secondary/department_store/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/department_store/palettes/15.gbapal"

	.align 2
gTilesetTiles_GoldenrodGym:: @ 8374BB0
	.incbin "data/tilesets/secondary/goldenrod_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_GoldenrodGym:: @ 8374F34
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/goldenrod_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_AzaleaGym:: @ 8375134
	.incbin "data/tilesets/secondary/azalea_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_AzaleaGym:: @ 8375400
	.incbin "data/tilesets/secondary/azalea_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/azalea_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_MauvilleGym:: @ 8375600
	.incbin "data/tilesets/secondary/mauville_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MauvilleGym:: @ 8375D84
	.incbin "data/tilesets/secondary/mauville_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_LavaridgeGym:: @ 8375F84
	.incbin "data/tilesets/secondary/lavaridge_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_LavaridgeGym:: @ 83762AC
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_VioletGym:: @ 83764AC
	.incbin "data/tilesets/secondary/violet_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_VioletGym:: @ 8376B50
	.incbin "data/tilesets/secondary/violet_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/violet_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/violet_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/violet_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/violet_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/violet_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/violet_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/violet_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/violet_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/violet_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/violet_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/violet_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/violet_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/violet_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/violet_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/violet_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_FortreeGym:: @ 8376D50
	.incbin "data/tilesets/secondary/fortree_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_FortreeGym:: @ 83770C4
	.incbin "data/tilesets/secondary/fortree_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_MossdeepGym:: @ 83772C4
	.incbin "data/tilesets/secondary/mossdeep_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MossdeepGym:: @ 8377730
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_SootopolisGym:: @ 8377930
	.incbin "data/tilesets/secondary/sootopolis_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SootopolisGym:: @ 8378AC4
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_TrickHousePuzzle:: @ 8378CC4
	.incbin "data/tilesets/secondary/trick_house_puzzle/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_TrickHousePuzzle:: @ 8379A78
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/15.gbapal"

	.align 2
gTilesetTiles_InsideShip:: @ 8379C78
	.incbin "data/tilesets/secondary/inside_ship/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_InsideShip:: @ 837A848
	.incbin "data/tilesets/secondary/inside_ship/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/15.gbapal"

	.align 2
gTilesetTiles_SecretBase:: @ 837AA48
	.incbin "data/tilesets/primary/secret_base/tiles.4bpp"

	.align 2
	.incbin "data/tilesets/primary/secret_base/unknown_tiles.4bpp"

	.align 2
gTilesetPalettes_SecretBase:: @ 8382A48
	.incbin "data/tilesets/primary/secret_base/palettes/00.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/01.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/02.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/03.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/04.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/05.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/06.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/07.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/08.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/09.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/10.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/11.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/12.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/13.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/14.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/15.gbapal"

	.align 2
gTilesetTiles_EliteFour:: @ 8382C48
	.incbin "data/tilesets/secondary/elite_four/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_EliteFour:: @ 8383CC4
	.incbin "data/tilesets/secondary/elite_four/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontier:: @ 8383EC4
	.incbin "data/tilesets/secondary/battle_frontier/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontier:: @ 8384BC8
	.incbin "data/tilesets/secondary/battle_frontier/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattlePalace:: @ 8384DC8
	.incbin "data/tilesets/secondary/battle_palace/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattlePalace:: @ 8385540
	.incbin "data/tilesets/secondary/battle_palace/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleDome:: @ 8385740
	.incbin "data/tilesets/secondary/battle_dome/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleDome:: @ 8386990
	.incbin "data/tilesets/secondary/battle_dome/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFactory:: @ 8386B90
	.incbin "data/tilesets/secondary/battle_factory/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFactory:: @ 8387D7C
	.incbin "data/tilesets/secondary/battle_factory/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattlePike:: @ 8387F7C
	.incbin "data/tilesets/secondary/battle_pike/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattlePike:: @ 8389250
	.incbin "data/tilesets/secondary/battle_pike/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleArena:: @ 8389450
	.incbin "data/tilesets/secondary/battle_arena/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleArena:: @ 8389F8C
	.incbin "data/tilesets/secondary/battle_arena/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattlePyramid:: @ 838A18C
	.incbin "data/tilesets/secondary/battle_pyramid/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattlePyramid:: @ 838B39C
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/15.gbapal"

	.align 2
gTilesetTiles_MirageTower:: @ 838B59C
	.incbin "data/tilesets/secondary/mirage_tower/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MirageTower:: @ 838CFE4
	.incbin "data/tilesets/secondary/mirage_tower/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/15.gbapal"

	.align 2
gTilesetTiles_MossdeepGameCorner:: @ 838D1E4
	.incbin "data/tilesets/secondary/mossdeep_game_corner/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MossdeepGameCorner:: @ 838D604
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/15.gbapal"

	.align 2
gTilesetTiles_IslandHarbor:: @ 838D804
	.incbin "data/tilesets/secondary/island_harbor/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_IslandHarbor:: @ 838F1D4
	.incbin "data/tilesets/secondary/island_harbor/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/15.gbapal"

	.align 2
gTilesetTiles_TrainerHill:: @ 838F3D4
	.incbin "data/tilesets/secondary/trainer_hill/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_TrainerHill:: @ 83904C4
	.incbin "data/tilesets/secondary/trainer_hill/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/15.gbapal"

	.align 2
gTilesetTiles_NavelRock:: @ 83906C4
	.incbin "data/tilesets/secondary/navel_rock/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_NavelRock:: @ 8392258
	.incbin "data/tilesets/secondary/navel_rock/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontierRankingHall:: @ 8392458
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontierRankingHall:: @ 8392CAC
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleTent:: @ 8392EAC
	.incbin "data/tilesets/secondary/battle_tent/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleTent:: @ 8393910
	.incbin "data/tilesets/secondary/battle_tent/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/15.gbapal"

	.align 2
gTilesetTiles_MysteryEventsHouse:: @ 8393B10
	.incbin "data/tilesets/secondary/mystery_events_house/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MysteryEventsHouse:: @ 8395478
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/15.gbapal"

	.align 2
gTilesetPalettes_UnionRoom:: @ 8395678
	.incbin "data/tilesets/secondary/union_room/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/15.gbapal"

	.align 2
gTilesetTiles_UnionRoom:: @ 8395878
	.incbin "data/tilesets/secondary/union_room/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_NationalPark::
	.incbin "data/tilesets/secondary/national_park/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/national_park/palettes/15.gbapal"

	.align 2
gTilesetTiles_NationalPark::
	.incbin "data/tilesets/secondary/national_park/tiles.4bpp.lz"

	.align 2
gTilesetPalOverride_General02::
	.incbin "data/tilesets/primary/general/palettes/02_over.gbapal"

	.align 2
gTilesetPalOverride_General07::
	.incbin "data/tilesets/primary/general/palettes/07_over.gbapal"

	.align 2
gTilesetPalOverride_NewBark08::
	.incbin "data/tilesets/secondary/new_bark/palettes/08_over.gbapal"

	.align 2
gTilesetPalOverride_Violet08::
	.incbin "data/tilesets/secondary/violet/palettes/08_over.gbapal"

	.align 2
gTilesetPalOverride_Violet09::
	.incbin "data/tilesets/secondary/violet/palettes/09_over.gbapal"

	.align 2
gTilesetPalOverride_Azalea09::
	.incbin "data/tilesets/secondary/azalea/palettes/09_over.gbapal"

	.align 2
gTilesetPalOverride_Goldenrod08::
	.incbin "data/tilesets/secondary/goldenrod/palettes/08_over.gbapal"

	.align 2
gTilesetPalOverride_Goldenrod09::
	.incbin "data/tilesets/secondary/goldenrod/palettes/09_over.gbapal"

	.align 2
gTilesetPalOverride_Goldenrod10::
	.incbin "data/tilesets/secondary/goldenrod/palettes/10_over.gbapal"

	.align 2
gTilesetPalOverride_Goldenrod12::
	.incbin "data/tilesets/secondary/goldenrod/palettes/12_over.gbapal"

	.align 2
gTilesetPalOverride_DeptStore09NoWin::
	.incbin "data/tilesets/secondary/department_store/palettes/09_over_nowin.gbapal"

	.align 2
gTilesetPalOverride_DeptStore09Win::
	.incbin "data/tilesets/secondary/department_store/palettes/09_over_win.gbapal"

	.align 2
gTilesetPalettes_PalletTown::
	.incbin "data/tilesets/secondary/pallettown/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/12.gbapal"

	.align 2
gTilesetTiles_PalletTown::
	.incbin "data/tilesets/secondary/pallettown/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_ViridianCity::
	.incbin "data/tilesets/secondary/viridiancity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/12.gbapal"

	.align 2
gTilesetTiles_ViridianCity::
	.incbin "data/tilesets/secondary/viridiancity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PewterCity::
	.incbin "data/tilesets/secondary/pewtercity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/12.gbapal"

	.align 2
gTilesetTiles_PewterCity::
	.incbin "data/tilesets/secondary/pewtercity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeruleanCity::
	.incbin "data/tilesets/secondary/ceruleancity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/12.gbapal"

	.align 2
gTilesetTiles_CeruleanCity::
	.incbin "data/tilesets/secondary/ceruleancity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_LavenderTown::
	.incbin "data/tilesets/secondary/lavendertown/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/12.gbapal"

	.align 2
gTilesetTiles_LavenderTown::
	.incbin "data/tilesets/secondary/lavendertown/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_VermilionCity::
	.incbin "data/tilesets/secondary/vermilioncity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/12.gbapal"

	.align 2
gTilesetTiles_VermilionCity::
	.incbin "data/tilesets/secondary/vermilioncity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeladonCity::
	.incbin "data/tilesets/secondary/celadoncity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/12.gbapal"

	.align 2
gTilesetTiles_CeladonCity::
	.incbin "data/tilesets/secondary/celadoncity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_FuchsiaCity::
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/12.gbapal"

	.align 2
gTilesetTiles_FuchsiaCity::
	.incbin "data/tilesets/secondary/fuchsiacity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_IndigoPlateau::
	.incbin "data/tilesets/secondary/indigoplateau/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/12.gbapal"

	.align 2
gTilesetTiles_IndigoPlateau::
	.incbin "data/tilesets/secondary/indigoplateau/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SaffronCity::
	.incbin "data/tilesets/secondary/saffroncity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/12.gbapal"

	.align 2
gTilesetTiles_SaffronCity::
	.incbin "data/tilesets/secondary/saffroncity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_GeneralKanto::
	.incbin "data/tilesets/primary/generalkanto/palettes/00.gbapal"
	.incbin "data/tilesets/primary/generalkanto/palettes/01.gbapal"
	.incbin "data/tilesets/primary/generalkanto/palettes/02.gbapal"
	.incbin "data/tilesets/primary/generalkanto/palettes/03.gbapal"
	.incbin "data/tilesets/primary/generalkanto/palettes/04.gbapal"
	.incbin "data/tilesets/primary/generalkanto/palettes/05.gbapal"
	.incbin "data/tilesets/primary/generalkanto/palettes/06.gbapal"
	.incbin "data/tilesets/primary/generalkanto/palettes/07.gbapal"
	.incbin "data/tilesets/primary/generalkanto/palettes/08.gbapal"
	.incbin "data/tilesets/primary/generalkanto/palettes/09.gbapal"
	.incbin "data/tilesets/primary/generalkanto/palettes/10.gbapal"
	.incbin "data/tilesets/primary/generalkanto/palettes/11.gbapal"
	.incbin "data/tilesets/primary/generalkanto/palettes/12.gbapal"

	.align 2
gTilesetTiles_GeneralKanto::
	.incbin "data/tilesets/primary/generalkanto/tiles.4bpp.lz"


	.align 2
gTilesetPalettes_RedsHouse::
	.incbin "data/tilesets/secondary/redshouse/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/redshouse/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/redshouse/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/redshouse/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/redshouse/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/redshouse/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/redshouse/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/redshouse/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/redshouse/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/redshouse/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/redshouse/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/redshouse/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/redshouse/palettes/12.gbapal"

	.align 2
gTilesetTiles_RedsHouse::
	.incbin "data/tilesets/secondary/redshouse/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_ViridianGym::
	.incbin "data/tilesets/secondary/viridiangym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/viridiangym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/viridiangym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/viridiangym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/viridiangym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/viridiangym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/viridiangym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/viridiangym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/viridiangym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/viridiangym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/viridiangym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/viridiangym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/viridiangym/palettes/12.gbapal"

	.align 2
gTilesetTiles_ViridianGym::
	.incbin "data/tilesets/secondary/viridiangym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PewterGym::
	.incbin "data/tilesets/secondary/pewtergym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pewtergym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pewtergym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pewtergym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pewtergym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pewtergym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pewtergym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pewtergym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pewtergym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pewtergym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pewtergym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pewtergym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pewtergym/palettes/12.gbapal"

	.align 2
gTilesetTiles_PewterGym::
	.incbin "data/tilesets/secondary/pewtergym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PewterMuseum::
	.incbin "data/tilesets/secondary/pewtermuseum/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pewtermuseum/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pewtermuseum/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pewtermuseum/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pewtermuseum/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pewtermuseum/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pewtermuseum/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pewtermuseum/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pewtermuseum/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pewtermuseum/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pewtermuseum/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pewtermuseum/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pewtermuseum/palettes/12.gbapal"

	.align 2
gTilesetTiles_PewterMuseum::
	.incbin "data/tilesets/secondary/pewtermuseum/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeruleanGym::
	.incbin "data/tilesets/secondary/ceruleangym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ceruleangym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ceruleangym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ceruleangym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ceruleangym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ceruleangym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ceruleangym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ceruleangym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ceruleangym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ceruleangym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ceruleangym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ceruleangym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ceruleangym/palettes/12.gbapal"

	.align 2
gTilesetTiles_CeruleanGym::
	.incbin "data/tilesets/secondary/ceruleangym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_VermilionGym::
	.incbin "data/tilesets/secondary/vermiliongym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/vermiliongym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/vermiliongym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/vermiliongym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/vermiliongym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/vermiliongym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/vermiliongym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/vermiliongym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/vermiliongym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/vermiliongym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/vermiliongym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/vermiliongym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/vermiliongym/palettes/12.gbapal"

	.align 2
gTilesetTiles_VermilionGym::
	.incbin "data/tilesets/secondary/vermiliongym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SoulHouse::
	.incbin "data/tilesets/secondary/soulhouse/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/soulhouse/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/soulhouse/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/soulhouse/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/soulhouse/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/soulhouse/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/soulhouse/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/soulhouse/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/soulhouse/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/soulhouse/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/soulhouse/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/soulhouse/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/soulhouse/palettes/12.gbapal"

	.align 2
gTilesetTiles_SoulHouse::
	.incbin "data/tilesets/secondary/soulhouse/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_RestaurantHotel::
	.incbin "data/tilesets/secondary/restauranthotel/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/restauranthotel/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/restauranthotel/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/restauranthotel/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/restauranthotel/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/restauranthotel/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/restauranthotel/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/restauranthotel/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/restauranthotel/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/restauranthotel/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/restauranthotel/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/restauranthotel/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/restauranthotel/palettes/12.gbapal"

	.align 2
gTilesetTiles_RestaurantHotel::
	.incbin "data/tilesets/secondary/restauranthotel/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeladonMansion::
	.incbin "data/tilesets/secondary/celadonmansion/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/celadonmansion/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/celadonmansion/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/celadonmansion/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/celadonmansion/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/celadonmansion/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/celadonmansion/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/celadonmansion/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/celadonmansion/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/celadonmansion/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/celadonmansion/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/celadonmansion/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/celadonmansion/palettes/12.gbapal"

	.align 2
gTilesetTiles_CeladonMansion::
	.incbin "data/tilesets/secondary/celadonmansion/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SaffronGym::
	.incbin "data/tilesets/secondary/saffrongym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/saffrongym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/saffrongym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/saffrongym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/saffrongym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/saffrongym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/saffrongym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/saffrongym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/saffrongym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/saffrongym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/saffrongym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/saffrongym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/saffrongym/palettes/12.gbapal"

	.align 2
gTilesetTiles_SaffronGym::
	.incbin "data/tilesets/secondary/saffrongym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SafariZoneHouse::
	.incbin "data/tilesets/secondary/safarizonehouse/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/safarizonehouse/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/safarizonehouse/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/safarizonehouse/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/safarizonehouse/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/safarizonehouse/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/safarizonehouse/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/safarizonehouse/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/safarizonehouse/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/safarizonehouse/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/safarizonehouse/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/safarizonehouse/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/safarizonehouse/palettes/12.gbapal"

	.align 2
gTilesetTiles_SafariZoneHouse::
	.incbin "data/tilesets/secondary/safarizonehouse/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_FuchsiaGym::
	.incbin "data/tilesets/secondary/fuchsiagym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fuchsiagym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fuchsiagym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fuchsiagym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fuchsiagym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fuchsiagym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fuchsiagym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fuchsiagym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fuchsiagym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fuchsiagym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fuchsiagym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fuchsiagym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fuchsiagym/palettes/12.gbapal"

	.align 2
gTilesetTiles_FuchsiaGym::
	.incbin "data/tilesets/secondary/fuchsiagym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_HallOfFame::
	.incbin "data/tilesets/secondary/halloffame/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/halloffame/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/halloffame/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/halloffame/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/halloffame/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/halloffame/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/halloffame/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/halloffame/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/halloffame/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/halloffame/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/halloffame/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/halloffame/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/halloffame/palettes/12.gbapal"

	.align 2
gTilesetTiles_HallOfFame::
	.incbin "data/tilesets/secondary/halloffame/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PowerPlant::
	.incbin "data/tilesets/secondary/powerplant/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/powerplant/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/powerplant/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/powerplant/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/powerplant/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/powerplant/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/powerplant/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/powerplant/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/powerplant/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/powerplant/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/powerplant/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/powerplant/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/powerplant/palettes/12.gbapal"

	.align 2
gTilesetTiles_PowerPlant::
	.incbin "data/tilesets/secondary/powerplant/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_DiglettsCave::
	.incbin "data/tilesets/secondary/diglettscave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/12.gbapal"

	.align 2
gTilesetTiles_DiglettsCave::
	.incbin "data/tilesets/secondary/diglettscave/tiles.4bpp.lz"
