	.align 2
gTileset_General::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_General
	.4byte gTilesetPalettes_General
	.4byte gMetatiles_General
	.4byte gMetatileAttributes_General
	.4byte InitTilesetAnim_General
	.4byte gTilesetPalOverrides_General

	.align 2
gTileset_NewBark::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_NewBark
	.4byte gTilesetPalettes_NewBark
	.4byte gMetatiles_NewBark
	.4byte gMetatileAttributes_NewBark
	.4byte InitTilesetAnim_NewBark
	.4byte gTilesetPalOverrides_NewBark

	.align 2
gTileset_Goldenrod::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Goldenrod
	.4byte gTilesetPalettes_Rustboro
	.4byte gMetatiles_Goldenrod
	.4byte gMetatileAttributes_Goldenrod
	.4byte InitTilesetAnim_Goldenrod
	.4byte gTilesetPalOverrides_Goldenrod

	.align 2
gTileset_Violet::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Violet
	.4byte gTilesetPalettes_Violet
	.4byte gMetatiles_Violet
	.4byte gMetatileAttributes_Violet
	.4byte InitTilesetAnim_Violet
	.4byte gTilesetPalOverrides_Violet

	.align 2
gTileset_Slateport::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Slateport
	.4byte gTilesetPalettes_Slateport
	.4byte gMetatiles_Slateport
	.4byte gMetatileAttributes_Slateport
	.4byte InitTilesetAnim_Slateport
	.4byte NULL @ palette overrides

	.align 2
gTileset_Mauville::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Mauville
	.4byte gTilesetPalettes_Mauville
	.4byte gMetatiles_Mauville
	.4byte gMetatileAttributes_Mauville
	.4byte InitTilesetAnim_Mauville
	.4byte NULL @ palette overrides

	.align 2
gTileset_Azalea::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Azalea
	.4byte gTilesetPalettes_Azalea
	.4byte gMetatiles_Azalea
	.4byte gMetatileAttributes_Azalea
	.4byte InitTilesetAnim_Azalea
	.4byte gTilesetPalOverrides_Azalea

	.align 2
gTileset_Fallarbor::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Fallarbor
	.4byte gTilesetPalettes_Fallarbor
	.4byte gMetatiles_Fallarbor
	.4byte gMetatileAttributes_Fallarbor
	.4byte InitTilesetAnim_Fallarbor
	.4byte NULL @ palette overrides

	.align 2
gTileset_Fortree::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Fortree
	.4byte gTilesetPalettes_Fortree
	.4byte gMetatiles_Fortree
	.4byte gMetatileAttributes_Fortree
	.4byte InitTilesetAnim_Fortree
	.4byte NULL @ palette overrides

	.align 2
gTileset_Lilycove::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Lilycove
	.4byte gTilesetPalettes_Lilycove
	.4byte gMetatiles_Lilycove
	.4byte gMetatileAttributes_Lilycove
	.4byte InitTilesetAnim_Lilycove
	.4byte NULL @ palette overrides

	.align 2
gTileset_Mossdeep::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Mossdeep
	.4byte gTilesetPalettes_Mossdeep
	.4byte gMetatiles_Mossdeep
	.4byte gMetatileAttributes_Mossdeep
	.4byte InitTilesetAnim_Mossdeep
	.4byte NULL @ palette overrides

	.align 2
gTileset_EverGrande::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_EverGrande
	.4byte gTilesetPalettes_EverGrande
	.4byte gMetatiles_EverGrande
	.4byte gMetatileAttributes_EverGrande
	.4byte InitTilesetAnim_EverGrande
	.4byte NULL @ palette overrides

	.align 2
gTileset_Pacifidlog::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Pacifidlog
	.4byte gTilesetPalettes_Pacifidlog
	.4byte gMetatiles_Pacifidlog
	.4byte gMetatileAttributes_Pacifidlog
	.4byte InitTilesetAnim_Pacifidlog
	.4byte NULL @ palette overrides

	.align 2
gTileset_Sootopolis::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Sootopolis
	.4byte gTilesetPalettes_Sootopolis
	.4byte gMetatiles_Sootopolis
	.4byte gMetatileAttributes_Sootopolis
	.4byte InitTilesetAnim_Sootopolis
	.4byte NULL @ palette overrides

	.align 2
gTileset_BattleFrontierOutsideWest::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleFrontierOutsideWest
	.4byte gTilesetPalettes_BattleFrontierOutsideWest
	.4byte gMetatiles_BattleFrontierOutsideWest
	.4byte gMetatileAttributes_BattleFrontierOutsideWest
	.4byte InitTilesetAnim_BattleFrontierOutsideWest
	.4byte NULL @ palette overrides

	.align 2
gTileset_BattleFrontierOutsideEast::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleFrontierOutsideEast
	.4byte gTilesetPalettes_BattleFrontierOutsideEast
	.4byte gMetatiles_BattleFrontierOutsideEast
	.4byte gMetatileAttributes_BattleFrontierOutsideEast
	.4byte InitTilesetAnim_BattleFrontierOutsideEast
	.4byte NULL @ palette overrides

	.align 2
gTileset_Building::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_InsideBuilding
	.4byte gTilesetPalettes_InsideBuilding
	.4byte gMetatiles_InsideBuilding
	.4byte gMetatileAttributes_InsideBuilding
	.4byte InitTilesetAnim_Building
	.4byte NULL @ palette overrides

	.align 2
gTileset_Shop::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Shop
	.4byte gTilesetPalettes_Shop
	.4byte gMetatiles_Shop
	.4byte gMetatileAttributes_Shop
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_PokemonCenter::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PokemonCenter
	.4byte gTilesetPalettes_PokemonCenter
	.4byte gMetatiles_PokemonCenter
	.4byte gMetatileAttributes_PokemonCenter
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_Cave::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Cave
	.4byte gTilesetPalettes_Cave
	.4byte gMetatiles_Cave
	.4byte gMetatileAttributes_Cave
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_PokemonSchool::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PokemonSchool
	.4byte gTilesetPalettes_PokemonSchool
	.4byte gMetatiles_PokemonSchool
	.4byte gMetatileAttributes_PokemonSchool
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_RadioTower::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_RadioTower
	.4byte gTilesetPalettes_RadioTower
	.4byte gMetatiles_RadioTower
	.4byte gMetatileAttributes_RadioTower
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_Gatehouse::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Gatehouse
	.4byte gTilesetPalettes_Gatehouse
	.4byte gMetatiles_Gatehouse
	.4byte gMetatileAttributes_Gatehouse
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_RockTunnel::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_RockTunnel
	.4byte gTilesetPalettes_RockTunnel
	.4byte gMetatiles_RockTunnel
	.4byte gMetatileAttributes_RockTunnel
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_Underground::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Underground
	.4byte gTilesetPalettes_Underground
	.4byte gMetatiles_Underground
	.4byte gMetatileAttributes_Underground
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_CableClub::
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_CableClub
	.4byte gTilesetPalettes_CableClub
	.4byte gMetatiles_CableClub
	.4byte gMetatileAttributes_CableClub
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_PagodaTower::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PagodaTower
	.4byte gTilesetPalettes_PagodaTower
	.4byte gMetatiles_PagodaTower
	.4byte gMetatileAttributes_PagodaTower
	.4byte InitTilesetAnim_PagodaTower
	.4byte NULL @ palette overrides

	.align 2
gTileset_RuinsOfAlph::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_RuinsOfAlph
	.4byte gTilesetPalettes_RuinsOfAlph
	.4byte gMetatiles_RuinsOfAlph
	.4byte gMetatileAttributes_RuinsOfAlph
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_PokemonDayCare::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PokemonDayCare
	.4byte gTilesetPalettes_PokemonDayCare
	.4byte gMetatiles_PokemonDayCare
	.4byte gMetatileAttributes_PokemonDayCare
	.4byte InitTilesetAnim_PokemonDayCare
	.4byte NULL @ palette overrides

	.align 2
gTileset_Facility::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Facility
	.4byte gTilesetPalettes_Facility
	.4byte gMetatiles_Facility
	.4byte gMetatileAttributes_Facility
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_BikeShop::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BikeShop
	.4byte gTilesetPalettes_BikeShop
	.4byte gMetatiles_BikeShop
	.4byte gMetatileAttributes_BikeShop
	.4byte NULL @ palette overrides
	.4byte NULL @ palette overrides

	.align 2
gTileset_Forest::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Forest
	.4byte gTilesetPalettes_Forest
	.4byte gMetatiles_Forest
	.4byte gMetatileAttributes_Forest
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_SecretBaseBrownCave::
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseBrownCave
	.4byte gTilesetPalettes_SecretBaseBrownCave
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_SecretBaseTree::
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseTree
	.4byte gTilesetPalettes_SecretBaseTree
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_SecretBaseShrub::
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseShrub
	.4byte gTilesetPalettes_SecretBaseShrub
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_SecretBaseBlueCave::
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseBlueCave
	.4byte gTilesetPalettes_SecretBaseBlueCave
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_SecretBaseYellowCave::
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseYellowCave
	.4byte gTilesetPalettes_SecretBaseYellowCave
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_SecretBaseRedCave::
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseRedCave
	.4byte gTilesetPalettes_SecretBaseRedCave
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_MagnetTrain::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MagnetTrain
	.4byte gTilesetPalettes_MagnetTrain
	.4byte gMetatiles_MagnetTrain
	.4byte gMetatileAttributes_MagnetTrain
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_DepartmentStore::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_DepartmentStore
	.4byte gTilesetPalettes_DepartmentStore
	.4byte gMetatiles_DepartmentStore
	.4byte gMetatileAttributes_DepartmentStore
	.4byte NULL @ animation callback
	.4byte gTilesetPalOverrides_DepartmentStore

	.align 2
gTileset_Contest::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Contest
	.4byte gTilesetPalettes_Contest
	.4byte gMetatiles_Contest
	.4byte gMetatileAttributes_Contest
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_LilycoveMuseum::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_LilycoveMuseum
	.4byte gTilesetPalettes_LilycoveMuseum
	.4byte gMetatiles_LilycoveMuseum
	.4byte gMetatileAttributes_LilycoveMuseum
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_PlayersHouse::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PlayersHouse
	.4byte gTilesetPalettes_PlayersHouse
	.4byte gMetatiles_PlayersHouse
	.4byte gMetatileAttributes_PlayersHouse
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_Lab::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Lab
	.4byte gTilesetPalettes_Lab
	.4byte gMetatiles_Lab
	.4byte gMetatileAttributes_Lab
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_Underwater::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Underwater
	.4byte gTilesetPalettes_Underwater
	.4byte gMetatiles_Underwater
	.4byte gMetatileAttributes_Underwater
	.4byte InitTilesetAnim_Underwater
	.4byte NULL @ palette overrides

	.align 2
gTileset_BurnedTower::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BurnedTower
	.4byte gTilesetPalettes_BurnedTower
	.4byte gMetatiles_BurnedTower
	.4byte gMetatilesAttributes_BurnedTower
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_SootopolisGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SootopolisGym
	.4byte gTilesetPalettes_SootopolisGym
	.4byte gMetatiles_SootopolisGym
	.4byte gMetatileAttributes_SootopolisGym
	.4byte InitTilesetAnim_SootopolisGym
	.4byte NULL @ palette overrides

	.align 2
gTileset_GenericBuilding::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_GenericBuilding
	.4byte gTilesetPalettes_GenericBuilding
	.4byte gMetatiles_GenericBuilding
	.4byte gMetatileAttributes_GenericBuilding
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_GameCorner::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_GameCorner
	.4byte gTilesetPalettes_GameCorner
	.4byte gMetatiles_GameCorner
	.4byte gMetatileAttributes_GameCorner
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_GoldenrodGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_GoldenrodGym
	.4byte gTilesetPalettes_GoldenrodGym
	.4byte gMetatiles_GoldenrodGym
	.4byte gMetatileAttributes_GoldenrodGym
	.4byte InitTilesetAnim_GoldenrodGym @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_AzaleaGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_AzaleaGym
	.4byte gTilesetPalettes_AzaleaGym
	.4byte gMetatiles_AzaleaGym
	.4byte gMetatileAttributes_AzaleaGym
	.4byte InitTilesetAnim_AzaleaGym
	.4byte NULL @ palette overrides

	.align 2
gTileset_MauvilleGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MauvilleGym
	.4byte gTilesetPalettes_MauvilleGym
	.4byte gMetatiles_MauvilleGym
	.4byte gMetatileAttributes_MauvilleGym
	.4byte InitTilesetAnim_MauvilleGym
	.4byte NULL @ palette overrides

	.align 2
gTileset_LavaridgeGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_LavaridgeGym
	.4byte gTilesetPalettes_LavaridgeGym
	.4byte gMetatiles_LavaridgeGym
	.4byte gMetatileAttributes_LavaridgeGym
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_TrickHousePuzzle::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_TrickHousePuzzle
	.4byte gTilesetPalettes_TrickHousePuzzle
	.4byte gMetatiles_TrickHousePuzzle
	.4byte gMetatileAttributes_TrickHousePuzzle
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_FortreeGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_FortreeGym
	.4byte gTilesetPalettes_FortreeGym
	.4byte gMetatiles_FortreeGym
	.4byte gMetatileAttributes_FortreeGym
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_MossdeepGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MossdeepGym
	.4byte gTilesetPalettes_MossdeepGym
	.4byte gMetatiles_MossdeepGym
	.4byte gMetatileAttributes_MossdeepGym
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_InsideShip::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_InsideShip
	.4byte gTilesetPalettes_InsideShip
	.4byte gMetatiles_InsideShip
	.4byte gMetatileAttributes_InsideShip
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_SecretBase::
	.byte FALSE @ is compressed
	.byte FALSE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBase
	.4byte gTilesetPalettes_SecretBase
	.4byte gMetatiles_SecretBasePrimary
	.4byte gMetatileAttributes_SecretBasePrimary
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTilesetPointer_SecretBase::
	.4byte gTileset_SecretBase

	.align 2
gTilesetPointer_SecretBaseRedCave::
	.4byte gTileset_SecretBaseRedCave

	.align 2
gTileset_EliteFour::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_EliteFour
	.4byte gTilesetPalettes_EliteFour
	.4byte gMetatiles_EliteFour
	.4byte gMetatileAttributes_EliteFour
	.4byte InitTilesetAnim_EliteFour
	.4byte NULL @ palette overrides

	.align 2
gTileset_BattleFrontier::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleFrontier
	.4byte gTilesetPalettes_BattleFrontier
	.4byte gMetatiles_BattleFrontier
	.4byte gMetatileAttributes_BattleFrontier
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_BattlePalace::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattlePalace
	.4byte gTilesetPalettes_BattlePalace
	.4byte gMetatiles_BattlePalace
	.4byte gMetatileAttributes_BattlePalace
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_BattleDome::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleDome
	.4byte gTilesetPalettes_BattleDome
	.4byte gMetatiles_BattleDome
	.4byte gMetatileAttributes_BattleDome
	.4byte InitTilesetAnim_BattleDome
	.4byte NULL @ palette overrides

	.align 2
gTileset_BattleFactory::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleFactory
	.4byte gTilesetPalettes_BattleFactory
	.4byte gMetatiles_BattleFactory
	.4byte gMetatileAttributes_BattleFactory
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_BattlePike::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattlePike
	.4byte gTilesetPalettes_BattlePike
	.4byte gMetatiles_BattlePike
	.4byte gMetatileAttributes_BattlePike
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_BattleArena::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleArena
	.4byte gTilesetPalettes_BattleArena
	.4byte gMetatiles_BattleArena
	.4byte gMetatileAttributes_BattleArena
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_BattlePyramid::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattlePyramid
	.4byte gTilesetPalettes_BattlePyramid
	.4byte gMetatiles_BattlePyramid
	.4byte gMetatileAttributes_BattlePyramid
	.4byte InitTilesetAnim_BattlePyramid
	.4byte NULL @ palette overrides

	.align 2
gTileset_MirageTower::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MirageTower
	.4byte gTilesetPalettes_MirageTower
	.4byte gMetatiles_MirageTower
	.4byte gMetatileAttributes_MirageTower
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_MossdeepGameCorner::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MossdeepGameCorner
	.4byte gTilesetPalettes_MossdeepGameCorner
	.4byte gMetatiles_MossdeepGameCorner
	.4byte gMetatileAttributes_MossdeepGameCorner
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_IslandHarbor::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_IslandHarbor
	.4byte gTilesetPalettes_IslandHarbor
	.4byte gMetatiles_IslandHarbor
	.4byte gMetatileAttributes_IslandHarbor
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_TrainerHill::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_TrainerHill
	.4byte gTilesetPalettes_TrainerHill
	.4byte gMetatiles_TrainerHill
	.4byte gMetatileAttributes_TrainerHill
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_NavelRock::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_NavelRock
	.4byte gTilesetPalettes_NavelRock
	.4byte gMetatiles_NavelRock
	.4byte gMetatileAttributes_NavelRock
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_BattleFrontierRankingHall::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleFrontierRankingHall
	.4byte gTilesetPalettes_BattleFrontierRankingHall
	.4byte gMetatiles_BattleFrontierRankingHall
	.4byte gMetatileAttributes_BattleFrontierRankingHall
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_BattleTent::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleTent
	.4byte gTilesetPalettes_BattleTent
	.4byte gMetatiles_BattleTent
	.4byte gMetatileAttributes_BattleTent
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_MysteryEventsHouse::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MysteryEventsHouse
	.4byte gTilesetPalettes_MysteryEventsHouse
	.4byte gMetatiles_MysteryEventsHouse
	.4byte gMetatileAttributes_MysteryEventsHouse
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_UnionRoom::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_UnionRoom
	.4byte gTilesetPalettes_UnionRoom
	.4byte gMetatiles_UnionRoom
	.4byte gMetatileAttributes_UnionRoom
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_NationalPark::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_NationalPark
	.4byte gTilesetPalettes_NationalPark
	.4byte gMetatiles_NationalPark
	.4byte gMetatileAttributes_NationalPark
	.4byte InitTilesetAnim_NationalPark
	.4byte NULL @ palette overrides

	.align 2
gTileset_PalletTown::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_PalletTown
	.4byte gTilesetPalettes_PalletTown
	.4byte gMetatiles_PalletTown
	.4byte gMetatileAttributes_PalletTown
	.4byte NULL
	.4byte gTilesetPalOverrides_PalletTown @ palette overrides

	.align 2
gTileset_ViridianCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_ViridianCity
	.4byte gTilesetPalettes_ViridianCity
	.4byte gMetatiles_ViridianCity
	.4byte gMetatileAttributes_ViridianCity
	.4byte NULL
	.4byte gTilesetPalOverrides_ViridianCity @ palette overrides

	.align 2
gTileset_PewterCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_PewterCity
	.4byte gTilesetPalettes_PewterCity
	.4byte gMetatiles_PewterCity
	.4byte gMetatileAttributes_PewterCity
	.4byte NULL
	.4byte gTilesetPalOverrides_PewterCity @ palette overrides

	.align 2
gTileset_CeruleanCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_CeruleanCity
	.4byte gTilesetPalettes_CeruleanCity
	.4byte gMetatiles_CeruleanCity
	.4byte gMetatileAttributes_CeruleanCity
	.4byte NULL
	.4byte NULL @ palette overrides

	.align 2
gTileset_LavenderTown::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_LavenderTown
	.4byte gTilesetPalettes_LavenderTown
	.4byte gMetatiles_LavenderTown
	.4byte gMetatileAttributes_LavenderTown
	.4byte NULL
	.4byte gTilesetPalOverrides_LavenderTown @ palette overrides

	.align 2
gTileset_VermilionCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_VermilionCity
	.4byte gTilesetPalettes_VermilionCity
	.4byte gMetatiles_VermilionCity
	.4byte gMetatileAttributes_VermilionCity
	.4byte NULL
	.4byte gTilesetPalOverrides_VermilionCity @ palette overrides

	.align 2
gTileset_CeladonCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_CeladonCity
	.4byte gTilesetPalettes_CeladonCity
	.4byte gMetatiles_CeladonCity
	.4byte gMetatileAttributes_CeladonCity
	.4byte InitTilesetAnim_CeladonCity
	.4byte gTilesetPalOverrides_CeladonCity @ palette overrides

	.align 2
gTileset_FuchsiaCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_FuchsiaCity
	.4byte gTilesetPalettes_FuchsiaCity
	.4byte gMetatiles_FuchsiaCity
	.4byte gMetatileAttributes_FuchsiaCity
	.4byte NULL
	.4byte gTilesetPalOverrides_FuchsiaCity @ palette overrides

	.align 2
gTileset_IndigoPlateau::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_IndigoPlateau
	.4byte gTilesetPalettes_IndigoPlateau
	.4byte gMetatiles_IndigoPlateau
	.4byte gMetatileAttributes_IndigoPlateau
	.4byte NULL
	.4byte gTilesetPalOverrides_IndigoPlateau @ palette overrides

	.align 2
gTileset_SaffronCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_SaffronCity
	.4byte gTilesetPalettes_SaffronCity
	.4byte gMetatiles_SaffronCity
	.4byte gMetatileAttributes_SaffronCity
	.4byte NULL
	.4byte gTilesetPalOverrides_SaffronCity @ palette overrides

	.align 2
gTileset_GeneralKanto::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_GeneralKanto
	.4byte gTilesetPalettes_GeneralKanto
	.4byte gMetatiles_GeneralKanto
	.4byte gMetatileAttributes_GeneralKanto
	.4byte InitTilesetAnim_General
	.4byte gTilesetPalOverrides_General @ palette overrides


	.align 2
gTileset_RedsHouse::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_RedsHouse
	.4byte gTilesetPalettes_RedsHouse
	.4byte gMetatiles_RedsHouse
	.4byte gMetatileAttributes_RedsHouse
	.4byte NULL
	.4byte NULL @ palette overrides

	.align 2
gTileset_ViridianGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_ViridianGym
	.4byte gTilesetPalettes_ViridianGym
	.4byte gMetatiles_ViridianGym
	.4byte gMetatileAttributes_ViridianGym
	.4byte NULL
	.4byte NULL @ palette overrides

	.align 2
gTileset_PewterGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_PewterGym
	.4byte gTilesetPalettes_PewterGym
	.4byte gMetatiles_PewterGym
	.4byte gMetatileAttributes_PewterGym
	.4byte NULL
	.4byte NULL @ palette overrides

	.align 2
gTileset_PewterMuseum::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_PewterMuseum
	.4byte gTilesetPalettes_PewterMuseum
	.4byte gMetatiles_PewterMuseum
	.4byte gMetatileAttributes_PewterMuseum
	.4byte NULL
	.4byte NULL @ palette overrides

	.align 2
gTileset_CeruleanGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_CeruleanGym
	.4byte gTilesetPalettes_CeruleanGym
	.4byte gMetatiles_CeruleanGym
	.4byte gMetatileAttributes_CeruleanGym
	.4byte NULL
	.4byte NULL @ palette overrides

	.align 2
gTileset_VermilionGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_VermilionGym
	.4byte gTilesetPalettes_VermilionGym
	.4byte gMetatiles_VermilionGym
	.4byte gMetatileAttributes_VermilionGym
	.4byte NULL
	.4byte NULL @ palette overrides

	.align 2
gTileset_SoulHouse::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_SoulHouse
	.4byte gTilesetPalettes_SoulHouse
	.4byte gMetatiles_SoulHouse
	.4byte gMetatileAttributes_SoulHouse
	.4byte NULL
	.4byte NULL @ palette overrides

	.align 2
gTileset_RestaurantHotel::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_RestaurantHotel
	.4byte gTilesetPalettes_RestaurantHotel
	.4byte gMetatiles_RestaurantHotel
	.4byte gMetatileAttributes_RestaurantHotel
	.4byte NULL
	.4byte NULL @ palette overrides

	.align 2
gTileset_CeladonMansion::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_CeladonMansion
	.4byte gTilesetPalettes_CeladonMansion
	.4byte gMetatiles_CeladonMansion
	.4byte gMetatileAttributes_CeladonMansion
	.4byte NULL
	.4byte gTilesetPalOverrides_CeladonMansion @ palette overrides

	.align 2
gTileset_SaffronGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_SaffronGym
	.4byte gTilesetPalettes_SaffronGym
	.4byte gMetatiles_SaffronGym
	.4byte gMetatileAttributes_SaffronGym
	.4byte NULL
	.4byte NULL @ palette overrides

	.align 2
gTileset_SafariZoneHouse::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_SafariZoneHouse
	.4byte gTilesetPalettes_SafariZoneHouse
	.4byte gMetatiles_SafariZoneHouse
	.4byte gMetatileAttributes_SafariZoneHouse
	.4byte NULL
	.4byte NULL @ palette overrides

	.align 2
gTileset_FuchsiaGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_FuchsiaGym
	.4byte gTilesetPalettes_FuchsiaGym
	.4byte gMetatiles_FuchsiaGym
	.4byte gMetatileAttributes_FuchsiaGym
	.4byte NULL
	.4byte NULL @ palette overrides

	.align 2
gTileset_HallOfFame::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_HallOfFame
	.4byte gTilesetPalettes_HallOfFame
	.4byte gMetatiles_HallOfFame
	.4byte gMetatileAttributes_HallOfFame
	.4byte NULL
	.4byte NULL @ palette overrides

	.align 2
gTileset_PowerPlant::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_PowerPlant
	.4byte gTilesetPalettes_PowerPlant
	.4byte gMetatiles_PowerPlant
	.4byte gMetatileAttributes_PowerPlant
	.4byte NULL
	.4byte NULL @ palette overrides

	.align 2
gTileset_DiglettsCave::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_DiglettsCave
	.4byte gTilesetPalettes_DiglettsCave
	.4byte gMetatiles_DiglettsCave
	.4byte gMetatileAttributes_DiglettsCave
	.4byte NULL
	.4byte NULL @ palette overrides

	.align 2
gTileset_BlackthornCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_BlackthornCity
	.4byte gTilesetPalettes_BlackthornCity
	.4byte gMetatiles_BlackthornCity
	.4byte gMetatileAttributes_BlackthornCity
	.4byte NULL
	.4byte NULL @ palette overrides

	.align 2
gTileset_MahoganyTown::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_MahoganyTown
	.4byte gTilesetPalettes_MahoganyTown
	.4byte gMetatiles_MahoganyTown
	.4byte gMetatileAttributes_MahoganyTown
	.4byte NULL
	.4byte NULL @ palette overrides

	.align 2
gTileset_EcruteakCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_EcruteakCity
	.4byte gTilesetPalettes_EcruteakCity
	.4byte gMetatiles_EcruteakCity
	.4byte gMetatileAttributes_EcruteakCity
	.4byte NULL
	.4byte gTilesetPalOverrides_EcruteakCity

	.align 2
gTileset_OlivineCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_OlivineCity
	.4byte gTilesetPalettes_OlivineCity
	.4byte gMetatiles_OlivineCity
	.4byte gMetatileAttributes_OlivineCity
	.4byte NULL
	.4byte gTilesetPalOverrides_OlivineCity

	.align 2
gTileset_Lighthouse::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_Lighthouse
	.4byte gTilesetPalettes_Lighthouse
	.4byte gMetatiles_Lighthouse
	.4byte gMetatileAttributes_Lighthouse
	.4byte NULL
	.4byte NULL

	.align 2
gTileset_RocketHideout::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_RocketHideout
	.4byte gTilesetPalettes_RocketHideout
	.4byte gMetatiles_RocketHideout
	.4byte gMetatileAttributes_RocketHideout
	.4byte NULL
	.4byte NULL @ palette overrides

	.align 2
gTileset_IcePath::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_IcePath
	.4byte gTilesetPalettes_IcePath
	.4byte gMetatiles_IcePath
	.4byte gMetatileAttributes_IcePath
	.4byte NULL
	.4byte NULL @ palette overrides

	.align 2
gTileset_WhirlIslands::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_WhirlIslands
	.4byte gTilesetPalettes_WhirlIslands
	.4byte gMetatiles_WhirlIslands
	.4byte gMetatileAttributes_WhirlIslands
	.4byte NULL
	.4byte NULL @ palette overrides

	.align 2
gTileset_PokemonLeague::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_PokemonLeague
	.4byte gTilesetPalettes_PokemonLeague
	.4byte gMetatiles_PokemonLeague
	.4byte gMetatileAttributes_PokemonLeague
	.4byte InitTilesetAnim_PokemonLeague
	.4byte NULL @ palette overrides

	.align 2
gTileset_ChampionsRoom::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_ChampionsRoom
	.4byte gTilesetPalettes_ChampionsRoom
	.4byte gMetatiles_ChampionsRoom
	.4byte gMetatileAttributes_ChampionsRoom
	.4byte NULL
	.4byte NULL @ palette overrides

	.align 2
gTileset_BlackthornGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_BlackthornGym
	.4byte gTilesetPalettes_BlackthornGym
	.4byte gMetatiles_BlackthornGym
	.4byte gMetatileAttributes_BlackthornGym
	.4byte InitTilesetAnim_BlackthornGym
	.4byte NULL @ palette overrides

	.align 2
gTileset_BattleFrontierPrimary::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_BattleFrontierPrimary
	.4byte gTilesetPalettes_BattleFrontierPrimary
	.4byte gMetatiles_BattleFrontierPrimary
	.4byte gMetatileAttributes_BattleFrontierPrimary
	.4byte InitTilesetAnim_General
	.4byte gTilesetPalOverrides_General

	.align 2
gTileset_SilphCo::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_SilphCo
	.4byte gTilesetPalettes_SilphCo
	.4byte gMetatiles_SilphCo
	.4byte gMetatileAttributes_SilphCo
	.4byte InitTilesetAnim_SilphCo
	.4byte NULL @ palette overrides

	.align 2
gTileset_SaffronGeneral::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_SaffronGeneral
	.4byte gTilesetPalettes_SaffronGeneral
	.4byte gMetatiles_SaffronGeneral
	.4byte gMetatileAttributes_SaffronGeneral
	.4byte InitTilesetAnim_General
	.4byte gTilesetPalOverrides_General @ palette overrides

	.align 2
gTileset_PlayersRoom::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_PlayersRoom
	.4byte gTilesetPalettes_PlayersRoom
	.4byte gMetatiles_PlayersRoom
	.4byte gMetatileAttributes_PlayersRoom
	.4byte NULL
	.4byte NULL @ palette overrides

	.align 2
gTileset_PlayersRoom2::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_PlayersRoom2
	.4byte gTilesetPalettes_PlayersRoom2
	.4byte gMetatiles_PlayersRoom2
	.4byte gMetatileAttributes_PlayersRoom2
	.4byte NULL
	.4byte NULL @ palette overrides

	.align 2
gTileset_VioletGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_VioletGym
	.4byte gTilesetPalettes_VioletGym
	.4byte gMetatiles_VioletGym
	.4byte gMetatileAttributes_VioletGym
	.4byte NULL
	.4byte NULL @ palette overrides

	.align 2
gTileset_DragonsDen_Shrine::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_DragonsDen_Shrine
	.4byte gTilesetPalettes_DragonsDen_Shrine
	.4byte gMetatiles_DragonsDen_Shrine
	.4byte gMetatileAttributes_DragonsDen_Shrine
	.4byte InitTilesetAnim_DragonsDen_Shrine
	.4byte gTilesetPalOverrides_DragonsDen_Shrine @ palette overrides
