	.align 2
gTileset_General:: @ 83DF704
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_General
	.4byte gTilesetPalettes_General
	.4byte gMetatiles_General
	.4byte gMetatileAttributes_General
	.4byte InitTilesetAnim_General
	.4byte gTilesetPalOverrides_General

	.align 2
gTileset_NewBark:: @ 83DF71C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_NewBark
	.4byte gTilesetPalettes_NewBark
	.4byte gMetatiles_NewBark
	.4byte gMetatileAttributes_NewBark
	.4byte InitTilesetAnim_NewBark
	.4byte gTilesetPalOverrides_NewBark

	.align 2
gTileset_Goldenrod:: @ 83DF734
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Goldenrod
	.4byte gTilesetPalettes_Rustboro
	.4byte gMetatiles_Goldenrod
	.4byte gMetatileAttributes_Goldenrod
	.4byte InitTilesetAnim_Goldenrod
	.4byte gTilesetPalOverrides_Goldenrod

	.align 2
gTileset_Violet:: @ 83DF74C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Violet
	.4byte gTilesetPalettes_Violet
	.4byte gMetatiles_Violet
	.4byte gMetatileAttributes_Violet
	.4byte InitTilesetAnim_Violet
	.4byte gTilesetPalOverrides_Violet

	.align 2
gTileset_Slateport:: @ 83DF764
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Slateport
	.4byte gTilesetPalettes_Slateport
	.4byte gMetatiles_Slateport
	.4byte gMetatileAttributes_Slateport
	.4byte InitTilesetAnim_Slateport
	.4byte NULL @ palette overrides

	.align 2
gTileset_Mauville:: @ 83DF77C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Mauville
	.4byte gTilesetPalettes_Mauville
	.4byte gMetatiles_Mauville
	.4byte gMetatileAttributes_Mauville
	.4byte InitTilesetAnim_Mauville
	.4byte NULL @ palette overrides

	.align 2
gTileset_Azalea:: @ 83DF794
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Azalea
	.4byte gTilesetPalettes_Azalea
	.4byte gMetatiles_Azalea
	.4byte gMetatileAttributes_Azalea
	.4byte InitTilesetAnim_Azalea
	.4byte gTilesetPalOverrides_Azalea

	.align 2
gTileset_Fallarbor:: @ 83DF7AC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Fallarbor
	.4byte gTilesetPalettes_Fallarbor
	.4byte gMetatiles_Fallarbor
	.4byte gMetatileAttributes_Fallarbor
	.4byte InitTilesetAnim_Fallarbor
	.4byte NULL @ palette overrides

	.align 2
gTileset_Fortree:: @ 83DF7C4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Fortree
	.4byte gTilesetPalettes_Fortree
	.4byte gMetatiles_Fortree
	.4byte gMetatileAttributes_Fortree
	.4byte InitTilesetAnim_Fortree
	.4byte NULL @ palette overrides

	.align 2
gTileset_Lilycove:: @ 83DF7DC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Lilycove
	.4byte gTilesetPalettes_Lilycove
	.4byte gMetatiles_Lilycove
	.4byte gMetatileAttributes_Lilycove
	.4byte InitTilesetAnim_Lilycove
	.4byte NULL @ palette overrides

	.align 2
gTileset_Mossdeep:: @ 83DF7F4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Mossdeep
	.4byte gTilesetPalettes_Mossdeep
	.4byte gMetatiles_Mossdeep
	.4byte gMetatileAttributes_Mossdeep
	.4byte InitTilesetAnim_Mossdeep
	.4byte NULL @ palette overrides

	.align 2
gTileset_EverGrande:: @ 83DF80C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_EverGrande
	.4byte gTilesetPalettes_EverGrande
	.4byte gMetatiles_EverGrande
	.4byte gMetatileAttributes_EverGrande
	.4byte InitTilesetAnim_EverGrande
	.4byte NULL @ palette overrides

	.align 2
gTileset_Pacifidlog:: @ 83DF824
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Pacifidlog
	.4byte gTilesetPalettes_Pacifidlog
	.4byte gMetatiles_Pacifidlog
	.4byte gMetatileAttributes_Pacifidlog
	.4byte InitTilesetAnim_Pacifidlog
	.4byte NULL @ palette overrides

	.align 2
gTileset_Sootopolis:: @ 83DF83C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Sootopolis
	.4byte gTilesetPalettes_Sootopolis
	.4byte gMetatiles_Sootopolis
	.4byte gMetatileAttributes_Sootopolis
	.4byte InitTilesetAnim_Sootopolis
	.4byte NULL @ palette overrides

	.align 2
gTileset_BattleFrontierOutsideWest:: @ 83DF854
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleFrontierOutsideWest
	.4byte gTilesetPalettes_BattleFrontierOutsideWest
	.4byte gMetatiles_BattleFrontierOutsideWest
	.4byte gMetatileAttributes_BattleFrontierOutsideWest
	.4byte InitTilesetAnim_BattleFrontierOutsideWest
	.4byte NULL @ palette overrides

	.align 2
gTileset_BattleFrontierOutsideEast:: @ 83DF86C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleFrontierOutsideEast
	.4byte gTilesetPalettes_BattleFrontierOutsideEast
	.4byte gMetatiles_BattleFrontierOutsideEast
	.4byte gMetatileAttributes_BattleFrontierOutsideEast
	.4byte InitTilesetAnim_BattleFrontierOutsideEast
	.4byte NULL @ palette overrides

	.align 2
gTileset_Building:: @ 83DF884
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_InsideBuilding
	.4byte gTilesetPalettes_InsideBuilding
	.4byte gMetatiles_InsideBuilding
	.4byte gMetatileAttributes_InsideBuilding
	.4byte InitTilesetAnim_Building
	.4byte NULL @ palette overrides

	.align 2
gTileset_Shop:: @ 83DF89C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Shop
	.4byte gTilesetPalettes_Shop
	.4byte gMetatiles_Shop
	.4byte gMetatileAttributes_Shop
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_PokemonCenter:: @ 83DF8B4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PokemonCenter
	.4byte gTilesetPalettes_PokemonCenter
	.4byte gMetatiles_PokemonCenter
	.4byte gMetatileAttributes_PokemonCenter
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_Cave:: @ 83DF8CC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Cave
	.4byte gTilesetPalettes_Cave
	.4byte gMetatiles_Cave
	.4byte gMetatileAttributes_Cave
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_PokemonSchool:: @ 83DF8E4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PokemonSchool
	.4byte gTilesetPalettes_PokemonSchool
	.4byte gMetatiles_PokemonSchool
	.4byte gMetatileAttributes_PokemonSchool
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_RadioTower:: @ 83DF8FC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_RadioTower
	.4byte gTilesetPalettes_RadioTower
	.4byte gMetatiles_RadioTower
	.4byte gMetatileAttributes_RadioTower
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_Gatehouse:: @ 83DF914
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Gatehouse
	.4byte gTilesetPalettes_Gatehouse
	.4byte gMetatiles_Gatehouse
	.4byte gMetatileAttributes_Gatehouse
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_RockTunnel:: @ 83DF92C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_RockTunnel
	.4byte gTilesetPalettes_RockTunnel
	.4byte gMetatiles_RockTunnel
	.4byte gMetatileAttributes_RockTunnel
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_Underground:: @ 83DF944
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Underground
	.4byte gTilesetPalettes_Underground
	.4byte gMetatiles_Underground
	.4byte gMetatileAttributes_Underground
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_CableClub:: @ 83DF95C
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_CableClub
	.4byte gTilesetPalettes_CableClub
	.4byte gMetatiles_CableClub
	.4byte gMetatileAttributes_CableClub
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_PagodaTower:: @ 83DF974
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PagodaTower
	.4byte gTilesetPalettes_PagodaTower
	.4byte gMetatiles_PagodaTower
	.4byte gMetatileAttributes_PagodaTower
	.4byte InitTilesetAnim_PagodaTower
	.4byte NULL @ palette overrides

	.align 2
gTileset_RuinsOfAlph:: @ 83DF98C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_RuinsOfAlph
	.4byte gTilesetPalettes_RuinsOfAlph
	.4byte gMetatiles_RuinsOfAlph
	.4byte gMetatileAttributes_RuinsOfAlph
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_PokemonDayCare:: @ 83DF9A4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PokemonDayCare
	.4byte gTilesetPalettes_PokemonDayCare
	.4byte gMetatiles_PokemonDayCare
	.4byte gMetatileAttributes_PokemonDayCare
	.4byte InitTilesetAnim_PokemonDayCare
	.4byte NULL @ palette overrides

	.align 2
gTileset_Facility:: @ 83DF9BC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Facility
	.4byte gTilesetPalettes_Facility
	.4byte gMetatiles_Facility
	.4byte gMetatileAttributes_Facility
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_BikeShop:: @ 83DF9D4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BikeShop
	.4byte gTilesetPalettes_BikeShop
	.4byte gMetatiles_BikeShop
	.4byte gMetatileAttributes_BikeShop
	.4byte NULL @ palette overrides
	.4byte NULL @ palette overrides

	.align 2
gTileset_Forest:: @ 83DF9EC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Forest
	.4byte gTilesetPalettes_Forest
	.4byte gMetatiles_Forest
	.4byte gMetatileAttributes_Forest
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_SecretBaseBrownCave:: @ 83DFA04
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseBrownCave
	.4byte gTilesetPalettes_SecretBaseBrownCave
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_SecretBaseTree:: @ 83DFA1C
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseTree
	.4byte gTilesetPalettes_SecretBaseTree
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_SecretBaseShrub:: @ 83DFA34
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseShrub
	.4byte gTilesetPalettes_SecretBaseShrub
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_SecretBaseBlueCave:: @ 83DFA4C
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseBlueCave
	.4byte gTilesetPalettes_SecretBaseBlueCave
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_SecretBaseYellowCave:: @ 83DFA64
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseYellowCave
	.4byte gTilesetPalettes_SecretBaseYellowCave
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_SecretBaseRedCave:: @ 83DFA7C
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseRedCave
	.4byte gTilesetPalettes_SecretBaseRedCave
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_MagnetTrain:: @ 83DFA94
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MagnetTrain
	.4byte gTilesetPalettes_MagnetTrain
	.4byte gMetatiles_MagnetTrain
	.4byte gMetatileAttributes_MagnetTrain
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_DepartmentStore:: @ 83DFAAC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_DepartmentStore
	.4byte gTilesetPalettes_DepartmentStore
	.4byte gMetatiles_DepartmentStore
	.4byte gMetatileAttributes_DepartmentStore
	.4byte NULL @ animation callback
	.4byte gTilesetPalOverrides_DepartmentStore

	.align 2
gTileset_Contest:: @ 83DFAC4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Contest
	.4byte gTilesetPalettes_Contest
	.4byte gMetatiles_Contest
	.4byte gMetatileAttributes_Contest
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_LilycoveMuseum:: @ 83DFADC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_LilycoveMuseum
	.4byte gTilesetPalettes_LilycoveMuseum
	.4byte gMetatiles_LilycoveMuseum
	.4byte gMetatileAttributes_LilycoveMuseum
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_PlayersHouse:: @ 83DFAF4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PlayersHouse
	.4byte gTilesetPalettes_PlayersHouse
	.4byte gMetatiles_PlayersHouse
	.4byte gMetatileAttributes_PlayersHouse
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_Lab:: @ 83DFB0C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Lab
	.4byte gTilesetPalettes_Lab
	.4byte gMetatiles_Lab
	.4byte gMetatileAttributes_Lab
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_Underwater:: @ 83DFB24
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Underwater
	.4byte gTilesetPalettes_Underwater
	.4byte gMetatiles_Underwater
	.4byte gMetatileAttributes_Underwater
	.4byte InitTilesetAnim_Underwater
	.4byte NULL @ palette overrides

	.align 2
gTileset_VioletGym:: @ 83DFB3C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_VioletGym
	.4byte gTilesetPalettes_VioletGym
	.4byte gMetatiles_VioletGym
	.4byte gMetatilesAttributes_VioletGym
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_SootopolisGym:: @ 83DFB54
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SootopolisGym
	.4byte gTilesetPalettes_SootopolisGym
	.4byte gMetatiles_SootopolisGym
	.4byte gMetatileAttributes_SootopolisGym
	.4byte InitTilesetAnim_SootopolisGym
	.4byte NULL @ palette overrides

	.align 2
gTileset_GenericBuilding:: @ 83DFB6C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_GenericBuilding
	.4byte gTilesetPalettes_GenericBuilding
	.4byte gMetatiles_GenericBuilding
	.4byte gMetatileAttributes_GenericBuilding
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_GameCorner:: @ 83DFB84
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_GameCorner
	.4byte gTilesetPalettes_GameCorner
	.4byte gMetatiles_GameCorner
	.4byte gMetatileAttributes_GameCorner
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_GoldenrodGym:: @ 83DFB9C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_GoldenrodGym
	.4byte gTilesetPalettes_GoldenrodGym
	.4byte gMetatiles_GoldenrodGym
	.4byte gMetatileAttributes_GoldenrodGym
	.4byte InitTilesetAnim_GoldenrodGym @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_AzaleaGym:: @ 83DFBB4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_AzaleaGym
	.4byte gTilesetPalettes_AzaleaGym
	.4byte gMetatiles_AzaleaGym
	.4byte gMetatileAttributes_AzaleaGym
	.4byte InitTilesetAnim_AzaleaGym
	.4byte NULL @ palette overrides

	.align 2
gTileset_MauvilleGym:: @ 83DFBCC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MauvilleGym
	.4byte gTilesetPalettes_MauvilleGym
	.4byte gMetatiles_MauvilleGym
	.4byte gMetatileAttributes_MauvilleGym
	.4byte InitTilesetAnim_MauvilleGym
	.4byte NULL @ palette overrides

	.align 2
gTileset_LavaridgeGym:: @ 83DFBE4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_LavaridgeGym
	.4byte gTilesetPalettes_LavaridgeGym
	.4byte gMetatiles_LavaridgeGym
	.4byte gMetatileAttributes_LavaridgeGym
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_TrickHousePuzzle:: @ 83DFBFC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_TrickHousePuzzle
	.4byte gTilesetPalettes_TrickHousePuzzle
	.4byte gMetatiles_TrickHousePuzzle
	.4byte gMetatileAttributes_TrickHousePuzzle
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_FortreeGym:: @ 83DFC14
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_FortreeGym
	.4byte gTilesetPalettes_FortreeGym
	.4byte gMetatiles_FortreeGym
	.4byte gMetatileAttributes_FortreeGym
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_MossdeepGym:: @ 83DFC2C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MossdeepGym
	.4byte gTilesetPalettes_MossdeepGym
	.4byte gMetatiles_MossdeepGym
	.4byte gMetatileAttributes_MossdeepGym
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_InsideShip:: @ 83DFC44
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_InsideShip
	.4byte gTilesetPalettes_InsideShip
	.4byte gMetatiles_InsideShip
	.4byte gMetatileAttributes_InsideShip
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_SecretBase:: @ 83DFC5C
	.byte FALSE @ is compressed
	.byte FALSE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBase
	.4byte gTilesetPalettes_SecretBase
	.4byte gMetatiles_SecretBasePrimary
	.4byte gMetatileAttributes_SecretBasePrimary
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTilesetPointer_SecretBase:: @ 83DFC74
	.4byte gTileset_SecretBase

	.align 2
gTilesetPointer_SecretBaseRedCave:: @ 83DFC78
	.4byte gTileset_SecretBaseRedCave

	.align 2
gTileset_EliteFour:: @ 83DFC7C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_EliteFour
	.4byte gTilesetPalettes_EliteFour
	.4byte gMetatiles_EliteFour
	.4byte gMetatileAttributes_EliteFour
	.4byte InitTilesetAnim_EliteFour
	.4byte NULL @ palette overrides

	.align 2
gTileset_BattleFrontier:: @ 83DFC94
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleFrontier
	.4byte gTilesetPalettes_BattleFrontier
	.4byte gMetatiles_BattleFrontier
	.4byte gMetatileAttributes_BattleFrontier
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_BattlePalace:: @ 83DFCAC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattlePalace
	.4byte gTilesetPalettes_BattlePalace
	.4byte gMetatiles_BattlePalace
	.4byte gMetatileAttributes_BattlePalace
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_BattleDome:: @ 83DFCC4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleDome
	.4byte gTilesetPalettes_BattleDome
	.4byte gMetatiles_BattleDome
	.4byte gMetatileAttributes_BattleDome
	.4byte InitTilesetAnim_BattleDome
	.4byte NULL @ palette overrides

	.align 2
gTileset_BattleFactory:: @ 83DFCDC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleFactory
	.4byte gTilesetPalettes_BattleFactory
	.4byte gMetatiles_BattleFactory
	.4byte gMetatileAttributes_BattleFactory
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_BattlePike:: @ 83DFCF4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattlePike
	.4byte gTilesetPalettes_BattlePike
	.4byte gMetatiles_BattlePike
	.4byte gMetatileAttributes_BattlePike
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_BattleArena:: @ 83DFD0C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleArena
	.4byte gTilesetPalettes_BattleArena
	.4byte gMetatiles_BattleArena
	.4byte gMetatileAttributes_BattleArena
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_BattlePyramid:: @ 83DFD24
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattlePyramid
	.4byte gTilesetPalettes_BattlePyramid
	.4byte gMetatiles_BattlePyramid
	.4byte gMetatileAttributes_BattlePyramid
	.4byte InitTilesetAnim_BattlePyramid
	.4byte NULL @ palette overrides

	.align 2
gTileset_MirageTower:: @ 83DFD3C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MirageTower
	.4byte gTilesetPalettes_MirageTower
	.4byte gMetatiles_MirageTower
	.4byte gMetatileAttributes_MirageTower
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_MossdeepGameCorner:: @ 83DFD54
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MossdeepGameCorner
	.4byte gTilesetPalettes_MossdeepGameCorner
	.4byte gMetatiles_MossdeepGameCorner
	.4byte gMetatileAttributes_MossdeepGameCorner
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_IslandHarbor:: @ 83DFD6C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_IslandHarbor
	.4byte gTilesetPalettes_IslandHarbor
	.4byte gMetatiles_IslandHarbor
	.4byte gMetatileAttributes_IslandHarbor
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_TrainerHill:: @ 83DFD84
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_TrainerHill
	.4byte gTilesetPalettes_TrainerHill
	.4byte gMetatiles_TrainerHill
	.4byte gMetatileAttributes_TrainerHill
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_NavelRock:: @ 83DFD9C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_NavelRock
	.4byte gTilesetPalettes_NavelRock
	.4byte gMetatiles_NavelRock
	.4byte gMetatileAttributes_NavelRock
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_BattleFrontierRankingHall:: @ 83DFDB4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleFrontierRankingHall
	.4byte gTilesetPalettes_BattleFrontierRankingHall
	.4byte gMetatiles_BattleFrontierRankingHall
	.4byte gMetatileAttributes_BattleFrontierRankingHall
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_BattleTent:: @ 83DFDCC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleTent
	.4byte gTilesetPalettes_BattleTent
	.4byte gMetatiles_BattleTent
	.4byte gMetatileAttributes_BattleTent
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_MysteryEventsHouse:: @ 83DFDE4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MysteryEventsHouse
	.4byte gTilesetPalettes_MysteryEventsHouse
	.4byte gMetatiles_MysteryEventsHouse
	.4byte gMetatileAttributes_MysteryEventsHouse
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_UnionRoom:: @ 83DFDFC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_UnionRoom
	.4byte gTilesetPalettes_UnionRoom
	.4byte gMetatiles_UnionRoom
	.4byte gMetatileAttributes_UnionRoom
	.4byte NULL @ animation callback
	.4byte NULL @ palette overrides

	.align 2
gTileset_NationalPark::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_NationalPark
	.4byte gTilesetPalettes_NationalPark
	.4byte gMetatiles_NationalPark
	.4byte gMetatileAttributes_NationalPark
	.4byte InitTilesetAnim_NationalPark
	.4byte NULL @ palette overrides

	.align 2
gTileset_PalletTown::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_PalletTown
	.4byte gTilesetPalettes_PalletTown
	.4byte gMetatiles_PalletTown
	.4byte gMetatileAttributes_PalletTown
	.4byte NULL

	.align 2
gTileset_ViridianCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_ViridianCity
	.4byte gTilesetPalettes_ViridianCity
	.4byte gMetatiles_ViridianCity
	.4byte gMetatileAttributes_ViridianCity
	.4byte NULL

	.align 2
gTileset_PewterCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_PewterCity
	.4byte gTilesetPalettes_PewterCity
	.4byte gMetatiles_PewterCity
	.4byte gMetatileAttributes_PewterCity
	.4byte NULL

	.align 2
gTileset_CeruleanCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_CeruleanCity
	.4byte gTilesetPalettes_CeruleanCity
	.4byte gMetatiles_CeruleanCity
	.4byte gMetatileAttributes_CeruleanCity
	.4byte NULL

	.align 2
gTileset_LavenderTown::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_LavenderTown
	.4byte gTilesetPalettes_LavenderTown
	.4byte gMetatiles_LavenderTown
	.4byte gMetatileAttributes_LavenderTown
	.4byte NULL

	.align 2
gTileset_VermilionCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_VermilionCity
	.4byte gTilesetPalettes_VermilionCity
	.4byte gMetatiles_VermilionCity
	.4byte gMetatileAttributes_VermilionCity
	.4byte NULL

	.align 2
gTileset_CeladonCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_CeladonCity
	.4byte gTilesetPalettes_CeladonCity
	.4byte gMetatiles_CeladonCity
	.4byte gMetatileAttributes_CeladonCity
	.4byte NULL

	.align 2
gTileset_FuchsiaCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_FuchsiaCity
	.4byte gTilesetPalettes_FuchsiaCity
	.4byte gMetatiles_FuchsiaCity
	.4byte gMetatileAttributes_FuchsiaCity
	.4byte NULL

	.align 2
gTileset_IndigoPlateau::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_IndigoPlateau
	.4byte gTilesetPalettes_IndigoPlateau
	.4byte gMetatiles_IndigoPlateau
	.4byte gMetatileAttributes_IndigoPlateau
	.4byte NULL

	.align 2
gTileset_SaffronCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_SaffronCity
	.4byte gTilesetPalettes_SaffronCity
	.4byte gMetatiles_SaffronCity
	.4byte gMetatileAttributes_SaffronCity
	.4byte NULL

	.align 2
gTileset_GeneralKanto::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_GeneralKanto
	.4byte gTilesetPalettes_GeneralKanto
	.4byte gMetatiles_GeneralKanto
	.4byte gMetatileAttributes_GeneralKanto
	.4byte NULL


	.align 2
gTileset_RedsHouse::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_RedsHouse
	.4byte gTilesetPalettes_RedsHouse
	.4byte gMetatiles_RedsHouse
	.4byte gMetatileAttributes_RedsHouse
	.4byte NULL

	.align 2
gTileset_ViridianGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_ViridianGym
	.4byte gTilesetPalettes_ViridianGym
	.4byte gMetatiles_ViridianGym
	.4byte gMetatileAttributes_ViridianGym
	.4byte NULL

	.align 2
gTileset_PewterGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_PewterGym
	.4byte gTilesetPalettes_PewterGym
	.4byte gMetatiles_PewterGym
	.4byte gMetatileAttributes_PewterGym
	.4byte NULL

	.align 2
gTileset_PewterMuseum::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_PewterMuseum
	.4byte gTilesetPalettes_PewterMuseum
	.4byte gMetatiles_PewterMuseum
	.4byte gMetatileAttributes_PewterMuseum
	.4byte NULL

	.align 2
gTileset_CeruleanGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_CeruleanGym
	.4byte gTilesetPalettes_CeruleanGym
	.4byte gMetatiles_CeruleanGym
	.4byte gMetatileAttributes_CeruleanGym
	.4byte NULL

	.align 2
gTileset_VermilionGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_VermilionGym
	.4byte gTilesetPalettes_VermilionGym
	.4byte gMetatiles_VermilionGym
	.4byte gMetatileAttributes_VermilionGym
	.4byte NULL

	.align 2
gTileset_SoulHouse::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_SoulHouse
	.4byte gTilesetPalettes_SoulHouse
	.4byte gMetatiles_SoulHouse
	.4byte gMetatileAttributes_SoulHouse
	.4byte NULL

	.align 2
gTileset_RestaurantHotel::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_RestaurantHotel
	.4byte gTilesetPalettes_RestaurantHotel
	.4byte gMetatiles_RestaurantHotel
	.4byte gMetatileAttributes_RestaurantHotel
	.4byte NULL

	.align 2
gTileset_CeladonMansion::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_CeladonMansion
	.4byte gTilesetPalettes_CeladonMansion
	.4byte gMetatiles_CeladonMansion
	.4byte gMetatileAttributes_CeladonMansion
	.4byte NULL

	.align 2
gTileset_SaffronGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_SaffronGym
	.4byte gTilesetPalettes_SaffronGym
	.4byte gMetatiles_SaffronGym
	.4byte gMetatileAttributes_SaffronGym
	.4byte NULL

	.align 2
gTileset_SafariZoneHouse::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_SafariZoneHouse
	.4byte gTilesetPalettes_SafariZoneHouse
	.4byte gMetatiles_SafariZoneHouse
	.4byte gMetatileAttributes_SafariZoneHouse
	.4byte NULL

	.align 2
gTileset_FuchsiaGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_FuchsiaGym
	.4byte gTilesetPalettes_FuchsiaGym
	.4byte gMetatiles_FuchsiaGym
	.4byte gMetatileAttributes_FuchsiaGym
	.4byte NULL

	.align 2
gTileset_HallOfFame::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_HallOfFame
	.4byte gTilesetPalettes_HallOfFame
	.4byte gMetatiles_HallOfFame
	.4byte gMetatileAttributes_HallOfFame
	.4byte NULL

	.align 2
gTileset_PowerPlant::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_PowerPlant
	.4byte gTilesetPalettes_PowerPlant
	.4byte gMetatiles_PowerPlant
	.4byte gMetatileAttributes_PowerPlant
	.4byte NULL

	.align 2
gTileset_DiglettsCave::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_DiglettsCave
	.4byte gTilesetPalettes_DiglettsCave
	.4byte gMetatiles_DiglettsCave
	.4byte gMetatileAttributes_DiglettsCave
	.4byte NULL
