	.align 1
gMetatiles_General:: @ 83960F0
	.incbin "data/tilesets/primary/general/metatiles.bin"

	.align 1
gMetatileAttributes_General:: @ 83980F0
	.incbin "data/tilesets/primary/general/metatile_attributes.bin"

	.align 1
gMetatiles_NewBark:: @ 83984F0
	.incbin "data/tilesets/secondary/new_bark/metatiles.bin"

	.align 1
gMetatileAttributes_NewBark:: @ 8398DF0
	.incbin "data/tilesets/secondary/new_bark/metatile_attributes.bin"

	.align 1
gMetatiles_Goldenrod:: @ 8398F10
	.incbin "data/tilesets/secondary/goldenrod/metatiles.bin"

	.align 1
gMetatileAttributes_Goldenrod:: @ 839A4F0
	.incbin "data/tilesets/secondary/goldenrod/metatile_attributes.bin"

	.align 1
gMetatiles_Violet:: @ 839A7AC
	.incbin "data/tilesets/secondary/violet/metatiles.bin"

	.align 1
gMetatileAttributes_Violet:: @ 839BF5C
	.incbin "data/tilesets/secondary/violet/metatile_attributes.bin"

	.align 1
gMetatiles_Slateport:: @ 839C252
	.incbin "data/tilesets/secondary/slateport/metatiles.bin"

	.align 1
gMetatileAttributes_Slateport:: @ 839DBB2
	.incbin "data/tilesets/secondary/slateport/metatile_attributes.bin"

	.align 1
gMetatiles_Mauville:: @ 839DEDE
	.incbin "data/tilesets/secondary/mauville/metatiles.bin"

	.align 1
gMetatileAttributes_Mauville:: @ 839FEBE
	.incbin "data/tilesets/secondary/mauville/metatile_attributes.bin"

	.align 1
gMetatiles_Azalea:: @ 83A02BA
	.incbin "data/tilesets/secondary/azalea/metatiles.bin"

	.align 1
gMetatileAttributes_Azalea:: @ 83A1E4A
	.incbin "data/tilesets/secondary/azalea/metatile_attributes.bin"

	.align 1
gMetatiles_Fallarbor:: @ 83A21BC
	.incbin "data/tilesets/secondary/fallarbor/metatiles.bin"

	.align 1
gMetatileAttributes_Fallarbor:: @ 83A38AC
	.incbin "data/tilesets/secondary/fallarbor/metatile_attributes.bin"

	.align 1
gMetatiles_Fortree:: @ 83A3B8A
	.incbin "data/tilesets/secondary/fortree/metatiles.bin"

	.align 1
gMetatileAttributes_Fortree:: @ 83A4D0A
	.incbin "data/tilesets/secondary/fortree/metatile_attributes.bin"

	.align 1
gMetatiles_Lilycove:: @ 83A4F3A
	.incbin "data/tilesets/secondary/lilycove/metatiles.bin"

	.align 1
gMetatileAttributes_Lilycove:: @ 83A652A
	.incbin "data/tilesets/secondary/lilycove/metatile_attributes.bin"

	.align 1
gMetatiles_Mossdeep:: @ 83A67E8
	.incbin "data/tilesets/secondary/mossdeep/metatiles.bin"

	.align 1
gMetatileAttributes_Mossdeep:: @ 83A8448
	.incbin "data/tilesets/secondary/mossdeep/metatile_attributes.bin"

	.align 1
gMetatiles_EverGrande:: @ 83A87D4
	.incbin "data/tilesets/secondary/ever_grande/metatiles.bin"

	.align 1
gMetatileAttributes_EverGrande:: @ 83A9254
	.incbin "data/tilesets/secondary/ever_grande/metatile_attributes.bin"

	.align 1
gMetatiles_Pacifidlog:: @ 83A93A4
	.incbin "data/tilesets/secondary/pacifidlog/metatiles.bin"

	.align 1
gMetatileAttributes_Pacifidlog:: @ 83AA054
	.incbin "data/tilesets/secondary/pacifidlog/metatile_attributes.bin"

	.align 1
gMetatiles_Sootopolis:: @ 83AA1EA
	.incbin "data/tilesets/secondary/sootopolis/metatiles.bin"

	.align 1
gMetatileAttributes_Sootopolis:: @ 83AB1CA
	.incbin "data/tilesets/secondary/sootopolis/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontierOutsideWest:: @ 83AB3C6
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontierOutsideWest:: @ 83AD3A6
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontierOutsideEast:: @ 83AD7A2
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontierOutsideEast:: @ 83AF782
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/metatile_attributes.bin"

	.align 1
gMetatiles_InsideBuilding:: @ 83AFB7E
	.incbin "data/tilesets/primary/building/metatiles.bin"

	.align 1
gMetatileAttributes_InsideBuilding:: @ 83AFBFE
	.incbin "data/tilesets/primary/building/metatile_attributes.bin"

	.align 1
gMetatiles_Shop:: @ 83AFC0E
	.incbin "data/tilesets/secondary/shop/metatiles.bin"

	.align 1
gMetatileAttributes_Shop:: @ 83B0E1E
	.incbin "data/tilesets/secondary/shop/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonCenter:: @ 83B1060
	.incbin "data/tilesets/secondary/pokemon_center/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonCenter:: @ 83B1EE0
	.incbin "data/tilesets/secondary/pokemon_center/metatile_attributes.bin"

	.align 1
gMetatiles_Cave:: @ 83B20B0
	.incbin "data/tilesets/secondary/cave/metatiles.bin"

	.align 1
gMetatileAttributes_Cave:: @ 83B3A90
	.incbin "data/tilesets/secondary/cave/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonSchool:: @ 83B3DCC
	.incbin "data/tilesets/secondary/pokemon_school/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonSchool:: @ 83B416C
	.incbin "data/tilesets/secondary/pokemon_school/metatile_attributes.bin"

	.align 1
gMetatiles_RadioTower:: @ 83B41E0
	.incbin "data/tilesets/secondary/radio_tower/metatiles.bin"

	.align 1
gMetatileAttributes_RadioTower:: @ 83B4860
	.incbin "data/tilesets/secondary/radio_tower/metatile_attributes.bin"

	.align 1
gMetatiles_Gatehouse:: @ 83B4930
	.incbin "data/tilesets/secondary/gatehouse/metatiles.bin"

	.align 1
gMetatileAttributes_Gatehouse:: @ 83B4950
	.incbin "data/tilesets/secondary/gatehouse/metatile_attributes.bin"

	.align 1
gMetatiles_RockTunnel:: @ 83B4954
	.incbin "data/tilesets/secondary/rock_tunnel/metatiles.bin"

	.align 1
gMetatileAttributes_RockTunnel:: @ 83B5344
	.incbin "data/tilesets/secondary/rock_tunnel/metatile_attributes.bin"

	.align 1
gMetatiles_Underground:: @ 83B5482
	.incbin "data/tilesets/secondary/underground/metatiles.bin"

	.align 1
gMetatileAttributes_Underground:: @ 83B5C22
	.incbin "data/tilesets/secondary/underground/metatile_attributes.bin"

	.align 1
gMetatiles_CableClub:: @ 83B5D16
	.incbin "data/tilesets/secondary/cable_club/metatiles.bin"

	.align 1
gMetatileAttributes_CableClub:: @ 83B6D16
	.incbin "data/tilesets/secondary/cable_club/metatile_attributes.bin"

	.align 1
gMetatiles_PagodaTower:: @ 83B6F16
	.incbin "data/tilesets/secondary/pagoda_tower/metatiles.bin"

	.align 1
gMetatileAttributes_PagodaTower:: @ 83B7296
	.incbin "data/tilesets/secondary/pagoda_tower/metatile_attributes.bin"

	.align 1
gMetatiles_RuinsOfAlph:: @ 83B7306
	.incbin "data/tilesets/secondary/ruins_of_alph/metatiles.bin"

	.align 1
gMetatileAttributes_RuinsOfAlph:: @ 83B7786
	.incbin "data/tilesets/secondary/ruins_of_alph/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonDayCare:: @ 83B7816
	.incbin "data/tilesets/secondary/pokemon_day_care/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonDayCare:: @ 83B7C56
	.incbin "data/tilesets/secondary/pokemon_day_care/metatile_attributes.bin"

	.align 1
gMetatiles_Facility:: @ 83B7CDE
	.incbin "data/tilesets/secondary/facility/metatiles.bin"

	.align 1
gMetatileAttributes_Facility:: @ 83B9CCE
	.incbin "data/tilesets/secondary/facility/metatile_attributes.bin"

	.align 1
gMetatiles_BikeShop:: @ 83BA0CC
	.incbin "data/tilesets/secondary/bike_shop/metatiles.bin"

	.align 1
gMetatileAttributes_BikeShop:: @ 83BB04C
	.incbin "data/tilesets/secondary/bike_shop/metatile_attributes.bin"

	.align 1
gMetatiles_Forest:: @ 83BB23C
	.incbin "data/tilesets/secondary/forest/metatiles.bin"

	.align 1
gMetatileAttributes_Forest:: @ 83BB76C
	.incbin "data/tilesets/secondary/forest/metatile_attributes.bin"

	.align 1
gMetatiles_SecretBaseSecondary:: @ 83BB812
	.incbin "data/tilesets/secondary/secret_base/metatiles.bin"

	.align 1
gMetatileAttributes_SecretBaseSecondary:: @ 83BCC52
	.incbin "data/tilesets/secondary/secret_base/metatile_attributes.bin"

	.align 1
gMetatiles_MagnetTrain:: @ 83BCEDA
	.incbin "data/tilesets/secondary/magnet_train/metatiles.bin"

	.align 1
gMetatileAttributes_MagnetTrain:: @ 83BD13A
	.incbin "data/tilesets/secondary/magnet_train/metatile_attributes.bin"

	.align 1
gMetatiles_Contest:: @ 83BD186
	.incbin "data/tilesets/secondary/contest/metatiles.bin"

	.align 1
gMetatileAttributes_Contest:: @ 83BE016
	.incbin "data/tilesets/secondary/contest/metatile_attributes.bin"

	.align 1
gMetatiles_LilycoveMuseum:: @ 83BE1E8
	.incbin "data/tilesets/secondary/lilycove_museum/metatiles.bin"

	.align 1
gMetatileAttributes_LilycoveMuseum:: @ 83BEAD8
	.incbin "data/tilesets/secondary/lilycove_museum/metatile_attributes.bin"

	.align 1
gMetatiles_PlayersHouse:: @ 83BEBF6
	.incbin "data/tilesets/secondary/players_house/metatiles.bin"

	.align 1
gMetatileAttributes_PlayersHouse:: @ 83BF836
	.incbin "data/tilesets/secondary/players_house/metatile_attributes.bin"

	.align 1
gMetatiles_Lab:: @ 83BF9BE
	.incbin "data/tilesets/secondary/lab/metatiles.bin"

	.align 1
gMetatileAttributes_Lab:: @ 83C039E
	.incbin "data/tilesets/secondary/lab/metatile_attributes.bin"

	.align 1
gMetatiles_Underwater:: @ 83C04DA
	.incbin "data/tilesets/secondary/underwater/metatiles.bin"

	.align 1
gMetatileAttributes_Underwater:: @ 83C139A
	.incbin "data/tilesets/secondary/underwater/metatile_attributes.bin"

	.align 1
gMetatiles_GenericBuilding:: @ 83C1572
	.incbin "data/tilesets/secondary/generic_building/metatiles.bin"

	.align 1
gMetatileAttributes_GenericBuilding:: @ 83C3572
	.incbin "data/tilesets/secondary/generic_building/metatile_attributes.bin"

	.align 1
gMetatiles_GameCorner:: @ 83C3972
	.incbin "data/tilesets/secondary/game_corner/metatiles.bin"

	.align 1
gMetatileAttributes_GameCorner:: @ 83C3F72
	.incbin "data/tilesets/secondary/game_corner/metatile_attributes.bin"

	.align 1
gMetatiles_DepartmentStore:: @ 83C4032
	.incbin "data/tilesets/secondary/department_store/metatiles.bin"

	.align 1
gMetatileAttributes_DepartmentStore:: @ 83C43D2
	.incbin "data/tilesets/secondary/department_store/metatile_attributes.bin"

	.align 1
gMetatiles_GoldenrodGym:: @ 83C4446
	.incbin "data/tilesets/secondary/goldenrod_gym/metatiles.bin"

	.align 1
gMetatileAttributes_GoldenrodGym:: @ 83C47C6
	.incbin "data/tilesets/secondary/goldenrod_gym/metatile_attributes.bin"

	.align 1
gMetatiles_AzaleaGym:: @ 83C4836
	.incbin "data/tilesets/secondary/azalea_gym/metatiles.bin"

	.align 1
gMetatileAttributes_AzaleaGym:: @ 83C4C86
	.incbin "data/tilesets/secondary/azalea_gym/metatile_attributes.bin"

	.align 1
gMetatiles_MauvilleGym:: @ 83C4D10
	.incbin "data/tilesets/secondary/mauville_gym/metatiles.bin"

	.align 1
gMetatileAttributes_MauvilleGym:: @ 83C5460
	.incbin "data/tilesets/secondary/mauville_gym/metatile_attributes.bin"

	.align 1
gMetatiles_LavaridgeGym:: @ 83C554A
	.incbin "data/tilesets/secondary/lavaridge_gym/metatiles.bin"

	.align 1
gMetatileAttributes_LavaridgeGym:: @ 83C591A
	.incbin "data/tilesets/secondary/lavaridge_gym/metatile_attributes.bin"

	.align 1
gMetatiles_VioletGym:: @ 83C5994
	.incbin "data/tilesets/secondary/violet_gym/metatiles.bin"

	.align 1
gMetatilesAttributes_VioletGym:: @ 83C6794
	.incbin "data/tilesets/secondary/violet_gym/metatile_attributes.bin"

	.align 1
gMetatiles_FortreeGym:: @ 83C6954
	.incbin "data/tilesets/secondary/fortree_gym/metatiles.bin"

	.align 1
gMetatileAttributes_FortreeGym:: @ 83C6E54
	.incbin "data/tilesets/secondary/fortree_gym/metatile_attributes.bin"

	.align 1
gMetatiles_MossdeepGym:: @ 83C6EF4
	.incbin "data/tilesets/secondary/mossdeep_gym/metatiles.bin"

	.align 1
gMetatileAttributes_MossdeepGym:: @ 83C7644
	.incbin "data/tilesets/secondary/mossdeep_gym/metatile_attributes.bin"

	.align 1
gMetatiles_SootopolisGym:: @ 83C772E
	.incbin "data/tilesets/secondary/sootopolis_gym/metatiles.bin"

	.align 1
gMetatileAttributes_SootopolisGym:: @ 83C7ECE
	.incbin "data/tilesets/secondary/sootopolis_gym/metatile_attributes.bin"

	.align 1
gMetatiles_TrickHousePuzzle:: @ 83C7FC2
	.incbin "data/tilesets/secondary/trick_house_puzzle/metatiles.bin"

	.align 1
gMetatileAttributes_TrickHousePuzzle:: @ 83C8B92
	.incbin "data/tilesets/secondary/trick_house_puzzle/metatile_attributes.bin"

	.align 1
gMetatiles_InsideShip:: @ 83C8D0C
	.incbin "data/tilesets/secondary/inside_ship/metatiles.bin"

	.align 1
gMetatileAttributes_InsideShip:: @ 83C9CCC
	.incbin "data/tilesets/secondary/inside_ship/metatile_attributes.bin"

	.align 1
gMetatiles_SecretBasePrimary:: @ 83C9EC4
	.incbin "data/tilesets/primary/secret_base/metatiles.bin"

	.align 1
gMetatileAttributes_SecretBasePrimary:: @ 83C9EE4
	.incbin "data/tilesets/primary/secret_base/metatile_attributes.bin"

	.align 1
gMetatiles_EliteFour:: @ 83C9EE8
	.incbin "data/tilesets/secondary/elite_four/metatiles.bin"

	.align 1
gMetatileAttributes_EliteFour:: @ 83CB3A8
	.incbin "data/tilesets/secondary/elite_four/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontier:: @ 83CB640
	.incbin "data/tilesets/secondary/battle_frontier/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontier:: @ 83CD610
	.incbin "data/tilesets/secondary/battle_frontier/metatile_attributes.bin"

	.align 1
gMetatiles_BattlePalace:: @ 83CDA0A
	.incbin "data/tilesets/secondary/battle_palace/metatiles.bin"

	.align 1
gMetatileAttributes_BattlePalace:: @ 83CE4EA
	.incbin "data/tilesets/secondary/battle_palace/metatile_attributes.bin"

	.align 1
gMetatiles_BattleDome:: @ 83CE646
	.incbin "data/tilesets/secondary/battle_dome/metatiles.bin"

	.align 1
gMetatileAttributes_BattleDome:: @ 83D00F6
	.incbin "data/tilesets/secondary/battle_dome/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFactory:: @ 83D044C
	.incbin "data/tilesets/secondary/battle_factory/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFactory:: @ 83D1A6C
	.incbin "data/tilesets/secondary/battle_factory/metatile_attributes.bin"

	.align 1
gMetatiles_BattlePike:: @ 83D1D30
	.incbin "data/tilesets/secondary/battle_pike/metatiles.bin"

	.align 1
gMetatileAttributes_BattlePike:: @ 83D32E0
	.incbin "data/tilesets/secondary/battle_pike/metatile_attributes.bin"

	.align 1
gMetatiles_BattleArena:: @ 83D3596
	.incbin "data/tilesets/secondary/battle_arena/metatiles.bin"

	.align 1
gMetatileAttributes_BattleArena:: @ 83D40A6
	.incbin "data/tilesets/secondary/battle_arena/metatile_attributes.bin"

	.align 1
gMetatiles_BattlePyramid:: @ 83D4208
	.incbin "data/tilesets/secondary/battle_pyramid/metatiles.bin"

	.align 1
gMetatileAttributes_BattlePyramid:: @ 83D4FD8
	.incbin "data/tilesets/secondary/battle_pyramid/metatile_attributes.bin"

	.align 1
gMetatiles_MirageTower:: @ 83D5192
	.incbin "data/tilesets/secondary/mirage_tower/metatiles.bin"

	.align 1
gMetatileAttributes_MirageTower:: @ 83D6B72
	.incbin "data/tilesets/secondary/mirage_tower/metatile_attributes.bin"

	.align 1
gMetatiles_MossdeepGameCorner:: @ 83D6EAE
	.incbin "data/tilesets/secondary/mossdeep_game_corner/metatiles.bin"

	.align 1
gMetatileAttributes_MossdeepGameCorner:: @ 83D71FE
	.incbin "data/tilesets/secondary/mossdeep_game_corner/metatile_attributes.bin"

	.align 1
gMetatiles_IslandHarbor:: @ 83D7268
	.incbin "data/tilesets/secondary/island_harbor/metatiles.bin"

	.align 1
gMetatileAttributes_IslandHarbor:: @ 83D8FC8
	.incbin "data/tilesets/secondary/island_harbor/metatile_attributes.bin"

	.align 1
gMetatiles_TrainerHill:: @ 83D9374
	.incbin "data/tilesets/secondary/trainer_hill/metatiles.bin"

	.align 1
gMetatileAttributes_TrainerHill:: @ 83DB1D4
	.incbin "data/tilesets/secondary/trainer_hill/metatile_attributes.bin"

	.align 1
gMetatiles_NavelRock:: @ 83DB5A0
	.incbin "data/tilesets/secondary/navel_rock/metatiles.bin"

	.align 1
gMetatileAttributes_NavelRock:: @ 83DD1D0
	.incbin "data/tilesets/secondary/navel_rock/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontierRankingHall:: @ 83DD556
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontierRankingHall:: @ 83DDB36
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/metatile_attributes.bin"

	.align 1
gMetatiles_BattleTent:: @ 83DDBF2
	.incbin "data/tilesets/secondary/battle_tent/metatiles.bin"

	.align 1
gMetatileAttributes_BattleTent:: @ 83DECC2
	.incbin "data/tilesets/secondary/battle_tent/metatile_attributes.bin"

	.align 1
gMetatiles_MysteryEventsHouse:: @ 83DEEDC
	.incbin "data/tilesets/secondary/mystery_events_house/metatiles.bin"

	.align 1
gMetatileAttributes_MysteryEventsHouse:: @ 83DF30C
	.incbin "data/tilesets/secondary/mystery_events_house/metatile_attributes.bin"

	.align 1
gMetatiles_UnionRoom:: @ 83DF392
	.incbin "data/tilesets/secondary/union_room/metatiles.bin"

	.align 1
gMetatileAttributes_UnionRoom:: @ 83DF6A2
	.incbin "data/tilesets/secondary/union_room/metatile_attributes.bin"

	.align 1
gMetatiles_NationalPark::
	.incbin "data/tilesets/secondary/national_park/metatiles.bin"

	.align 1
gMetatileAttributes_NationalPark::
	.incbin "data/tilesets/secondary/national_park/metatile_attributes.bin"

	.align 1
gMetatiles_PalletTown::
	.incbin "data/tilesets/secondary/pallettown/metatiles.bin"

	.align 1
gMetatileAttributes_PalletTown::
	.incbin "data/tilesets/secondary/pallettown/metatile_attributes.bin"
	.align 1
gMetatiles_ViridianCity::
	.incbin "data/tilesets/secondary/viridiancity/metatiles.bin"

	.align 1
gMetatileAttributes_ViridianCity::
	.incbin "data/tilesets/secondary/viridiancity/metatile_attributes.bin"
	.align 1
gMetatiles_PewterCity::
	.incbin "data/tilesets/secondary/pewtercity/metatiles.bin"

	.align 1
gMetatileAttributes_PewterCity::
	.incbin "data/tilesets/secondary/pewtercity/metatile_attributes.bin"
	.align 1
gMetatiles_CeruleanCity::
	.incbin "data/tilesets/secondary/ceruleancity/metatiles.bin"

	.align 1
gMetatileAttributes_CeruleanCity::
	.incbin "data/tilesets/secondary/ceruleancity/metatile_attributes.bin"
	.align 1
gMetatiles_LavenderTown::
	.incbin "data/tilesets/secondary/lavendertown/metatiles.bin"

	.align 1
gMetatileAttributes_LavenderTown::
	.incbin "data/tilesets/secondary/lavendertown/metatile_attributes.bin"
	.align 1
gMetatiles_VermilionCity::
	.incbin "data/tilesets/secondary/vermilioncity/metatiles.bin"

	.align 1
gMetatileAttributes_VermilionCity::
	.incbin "data/tilesets/secondary/vermilioncity/metatile_attributes.bin"
	.align 1
gMetatiles_CeladonCity::
	.incbin "data/tilesets/secondary/celadoncity/metatiles.bin"

	.align 1
gMetatileAttributes_CeladonCity::
	.incbin "data/tilesets/secondary/celadoncity/metatile_attributes.bin"
	.align 1
gMetatiles_FuchsiaCity::
	.incbin "data/tilesets/secondary/fuchsiacity/metatiles.bin"

	.align 1
gMetatileAttributes_FuchsiaCity::
	.incbin "data/tilesets/secondary/fuchsiacity/metatile_attributes.bin"
	.align 1
gMetatiles_IndigoPlateau::
	.incbin "data/tilesets/secondary/indigoplateau/metatiles.bin"

	.align 1
gMetatileAttributes_IndigoPlateau::
	.incbin "data/tilesets/secondary/indigoplateau/metatile_attributes.bin"
	.align 1
gMetatiles_SaffronCity::
	.incbin "data/tilesets/secondary/saffroncity/metatiles.bin"

	.align 1
gMetatileAttributes_SaffronCity::
	.incbin "data/tilesets/secondary/saffroncity/metatile_attributes.bin"
	.align 1
gMetatiles_GeneralKanto::
	.incbin "data/tilesets/primary/generalkanto/metatiles.bin"

	.align 1
gMetatileAttributes_GeneralKanto::
	.incbin "data/tilesets/primary/generalkanto/metatile_attributes.bin"

	.align 1
gMetatiles_RedsHouse::
	.incbin "data/tilesets/secondary/redshouse/metatiles.bin"

	.align 1
gMetatileAttributes_RedsHouse::
	.incbin "data/tilesets/secondary/redshouse/metatile_attributes.bin"
	.align 1
gMetatiles_ViridianGym::
	.incbin "data/tilesets/secondary/viridiangym/metatiles.bin"

	.align 1
gMetatileAttributes_ViridianGym::
	.incbin "data/tilesets/secondary/viridiangym/metatile_attributes.bin"
	.align 1
gMetatiles_PewterGym::
	.incbin "data/tilesets/secondary/pewtergym/metatiles.bin"

	.align 1
gMetatileAttributes_PewterGym::
	.incbin "data/tilesets/secondary/pewtergym/metatile_attributes.bin"
	.align 1
gMetatiles_PewterMuseum::
	.incbin "data/tilesets/secondary/pewtermuseum/metatiles.bin"

	.align 1
gMetatileAttributes_PewterMuseum::
	.incbin "data/tilesets/secondary/pewtermuseum/metatile_attributes.bin"
	.align 1
gMetatiles_CeruleanGym::
	.incbin "data/tilesets/secondary/ceruleangym/metatiles.bin"

	.align 1
gMetatileAttributes_CeruleanGym::
	.incbin "data/tilesets/secondary/ceruleangym/metatile_attributes.bin"
	.align 1
gMetatiles_VermilionGym::
	.incbin "data/tilesets/secondary/vermiliongym/metatiles.bin"

	.align 1
gMetatileAttributes_VermilionGym::
	.incbin "data/tilesets/secondary/vermiliongym/metatile_attributes.bin"
	.align 1
gMetatiles_SoulHouse::
	.incbin "data/tilesets/secondary/soulhouse/metatiles.bin"

	.align 1
gMetatileAttributes_SoulHouse::
	.incbin "data/tilesets/secondary/soulhouse/metatile_attributes.bin"
	.align 1
gMetatiles_RestaurantHotel::
	.incbin "data/tilesets/secondary/restauranthotel/metatiles.bin"

	.align 1
gMetatileAttributes_RestaurantHotel::
	.incbin "data/tilesets/secondary/restauranthotel/metatile_attributes.bin"
	.align 1
gMetatiles_CeladonMansion::
	.incbin "data/tilesets/secondary/celadonmansion/metatiles.bin"

	.align 1
gMetatileAttributes_CeladonMansion::
	.incbin "data/tilesets/secondary/celadonmansion/metatile_attributes.bin"
	.align 1
gMetatiles_SaffronGym::
	.incbin "data/tilesets/secondary/saffrongym/metatiles.bin"

	.align 1
gMetatileAttributes_SaffronGym::
	.incbin "data/tilesets/secondary/saffrongym/metatile_attributes.bin"
	.align 1
gMetatiles_SafariZoneHouse::
	.incbin "data/tilesets/secondary/safarizonehouse/metatiles.bin"

	.align 1
gMetatileAttributes_SafariZoneHouse::
	.incbin "data/tilesets/secondary/safarizonehouse/metatile_attributes.bin"
	.align 1
gMetatiles_FuchsiaGym::
	.incbin "data/tilesets/secondary/fuchsiagym/metatiles.bin"

	.align 1
gMetatileAttributes_FuchsiaGym::
	.incbin "data/tilesets/secondary/fuchsiagym/metatile_attributes.bin"
	.align 1
gMetatiles_HallOfFame::
	.incbin "data/tilesets/secondary/halloffame/metatiles.bin"

	.align 1
gMetatileAttributes_HallOfFame::
	.incbin "data/tilesets/secondary/halloffame/metatile_attributes.bin"
	.align 1
gMetatiles_PowerPlant::
	.incbin "data/tilesets/secondary/powerplant/metatiles.bin"

	.align 1
gMetatileAttributes_PowerPlant::
	.incbin "data/tilesets/secondary/powerplant/metatile_attributes.bin"
	.align 1
gMetatiles_DiglettsCave::
	.incbin "data/tilesets/secondary/diglettscave/metatiles.bin"

	.align 1
gMetatileAttributes_DiglettsCave::
	.incbin "data/tilesets/secondary/diglettscave/metatile_attributes.bin"