	.align 1
gMetatiles_General::
	.incbin "data/tilesets/primary/general/metatiles.bin"

	.align 1
gMetatileAttributes_General::
	.incbin "data/tilesets/primary/general/metatile_attributes.bin"

	.align 1
gMetatiles_NewBark::
	.incbin "data/tilesets/secondary/new_bark/metatiles.bin"

	.align 1
gMetatileAttributes_NewBark::
	.incbin "data/tilesets/secondary/new_bark/metatile_attributes.bin"

	.align 1
gMetatiles_Goldenrod::
	.incbin "data/tilesets/secondary/goldenrod/metatiles.bin"

	.align 1
gMetatileAttributes_Goldenrod::
	.incbin "data/tilesets/secondary/goldenrod/metatile_attributes.bin"

	.align 1
gMetatiles_Violet::
	.incbin "data/tilesets/secondary/violet/metatiles.bin"

	.align 1
gMetatileAttributes_Violet::
	.incbin "data/tilesets/secondary/violet/metatile_attributes.bin"

	.align 1
gMetatiles_Slateport::
	.incbin "data/tilesets/secondary/slateport/metatiles.bin"

	.align 1
gMetatileAttributes_Slateport::
	.incbin "data/tilesets/secondary/slateport/metatile_attributes.bin"

	.align 1
gMetatiles_Mauville::
	.incbin "data/tilesets/secondary/mauville/metatiles.bin"

	.align 1
gMetatileAttributes_Mauville::
	.incbin "data/tilesets/secondary/mauville/metatile_attributes.bin"

	.align 1
gMetatiles_Azalea::
	.incbin "data/tilesets/secondary/azalea/metatiles.bin"

	.align 1
gMetatileAttributes_Azalea::
	.incbin "data/tilesets/secondary/azalea/metatile_attributes.bin"

	.align 1
gMetatiles_Fallarbor::
	.incbin "data/tilesets/secondary/fallarbor/metatiles.bin"

	.align 1
gMetatileAttributes_Fallarbor::
	.incbin "data/tilesets/secondary/fallarbor/metatile_attributes.bin"

	.align 1
gMetatiles_Fortree::
	.incbin "data/tilesets/secondary/fortree/metatiles.bin"

	.align 1
gMetatileAttributes_Fortree::
	.incbin "data/tilesets/secondary/fortree/metatile_attributes.bin"

	.align 1
gMetatiles_Lilycove::
	.incbin "data/tilesets/secondary/lilycove/metatiles.bin"

	.align 1
gMetatileAttributes_Lilycove::
	.incbin "data/tilesets/secondary/lilycove/metatile_attributes.bin"

	.align 1
gMetatiles_Mossdeep::
	.incbin "data/tilesets/secondary/mossdeep/metatiles.bin"

	.align 1
gMetatileAttributes_Mossdeep::
	.incbin "data/tilesets/secondary/mossdeep/metatile_attributes.bin"

	.align 1
gMetatiles_EverGrande::
	.incbin "data/tilesets/secondary/ever_grande/metatiles.bin"

	.align 1
gMetatileAttributes_EverGrande::
	.incbin "data/tilesets/secondary/ever_grande/metatile_attributes.bin"

	.align 1
gMetatiles_Pacifidlog::
	.incbin "data/tilesets/secondary/pacifidlog/metatiles.bin"

	.align 1
gMetatileAttributes_Pacifidlog::
	.incbin "data/tilesets/secondary/pacifidlog/metatile_attributes.bin"

	.align 1
gMetatiles_Sootopolis::
	.incbin "data/tilesets/secondary/sootopolis/metatiles.bin"

	.align 1
gMetatileAttributes_Sootopolis::
	.incbin "data/tilesets/secondary/sootopolis/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontierOutsideWest::
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontierOutsideWest::
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontierOutsideEast::
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontierOutsideEast::
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/metatile_attributes.bin"

	.align 1
gMetatiles_InsideBuilding::
	.incbin "data/tilesets/primary/building/metatiles.bin"

	.align 1
gMetatileAttributes_InsideBuilding::
	.incbin "data/tilesets/primary/building/metatile_attributes.bin"

	.align 1
gMetatiles_Shop::
	.incbin "data/tilesets/secondary/shop/metatiles.bin"

	.align 1
gMetatileAttributes_Shop::
	.incbin "data/tilesets/secondary/shop/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonCenter::
	.incbin "data/tilesets/secondary/pokemon_center/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonCenter::
	.incbin "data/tilesets/secondary/pokemon_center/metatile_attributes.bin"

	.align 1
gMetatiles_Cave::
	.incbin "data/tilesets/secondary/cave/metatiles.bin"

	.align 1
gMetatileAttributes_Cave::
	.incbin "data/tilesets/secondary/cave/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonSchool::
	.incbin "data/tilesets/secondary/pokemon_school/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonSchool::
	.incbin "data/tilesets/secondary/pokemon_school/metatile_attributes.bin"

	.align 1
gMetatiles_RadioTower::
	.incbin "data/tilesets/secondary/radio_tower/metatiles.bin"

	.align 1
gMetatileAttributes_RadioTower::
	.incbin "data/tilesets/secondary/radio_tower/metatile_attributes.bin"

	.align 1
gMetatiles_Gatehouse::
	.incbin "data/tilesets/secondary/gatehouse/metatiles.bin"

	.align 1
gMetatileAttributes_Gatehouse::
	.incbin "data/tilesets/secondary/gatehouse/metatile_attributes.bin"

	.align 1
gMetatiles_RockTunnel::
	.incbin "data/tilesets/secondary/rock_tunnel/metatiles.bin"

	.align 1
gMetatileAttributes_RockTunnel::
	.incbin "data/tilesets/secondary/rock_tunnel/metatile_attributes.bin"

	.align 1
gMetatiles_Underground::
	.incbin "data/tilesets/secondary/underground/metatiles.bin"

	.align 1
gMetatileAttributes_Underground::
	.incbin "data/tilesets/secondary/underground/metatile_attributes.bin"

	.align 1
gMetatiles_CableClub::
	.incbin "data/tilesets/secondary/cable_club/metatiles.bin"

	.align 1
gMetatileAttributes_CableClub::
	.incbin "data/tilesets/secondary/cable_club/metatile_attributes.bin"

	.align 1
gMetatiles_PagodaTower::
	.incbin "data/tilesets/secondary/pagoda_tower/metatiles.bin"

	.align 1
gMetatileAttributes_PagodaTower::
	.incbin "data/tilesets/secondary/pagoda_tower/metatile_attributes.bin"

	.align 1
gMetatiles_RuinsOfAlph::
	.incbin "data/tilesets/secondary/ruins_of_alph/metatiles.bin"

	.align 1
gMetatileAttributes_RuinsOfAlph::
	.incbin "data/tilesets/secondary/ruins_of_alph/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonDayCare::
	.incbin "data/tilesets/secondary/pokemon_day_care/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonDayCare::
	.incbin "data/tilesets/secondary/pokemon_day_care/metatile_attributes.bin"

	.align 1
gMetatiles_Facility::
	.incbin "data/tilesets/secondary/facility/metatiles.bin"

	.align 1
gMetatileAttributes_Facility::
	.incbin "data/tilesets/secondary/facility/metatile_attributes.bin"

	.align 1
gMetatiles_BikeShop::
	.incbin "data/tilesets/secondary/bike_shop/metatiles.bin"

	.align 1
gMetatileAttributes_BikeShop::
	.incbin "data/tilesets/secondary/bike_shop/metatile_attributes.bin"

	.align 1
gMetatiles_Forest::
	.incbin "data/tilesets/secondary/forest/metatiles.bin"

	.align 1
gMetatileAttributes_Forest::
	.incbin "data/tilesets/secondary/forest/metatile_attributes.bin"

	.align 1
gMetatiles_SecretBaseSecondary::
	.incbin "data/tilesets/secondary/secret_base/metatiles.bin"

	.align 1
gMetatileAttributes_SecretBaseSecondary::
	.incbin "data/tilesets/secondary/secret_base/metatile_attributes.bin"

	.align 1
gMetatiles_MagnetTrain::
	.incbin "data/tilesets/secondary/magnet_train/metatiles.bin"

	.align 1
gMetatileAttributes_MagnetTrain::
	.incbin "data/tilesets/secondary/magnet_train/metatile_attributes.bin"

	.align 1
gMetatiles_Contest::
	.incbin "data/tilesets/secondary/contest/metatiles.bin"

	.align 1
gMetatileAttributes_Contest::
	.incbin "data/tilesets/secondary/contest/metatile_attributes.bin"

	.align 1
gMetatiles_LilycoveMuseum::
	.incbin "data/tilesets/secondary/lilycove_museum/metatiles.bin"

	.align 1
gMetatileAttributes_LilycoveMuseum::
	.incbin "data/tilesets/secondary/lilycove_museum/metatile_attributes.bin"

	.align 1
gMetatiles_PlayersHouse::
	.incbin "data/tilesets/secondary/players_house/metatiles.bin"

	.align 1
gMetatileAttributes_PlayersHouse::
	.incbin "data/tilesets/secondary/players_house/metatile_attributes.bin"

	.align 1
gMetatiles_Lab::
	.incbin "data/tilesets/secondary/lab/metatiles.bin"

	.align 1
gMetatileAttributes_Lab::
	.incbin "data/tilesets/secondary/lab/metatile_attributes.bin"

	.align 1
gMetatiles_Underwater::
	.incbin "data/tilesets/secondary/underwater/metatiles.bin"

	.align 1
gMetatileAttributes_Underwater::
	.incbin "data/tilesets/secondary/underwater/metatile_attributes.bin"

	.align 1
gMetatiles_GenericBuilding::
	.incbin "data/tilesets/secondary/generic_building/metatiles.bin"

	.align 1
gMetatileAttributes_GenericBuilding::
	.incbin "data/tilesets/secondary/generic_building/metatile_attributes.bin"

	.align 1
gMetatiles_GameCorner::
	.incbin "data/tilesets/secondary/game_corner/metatiles.bin"

	.align 1
gMetatileAttributes_GameCorner::
	.incbin "data/tilesets/secondary/game_corner/metatile_attributes.bin"

	.align 1
gMetatiles_DepartmentStore::
	.incbin "data/tilesets/secondary/department_store/metatiles.bin"

	.align 1
gMetatileAttributes_DepartmentStore::
	.incbin "data/tilesets/secondary/department_store/metatile_attributes.bin"

	.align 1
gMetatiles_GoldenrodGym::
	.incbin "data/tilesets/secondary/goldenrod_gym/metatiles.bin"

	.align 1
gMetatileAttributes_GoldenrodGym::
	.incbin "data/tilesets/secondary/goldenrod_gym/metatile_attributes.bin"

	.align 1
gMetatiles_AzaleaGym::
	.incbin "data/tilesets/secondary/azalea_gym/metatiles.bin"

	.align 1
gMetatileAttributes_AzaleaGym::
	.incbin "data/tilesets/secondary/azalea_gym/metatile_attributes.bin"

	.align 1
gMetatiles_MauvilleGym::
	.incbin "data/tilesets/secondary/mauville_gym/metatiles.bin"

	.align 1
gMetatileAttributes_MauvilleGym::
	.incbin "data/tilesets/secondary/mauville_gym/metatile_attributes.bin"

	.align 1
gMetatiles_LavaridgeGym::
	.incbin "data/tilesets/secondary/lavaridge_gym/metatiles.bin"

	.align 1
gMetatileAttributes_LavaridgeGym::
	.incbin "data/tilesets/secondary/lavaridge_gym/metatile_attributes.bin"

	.align 1
gMetatiles_BurnedTower::
	.incbin "data/tilesets/secondary/burned_tower/metatiles.bin"

	.align 1
gMetatilesAttributes_BurnedTower::
	.incbin "data/tilesets/secondary/burned_tower/metatile_attributes.bin"

	.align 1
gMetatiles_FortreeGym::
	.incbin "data/tilesets/secondary/fortree_gym/metatiles.bin"

	.align 1
gMetatileAttributes_FortreeGym::
	.incbin "data/tilesets/secondary/fortree_gym/metatile_attributes.bin"

	.align 1
gMetatiles_MossdeepGym::
	.incbin "data/tilesets/secondary/mossdeep_gym/metatiles.bin"

	.align 1
gMetatileAttributes_MossdeepGym::
	.incbin "data/tilesets/secondary/mossdeep_gym/metatile_attributes.bin"

	.align 1
gMetatiles_SootopolisGym::
	.incbin "data/tilesets/secondary/sootopolis_gym/metatiles.bin"

	.align 1
gMetatileAttributes_SootopolisGym::
	.incbin "data/tilesets/secondary/sootopolis_gym/metatile_attributes.bin"

	.align 1
gMetatiles_TrickHousePuzzle::
	.incbin "data/tilesets/secondary/trick_house_puzzle/metatiles.bin"

	.align 1
gMetatileAttributes_TrickHousePuzzle::
	.incbin "data/tilesets/secondary/trick_house_puzzle/metatile_attributes.bin"

	.align 1
gMetatiles_InsideShip::
	.incbin "data/tilesets/secondary/inside_ship/metatiles.bin"

	.align 1
gMetatileAttributes_InsideShip::
	.incbin "data/tilesets/secondary/inside_ship/metatile_attributes.bin"

	.align 1
gMetatiles_SecretBasePrimary::
	.incbin "data/tilesets/primary/secret_base/metatiles.bin"

	.align 1
gMetatileAttributes_SecretBasePrimary::
	.incbin "data/tilesets/primary/secret_base/metatile_attributes.bin"

	.align 1
gMetatiles_EliteFour::
	.incbin "data/tilesets/secondary/elite_four/metatiles.bin"

	.align 1
gMetatileAttributes_EliteFour::
	.incbin "data/tilesets/secondary/elite_four/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontier::
	.incbin "data/tilesets/secondary/battle_frontier/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontier::
	.incbin "data/tilesets/secondary/battle_frontier/metatile_attributes.bin"

	.align 1
gMetatiles_BattlePalace::
	.incbin "data/tilesets/secondary/battle_palace/metatiles.bin"

	.align 1
gMetatileAttributes_BattlePalace::
	.incbin "data/tilesets/secondary/battle_palace/metatile_attributes.bin"

	.align 1
gMetatiles_BattleDome::
	.incbin "data/tilesets/secondary/battle_dome/metatiles.bin"

	.align 1
gMetatileAttributes_BattleDome::
	.incbin "data/tilesets/secondary/battle_dome/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFactory::
	.incbin "data/tilesets/secondary/battle_factory/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFactory::
	.incbin "data/tilesets/secondary/battle_factory/metatile_attributes.bin"

	.align 1
gMetatiles_BattlePike::
	.incbin "data/tilesets/secondary/battle_pike/metatiles.bin"

	.align 1
gMetatileAttributes_BattlePike::
	.incbin "data/tilesets/secondary/battle_pike/metatile_attributes.bin"

	.align 1
gMetatiles_BattleArena::
	.incbin "data/tilesets/secondary/battle_arena/metatiles.bin"

	.align 1
gMetatileAttributes_BattleArena::
	.incbin "data/tilesets/secondary/battle_arena/metatile_attributes.bin"

	.align 1
gMetatiles_BattlePyramid::
	.incbin "data/tilesets/secondary/battle_pyramid/metatiles.bin"

	.align 1
gMetatileAttributes_BattlePyramid::
	.incbin "data/tilesets/secondary/battle_pyramid/metatile_attributes.bin"

	.align 1
gMetatiles_MirageTower::
	.incbin "data/tilesets/secondary/mirage_tower/metatiles.bin"

	.align 1
gMetatileAttributes_MirageTower::
	.incbin "data/tilesets/secondary/mirage_tower/metatile_attributes.bin"

	.align 1
gMetatiles_MossdeepGameCorner::
	.incbin "data/tilesets/secondary/mossdeep_game_corner/metatiles.bin"

	.align 1
gMetatileAttributes_MossdeepGameCorner::
	.incbin "data/tilesets/secondary/mossdeep_game_corner/metatile_attributes.bin"

	.align 1
gMetatiles_IslandHarbor::
	.incbin "data/tilesets/secondary/island_harbor/metatiles.bin"

	.align 1
gMetatileAttributes_IslandHarbor::
	.incbin "data/tilesets/secondary/island_harbor/metatile_attributes.bin"

	.align 1
gMetatiles_TrainerHill::
	.incbin "data/tilesets/secondary/trainer_hill/metatiles.bin"

	.align 1
gMetatileAttributes_TrainerHill::
	.incbin "data/tilesets/secondary/trainer_hill/metatile_attributes.bin"

	.align 1
gMetatiles_NavelRock::
	.incbin "data/tilesets/secondary/navel_rock/metatiles.bin"

	.align 1
gMetatileAttributes_NavelRock::
	.incbin "data/tilesets/secondary/navel_rock/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontierRankingHall::
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontierRankingHall::
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/metatile_attributes.bin"

	.align 1
gMetatiles_BattleTent::
	.incbin "data/tilesets/secondary/battle_tent/metatiles.bin"

	.align 1
gMetatileAttributes_BattleTent::
	.incbin "data/tilesets/secondary/battle_tent/metatile_attributes.bin"

	.align 1
gMetatiles_MysteryEventsHouse::
	.incbin "data/tilesets/secondary/mystery_events_house/metatiles.bin"

	.align 1
gMetatileAttributes_MysteryEventsHouse::
	.incbin "data/tilesets/secondary/mystery_events_house/metatile_attributes.bin"

	.align 1
gMetatiles_UnionRoom::
	.incbin "data/tilesets/secondary/union_room/metatiles.bin"

	.align 1
gMetatileAttributes_UnionRoom::
	.incbin "data/tilesets/secondary/union_room/metatile_attributes.bin"

	.align 1
gMetatiles_NationalPark::
	.incbin "data/tilesets/secondary/national_park/metatiles.bin"

	.align 1
gMetatileAttributes_NationalPark::
	.incbin "data/tilesets/secondary/national_park/metatile_attributes.bin"

	.align 1
gMetatiles_PalletTown::
	.incbin "data/tilesets/secondary/pallettown/metatiles.bin"

	.align 1
gMetatileAttributes_PalletTown::
	.incbin "data/tilesets/secondary/pallettown/metatile_attributes.bin"
	.align 1
gMetatiles_ViridianCity::
	.incbin "data/tilesets/secondary/viridiancity/metatiles.bin"

	.align 1
gMetatileAttributes_ViridianCity::
	.incbin "data/tilesets/secondary/viridiancity/metatile_attributes.bin"
	.align 1
gMetatiles_PewterCity::
	.incbin "data/tilesets/secondary/pewtercity/metatiles.bin"

	.align 1
gMetatileAttributes_PewterCity::
	.incbin "data/tilesets/secondary/pewtercity/metatile_attributes.bin"
	.align 1
gMetatiles_CeruleanCity::
	.incbin "data/tilesets/secondary/ceruleancity/metatiles.bin"

	.align 1
gMetatileAttributes_CeruleanCity::
	.incbin "data/tilesets/secondary/ceruleancity/metatile_attributes.bin"
	.align 1
gMetatiles_LavenderTown::
	.incbin "data/tilesets/secondary/lavendertown/metatiles.bin"

	.align 1
gMetatileAttributes_LavenderTown::
	.incbin "data/tilesets/secondary/lavendertown/metatile_attributes.bin"
	.align 1
gMetatiles_VermilionCity::
	.incbin "data/tilesets/secondary/vermilioncity/metatiles.bin"

	.align 1
gMetatileAttributes_VermilionCity::
	.incbin "data/tilesets/secondary/vermilioncity/metatile_attributes.bin"
	.align 1
gMetatiles_CeladonCity::
	.incbin "data/tilesets/secondary/celadoncity/metatiles.bin"

	.align 1
gMetatileAttributes_CeladonCity::
	.incbin "data/tilesets/secondary/celadoncity/metatile_attributes.bin"
	.align 1
gMetatiles_FuchsiaCity::
	.incbin "data/tilesets/secondary/fuchsiacity/metatiles.bin"

	.align 1
gMetatileAttributes_FuchsiaCity::
	.incbin "data/tilesets/secondary/fuchsiacity/metatile_attributes.bin"
	.align 1
gMetatiles_IndigoPlateau::
	.incbin "data/tilesets/secondary/indigoplateau/metatiles.bin"

	.align 1
gMetatileAttributes_IndigoPlateau::
	.incbin "data/tilesets/secondary/indigoplateau/metatile_attributes.bin"
	.align 1
gMetatiles_SaffronCity::
	.incbin "data/tilesets/secondary/saffroncity/metatiles.bin"

	.align 1
gMetatileAttributes_SaffronCity::
	.incbin "data/tilesets/secondary/saffroncity/metatile_attributes.bin"
	.align 1
gMetatiles_GeneralKanto::
	.incbin "data/tilesets/primary/generalkanto/metatiles.bin"

	.align 1
gMetatileAttributes_GeneralKanto::
	.incbin "data/tilesets/primary/generalkanto/metatile_attributes.bin"

	.align 1
gMetatiles_RedsHouse::
	.incbin "data/tilesets/secondary/redshouse/metatiles.bin"

	.align 1
gMetatileAttributes_RedsHouse::
	.incbin "data/tilesets/secondary/redshouse/metatile_attributes.bin"
	.align 1
gMetatiles_ViridianGym::
	.incbin "data/tilesets/secondary/viridiangym/metatiles.bin"

	.align 1
gMetatileAttributes_ViridianGym::
	.incbin "data/tilesets/secondary/viridiangym/metatile_attributes.bin"
	.align 1
gMetatiles_PewterGym::
	.incbin "data/tilesets/secondary/pewtergym/metatiles.bin"

	.align 1
gMetatileAttributes_PewterGym::
	.incbin "data/tilesets/secondary/pewtergym/metatile_attributes.bin"
	.align 1
gMetatiles_PewterMuseum::
	.incbin "data/tilesets/secondary/pewtermuseum/metatiles.bin"

	.align 1
gMetatileAttributes_PewterMuseum::
	.incbin "data/tilesets/secondary/pewtermuseum/metatile_attributes.bin"
	.align 1
gMetatiles_CeruleanGym::
	.incbin "data/tilesets/secondary/ceruleangym/metatiles.bin"

	.align 1
gMetatileAttributes_CeruleanGym::
	.incbin "data/tilesets/secondary/ceruleangym/metatile_attributes.bin"
	.align 1
gMetatiles_VermilionGym::
	.incbin "data/tilesets/secondary/vermiliongym/metatiles.bin"

	.align 1
gMetatileAttributes_VermilionGym::
	.incbin "data/tilesets/secondary/vermiliongym/metatile_attributes.bin"
	.align 1
gMetatiles_SoulHouse::
	.incbin "data/tilesets/secondary/soulhouse/metatiles.bin"

	.align 1
gMetatileAttributes_SoulHouse::
	.incbin "data/tilesets/secondary/soulhouse/metatile_attributes.bin"
	.align 1
gMetatiles_RestaurantHotel::
	.incbin "data/tilesets/secondary/restauranthotel/metatiles.bin"

	.align 1
gMetatileAttributes_RestaurantHotel::
	.incbin "data/tilesets/secondary/restauranthotel/metatile_attributes.bin"
	.align 1
gMetatiles_CeladonMansion::
	.incbin "data/tilesets/secondary/celadonmansion/metatiles.bin"

	.align 1
gMetatileAttributes_CeladonMansion::
	.incbin "data/tilesets/secondary/celadonmansion/metatile_attributes.bin"
	.align 1
gMetatiles_SaffronGym::
	.incbin "data/tilesets/secondary/saffrongym/metatiles.bin"

	.align 1
gMetatileAttributes_SaffronGym::
	.incbin "data/tilesets/secondary/saffrongym/metatile_attributes.bin"
	.align 1
gMetatiles_SafariZoneHouse::
	.incbin "data/tilesets/secondary/safarizonehouse/metatiles.bin"

	.align 1
gMetatileAttributes_SafariZoneHouse::
	.incbin "data/tilesets/secondary/safarizonehouse/metatile_attributes.bin"
	.align 1
gMetatiles_FuchsiaGym::
	.incbin "data/tilesets/secondary/fuchsiagym/metatiles.bin"

	.align 1
gMetatileAttributes_FuchsiaGym::
	.incbin "data/tilesets/secondary/fuchsiagym/metatile_attributes.bin"
	.align 1
gMetatiles_HallOfFame::
	.incbin "data/tilesets/secondary/halloffame/metatiles.bin"

	.align 1
gMetatileAttributes_HallOfFame::
	.incbin "data/tilesets/secondary/halloffame/metatile_attributes.bin"
	.align 1
gMetatiles_PowerPlant::
	.incbin "data/tilesets/secondary/powerplant/metatiles.bin"

	.align 1
gMetatileAttributes_PowerPlant::
	.incbin "data/tilesets/secondary/powerplant/metatile_attributes.bin"
	.align 1
gMetatiles_DiglettsCave::
	.incbin "data/tilesets/secondary/diglettscave/metatiles.bin"

	.align 1
gMetatileAttributes_DiglettsCave::
	.incbin "data/tilesets/secondary/diglettscave/metatile_attributes.bin"
	.align 1
gMetatiles_BlackthornCity::
	.incbin "data/tilesets/secondary/blackthorncity/metatiles.bin"

	.align 1
gMetatileAttributes_BlackthornCity::
	.incbin "data/tilesets/secondary/blackthorncity/metatile_attributes.bin"
	.align 1
gMetatiles_MahoganyTown::
	.incbin "data/tilesets/secondary/mahoganytown/metatiles.bin"

	.align 1
gMetatileAttributes_MahoganyTown::
	.incbin "data/tilesets/secondary/mahoganytown/metatile_attributes.bin"
	.align 1
gMetatiles_EcruteakCity::
	.incbin "data/tilesets/secondary/ecruteakcity/metatiles.bin"

	.align 1
gMetatileAttributes_EcruteakCity::
	.incbin "data/tilesets/secondary/ecruteakcity/metatile_attributes.bin"
	.align 1
gMetatiles_OlivineCity::
	.incbin "data/tilesets/secondary/olivinecity/metatiles.bin"

	.align 1
gMetatileAttributes_OlivineCity::
	.incbin "data/tilesets/secondary/olivinecity/metatile_attributes.bin"
	.align 1
gMetatiles_Lighthouse::
	.incbin "data/tilesets/secondary/lighthouse/metatiles.bin"

	.align 1
gMetatileAttributes_Lighthouse::
	.incbin "data/tilesets/secondary/lighthouse/metatile_attributes.bin"
	.align 1
gMetatiles_RocketHideout::
	.incbin "data/tilesets/secondary/rockethideout/metatiles.bin"

	.align 1
gMetatileAttributes_RocketHideout::
	.incbin "data/tilesets/secondary/rockethideout/metatile_attributes.bin"
	.align 1
gMetatiles_IcePath::
	.incbin "data/tilesets/secondary/icepath/metatiles.bin"

	.align 1
gMetatileAttributes_IcePath::
	.incbin "data/tilesets/secondary/icepath/metatile_attributes.bin"
	.align 1
gMetatiles_WhirlIslands::
	.incbin "data/tilesets/secondary/whirlislands/metatiles.bin"

	.align 1
gMetatileAttributes_WhirlIslands::
	.incbin "data/tilesets/secondary/whirlislands/metatile_attributes.bin"
	.align 1
gMetatiles_PokemonLeague::
	.incbin "data/tilesets/secondary/pokemonleague/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonLeague::
	.incbin "data/tilesets/secondary/pokemonleague/metatile_attributes.bin"
	.align 1
gMetatiles_ChampionsRoom::
	.incbin "data/tilesets/secondary/championsroom/metatiles.bin"

	.align 1
gMetatileAttributes_ChampionsRoom::
	.incbin "data/tilesets/secondary/championsroom/metatile_attributes.bin"
	.align 1
gMetatiles_BlackthornGym::
	.incbin "data/tilesets/secondary/blackthorngym/metatiles.bin"

	.align 1
gMetatileAttributes_BlackthornGym::
	.incbin "data/tilesets/secondary/blackthorngym/metatile_attributes.bin"
	.align 1
gMetatiles_BattleFrontierPrimary::
	.incbin "data/tilesets/primary/battlefrontierprimary/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontierPrimary::
	.incbin "data/tilesets/primary/battlefrontierprimary/metatile_attributes.bin"
	.align 1
gMetatiles_SilphCo::
	.incbin "data/tilesets/secondary/silphco/metatiles.bin"

	.align 1
gMetatileAttributes_SilphCo::
	.incbin "data/tilesets/secondary/silphco/metatile_attributes.bin"
	.align 1
gMetatiles_SaffronGeneral::
	.incbin "data/tilesets/primary/saffrongeneral/metatiles.bin"

	.align 1
gMetatileAttributes_SaffronGeneral::
	.incbin "data/tilesets/primary/saffrongeneral/metatile_attributes.bin"
	.align 1
gMetatiles_PlayersRoom::
	.incbin "data/tilesets/primary/playersroom/metatiles.bin"

	.align 1
gMetatileAttributes_PlayersRoom::
	.incbin "data/tilesets/primary/playersroom/metatile_attributes.bin"
	.align 1
gMetatiles_PlayersRoom2::
	.incbin "data/tilesets/secondary/playersroom2/metatiles.bin"

	.align 1
gMetatileAttributes_PlayersRoom2::
	.incbin "data/tilesets/secondary/playersroom2/metatile_attributes.bin"
	.align 1
gMetatiles_VioletGym::
	.incbin "data/tilesets/secondary/violetgym/metatiles.bin"

	.align 1
gMetatileAttributes_VioletGym::
	.incbin "data/tilesets/secondary/violetgym/metatile_attributes.bin"
	.align 1
gMetatiles_DragonsDen_Shrine::
	.incbin "data/tilesets/secondary/dragonsden_shrine/metatiles.bin"

	.align 1
gMetatileAttributes_DragonsDen_Shrine::
	.incbin "data/tilesets/secondary/dragonsden_shrine/metatile_attributes.bin"
