	.align 2
gTilesetPalOverrides_General::
	.byte 2
	.byte HOUR_NIGHT
	.byte HOUR_MORNING
	.byte 0 @ padding
	.4byte gTilesetPalOverride_General02
	.byte 7
	.byte HOUR_NIGHT
	.byte HOUR_MORNING
	.byte 0 @ padding
	.4byte gTilesetPalOverride_General07
	.byte 0xFF
	.byte 0
	.byte 0
	.byte 0 @ padding
	.4byte NULL

	.align 2
gTilesetPalOverrides_NewBark::
	.byte 8
	.byte HOUR_NIGHT
	.byte HOUR_MORNING
	.byte 0 @ padding
	.4byte gTilesetPalOverride_NewBark08
	.byte 9
	.byte HOUR_NIGHT
	.byte HOUR_MORNING
	.byte 0 @ padding
	.4byte gTilesetPalOverride_NewBark08
	.byte 12
	.byte HOUR_NIGHT
	.byte HOUR_MORNING
	.byte 0 @ padding
	.4byte gTilesetPalOverride_NewBark08
	.byte 0xFF
	.byte 0
	.byte 0
	.byte 0 @ padding
	.4byte NULL

	.align 2
gTilesetPalOverrides_Violet::
	.byte 8
	.byte HOUR_NIGHT
	.byte HOUR_MORNING
	.byte 0 @ padding
	.4byte gTilesetPalOverride_Violet08
	.byte 0xFF
	.byte 0
	.byte 0
	.byte 0 @ padding
	.4byte NULL

	.align 2
gTilesetPalOverrides_Azalea::
	.byte 9
	.byte HOUR_NIGHT
	.byte HOUR_MORNING
	.byte 0 @ padding
	.4byte gTilesetPalOverride_Azalea09
	.byte 0xFF
	.byte 0
	.byte 0
	.byte 0 @ padding
	.4byte NULL

	.align 2
gTilesetPalOverrides_Goldenrod::
	.byte 8
	.byte HOUR_NIGHT
	.byte HOUR_MORNING
	.byte 0 @ padding
	.4byte gTilesetPalOverride_Goldenrod08
	.byte 9
	.byte HOUR_NIGHT
	.byte HOUR_MORNING
	.byte 0 @ padding
	.4byte gTilesetPalOverride_Goldenrod09
	.byte 10
	.byte HOUR_NIGHT
	.byte HOUR_MORNING
	.byte 0 @ padding
	.4byte gTilesetPalOverride_Goldenrod10
	.byte 12
	.byte HOUR_NIGHT
	.byte HOUR_MORNING
	.byte 0 @ padding
	.4byte gTilesetPalOverride_Goldenrod12
	.byte 0xFF
	.byte 0
	.byte 0
	.byte 0 @ padding
	.4byte NULL

.align 2
gTilesetPalOverrides_DepartmentStore::
	.byte 9
	.byte 0
	.byte 24 @ 24 hours a day, bby
	.byte 0 @ padding
	.4byte gTilesetPalOverride_DeptStore09NoWin
	.byte 9
	.byte HOUR_NIGHT
	.byte HOUR_MORNING
	.byte 0 @ padding
	.4byte gTilesetPalOverride_DeptStore09Win
	.byte 0xFF
	.byte 0
	.byte 0
	.byte 0 @ padding
	.4byte NULL
