	.align 2
gTilesetPalOverrides_General::
	.byte 7
	.byte 0
	.2byte 0 @ padding
	.4byte gTilesetPalOverride_General07
	.byte 0xFF
	.byte 0
	.2byte 0 @ padding
	.4byte NULL
	.align 2

	.align 2
gTilesetPalOverrides_Petalburg::
	.byte 8
	.byte 0
	.2byte 0 @ padding
	.4byte gTilesetPalOverride_Petalburg08
	.byte 9
	.byte 0
	.2byte 0 @ padding
	.4byte gTilesetPalOverride_Petalburg08
	.byte 12
	.byte 0
	.2byte 0 @ padding
	.4byte gTilesetPalOverride_Petalburg08
	.byte 0xFF
	.byte 0
	.2byte 0 @ padding
	.4byte NULL
