Lighthouse_1F_MapScripts::
	.byte 0


Lighthouse_1F_Eventscript_Woman::
	msgbox Lighthouse_1F_Eventscript_Woman_Text_0, MSGBOX_NPC
	end


Lighthouse_1F_Eventscript_Man::
	msgbox Lighthouse_1F_Eventscript_Man_Text_0, MSGBOX_NPC
	end


Lighthouse_1F_Eventscript_Woman_Text_0:
	.string "In the past, POKéMON used to light\nthe sea around OLIVINE at night.\pThe LIGHTHOUSE was made in honor of\nthose POKéMON.$"

Lighthouse_1F_Eventscript_Man_Text_0:
	.string "People train at this LIGHTHOUSE.\pIt's not easy to climb because of\nall the TRAINERS.$"
